#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.7

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm dig get-info domain [options]

Options:
   --domain=DOMAIN
        Domain name to be checked.
   --waiting-time=[SECOND]
        Time to waiting until next check. Default to 60.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --domain=*) domain="${1#*=}"; shift ;;
        --domain) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then domain="$2"; shift; fi; shift ;;
        --waiting-time=*) waiting_time="${1#*=}"; shift ;;
        --waiting-time) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then waiting_time="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# If set in environment, set to variable.
[ -n "$RCM_QUIET" ] && quiet="$RCM_QUIET"
[ -n "$RCM_LOUD" ] && loud="$RCM_LOUD"
[ -n "$RCM_LOUDER" ] && louder="$RCM_LOUDER"
[ -n "$RCM_DEBUG" ] && debug="$RCM_DEBUG"

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Require.
require vendor/ijortengab/rcm/functions/utility/sleep-extended.sh

# ------------------------------------------------------------------------------

# Title.
title rcm dig get-info domain
____

# Dependency.
require rcm dig get-info a
require rcm dig get-info cname

# Requirement, validate, and populate value.
[ -n "$debug" ] && chapter Variable dump.
if [ -z "$domain" ];then
    error "Argument --domain required."; x
fi
[ -n "$debug" ] && code 'domain="'$domain'"'
if [ -z "$waiting_time" ];then
    waiting_time=60
fi
if [[ "$waiting_time" =~ [^0-9] ]];then
    waiting_time=60
fi
[ -n "$debug" ] && code 'waiting_time="'$waiting_time'"'
[ -n "$debug" ] && ____

chapter Watching Begin
__ Make sure the DNS Record '(A or CNAME)' of '`'$domain'`' is exist.
finish=
_ Begin: $(date +%Y%m%d-%H%M%S); _.
Rcm_BEGIN=$SECONDS
____

until [ -n "$finish" ];do
    _finish=""

    INDENT+="    " \
    rcm dig get-info a --name-exists-sure \
        --without-color \
        --domain="$domain" \
        '*' \
        ; [ $? -eq 0 ] && _finish+="1"

    INDENT+="    " \
    rcm dig get-info cname --name-exists-sure \
        --without-color \
        --domain="$domain" \
        --type=cname \
        --hostname="@" \
        '*' \
        ; [ $? -eq 0 ] && _finish+="1"

    if [[ "$_finish" =~ 1 ]];then
        chapter Watching End
        success The required DNS Records already exist '(A or CNAME)'.
        _ End: $(date +%Y%m%d-%H%M%S); _.
        Rcm_END=$SECONDS
        duration=$(( Rcm_END - Rcm_BEGIN ))
        hours=$((duration / 3600)); minutes=$(( (duration % 3600) / 60 )); seconds=$(( (duration % 3600) % 60 ));
        runtime=`printf "%02d:%02d:%02d" $hours $minutes $seconds`
        _ Duration: $runtime; if [ $duration -gt 60 ];then _, " (${duration} seconds)"; fi; _, '.'; _.
        finish=1
        ____
    else
        error There are not exist DNS Record of '`'$domain'`' '(neither A nor CNAME)'.
        _ We are still waiting.; _.
        sleep-extended $waiting_time
    fi
done

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --domain
# --waiting-time
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
