#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.3

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm-dig-is-name-exists [options]

Options:
   --domain *
        Domain name to be checked.
   --name-server
        Set the Name server. Default value is - (dash). Available values: [1], [2], or other.
        [1]: 8.8.8.8
        [2]: 1.1.1.1

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.
   --reverse
        Reverse the result.

Dependency:
   dig
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --domain=*) domain="${1#*=}"; shift ;;
        --domain) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then domain="$2"; shift; fi; shift ;;
        --name-server=*) name_server="${1#*=}"; shift ;;
        --name-server) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then name_server="$2"; shift; fi; shift ;;
        --reverse) reverse=1; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm-dig-is-name-exists
____

# Dependency.

# Require, validate, and populate value.
chapter Variable dump.
if [ -z "$domain" ];then
    error "Argument --domain required."; x
fi
code 'domain="'$domain'"'
code 'name_server="'$name_server'"'
if [[ "$name_server" == - ]];then
    name_server=
fi
[ -n "$name_server" ] && add_name_server=' @'"$name_server" || add_name_server=''
[ -n "$name_server" ] && label_name_server=' in DNS '"$name_server" || label_name_server=''
tempfile=$(mktemp -p /dev/shm -t rcm-dig-is-name-exists.XXXXXX)
domain_dot="${domain}."
domain_dot_escape=${domain_dot//\./\\.}
____

chapter Mengecek Name Server domain '`'$domain'`'
code dig NS ${domain}${add_name_server}
dig NS $domain $add_name_server | tee "$tempfile"
stdout=$(<"$tempfile")
found=
if grep -q -E --ignore-case ^"$domain_dot_escape"'\s+''[0-9]+''\s+'IN'\s+'NS'\s+' <<< "$stdout";then
    code grep -E --ignore-case "'"^"$domain_dot_escape"'\s+''[0-9]+''\s+'IN'\s+'NS'\s+'"'"
    grep -E --ignore-case ^"$domain_dot_escape"'\s+''[0-9]+''\s+'IN'\s+'NS'\s+' <<< "$stdout"
    found=1
fi
____

chapter Result
rm "$tempfile"
if [ -n "$found" ];then
    result='success'
    if [ -n "$reverse" ];then
        result='error'
    fi
    $result Name Server pada domain "$domain" FOUND${label_name_server}.
else
    result='error'
    if [ -n "$reverse" ];then
        result='success'
    fi
    $result Name Server pada domain "$domain" NOT FOUND${label_name_server}.
fi

[ "$result" == error ] && x
____

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --reverse
# )
# VALUE=(
# --domain
# --name-server
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
