#!/bin/bash

[ -f "$0" ] || { echo "Cannot run as dot command." >&2; kill -INT $$; }

# Define variables and constants.
RCM_EXTENSION_VERSION=0.19.0-alpha.14

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm system list user regular

Options:
   --with-web-server=[HTTP]
        Select web server to get the user belong the process.
        Values available from command: rcm(plugin list web-server).
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --with-web-server=*) with_web_server="${1#*=}"; shift ;;
        --with-web-server) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then with_web_server="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Require, validate, and populate value.
chapter Variable dump.
code with_web_server="$with_web_server"
web_server="$with_web_server"
code web_server="$web_server"
____

if [ -n "$with_web_server" ];then
    RCM_WEB_SERVER_USER=
    include `rcm plugin run-method web-server $web_server get-user-process`
    if [ -z "$RCM_WEB_SERVER_USER" ];then
        error "Variable \$RCM_WEB_SERVER_USER failed to populate."; x
    fi
    echo "$RCM_WEB_SERVER_USER"
fi

[ -f /etc/passwd ] || { error File not found; x; }

cut -d: -f1 /etc/passwd | while IFS= read -r line; do [ -d /home/$line ] && echo "${line}"; done

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --with-web-server
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
