#!/bin/bash

[ -f "$0" ] || { echo "Cannot run as dot command." >&2; kill -INT $$; }

# Define variables and constants.
RCM_EXTENSION_VERSION=0.19.0-alpha.14

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm php list available

Options:
   --installed
        Filter to list installed only.
   --which=[VALUE]
        Conditional: Bypass if --installed is not added.
        Select which package that available. If omit, common is used.

Other Options (For expert only):
   --fpm
        Alias of --installed --which=fpm
   --cli
        Alias of --installed --which=cli
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --cli) cli=1; shift ;;
        --fpm) fpm=1; shift ;;
        --installed) installed=1; shift ;;
        --which=*) which="${1#*=}"; shift ;;
        --which) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then which="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm php list available
____

# Dependency.
require command dpkg-query
require command apt-cache

# Require, validate, and populate value.
chapter Variable dump.
code installed="$installed"
binary=
[ -n "$fpm" ] && { installed=1; binary+=1; which=fpm; }
[ -n "$cli" ] && { installed=1; binary+=1; which=cli; }
if [ ${#binary} -gt 1 ];then
    error "Argument --fpm or --cli cannot both be present."; x
fi
if [ -n "$installed" ];then
    if [ -z "$which" ];then
        which=common
    fi
fi
code installed="$installed"
code which="$which"
____

if [ -n "$installed" ];then
    glob="php*${which}"
    regex="php(.+)-${which}"
    dpkg-query -W -f='${Status}${binary:Package}\n' "$glob" | \
        grep '^install ok installed' | \
        sed 's,^install ok installed,,' | \
        sed -nE 's,'"$regex"',\1,p'
else
    apt-cache search '^php[0-9.]+$' | sed -E 's/^php([0-9]+\.[0-9]+).*/\1/' | sort
fi

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --fpm
# --cli
# --installed
# )
# VALUE=(
# --which
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
