#!/bin/bash

# Define variables and constants.
RCM_EXTENSION_VERSION=0.19.0-alpha.13
PHPMYADMIN_FQDN_LOCALHOST=${PHPMYADMIN_FQDN_LOCALHOST:=phpmyadmin.localhost}
MARIADB_PREFIX_MASTER=${MARIADB_PREFIX_MASTER:=/usr/local/share/mariadb}
MARIADB_USERS_CONTAINER_MASTER=${MARIADB_USERS_CONTAINER_MASTER:=users}

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm phpmyadmin init [options]

Options:
   --php-version *
        Set the version of PHP FPM.
   --phpmyadmin-version *
        Set the version of PHPMyAdmin.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.

Environment Variables:
   PHPMYADMIN_FQDN_LOCALHOST
        Default to $PHPMYADMIN_FQDN_LOCALHOST
   MARIADB_PREFIX_MASTER
        Default to $MARIADB_PREFIX_MASTER
   MARIADB_USERS_CONTAINER_MASTER
        Default to $MARIADB_USERS_CONTAINER_MASTER
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --php-version=*) php_version="${1#*=}"; shift ;;
        --php-version) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then php_version="$2"; shift; fi; shift ;;
        --phpmyadmin-version=*) phpmyadmin_version="${1#*=}"; shift ;;
        --phpmyadmin-version) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then phpmyadmin_version="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm phpmyadmin init
____

# Dependency.
require command php
require command curl
require rcm nginx add vhost php-default
require vendor/ijortengab/rcm/functions/utility/backup-file.sh
require vendor/ijortengab/rcm/functions/utility/backup-dir.sh
require vendor/ijortengab/rcm/functions/classes/rcm-file.sh
require vendor/ijortengab/rcm/functions/classes/rcm-dir.sh
require vendor/ijortengab/rcm/functions/utility/link-symbolic.sh
require vendor/ijortengab/rcm/functions/utility/link-symbolic-dir.sh

# Functions.
databaseCredentialPhpmyadmin() {
    # global MARIADB_PREFIX_MASTER MARIADB_USERS_CONTAINER_MASTER db_user
    local path="${MARIADB_PREFIX_MASTER}/${MARIADB_USERS_CONTAINER_MASTER}/${db_user}"
    local DB_USER DB_USER_PASSWORD
    rcm-file "$path" terminateIfNotExists
    # Populate.
    . "$path"
    db_user=$DB_USER
    db_user_password=$DB_USER_PASSWORD
}

# Requirement, validate, and populate value.
chapter Variable dump.
[ -n "$fast" ] && isfast=' --fast' || isfast=''
code 'PHPMYADMIN_FQDN_LOCALHOST="'$PHPMYADMIN_FQDN_LOCALHOST'"'
code 'MARIADB_PREFIX_MASTER="'$MARIADB_PREFIX_MASTER'"'
code 'MARIADB_USERS_CONTAINER_MASTER="'$MARIADB_USERS_CONTAINER_MASTER'"'
if [ -z "$phpmyadmin_version" ];then
    error "Argument --phpmyadmin-version required."; x
fi
code 'phpmyadmin_version="'$phpmyadmin_version'"'
if [ -z "$php_version" ];then
    error "Argument --php-version required."; x
fi
code 'php_version="'$php_version'"'
nginx_user=
conf_nginx=`command -v nginx > /dev/null && command -v nginx > /dev/null && nginx -V 2>&1 | grep -o -P -- '--conf-path=\K(\S+)'`
if [ -f "$conf_nginx" ];then
    nginx_user=`grep -o -P '^user\s+\K([^;]+)' "$conf_nginx"`
fi
code 'nginx_user="'$nginx_user'"'
if [ -z "$nginx_user" ];then
    error "Variable \$nginx_user failed to populate."; x
fi
php_fpm_user="$nginx_user"
code 'php_fpm_user="'$php_fpm_user'"'
prefix=$(getent passwd "$php_fpm_user" | cut -d: -f6 )
code 'prefix="'$prefix'"'
project_container="$PHPMYADMIN_FQDN_LOCALHOST"
code 'project_container="'$project_container'"'
php_project_name=www
code 'php_project_name="'$php_project_name'"'
mariadb_project_name=phpmyadmin
code 'mariadb_project_name="'$mariadb_project_name'"'
root="$prefix/${project_container}/web"
code 'root="'$root'"'
root_source="$prefix/${project_container}/${phpmyadmin_version}"
code 'root_source="'$root_source'"'
php_fpm_section="$php_project_name"
code 'php_fpm_section="'$php_fpm_section'"'
____

target_project_container="${prefix}/${project_container}"
chapter Mengecek direktori project container '`'$target_project_container'`'.
rcm-dir "$target_project_container" isExists
____

if [ -n "$notfound" ];then
    chapter Membuat direktori project container.
    code mkdir -p '"'$target_project_container'"'
    code chown $php_fpm_user:$php_fpm_user '"'$target_project_container'"'
    mkdir -p "$target_project_container"
    chown $php_fpm_user:$php_fpm_user "$target_project_container"
    rcm-dir "$target_project_container" mustExists
    ____
fi

chapter Prepare arguments.
socket_filename=$(rcm-php-fpm-setup-project-config get --php-version="$php_version" --section="$php_fpm_section" --key=listen)
if [ -z "$socket_filename" ];then
    __; red Socket Filename of PHP-FPM not found.; x
fi
code socket_filename="$socket_filename"
code root="$root"
url="http://${PHPMYADMIN_FQDN_LOCALHOST}"
code 'url="'$url'"'
____

chapter Mengecek '$PATH'.
code PATH="$PATH"
if grep -q '/snap/bin' <<< "$PATH";then
    __ '$PATH' sudah lengkap.
else
    __ '$PATH' belum lengkap.
    __ Memperbaiki '$PATH'
    PATH=/snap/bin:$PATH
    if grep -q '/snap/bin' <<< "$PATH";then
        __; green '$PATH' sudah lengkap.; _.
        __; magenta PATH="$PATH"; _.
    else
        __; red '$PATH' belum lengkap.; x
    fi
fi
____

INDENT+="    " \
PATH=$PATH \
rcm-nginx-virtual-host-autocreate-php $isfast \
    --root="$root" \
    --url="$url" \
    --fastcgi-pass="unix:${socket_filename}" \
    ; [ ! $? -eq 0 ] && x

chapter Mengecek address host local '`'$PHPMYADMIN_FQDN_LOCALHOST'`'.
notfound=
string="$PHPMYADMIN_FQDN_LOCALHOST"
string_quoted=$(sed "s/\./\\\./g" <<< "$string")
if grep -q -E "^\s*127\.0\.0\.1\s+${string_quoted}" /etc/hosts;then
    __ Address Host local terdapat pada local DNS resolver '`'/etc/hosts'`'.
else
    __ Address Host local tidak terdapat pada local DNS resolver '`'/etc/hosts'`'.
    notfound=1
fi
____

if [ -n "$notfound" ];then
    chapter Menambahkan host '`'$PHPMYADMIN_FQDN_LOCALHOST'`'.
    echo "127.0.0.1"$'\t'"${PHPMYADMIN_FQDN_LOCALHOST}" >> /etc/hosts
    if grep -q -E "^\s*127\.0\.0\.1\s+${string_quoted}" /etc/hosts;then
        __; green Address Host local terdapat pada local DNS resolver '`'/etc/hosts'`'.; _.
    else
        __; red Address Host local tidak terdapat pada local DNS resolver '`'/etc/hosts'`'.; x
    fi
    ____
fi

chapter Mengecek file '`'composer.json'`' untuk project '`'phpmyadmin/phpmyadmin'`'
path="${root_source}/composer.json"
rcm-file "$path" isExists
____

if [ -n "$notfound" ];then
    chapter Mendownload PHPMyAdmin
    code sudo -u $php_fpm_user mkdir -p '"'$root_source'"'
    sudo -u $php_fpm_user mkdir -p "$root_source"
    cd $root_source
    __ Mendownload PHPMyAdmin
    path="${root_source}/phpMyAdmin-${phpmyadmin_version}-all-languages.tar.gz"
    rcm-file "$path" isExists
    if [ -n "$notfound" ];then
        sudo -u $php_fpm_user wget "https://files.phpmyadmin.net/phpMyAdmin/${phpmyadmin_version}/phpMyAdmin-${phpmyadmin_version}-all-languages.tar.gz"
        rcm-file "$path" mustExists
    fi
    rcm-file "$path" terminateIfNotExists
    __ Extract File.
    path_tar_gz="$path"
    path="${root_source}/phpMyAdmin-${phpmyadmin_version}-all-languages/composer.json"
    rcm-file "$path" isExists
    if [ -n "$notfound" ];then
        code sudo -u $php_fpm_user tar xfz "$path_tar_gz"
        sudo -u $php_fpm_user tar xfz "$path_tar_gz"
        rcm-file "$path" mustExists
        __ Memindahkan hasil download ke parent.
        code sudo -u $php_fpm_user mv "$path_tar_gz" -t ..
        sudo -u $php_fpm_user mv "$path_tar_gz" -t ..
    fi
    rcm-file "$path" terminateIfNotExists
    __ Memindahkan codebase.
    code mv "${root_source}/phpMyAdmin-${phpmyadmin_version}-all-languages/"'*' -t '"'$root_source'"'
    code mv "${root_source}/phpMyAdmin-${phpmyadmin_version}-all-languages/"'.[!.]*' -t '"'$root_source'"'
    code rmdir "${root_source}/phpMyAdmin-${phpmyadmin_version}-all-languages"
    mv "${root_source}/phpMyAdmin-${phpmyadmin_version}-all-languages/"* -t "$root_source"
    mv "${root_source}/phpMyAdmin-${phpmyadmin_version}-all-languages/".[!.]* -t "$root_source"
    rmdir "${root_source}/phpMyAdmin-${phpmyadmin_version}-all-languages"
    path="${root_source}/composer.json"
    rcm-file "$path" mustExists
    cd - >/dev/null
    ____
fi
rcm-file "$path" terminateIfNotExists

source="$root_source"
target="$root"
link-symbolic_dir "$source" "$target" "$php_fpm_user"

chapter Mengecek file konfigurasi PHPMyAdmin.
path="${root_source}/config.inc.php"
rcm-file "$path" isExists
if [ -n "$notfound" ];then
    source="${root_source}/config.sample.inc.php"
    rcm-file "$source" mustExists
    code sudo -u $php_fpm_user cp "$source" "$path"
    sudo -u $php_fpm_user cp "$source" "$path"
    rcm-file "$path" mustExists
fi
rcm-file "$path" terminateIfNotExists
____

INDENT+="    " \
rcm-mariadb-setup-project-database $isfast \
    --project-name="$mariadb_project_name" \
    ; [ ! $? -eq 0 ] && x

chapter Prepare arguments.
db_name="$mariadb_project_name"
db_user="$mariadb_project_name"
code 'db_name="'$db_name'"'
code 'db_user="'$db_user'"'
databaseCredentialPhpmyadmin
code 'db_user_password="'$db_user_password'"'
db_user_host=localhost
code 'db_user_host="'$db_user_host'"'
____

chapter Mengecek apakah PHPMyAdmin sudah imported SQL.
notfound=
msg=$(mysql \
    --defaults-extra-file=<(printf "[client]\nuser = %s\npassword = %s" "${db_user}" "${db_user_password}") \
    --silent --skip-column-names \
    $db_name -e "show tables;" | wc -l)
if [[ $msg -gt 0 ]];then
    __ PHPMyAdmin sudah imported SQL.
else
    __ PHPMyAdmin belum imported SQL.
    notfound=1
fi
____

if [ -n "$notfound" ];then
    chapter PHPMyAdmin Import SQL
    rcm-file "${root_source}/sql/create_tables.sql" terminateIfNotExists
    mysql \
        --defaults-extra-file=<(printf "[client]\nuser = %s\npassword = %s" "${db_user}" "${db_user_password}") \
        $db_name < "${root_source}/sql/create_tables.sql"
    msg=$(mysql \
        --defaults-extra-file=<(printf "[client]\nuser = %s\npassword = %s" "${db_user}" "${db_user_password}") \
        --silent --skip-column-names \
        $db_name -e "show tables;" | wc -l)
    if [[ $msg -gt 0 ]];then
        __; green PHPMyAdmin sudah imported SQL.; _.
    else
        __; red PHPMyAdmin belum imported SQL.; x
    fi
    ____
fi

chapter Mengecek informasi file konfigurasi PHPMyAdmin.
php=$(cat <<'EOF'
$mode = $_SERVER['argv'][1];
switch ($mode) {
    case 'is_empty' :
        $path = $_SERVER['argv'][2];
        $key = $_SERVER['argv'][3];
        include($path);
        $cfg = isset($cfg) ? $cfg : [];
        if (array_key_exists($key, $cfg)) {
            if (is_string($cfg[$key]) && strlen($cfg[$key]) === 0) {
                exit(0);
            }
        }
        exit(1);
        break;
    case 'generate_sodium':
        $key = sodium_crypto_secretbox_keygen();
        echo sodium_bin2hex($key);
        break;
    case 'is_different':
    case 'save':
        # Populate variable $is_different.
        $file = $_SERVER['argv'][2];
        $reference = unserialize($_SERVER['argv'][3]);
        include($file);
        $cfg = isset($cfg) ? $cfg : [];
        $cfg['Servers']['1'] = isset($cfg['Servers']['1']) ? $cfg['Servers']['1'] : [];
        // Tidak menggunakan array_map serialize seperti rcm-roundcube-autoinstaller-nginx karena dipastikan seluruh value non array.
        $is_different = !empty(array_diff_assoc($reference['Servers']['1'], $cfg['Servers']['1']));
        break;
}
switch ($mode) {
    case 'is_different':
        $is_different ? exit(0) : exit(1);
        break;
    case 'save':
        if (!$is_different) {
            exit(0);
        }
        $contents = file_get_contents($file);
        $need_edit = array_diff_assoc($reference['Servers']['1'], $cfg['Servers']['1']);
        $new_lines = [];
        foreach ($need_edit as $key => $value) {
            $new_line = "__PARAMETER__[__KEY__] = __VALUE__; # managed by RCM";
            // Jika indexed array dan hanya satu , maka buat one line.
            if (is_array($value) && array_key_exists(0, $value) && count($value) === 1) {
                $new_line = str_replace(['__PARAMETER__','__KEY__','__VALUE__'],['$cfg'."['Servers'][1]", var_export($key, true), "['".$value[0]."']"], $new_line);
            }
            else {
                $new_line = str_replace(['__PARAMETER__','__KEY__','__VALUE__'],['$cfg'."['Servers'][1]", var_export($key, true), var_export($value, true)], $new_line);
            }
            $is_one_line = preg_match('/\n/', $new_line) ? false : true;
            $find_existing = "__PARAMETER__[__KEY__] = __VALUE__; # managed by RCM";
            $find_existing = str_replace(['__PARAMETER__','__KEY__'],['$cfg'."['Servers'][1]", var_export($key, true)], $find_existing);
            $find_existing = preg_quote($find_existing);
            $find_existing = str_replace('__VALUE__', '.*', $find_existing);
            $find_existing = '/\s*'.$find_existing.'/';
            if ($is_one_line && preg_match_all($find_existing, $contents, $matches, PREG_PATTERN_ORDER)) {
                $contents = str_replace($matches[0], '', $contents);
            }
            $new_lines[] = $new_line;
        }
        if (substr($contents, -1) != "\n") {
            $contents .= "\n";
        }
        $contents .= implode("\n", $new_lines);
        $contents .= "\n";
        file_put_contents($file, $contents);
        break;
}
EOF
)

path="${root_source}/config.inc.php"
if php -r "$php" is_empty "$path" blowfish_secret;then
    __ Key '`'blowfish_secret'`' belum berisi nilai. Diperlukan modifikasi file '`'config.inc.php'`'.
    blowfish_secret=`php -r "$php" generate_sodium`
    sed -i "s,\$cfg\['blowfish_secret'\] = '';.*,\$cfg['blowfish_secret'] = \\\sodium_hex2bin('$blowfish_secret');," "$path"
    if php -r "$php" is_empty "$path" blowfish_secret;then
        __; red Key '`'blowfish_secret'`' belum berisi nilai. Gagal modifikasi file '`'config.inc.php'`'.
    else
        __; green Key '`'blowfish_secret'`' sudah terisi nilai. Berhasil modifikasi file '`'config.inc.php'`'.; _.
    fi
else
    __ Key '`'blowfish_secret'`' sudah terisi nilai. Tidak diperlukan modifikasi file '`'config.inc.php'`'.
fi

reference="$(php -r "echo serialize([
    'Servers' => [
        '1' => [
            'controlhost' => '$db_user_host',
            'controluser' => '$db_user',
            'controlpass' => '$db_user_password',
            'pmadb' => '$db_name',
            'bookmarktable' => 'pma__bookmark',
            'relation' => 'pma__relation',
            'table_info' => 'pma__table_info',
            'table_coords' => 'pma__table_coords',
            'pdf_pages' => 'pma__pdf_pages',
            'column_info' => 'pma__column_info',
            'history' => 'pma__history',
            'table_uiprefs' => 'pma__table_uiprefs',
            'tracking' => 'pma__tracking',
            'userconfig' => 'pma__userconfig',
            'recent' => 'pma__recent',
            'favorite' => 'pma__favorite',
            'users' => 'pma__users',
            'usergroups' => 'pma__usergroups',
            'navigationhiding' => 'pma__navigationhiding',
            'savedsearches' => 'pma__savedsearches',
            'central_columns' => 'pma__central_columns',
            'designer_settings' => 'pma__designer_settings',
            'export_templates' => 'pma__export_templates',
        ],
    ],
]);")"
is_different=
if php -r "$php" is_different "$path" "$reference";then
    is_different=1
    __ Diperlukan modifikasi file '`'config.inc.php'`'.
else
    __ File '`'config.inc.php'`' tidak ada perubahan.
fi
____

if [ -n "$is_different" ];then
    chapter Memodifikasi file '`'config.inc.php'`'.
    __ Backup file "$path"
    backup-file copy "$path"
    php -r "$php" save "$path" "$reference"
    if php -r "$php" is_different "$path" "$reference";then
        __; red Modifikasi file '`'config.inc.php'`' gagal.; x
    else
        __; green Modifikasi file '`'config.inc.php'`' berhasil.; _.
    fi
    ____
fi
____

chapter Mengecek HTTP Response Code.
i=0
code=
if [ -z "$tempfile" ];then
    tempfile=$(mktemp -p /dev/shm -t rcm-phpmyadmin-init.XXXXXX)
fi
until [ $i -eq 10 ];do
    __; magenta curl -o /dev/null -s -w '"'%{http_code}\\n'"' '"'http://127.0.0.1'"' -H '"'Host: $PHPMYADMIN_FQDN_LOCALHOST'"'; _.
    curl -o /dev/null -s -w "%{http_code}\n" "http://127.0.0.1" -H "Host: ${PHPMYADMIN_FQDN_LOCALHOST}" > $tempfile
    while read line; do e "$line"; _.; done < $tempfile
    code=$(head -1 $tempfile)
    if [[ "$code" =~ ^[2,3] ]];then
        break
    else
        __ Retry.
        __; magenta sleep .5; _.
        sleep .5
    fi
    let i++
done
if [[ "$code" =~ ^[2,3] ]];then
    __ HTTP Response code '`'$code'`' '('Required')'.
else
    __; red Terjadi kesalahan. HTTP Response code '`'$code'`'.; x
fi
____

if [ -n "$tempfile" ];then
    rm "$tempfile"
fi

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --phpmyadmin-version
# --php-version
# )
# FLAG_VALUE=(
# )
# EOF
# clear
