#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.5

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm-plugin <command> [options]

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.

Environment Variables:
   BINARY_DIRECTORY
        Default to $BINARY_DIRECTORY

RCM Config:
   --no-timer
   --no-confirmation
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --[^-]*) shift ;;
        helper)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Command.
if [ -n "$1" ];then
    command=
    case "$1" in
        helper) command="$1"; shift ;;
    esac
    if [ -z "$command" ];then
        error Command unknown: '`'"$1"'`'.; x
    fi
fi

# Define variables and constants.

# If not set in argument, try load from environment.
[ -z "$fast" ] && fast="$RCM_FAST"

# If set in environment, set to variable.
[ -n "$RCM_VERBOSE" ] && verbose="$RCM_VERBOSE"
[ -n "$RCM_RESOLVE_DEPENDENCIES" ] && resolve_dependencies="$RCM_RESOLVE_DEPENDENCIES"
[ -n "$RCM_TABLE_DOWNLOADS" ] && table_downloads="$RCM_TABLE_DOWNLOADS"
[ -n "$RCM_TABLE_DEPENDENCIES" ] && table_dependencies="$RCM_TABLE_DEPENDENCIES"
[ -n "$RCM_TABLE_COMMAND_RESOLVED" ] && table_command_resolved="$RCM_TABLE_COMMAND_RESOLVED"
[ -n "$RCM_VERSION" ] && rcm_version="$RCM_VERSION"

# Boolean default to TRUE.
[ -z "$fast" ] && fast=1; [ "$fast" == 0 ] && fast=
[ -z "$resolve_dependencies" ] && resolve_dependencies=1; [ "$resolve_dependencies" == 0 ] && resolve_dependencies=

# Verbosity.
quiet=; loud=; louder=; debug=;
[[ -z "$verbose" || "$verbose" -lt 1 ]] && quiet=1 || quiet=
[[ "$verbose" -gt 0 ]] && loud=1
[[ "$verbose" -gt 1 ]] && loud=1 && louder=1
[[ "$verbose" -gt 2 ]] && loud=1 && louder=1 && debug=1

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

command-helper() {
    local which=$1; shift
    if [ "$which" == do-nothing ];then
        return
    fi
    if [ -n "$which" ];then
        if [[ $(type -t "helper-${which}") == function ]];then
            helper-${which} "$@"
            exit 0
        else
            error Helper unknown: '`'"$command"'`'.; x
        fi
    fi
}
helper-interface-available() {
    if [ -d "${HOME}/.config/rcm" ];then
        cd "${HOME}/.config/rcm"
        ls -1 rcm.plugin.table.* | grep -o -P 'rcm\.plugin\.table\.\K(\S+)'
    fi
}
helper-temporary-suggestion() {
    local is_temporary=$1
    if [ "$is_temporary" == 0 ];then
        exit 1
    fi
    local category=$2
    echo "\$HOME/.cache/rcm/rcm.plugin.table.$category.${RANDOM}${RANDOM}"
}
helper-list() {
    local category=$1
    local table=$2; [ "$table" == - ] && table=
    local table_temporary=$3; [ "$table_temporary" == - ] && table_temporary=
}

# Execute command.
if [ -n "$command" ];then
    if [[ $(type -t "command-${command}") == function ]];then
        command-${command} "$@"
        exit 0
    else
        error The function of command '`'"$command"'`' has not yet defined.; x
    fi
fi

usage >/dev/null | head -3
_ Try; blue ' 'rcm-plugin; magenta ' '--help; _, ' 'for more information.; _.

# parse-options.sh \
# --without-end-options-double-dash \
# --with-end-options-specific-operand \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# OPERAND=(
# helper
# )
# EOF
# clear
