#!/bin/bash

# Common Functions.
red() { echo -ne "\e[91m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
green() { echo -ne "\e[92m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
yellow() { echo -ne "\e[93m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
blue() { echo -ne "\e[94m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
magenta() { echo -ne "\e[95m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
error() { echo -n "$INDENT" >&2; red '#' "$@" >&2; echo >&2; }
success() { echo -n "$INDENT" >&2; green '#' "$@" >&2; echo >&2; }
chapter() { echo -n "$INDENT" >&2; yellow '#' "$@" >&2; echo >&2; }
title() { echo -n "$INDENT" >&2; blue '#' "$@" >&2; echo >&2; }
code() { echo -n "$INDENT" >&2; magenta "$@" >&2; echo >&2; }
x() { echo >&2; exit 1; }
e() { echo -n "$INDENT" >&2; echo -n "$@" >&2; }
_() { echo -n "$INDENT" >&2; echo -n "#"' ' >&2; [ -n "$1" ] && echo -n "$@" >&2; }
_,() { echo -n "$@" >&2; }
_.() { echo >&2; }
__() { echo -n "$INDENT" >&2; echo -n "# ${RCM_INDENT}" >&2; [ -n "$1" ] && echo "$@" >&2; }
____() { echo >&2; [ -n "$RCM_DELAY" ] && sleep "$RCM_DELAY"; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --fast) fast=1; shift ;;
        --verbose|-v) verbose="$((verbose+1))"; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        -[^-]*) OPTIND=1
            while getopts ":v" opt; do
                case $opt in
                    v) verbose="$((verbose+1))" ;;
                esac
            done
            shift "$((OPTIND-1))"
            ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# If not set in argument, try load from environment.
[ -z "$fast" ] && fast="$RCM_FAST"
[ -z "$verbose" ] && verbose="$RCM_VERBOSE"

# If set in environment, set to variable.
[ -n "$RCM_TABLE_DEPENDENCIES" ] && table_dependencies="$RCM_TABLE_DEPENDENCIES"
[ -n "$RCM_TABLE_DOWNLOADS" ] && table_downloads="$RCM_TABLE_DOWNLOADS"
[ -n "$RCM_VERSION" ] && rcm_version="$RCM_VERSION" || { error Environment Variable RCM_VERSION required.; x; }

# Boolean default to TRUE.
[ -z "$fast" ] && fast=1; [ "$fast" == 0 ] && fast=

# Verbosity.
quiet=; loud=; louder=; debug=;
[[ -z "$verbose" || "$verbose" -lt 1 ]] && quiet=1 || quiet=
[[ "$verbose" -gt 0 ]] && loud=1
[[ "$verbose" -gt 1 ]] && loud=1 && louder=1
[[ "$verbose" -gt 2 ]] && loud=1 && louder=1 && debug=1

# Define variables and constants.
RCM_DELAY=${RCM_DELAY:=.5}; [ -n "$fast" ] && unset RCM_DELAY
RCM_INDENT='    '; [ "$(tput cols)" -le 80 ] && RCM_INDENT='  '

# Functions. Help and Version.
printVersion() {
    echo '0.18.0-alpha.4'
}
printHelp() {
    title Rapid Construct Massive
    _ 'Resolve Dependencies'; _.
    _ 'Version '; yellow `printVersion`; _.
    _.
cat << EOF
Usage: rcm-resolve <command> [options]

Global Options:
   --fast
        No delay every subtask.
   --version
        Print version of this script.
   --help
        Show this help.

EOF
}

# Help and Version.
[ -n "$help" ] && { printHelp; exit 1; }
[ -n "$version" ] && { printVersion; exit 1; }

# Functions.
ArrayDiff() {
    # Computes the difference of arrays.
    #
    # Globals:
    #   Modified: _return
    #
    # Arguments:
    #   1 = Parameter of the array to compare from.
    #   2 = Parameter of the array to compare against.
    #
    # Returns:
    #   None
    #
    # Example:
    #   ```
    #   my=("cherry" "manggo" "blackberry" "manggo" "blackberry")
    #   yours=("cherry" "blackberry")
    #   ArrayDiff my[@] yours[@]
    #   # Get result in variable `$_return`.
    #   # _return=("manggo" "manggo")
    #   ```
    local e
    local source=("${!1}")
    local reference=("${!2}")
    _return=()
    # inArray is alternative of ArraySearch.
    inArray () {
        local e match="$1"
        shift
        for e; do [[ "$e" == "$match" ]] && return 0; done
        return 1
    }
    if [[ "${#reference[@]}" -gt 0 ]];then
        for e in "${source[@]}";do
            if ! inArray "$e" "${reference[@]}";then
                _return+=("$e")
            fi
        done
    else
        _return=("${source[@]}")
    fi
}
ArrayUnique() {
    # Removes duplicate values from an array.
    #
    # Globals:
    #   Modified: _return
    #
    # Arguments:
    #   1 = Parameter of the input array.
    #
    # Returns:
    #   None
    #
    # Example:
    #   ```
    #   my=("cherry" "manggo" "blackberry" "manggo" "blackberry")
    #   ArrayUnique my[@]
    #   # Get result in variable `$_return`.
    #   # _return=("cherry" "manggo" "blackberry")
    #   ```
    local e source=("${!1}")
    # inArray is alternative of ArraySearch.
    inArray () {
        local e match="$1"
        shift
        for e; do [[ "$e" == "$match" ]] && return 0; done
        return 1
    }
    _return=()
    for e in "${source[@]}";do
        if ! inArray "$e" "${_return[@]}";then
            _return+=("$e")
        fi
    done
}
Rcm_resolve_dependencies() {
    local extension
    Rcm_resolve_dependencies_install() {
        # global: command_required command_required_version
        if [[ -f "$BINARY_DIRECTORY/$command_required" && ! -s "$BINARY_DIRECTORY/$command_required" ]];then
            __ Empty file detected.
            __; magenta rm "$BINARY_DIRECTORY/$command_required"; _.
            rm "$BINARY_DIRECTORY/$command_required"
        fi
        if [ ! -f "$BINARY_DIRECTORY/$command_required" ];then
            if [[ "$command_required" =~ ^rcm- ]];then
                [ -z "$fast" ] && isfast='' || isfast=' --fast'
                [ -z "$quiet" ] && isquiet='' || isquiet=' --quiet'
                extension="${command_required:4}"
                if [ -n "$display_waiting" ];then
                    RCM_TABLE_DOWNLOADS="$table_downloads" \
                    RCM_TABLE_DEPENDENCIES="$table_dependencies" \
                    INDENT+="${RCM_INDENT}" \
                    rcm-install $isfast $isquiet "$extension" "$command_required_version" --source=install 2>/dev/null
                    [ ! $? -eq 0 ] && x
                else
                    _.
                    RCM_TABLE_DOWNLOADS="$table_downloads" \
                    RCM_TABLE_DEPENDENCIES="$table_dependencies" \
                    INDENT+="${RCM_INDENT}" \
                    rcm-install $isfast $isquiet "$extension" "$command_required_version" --source=install
                    [ ! $? -eq 0 ] && x
                fi
            elif [[ "$command_required" =~ \.sh$ ]];then
                url=$(grep -F '['$command_required']' <<< "$table_downloads" | tail -1 | sed -E 's/.*\((.*)\).*/\1/')
                if [ -n "$url" ];then
                    Rcm_parse_url "$url"
                    OLDINDENT="$INDENT"; INDENT+=''
                    save_as="$command_required"
                    if [[ $(basename "$PHP_URL_PATH") == "$command_required" ]];then
                        if [ -z "$display_waiting" ];then
                            code rcm get "$url"
                        fi
                        INDENT+="${RCM_INDENT}"
                        Rcm_get "$url"
                    else
                        if [ -z "$display_waiting" ];then
                            code rcm get "$url" --save-as='"'"$command_required"'"'
                        fi
                        INDENT+="${RCM_INDENT}"
                        Rcm_get "$url"
                    fi
                    INDENT="$OLDINDENT"
                fi
            fi
            if ! command -v "$command_required" > /dev/null;then
                if [ -n "$display_waiting" ];then
                    printf "\r\033[K" >&2
                fi
                extension="${command_required:4}"
                error Command '`'$command_required'`' not found, unable to auto download.;
                _ Please execute; magenta ' 'rcm install $extension; _, ' 'manually; _.
                [ -n "$display_waiting" ] && kill -SIGTERM $$
                x
            fi
        elif [[ ! -x "$BINARY_DIRECTORY/$command_required" ]];then
            __; magenta chmod a+x "$BINARY_DIRECTORY/$command_required"; _.
            chmod a+x "$BINARY_DIRECTORY/$command_required"
        fi
    }
    Rcm_resolve_dependencies_update() {
        local is_updated=
        if [[ "$command_required" == rcm ]];then
            # Melakukan rcm self-udpate, maka bash interpreter
            # bisa gagal, karena script rcm berubah.
            # Kita perlu paksa user agar melakukan eksekusi
            # ulang.
            if [ -n "$display_waiting" ];then
                printf "\r\033[K" >&2
            fi
            if [ -z "$display_waiting" ];then
                ____

                chapter Attention
            fi
            __ The subcommand or extension requires rcm to be updated.
            if [ -z "$display_waiting" ];then
                x
            fi
            [ -n "$display_waiting" ] && kill -SIGTERM $$
            # Pastikan exit.
            x
        elif [[ "$command_required" =~ ^rcm- ]];then
            [ -z "$fast" ] && isfast='' || isfast=' --fast'
            [ -z "$quiet" ] && isquiet='' || isquiet=' --quiet'
            extension="${command_required:4}"
            if [ -n "$display_waiting" ];then
                RCM_TABLE_DOWNLOADS="$table_downloads" \
                RCM_TABLE_DEPENDENCIES="$table_dependencies" \
                INDENT+="${RCM_INDENT}" \
                rcm-update $isfast $isquiet "$extension" "$command_required_version" --source=install 2>/dev/null
                [ ! $? -eq 0 ] && x
            else
                _.
                RCM_TABLE_DOWNLOADS="$table_downloads" \
                RCM_TABLE_DEPENDENCIES="$table_dependencies" \
                INDENT+="${RCM_INDENT}" \
                rcm-update $isfast $isquiet "$extension" "$command_required_version" --source=install
                [ ! $? -eq 0 ] && x
            fi

            is_updated=1
        fi
        if [[ -z "$is_updated" ]];then
            if [ -n "$display_waiting" ];then
                printf "\r\033[K" >&2
            fi
            error Gagal Update;
            [ -n "$display_waiting" ] && kill -SIGTERM $$
            x
        fi
    }
    Rcm_resolve_dependencies_insert_table() {
        # global table_dependencies
        # global command_required command_required_version
        # global display_waiting
        local _help _dependency _download
        local _command_required_raw _command_required _command_required_version
        local _found _found_command _found_command_version
        local _line
        if ! grep -q -F -- "${command_required} ${command_required_version}" <<< "$table_dependencies";then
            table_dependencies+="${command_required} ${command_required_version}"$'\n'
        fi
        _help=$("$command_required" --help 2>/dev/null)
        _dependency=$(echo "$_help" | sed -n '/^Dependency:/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p' | sed 's/^ *//g' | grep -E '(^rcm|^rcm-[^:]+|[^:]+\.sh)(:[^:]+)*$')
        if [ -n "$_dependency" ];then
            while IFS= read -r _command_required_raw; do
                if grep -q -F : <<< "$_command_required_raw";then
                    _command_required=$(cut -d':' -f1 <<< "$_command_required_raw")
                    _command_required_version=$(cut -d':' -f2 <<< "$_command_required_raw")
                else
                    _command_required="$_command_required_raw"
                    _command_required_version=
                fi
                _found=$(grep -F "$_command_required"' ' <<< "$table_dependencies")
                if [ -n "$_found" ];then
                    _found_command=$(cut -d' ' -f1 <<< "$_found")
                    _found_command_version=$(cut -d' ' -f2 <<< "$_found")
                    if [ -n "$_command_required_version" ];then
                        if [ ! "$_found_command_version" == "$_command_required_version" ];then
                            if [ -n "$display_waiting" ];then
                                printf "\r\033[K" >&2
                            fi
                            error Conflict found.;
                            _ The command; magenta ' '"$command_required"; _, ':'"$command_required_version" is require; magenta ' '"$_command_required"; _, ':'"$_command_required_version" conflict with requirement of ; magenta ' '"$_found_command"; _, ':'"$_found_command_version".
                            if [ -n "$display_waiting" ];then
                                kill -SIGTERM $$
                            fi
                            # Pastikan exit.
                            x
                        fi
                    fi
                else
                    commands_required_raw+=("$_command_required_raw")
                fi
            done <<< "$_dependency"
        fi
        _download=$(echo "$_help" | sed -n '/^Download:/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p' | sed 's/^ *//g')
        if [ -n "$_download" ];then
            while IFS= read -r _line; do
                if ! grep -q -F -- "$_line" <<< "$table_downloads";then
                    [ -n "$_line" ] && table_downloads+="$_line"$'\n'
                fi
            done <<< "$_download"
        fi
    }
    Rcm_resolve_dependencies_execute() {
        # global command_required_raw
        local command_required command_required_version
        local command_required_exists command_existing_version command_required_exists_updated
        if grep -q -F : <<< "$command_required_raw";then
            command_required=$(cut -d: -f1 <<< "$command_required_raw")
            command_required_version=$(cut -d: -f2 <<< "$command_required_raw")
        else
            command_required="$command_required_raw"
            command_required_version=
        fi
        if command -v "$command_required" > /dev/null;then
            _help=$("$command_required" --help 2>/dev/null)
            _download=$(echo "$_help" | sed -n '/^Download:/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p' | sed 's/^ *//g')
            if [ -n "$_download" ];then
                while IFS= read -r _line; do
                    if ! grep -q -F -- "$_line" <<< "$table_downloads";then
                        [ -n "$_line" ] && table_downloads+="$_line"$'\n'
                    fi
                done <<< "$_download"
            fi
            command_required_exists=1
            command_existing_version=$("$command_required" --version)
            if [ -z "$command_required_version" ];then
                command_required_version="$command_existing_version"
                command_required_exists_updated=1
            else
                if [[ "$command_required_version" == "$command_existing_version" ]];then
                    command_required_exists_updated=1
                else
                    command_required_exists_updated=
                fi
            fi
        else
            if [ -z "$command_required_version" ];then
                command_required_version=`printVersion`
            fi
            command_required_exists=
        fi
        if [ -z "$display_waiting" ];then
            _ Requires command:' '; magenta "$command_required"
            if [ -n "$command_required_exists" ];then
                if [ -n "$command_required_version" ];then
                    _, ':'"$command_required_version"
                fi
                if [ -n "$command_required_exists_updated" ];then
                    green ' [FOUND]'; _, .; _.
                else
                    yellow ' [UPDATE]'; _, .; _.
                fi
            else
                red ' [NOTFOUND]'; _, .; _.
            fi
        fi
        if [ -n "$command_required_exists" ];then
            if [ -z "$command_required_exists_updated" ];then
                Rcm_resolve_dependencies_update
            fi
        else
            Rcm_resolve_dependencies_install
            command_required_version=$("$command_required" --version)
        fi

        Rcm_resolve_dependencies_insert_table
    }
    PATH="${BINARY_DIRECTORY}:${PATH}"
    local commands_required_raw=() command_required_raw="$1"
    if [ -z "$display_waiting" ];then
        chapter Resolve Dependency.
    fi

    # Tambahkan rcm sebagai dependency.
    if ! grep -q -F -- "rcm ${rcm_version}" <<< "$table_dependencies";then
        table_dependencies+="rcm ${rcm_version}"$'\n'
    fi

    Rcm_resolve_dependencies_execute

    until [[ ${#commands_required_raw[@]} -eq 0 ]];do
        for command_required_raw in "${commands_required_raw[@]}"; do
            Rcm_resolve_dependencies_execute
            _command_required_raw=("$command_required_raw")
            ArrayDiff commands_required_raw[@] _command_required_raw[@]
            commands_required_raw=("${_return[@]}")
            unset _return
            unset _command_required_raw
            ArrayUnique commands_required_raw[@]
            commands_required_raw=("${_return[@]}")
            unset _return
        done
    done
    if [ -z "$display_waiting" ];then
        ____
    else
        printf "\r\033[K" >&2
    fi
}

# Title.
title rcm-resolve
____

command="$1"; shift
if [ -z "$command" ];then
    error "Operand <command> required."; x
fi
[ -n "$debug" ] && chapter Dump variable.
[ -n "$debug" ] && code 'command="'$command'"'
[ -n "$debug" ] && code 'BINARY_DIRECTORY="'$BINARY_DIRECTORY'"'
[ -n "$debug" ] && code 'RCM_VERBOSE="'$RCM_VERBOSE'"'
[ -n "$debug" ] && code 'RCM_TABLE_DOWNLOADS="'"$RCM_TABLE_DOWNLOADS"'"'
[ -n "$debug" ] && code 'RCM_TABLE_DEPENDENCIES="'"$RCM_TABLE_DEPENDENCIES"'"'
[ -n "$debug" ] && code 'RCM_FAST="'$RCM_FAST'"'
[ -n "$debug" ] && code 'RCM_VERSION="'$RCM_VERSION'"'
[ -n "$debug" ] && code 'verbose="'$verbose'"'
[ -n "$debug" ] && code 'quiet="'$quiet'"'
[ -n "$debug" ] && code 'loud="'$loud'"'
[ -n "$debug" ] && code 'louder="'$louder'"'
[ -n "$debug" ] && code 'debug="'$debug'"'
[ -n "$debug" ] && ____

# Simpan informasi download.
_download=$(echo "$_help" | sed -n '/^Download:/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p' | sed 's/^ *//g')
if [ -n "$_download" ];then
    while IFS= read -r _line; do
        if ! grep -q -F -- "$_line" <<< "$table_downloads";then
            [ -n "$_line" ] && table_downloads+="$_line"$'\n'
        fi
    done <<< "$_download"
fi
display_waiting=

if [ -n "$quiet" ];then
    display_waiting=1

    chapter Resolve dependency for command '`'$command'`'.
    trap x SIGTERM
    Rcm_resolve_dependencies "${command}" &
    pid=$!
    spin='-\|/'
    i=0
    while kill -0 $pid 2>/dev/null
    do
      i=$(( (i+1) %4 ))
      printf "\r" >&2; __; _, "Waiting...${spin:$i:1}"
      sleep .1
    done
    __ Resolved.
    ____

else
    Rcm_resolve_dependencies "${command}"
fi

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --with-end-options-specific-operand \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# INCREMENT=(
#     '--verbose|-v'
# )
# FLAG=(
# --fast
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# OPERAND=(
# )
# EOF
# clear
