#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.2

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm-history <command> [options]

Options:
   --delete-all ^
        Delete all of history.
   --delete <script> [--delete <script>]...
        Delete history spesific for the script. Multiple.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.

Environment Variables:
   BINARY_DIRECTORY
        Default to $BINARY_DIRECTORY

RCM Config:
   --no-timer
   --no-confirmation
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --delete-all) delete_all=1; shift ;;
        --delete=*) delete+=("${1#*=}"); shift ;;
        --delete) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then delete+=("$2"); shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.
# If not set in argument, try load from environment.
[ -z "$verbose" ] && verbose="$RCM_VERBOSE"
quiet=; loud=; louder=; debug=;
[[ -z "$verbose" || "$verbose" -lt 1 ]] && quiet=1 || quiet=
[[ "$verbose" -gt 0 ]] && loud=1
[[ "$verbose" -gt 1 ]] && loud=1 && louder=1
[[ "$verbose" -gt 2 ]] && loud=1 && louder=1 && debug=1

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm-history
____

directory=$HOME/.cache/rcm
if [ ! -d "$directory" ];then
    exit 0
fi
cd "$directory"
if [ -n "$delete_all" ];then
    rm *.bak 2>/dev/null
    rm *.history 2>/dev/null
    _ All history deleted.; _.
elif [ "${#delete[@]}" -gt 0 ];then
    for each in "${delete[@]}";do
        if [ -f rcm."$each".history ];then
            rm rcm."$each".history
        fi
        if [ -f rcm."$each".bak ];then
            rm rcm."$each".bak
        fi
        _ History "$each" deleted.; _.
    done
else
    ls *.history 2>/dev/null | sed -E 's,^rcm\.(.*)\.history$,\1,' | while read line; do
        _; yellow $line; _.
        if [ -f $line ];then
            contents="$(cat $line)"
            code "$contents"
            ____

        elif [ -f rcm.$line.history ];then
            while read _line; do
                e "$_line"; _.
            done < rcm.${line}.history
            # contents="$(cat rcm.${line}.history)"
            # code "$contents"
            ____
        fi
    done
fi

# parse-options.sh \
# --without-end-options-double-dash \
# --with-end-options-specific-operand \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --delete-all
# )
# VALUE=(
# )
# MULTIVALUE=(
# --delete
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# OPERAND=(
# )
# EOF
# clear
