#!/bin/bash

# Common Functions.
printVersion() {
    echo '0.18.0-alpha.6'
}
red() { echo -ne "\e[91m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
green() { echo -ne "\e[92m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
yellow() { echo -ne "\e[93m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
blue() { echo -ne "\e[94m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
magenta() { echo -ne "\e[95m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
error() { echo -n "$INDENT" >&2; red '#' "$@" >&2; echo >&2; }
success() { echo -n "$INDENT" >&2; green '#' "$@" >&2; echo >&2; }
chapter() { echo -n "$INDENT" >&2; yellow '#' "$@" >&2; echo >&2; }
title() { echo -n "$INDENT" >&2; blue '#' "$@" >&2; echo >&2; }
code() { echo -n "$INDENT" >&2; magenta "$@" >&2; echo >&2; }
x() { echo >&2; exit 1; }
e() { echo -n "$INDENT" >&2; echo -n "$@" >&2; }
_() { echo -n "$INDENT" >&2; echo -n "#"' ' >&2; [ -n "$1" ] && echo -n "$@" >&2; }
_,() { echo -n "$@" >&2; }
_.() { echo >&2; }
__() { echo -n "$INDENT" >&2; echo -n "# ${RCM_INDENT}" >&2; [ -n "$1" ] && echo "$@" >&2; }
____() { echo >&2; [ -n "$RCM_DELAY" ] && sleep "$RCM_DELAY"; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
_n=
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --fast) fast=1; shift ;;
        --no-confirmation) confirmation=0; shift ;;
        --verbose|-v) verbose="$((verbose+1))"; shift ;;
        --)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        *)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
    esac
done
set -- "${_new_arguments[@]}"
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        -[^-]*) OPTIND=1
            while getopts ":v" opt; do
                case $opt in
                    v) verbose="$((verbose+1))" ;;
                esac
            done
            _n="$((OPTIND-1))"
            _n=${!_n}
            shift "$((OPTIND-1))"
            if [[ "$_n" == '--' ]];then
                while [[ $# -gt 0 ]]; do
                    case "$1" in
                        *) _new_arguments+=("$1"); shift ;;
                    esac
                done
            fi
            ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        *)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments
unset _n

# Define variables and constants.
BINARY_DIRECTORY=${BINARY_DIRECTORY:=[__DIR__]}

# Functions.
resolve_relative_path() {
    if [ -d "$1" ];then
        cd "$1" || return 1
        pwd
    elif [ -e "$1" ];then
        if [ ! "${1%/*}" = "$1" ]; then
            cd "${1%/*}" || return 1
        fi
        echo "$(pwd)/${1##*/}"
    else
        return 1
    fi
}

# If not set in argument, try load from environment.
[ -z "$fast" ] && fast="$RCM_FAST"
[ -z "$verbose" ] && verbose="$RCM_VERBOSE"

# If set in environment, set to variable.
[ -n "$RCM_INTERACTIVE" ] && interactive="$RCM_INTERACTIVE"
[ -n "$RCM_LOG" ] && log="$RCM_LOG"
[ -n "$RCM_RESOLVE_DEPENDENCIES" ] && resolve_dependencies="$RCM_RESOLVE_DEPENDENCIES"
[ -n "$RCM_TABLE_DOWNLOADS" ] && table_downloads="$RCM_TABLE_DOWNLOADS"
[ -n "$RCM_TABLE_DEPENDENCIES" ] && table_dependencies="$RCM_TABLE_DEPENDENCIES"
[ -n "$RCM_TABLE_COMMAND_RESOLVED" ] && table_command_resolved="$RCM_TABLE_COMMAND_RESOLVED"
[ -n "$RCM_VERSION" ] && rcm_version="$RCM_VERSION"

# Boolean default to TRUE.
[ -z "$confirmation" ] && confirmation=1; [ "$confirmation" == 0 ] && confirmation=
[ -z "$fast" ] && fast=1; [ "$fast" == 0 ] && fast=
[ -z "$resolve_dependencies" ] && resolve_dependencies=1; [ "$resolve_dependencies" == 0 ] && resolve_dependencies=
[ -z "$interactive" ] && interactive=1; [ "$interactive" == 0 ] && interactive=

# Verbosity.
quiet=; loud=; louder=; debug=;
[[ -z "$verbose" || "$verbose" -lt 1 ]] && quiet=1 || quiet=
[[ "$verbose" -gt 0 ]] && loud=1
[[ "$verbose" -gt 1 ]] && loud=1 && louder=1
[[ "$verbose" -gt 2 ]] && loud=1 && louder=1 && debug=1

# Define variables and constants.
RCM_DELAY=${RCM_DELAY:=.5}; [ -n "$fast" ] && unset RCM_DELAY
RCM_INDENT='    '; [ "$(tput cols)" -le 80 ] && RCM_INDENT='  '
[ -z "$log" ] && log=rcm.log
__FILE__=$(resolve_relative_path "$0")
__DIR__=$(dirname "$__FILE__")
find='[__DIR__]'
replace="$__DIR__"
BINARY_DIRECTORY="${BINARY_DIRECTORY/"$find"/"$replace"}"

# Functions. Help and Version.
printHelp() {
    title Rapid Construct Massive
    _ 'Execute extension'; _.
    _ 'Version '; yellow `printVersion`; _.
    _.
cat << EOF
Usage: rcm-exec <command> [options]

Global Options:
   --fast
        No delay every subtask.
   --version
        Print version of this script.
   --help
        Show this help.

EOF
}

# Help and Version.
[ -n "$help" ] && { printHelp; exit 1; }
[ -n "$version" ] && { printVersion; exit 1; }

# Functions.
ArrayDiff() {
    # Computes the difference of arrays.
    #
    # Globals:
    #   Modified: _return
    #
    # Arguments:
    #   1 = Parameter of the array to compare from.
    #   2 = Parameter of the array to compare against.
    #
    # Returns:
    #   None
    #
    # Example:
    #   ```
    #   my=("cherry" "manggo" "blackberry" "manggo" "blackberry")
    #   yours=("cherry" "blackberry")
    #   ArrayDiff my[@] yours[@]
    #   # Get result in variable `$_return`.
    #   # _return=("manggo" "manggo")
    #   ```
    local e
    local source=("${!1}")
    local reference=("${!2}")
    _return=()
    # inArray is alternative of ArraySearch.
    inArray () {
        local e match="$1"
        shift
        for e; do [[ "$e" == "$match" ]] && return 0; done
        return 1
    }
    if [[ "${#reference[@]}" -gt 0 ]];then
        for e in "${source[@]}";do
            if ! inArray "$e" "${reference[@]}";then
                _return+=("$e")
            fi
        done
    else
        _return=("${source[@]}")
    fi
}
ArrayUnique() {
    # Removes duplicate values from an array.
    #
    # Globals:
    #   Modified: _return
    #
    # Arguments:
    #   1 = Parameter of the input array.
    #
    # Returns:
    #   None
    #
    # Example:
    #   ```
    #   my=("cherry" "manggo" "blackberry" "manggo" "blackberry")
    #   ArrayUnique my[@]
    #   # Get result in variable `$_return`.
    #   # _return=("cherry" "manggo" "blackberry")
    #   ```
    local e source=("${!1}")
    # inArray is alternative of ArraySearch.
    inArray () {
        local e match="$1"
        shift
        for e; do [[ "$e" == "$match" ]] && return 0; done
        return 1
    }
    _return=()
    for e in "${source[@]}";do
        if ! inArray "$e" "${_return[@]}";then
            _return+=("$e")
        fi
    done
}
wordWrapDescription() {
    local paragraph="$1" indent_first_line=$2 words_array
    local current_line first_line last
    local max=0
    local min=0
    local _indent_first_line
    [ -z "$indent_first_line" ] && indent_first_line=1
    indent_first_line=$((indent_first_line*${#RCM_INDENT}))
    _indent_first_line=$((indent_first_line + 2))
    # Angka 2 adalah tambahan dari '# '.
    max=$(tput cols)
    _max=$((100 + ${#INDENT} + $_indent_first_line))
    if [ $max -gt $_max ];then
        max=100
        min=80
    else
        max=$((max - ${#INDENT} - 6))
        min="$max"
    fi

    local i=0
    words_array=($paragraph)
    local count="${#words_array[@]}"
    current_line=
    first_line=1
    for each in "${words_array[@]}"; do
        let i++
        [ "$i" == "$count" ] && last=1 || last=
        if [ -z "$current_line" ]; then
            if [ -n "$first_line" ];then
                first_line=
                current_line="$each"
                _; printf %"${indent_first_line}"s >&2; _, "$each"
            else
                current_line="$each"
                _; printf %"${indent_first_line}"s >&2; _, "$each"
            fi
            if [ -n "$last" ];then
                _.
            fi
        else
            _current_line="${current_line} ${each}"
            if [ "${#_current_line}" -le $min ];then
                current_line+=" ${each}"
                _, " ${each}"
                if [ -n "$last" ];then
                    _.
                fi
            elif [ "${#_current_line}" -le $max ];then
                _, " ${each}"; _.
                current_line=
            else
                _.;
                _; printf %"${indent_first_line}"s >&2;
                _, "$each"
                current_line="$each"
                if [ -n "$last" ];then
                    _.
                fi
            fi
        fi
    done
}
wordWrapDescriptionColorize() {
    cleaningTag() {
        # global each
        # global color
        local string="$1"
        opentag=$(echo "$string" | grep -E -o '<[^</>]+>')
        if [ -n "$opentag" ];then
            color=$(echo "$opentag" | grep -E -o '[^<>]+')
            string=${string//"$opentag"/}
            closetag="</${color}>"
            if grep -q -F "$closetag" <<< "$string";then
                color_stop=1
                string=${string//"$closetag"/}
            fi
        fi
        each="$string"
    }
    cleaningCloseTag() {
        # global each
        # global color
        local string="$1"
        closetag="</${color}>"
        if grep -q -F "$closetag" <<< "$string";then
            color_stop=1
            string=${string//"$closetag"/}
        fi
        each="$string"
    }
    colorStop() {
        # global color_stop
        if [ -n "$color_stop" ];then
            color=$default_color
            color_stop=
        fi
    }
    local paragraph="$1" words_array default_color="$2"
    [ -z $default_color ] && default_color=_,
    color="$default_color"
    local current_line first_line last
    local max=0
    local min=0
    max=$(tput cols)
    # Angka 6 adalah 4+2.
    # Angka 4 adalah tambahan indent.
    # Angka 2 adalah tambahan dari '# '.
    _max=$((100 + ${#INDENT} + ${#RCM_INDENT} + 2))
    if [ $max -gt $_max ];then
        max=100
        min=80
    else
        max=$((max - ${#INDENT} - ${#RCM_INDENT} - 2))
        min="$max"
    fi
    local i=0
    words_array=($paragraph)
    local count="${#words_array[@]}"
    current_line=
    first_line=1

    wordWrapSentence() {
        for each in "${words_array[@]}"; do
            cleaningTag "$each"
            cleaningCloseTag "$each"
            let i++
            [ "$i" == "$count" ] && last=1 || last=
            if [ -z "$current_line" ]; then
                if [ -n "$first_line" ];then
                    first_line=
                    current_line="$each"
                    __; $color "$each"
                else
                    current_line="$each"
                    __; $color "$each"
                fi
                if [ -n "$last" ];then
                    _.
                fi
            else
                _current_line="${current_line} ${each}"
                if [ "${#_current_line}" -le $min ];then
                    current_line+=" ${each}"
                    $color " ${each}"
                    if [ -n "$last" ];then
                        _.
                    fi
                elif [ "${#_current_line}" -le $max ];then
                    $color " ${each}"; _.
                    current_line=
                else
                    _.; __; $color "$each"
                    current_line="$each"
                    if [ -n "$last" ];then
                        _.
                    fi
                fi
            fi
            colorStop
        done
    }
    temp=$(wordWrapSentence 2>&1)
    echo "$temp" >&2
}
fileMustExists() {
    # global used:
    # global modified:
    # function used: __, success, error, x
    if [ -f "$1" ];then
        __; green File '`'$(basename "$1")'`' ditemukan.; _.
    else
        __; red File '`'$(basename "$1")'`' tidak ditemukan.; x
    fi
}
userInputBooleanDefaultYes() {
    _; _.
    __;  _, '['; yellow Enter; _, ']'; _, ' '; yellow Y; _, 'es and continue.'; _.
    __;  _, '['; yellow Esc; _, ']'; _, ' '; yellow N; _, 'o and skip.'; _.
    boolean=
    _; _.
    __ Press the yellow key to select.
    while true; do
        __; read -rsn 1 -p "Select: " char
        if [ -z "$char" ];then
            char=y
        fi
        case $char in
            y|Y) echo "$char" >&2; boolean=1; break;;
            n|N) echo "$char" >&2; break ;;
            $'\33') echo "n" >&2; break ;;
            *) echo >&2
        esac
    done
}
userInputBooleanDefaultNo() {
    _; _.
    __;  _, '['; yellow Enter; _, ']'; _, ' '; yellow N; _, 'o and skip.'; _.
    __;  _, '['; yellow Y; _, ']'; _, ' '; yellow Y; _, 'es and continue.'; _.
    boolean=
    _; _.
    __ Press the yellow key to select.
    while true; do
        __; read -rsn 1 -p "Select: " char
        if [ -z "$char" ];then
            char=n
        fi
        case $char in
            y|Y) echo "$char" >&2; boolean=1; break;;
            n|N) echo "$char" >&2; break ;;
            *) echo >&2
        esac
    done
}
printBackupDialog() {
    _; _.
    wordWrapDescriptionColorize "Restore the value: <yellow>$backup_value</yellow>. Would you like to use that value?"
    userInputBooleanDefaultYes
    if [ -n "$boolean" ];then
        _; _.
        value="$backup_value";
        if [ -n "$is_flag" ];then
            wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> added with value <yellow>$value</yellow> which is restored." green
        else
            wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> filled with value <yellow>$value</yellow> which is restored." green
        fi
    fi
}
printBackupFlagDialog() {
    _; _.
    wordWrapDescription "This argument has been added before. Would you like to restore this argument?"
    userInputBooleanDefaultYes
    if [ -n "$boolean" ];then
        _; _.
        wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> added which is restored." green
    fi
}
printHistoryDialog() {
    local count_max=$(wc -l <<< "$history_value")
    if [ $count_max -gt 9 ];then
        count_max=9
    fi
    unset count
    declare -i count
    count=0
    _; _.
    wordWrapDescription 'There are values available from history.'

    while read opt; do
        count+=1
        __; _, '['; yellow $count; _, ']'; _, ' '; _, "$opt"; _.
    done <<< "$history_value"
    _; _.
    __;  _, '['; yellow Enter; _, ']'; _, ' '; yellow S; _, 'kip and continue.'; _.
    _; _.
    __ Press the yellow key to select.
    while true; do
        __; read -rsn 1 -p "Select: " char;
        if [ -z "$char" ];then
            char=s
        fi
        case $char in
            s|S) echo "$char" >&2; break ;;
            [1-$count_max])
                echo "$char" >&2
                value=$(sed -n ${char}p <<< "$history_value")
                save_history=
                break ;;
            *) echo >&2
        esac
    done
}
printSelectDialog() {
    declare -i count
    declare -i new_line
    local source=("${!1}")
    local what="$2"
    local each reference_key
    if [ -z "$what" ];then
        what=value
        if [ "${#source[@]}" -gt 1 ];then
            what=values
        fi
    fi
    _; _.
    words_array=("${source[@]}")
    wordWrapList "Available ${what}:"
    _; _.
    __; _, '['; yellow Enter; _, ']'; _, ' '; yellow T; _, 'ype the value.'; _.
    __; _, '['; yellow Backspace; _, ']'; _, ' '; yellow S; _, 'witch to select list.'; _.
    if [ -z "$is_required" ];then
        __; _, '['; yellow Esc; _, ']'; _, ' '; yellow L; _, 'eave blank and skip.'; _.
    fi
    _; _.
    __ Press the yellow key to select.
    select_mode=
    local type_mode=
    local skip=
    while true; do
        __; read -rsn 1 -p "Select: " char;
        if [ -z "$char" ];then
            char=t
        fi
        if [ -n "$is_required" ];then
            case $char in
                t|T) type_mode=1; echo "$char" >&2; break ;;
                s|S) select_mode=1; echo "$char" >&2; break ;;
                $'\177') select_mode=1; echo "s" >&2; break ;;
                *) echo >&2; new_line+=1
            esac
        else
            case $char in
                t|T) type_mode=1; echo "$char" >&2; break ;;
                s|S) select_mode=1; echo "$char" >&2; break ;;
                $'\177') select_mode=1; echo "s" >&2; break ;;
                $'\33') skip=1; echo "l" >&2; break ;;
                l|L) skip=1; echo "$char" >&2; break ;;
                *) echo >&2; new_line+=1
            esac
        fi
    done
    # Credit: https://stackoverflow.com/questions/5861428/bash-script-erase-previous-line
    PREVIOUS_LINE=5
    if [ -z "$is_required" ];then
        PREVIOUS_LINE=$((PREVIOUS_LINE+1))
    fi
    if [[ -n "$select_mode" ]];then
        PREVIOUS_LINE=$((PREVIOUS_LINE+WRAP_LINE+1+new_line))
        for ((i = 0 ; i < $PREVIOUS_LINE ; i++)); do
            printf '\e[A\e[K' >&2
        done
        __ "Available ${what}:"
        for ((i = 0 ; i < ${#source[@]} ; i++)); do
            count+=1
            if [ $count -lt 10 ];then
                __; _, '['; yellow $count; _, ']'; _, ' '; _, "${source[$i]}"; _.
            else
                __; _, '['$count']' "${source[$i]}"; _.
            fi
        done
        _; _.
        __; _, '['; yellow Enter; _, ']'; _, ' '; _, 'Type the '; yellow N; _, 'umber key.'; _.
        if [ -z "$is_required" ];then
            __; _, '['; yellow Esc; _, ']'; _, ' '; yellow L; _, 'eave blank and skip.'; _.
        fi
        _; _.
        __ Press the yellow key to select.
        count_max="${#source[@]}"
        if [ $count_max -gt 9 ];then
            count_max=9
        fi
        while true; do
            __; read -rsn 1 -p "Select: " char;
            if [ -z "$char" ];then
                char=n
            fi
            case $char in
                n|N) echo "$char" >&2; break ;;
                [1-$count_max])
                    echo "$char" >&2
                    i=$((char - 1))
                    value="${source[$i]}"
                    break ;;
                *)
                    if [ -n "$is_required" ];then
                        echo >&2
                    else
                        case $char in
                            $'\33') skip=1; echo "l" >&2; break ;;
                            l|L) skip=1; echo "$char" >&2; break ;;
                            *) echo >&2
                        esac
                    fi
            esac
        done
        if [[ -z "$skip" ]];then
            if [ -z "$value" ];then
                _; _.
            fi
            until [ -n "$value" ];do
                __; read -p "Type the number: " value
                if [[ $value =~ [^0-9] ]];then
                    value=
                    __; red Please type one of available number.;_.
                fi
                if [[ $value =~ ^0 ]];then
                    value=
                    __; red Please type one of available number.;_.
                fi
                if [ -n "$value" ];then
                    value=$((value - 1))
                    value="${source[$value]}"
                    if [ -z "$value" ];then
                        __; red Please type one of available number.;_.
                    fi
                fi
            done
            _; _.
            wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> filled with value <yellow>$value</yellow> which is selected from the list." green
        fi
    fi
    if [[ -n "$type_mode" ]];then
        _; _.
    fi
    while true; do
        if [ -n "$value" ];then
            ArraySearch "$value" source[@]
            reference_key="$_return"; unset _return; # Clear.
            if [ -n "$reference_key" ];then
                break
            else
                __; red Please type one of available values.;_.
                value=
            fi
        else
            if [ -n "$is_required" ];then
                __; read -p "Type the value: " value
            elif [ -z "$skip" ];then
                __; read -p "Type the value or leave blank to skip: " value
                if [ -z "$value" ];then
                    break
                fi
            else
                break
            fi
        fi
    done
}
printSelectOtherDialog() {
    declare -i count
    declare -i new_line
    local source=("${!1}")
    local what="$2"
    local each reference_key
    if [ -z "$what" ];then
        what=value
        if [ "${#source[@]}" -gt 1 ];then
            what=values
        fi
    fi
    _; _.
    words_array=("${source[@]}")
    words_array+=(other)
    wordWrapList "Available ${what}:"
    _; _.
    __; _, '['; yellow Enter; _, ']'; _, ' '; yellow T; _, 'ype the value.'; _.
    __; _, '['; yellow Backspace; _, ']'; _, ' '; yellow S; _, 'witch to select list.'; _.
    if [ -z "$is_required" ];then
        __; _, '['; yellow Esc; _, ']'; _, ' '; yellow L; _, 'eave blank and skip.'; _.
    fi
    _; _.
    __ Press the yellow key to select.
    local select_mode=
    local type_mode=
    local skip=
    while true; do
        __; read -rsn 1 -p "Select: " char;
        if [ -z "$char" ];then
            char=t
        fi
        case $char in
            t|T) type_mode=1; echo "$char" >&2; break ;;
            s|S) select_mode=1; echo "$char" >&2; break ;;
            $'\177') select_mode=1; echo "s" >&2; break ;;
            *)
                if [ -n "$is_required" ];then
                    echo >&2; new_line+=1
                else
                    case $char in
                        $'\33') skip=1; echo "l" >&2; break ;;
                        l|L) skip=1; echo "$char" >&2; break ;;
                        *) echo >&2; new_line+=1
                    esac
                fi
        esac
    done
    # Credit: https://stackoverflow.com/questions/5861428/bash-script-erase-previous-line
    PREVIOUS_LINE=5
    if [ -z "$is_required" ];then
        PREVIOUS_LINE=$((PREVIOUS_LINE+1))
    fi
    if [[ -n "$select_mode" ]];then
        PREVIOUS_LINE=$((PREVIOUS_LINE+WRAP_LINE+1+new_line))
        for ((i = 0 ; i < $PREVIOUS_LINE ; i++)); do
            printf '\e[A\e[K' >&2
        done
        __ Available values:
        for ((i = 0 ; i < ${#source[@]} ; i++)); do
            count+=1
            if [ $count -lt 10 ];then
                __; _, '['; yellow $count; _, ']'; _, ' '; _, "${source[$i]}"; _.
            else
                __; _, '['$count']' "${source[$i]}"; _.
            fi
        done
        _; _.
        __; _, '['; yellow Enter; _, ']'; _, ' '; _, 'Type the '; yellow N; _, 'umber key.'; _.
        __; _, '['; yellow Backspace; _, ']'; _, ' '; _, 'Switch to '; yellow T; _, 'ype other value.'; _.
        if [ -z "$is_required" ];then
            __; _, '['; yellow Esc; _, ']'; _, ' '; yellow L; _, 'eave blank and skip.'; _.
        fi
        _; _.
        __ Press the yellow key to select.
        count_max="${#source[@]}"
        if [ $count_max -gt 9 ];then
            count_max=9
        fi
        while true; do
            __; read -rsn 1 -p "Select: " char;
            if [ -z "$char" ];then
                char=n
            fi
            case $char in
                t|T) type_mode=1; echo "$char" >&2; break ;;
                $'\177') type_mode=1; echo "s" >&2; break ;;
                n|N) echo "$char" >&2; break ;;
                [1-$count_max])
                    echo "$char" >&2
                    i=$((char - 1))
                    value="${source[$i]}"
                    break ;;
                *)
                    if [ -n "$is_required" ];then
                        echo >&2
                    else
                        case $char in
                            $'\33') skip=1; echo "l" >&2; break ;;
                            l|L) skip=1; echo "$char" >&2; break ;;
                            *) echo >&2
                        esac
                    fi
            esac
        done
        if [[ -z "$type_mode" && -z "$skip" ]];then
            if [ -z "$value" ];then
                _; _.
            fi
            until [ -n "$value" ];do
                __; read -p "Type the number: " value
                if [[ $value =~ [^0-9] ]];then
                    value=
                    __; red Please type one of available number.;_.
                fi
                if [[ $value =~ ^0 ]];then
                    value=
                    __; red Please type one of available number.;_.
                fi
                if [ -n "$value" ];then
                    value=$((value - 1))
                    value="${source[$value]}"
                    if [ -z "$value" ];then
                        __; red Please type one of available number.;_.
                    fi
                fi
            done
            _; _.
            wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> filled with value <yellow>$value</yellow> which is selected from the list." green
        fi
    fi
    if [[ -n "$type_mode" ]];then
        _; _.
        if [ -z "$value" ];then
            if [ -n "$is_required" ];then
                __; read -p "Type the value: " value
            elif [ -z "$skip" ];then
                __; read -p "Type the value or leave blank to skip: " value
            fi
            is_typing=1
        fi
    fi
}
sleepExtended() {
    # Menggunakan global variable countdown agar sleep ini dapat di-interupsi.
    # Contoh:
    # ```
    # immediately() {
    #     countdown=0
    # }
    # trap immediately SIGINT
    # sleepExtended 30
    # trap x SIGINT
    # ```
    local timer=$1
    local width=$2
    if [ -z "$width" ];then
        width=80
    fi
    if [ "$timer" -gt 0 ];then
        dikali10=$((timer*10))
        countdown=$dikali10
        _dotLength=$(( ( width * countdown ) / dikali10 ))
        printf "\r\033[K" >&2
        e; printf %"$_dotLength"s | tr " " "." >&2
        printf "\r" >&2
        while [ "$countdown" -ge 0 ]; do
            dotLength=$(( ( width * countdown ) / dikali10 ))
            if [[ ! "$dotLength" == "$_dotLength" ]];then
                _dotLength="$dotLength"
                printf "\r\033[K" >&2
                e; printf %"$dotLength"s | tr " " "." >&2
                printf "\r" >&2
            fi
            countdown=$((countdown - 1))
            sleep .1
        done
    fi
}
immediately() {
    countdown=0
}
backupFile() {
    local mode="$1"
    local oldpath="$2" i newpath
    local target_dir="$3"
    i=1
    dirname=$(dirname "$oldpath")
    basename=$(basename "$oldpath")
    if [ -n "$target_dir" ];then
        case "$target_dir" in
            parent) dirname=$(dirname "$dirname") ;;
            *) dirname="$target_dir"
        esac
    fi
    [ -d "$dirname" ] || { echo 'Directory is not exists.' >&2; return 1; }
    newpath="${dirname}/${basename}.${i}"
    if [ -f "$newpath" ]; then
        let i++
        newpath="${dirname}/${basename}.${i}"
        while [ -f "$newpath" ] ; do
            let i++
            newpath="${dirname}/${basename}.${i}"
        done
    fi
    case $mode in
        move)
            mv "$oldpath" "$newpath" ;;
        copy)
            local user=$(stat -c "%U" "$oldpath")
            local group=$(stat -c "%G" "$oldpath")
            cp "$oldpath" "$newpath"
            chown ${user}:${group} "$newpath"
    esac
}
Rcm_parse_url() {
    # Reset
    PHP_URL_SCHEME=
    PHP_URL_HOST=
    PHP_URL_PORT=
    PHP_URL_USER=
    PHP_URL_PASS=
    PHP_URL_PATH=
    PHP_URL_QUERY=
    PHP_URL_FRAGMENT=
    PHP_URL_SCHEME="$(echo "$1" | grep :// | sed -e's,^\(.*\)://.*,\1,g')"
    _PHP_URL_SCHEME_SLASH="${PHP_URL_SCHEME}://"
    _PHP_URL_SCHEME_REVERSE="$(echo ${1/${_PHP_URL_SCHEME_SLASH}/})"
    if grep -q '#' <<< "$_PHP_URL_SCHEME_REVERSE";then
        PHP_URL_FRAGMENT=$(echo $_PHP_URL_SCHEME_REVERSE | cut -d# -f2)
        _PHP_URL_SCHEME_REVERSE=$(echo $_PHP_URL_SCHEME_REVERSE | cut -d# -f1)
    fi
    if grep -q '\?' <<< "$_PHP_URL_SCHEME_REVERSE";then
        PHP_URL_QUERY=$(echo $_PHP_URL_SCHEME_REVERSE | cut -d? -f2)
        _PHP_URL_SCHEME_REVERSE=$(echo $_PHP_URL_SCHEME_REVERSE | cut -d? -f1)
    fi
    _PHP_URL_USER_PASS="$(echo $_PHP_URL_SCHEME_REVERSE | grep @ | cut -d@ -f1)"
    PHP_URL_PASS=`echo $_PHP_URL_USER_PASS | grep : | cut -d: -f2`
    if [ -n "$PHP_URL_PASS" ]; then
        PHP_URL_USER=`echo $_PHP_URL_USER_PASS | grep : | cut -d: -f1`
    else
        PHP_URL_USER=$_PHP_URL_USER_PASS
    fi
    _PHP_URL_HOST_PORT="$(echo ${_PHP_URL_SCHEME_REVERSE/$_PHP_URL_USER_PASS@/} | cut -d/ -f1)"
    PHP_URL_HOST="$(echo $_PHP_URL_HOST_PORT | sed -e 's,:.*,,g')"
    if grep -q -E ':[0-9]+$' <<< "$_PHP_URL_HOST_PORT";then
        PHP_URL_PORT="$(echo $_PHP_URL_HOST_PORT | sed -e 's,^.*:,:,g' -e 's,.*:\([0-9]*\).*,\1,g' -e 's,[^0-9],,g')"
    fi
    _PHP_URL_HOST_PORT_LENGTH=${#_PHP_URL_HOST_PORT}
    _LENGTH="$_PHP_URL_HOST_PORT_LENGTH"
    if [ -n "$_PHP_URL_USER_PASS" ];then
        _PHP_URL_USER_PASS_LENGTH=${#_PHP_URL_USER_PASS}
        _LENGTH=$((_LENGTH + 1 + _PHP_URL_USER_PASS_LENGTH))
    fi
    PHP_URL_PATH="${_PHP_URL_SCHEME_REVERSE:$_LENGTH}"

    # Debug
    # e '"$PHP_URL_SCHEME"' "$PHP_URL_SCHEME"
    # e '"$PHP_URL_HOST"' "$PHP_URL_HOST"
    # e '"$PHP_URL_PORT"' "$PHP_URL_PORT"
    # e '"$PHP_URL_USER"' "$PHP_URL_USER"
    # e '"$PHP_URL_PASS"' "$PHP_URL_PASS"
    # e '"$PHP_URL_PATH"' "$PHP_URL_PATH"
    # e '"$PHP_URL_QUERY"' "$PHP_URL_QUERY"
    # e '"$PHP_URL_FRAGMENT"' "$PHP_URL_FRAGMENT"
}

# Title.
title rcm-exec
____

command="$1"; shift
if [ -z "$command" ];then
    error "Operand <command> required."; x
fi
[ -n "$debug" ] && chapter Dump variable.
[ -n "$debug" ] && code 'command="'$command'"'
[ -n "$debug" ] && code 'BINARY_DIRECTORY="'$BINARY_DIRECTORY'"'
[ -n "$debug" ] && code 'RCM_INTERACTIVE="'$RCM_INTERACTIVE'"'
[ -n "$debug" ] && code 'RCM_VERBOSE="'$RCM_VERBOSE'"'
[ -n "$debug" ] && code 'RCM_RESOLVE_DEPENDENCIES="'$RCM_RESOLVE_DEPENDENCIES'"'
[ -n "$debug" ] && code 'RCM_TABLE_DOWNLOADS="'"$RCM_TABLE_DOWNLOADS"'"'
[ -n "$debug" ] && code 'RCM_TABLE_DEPENDENCIES="'"$RCM_TABLE_DEPENDENCIES"'"'
[ -n "$debug" ] && code 'RCM_TABLE_COMMAND_RESOLVED="'"$RCM_TABLE_COMMAND_RESOLVED"'"'
[ -n "$debug" ] && code 'RCM_FAST="'$RCM_FAST'"'
[ -n "$debug" ] && code 'RCM_LOG="'$RCM_LOG'"'
[ -n "$debug" ] && code 'RCM_VERSION="'$RCM_VERSION'"'
[ -n "$debug" ] && code 'interactive="'$interactive'"'
[ -n "$debug" ] && code 'verbose="'$verbose'"'
[ -n "$debug" ] && code 'quiet="'$quiet'"'
[ -n "$debug" ] && code 'loud="'$loud'"'
[ -n "$debug" ] && code 'louder="'$louder'"'
[ -n "$debug" ] && code 'debug="'$debug'"'
[ -n "$debug" ] && code 'resolve_dependencies="'$resolve_dependencies'"'
[ -n "$debug" ] && code 'log="'$log'"'
if [[ ! "$command" =~ ^rcm- ]];then
    error Command is not valid; x
fi
extension="${command:4}"
[ -n "$debug" ] && code 'extension="'$extension'"'
[ -z "$rcm_version" ] && rcm_version=$(rcm --version)
[ -n "$debug" ] && code 'rcm_version="'$rcm_version'"'

[ -n "$debug" ] && ____

# Title.
# title rcm-exec
# ____

# Functions.
# https://github.com/ijortengab/bash/tree/master/functions
ArraySearch() {
    local index match="$1"
    local source=("${!2}")
    for index in "${!source[@]}"; do
       if [[ "${source[$index]}" == "${match}" ]]; then
           _return=$index; return 0
       fi
    done
    return 1
}
ArrayDiff() {
    # Computes the difference of arrays.
    #
    # Globals:
    #   Modified: _return
    #
    # Arguments:
    #   1 = Parameter of the array to compare from.
    #   2 = Parameter of the array to compare against.
    #
    # Returns:
    #   None
    #
    # Example:
    #   ```
    #   my=("cherry" "manggo" "blackberry" "manggo" "blackberry")
    #   yours=("cherry" "blackberry")
    #   ArrayDiff my[@] yours[@]
    #   # Get result in variable `$_return`.
    #   # _return=("manggo" "manggo")
    #   ```
    local e
    local source=("${!1}")
    local reference=("${!2}")
    _return=()
    # inArray is alternative of ArraySearch.
    inArray () {
        local e match="$1"
        shift
        for e; do [[ "$e" == "$match" ]] && return 0; done
        return 1
    }
    if [[ "${#reference[@]}" -gt 0 ]];then
        for e in "${source[@]}";do
            if ! inArray "$e" "${reference[@]}";then
                _return+=("$e")
            fi
        done
    else
        _return=("${source[@]}")
    fi
}
ArrayUnique() {
    # Removes duplicate values from an array.
    #
    # Globals:
    #   Modified: _return
    #
    # Arguments:
    #   1 = Parameter of the input array.
    #
    # Returns:
    #   None
    #
    # Example:
    #   ```
    #   my=("cherry" "manggo" "blackberry" "manggo" "blackberry")
    #   ArrayUnique my[@]
    #   # Get result in variable `$_return`.
    #   # _return=("cherry" "manggo" "blackberry")
    #   ```
    local e source=("${!1}")
    # inArray is alternative of ArraySearch.
    inArray () {
        local e match="$1"
        shift
        for e; do [[ "$e" == "$match" ]] && return 0; done
        return 1
    }
    _return=()
    for e in "${source[@]}";do
        if ! inArray "$e" "${_return[@]}";then
            _return+=("$e")
        fi
    done
}
ArrayShift() {
    local index
    local source=("${!1}")
    _return=()
    for (( index=1; index < ${#source[@]} ; index++ )); do
        _return+=("${source[$index]}")
    done
}
ArrayRemove() {
    local index match="$1"
    _return=("${!2}")
    for index in "${!_return[@]}"; do
       if [[ "${_return[$index]}" == "${match}" ]]; then
            _return=("${_return[@]:0:$index}" "${_return[@]:$(($index + 1))}")
           break
       fi
    done
}
ArrayRemoveAll() {
    local index match="$1"
    local source=("${!2}")
    _return=()
    for index in "${!source[@]}"; do
       if [[ ! "${source[$index]}" == "${match}" ]]; then
           _return+=("${source[$index]}")
       fi
    done
}
wordWrapCommand() {
    # global words_array RCM_INDENT
    local inline_description="$1"
    local current_line first_line
    local each
    declare -i max
    declare -i min

    max=$(tput cols)
    # Angka 2 adalah tambahan dari ' \'.
    _max=$((100 + ${#INDENT} + 2))
    if [ $max -gt $_max ];then
        max=100
        min=80
    else
        max=$((max - ${#INDENT} - 2))
        min="$max"
    fi

    declare -i i; i=0
    local count="${#words_array[@]}"
    current_line=
    first_line=1
    for each in "${words_array[@]}"; do
        i+=1
        [ "$i" == "$count" ] && last=1 || last=
        if [ -z "$current_line" ]; then
            if [ -z "$first_line" ];then
                current_line="${RCM_INDENT}${each}"
                e; magenta "${RCM_INDENT}$each";
            else
                first_line=
                if [ -n "$inline_description" ];then
                    e; _, "${inline_description} "; magenta "$each"
                    current_line="${inline_description} ${each}"
                else
                    e; magenta "$each"
                    current_line="$each"
                fi
            fi
            if [ -n "$last" ];then
                _.
            fi
        else
            _current_line="${current_line} ${each}"
            if [ "${#_current_line}" -le $min ];then
                if [ -n "$last" ];then
                    _, ' '; magenta "$each"; _.
                else
                    _, ' '; magenta "$each"
                fi
                current_line+=" ${each}"
            elif [ "${#_current_line}" -le $max ];then
                if [ -n "$last" ];then
                    _, ' '; magenta "${each}"''; _.
                else
                    _, ' '; magenta "${each}"' \'; _.
                fi
                current_line=
            else
                magenta ' \'; _.; e; magenta "${RCM_INDENT}$each"
                current_line="${RCM_INDENT}${each}"
                if [ -n "$last" ];then
                    _.
                fi
            fi
        fi
    done
}
wordWrapList() {
    # global words_array
    local inline_description="$1"
    local current_line first_line last
    declare -i max
    declare -i min

    max=$(tput cols)
    # Angka 11 adalah 4+2+5.
    # Angka 4 adalah tambahan indent.
    # Angka 2 adalah tambahan dari '# '.
    # Angka 5 adalah tambahan dari ', or '.
    _max=$((100 + ${#INDENT} + 11))
    if [ $max -gt $_max ];then
        max=100
        min=80
    else
        max=$((max - ${#INDENT} - 11))
        min="$max"
    fi

    declare -i i; i=0
    WRAP_LINE=1
    local count="${#words_array[@]}"
    current_line=
    first_line=1
    for each in "${words_array[@]}"; do
        i+=1
        [ "$i" == "$count" ] && last=1 || last=
        if [ -z "$current_line" ]; then
            if [ -n "$first_line" ];then
                first_line=
                current_line="${inline_description} ${each}"
                __; _, "${inline_description} "; yellow "$each"
            else
                if [ -n "$last" ];then
                    __; _, 'or '; yellow "$each"
                    current_line="or ${each}"
                else
                    __; yellow "$each"
                    current_line="$each"
                fi
            fi
            if [ -n "$last" ];then
                _, '.'; _.
            fi
        else
            if [ -n "$last" ];then
                _current_line="${current_line}, or ${each}"
            else
                _current_line="${current_line}, ${each}"
            fi
            if [ "${#_current_line}" -le $min ];then
                if [ -n "$last" ];then
                    _, ', or '; yellow "$each"; _, '.'; _.
                else
                    _, ', '; yellow "$each"
                fi
                current_line+=", ${each}"
            elif [ "${#_current_line}" -le $max ];then
                if [ -n "$last" ];then
                    _, ', or '; yellow "$each"; _, '.'; _.
                else
                    _, ', '; yellow "$each"; _, ','; _.
                    WRAP_LINE=$((WRAP_LINE+1))
                fi
                current_line=
            else
                WRAP_LINE=$((WRAP_LINE+1))
                if [ -n "$last" ];then
                    _.; __; _, 'or '; yellow "$each"; _, '.'; _.
                    current_line="or ${each}"
                else
                    _, ,; _.; __; yellow "$each"
                    current_line="$each"
                fi
            fi
        fi
    done
}
is_command_resolved() {
    if [ -z "$resolve_dependencies" ];then
        return 0
    fi
    if grep -q -F "$rcm_extension" <<< "$table_command_resolved";then
        return 0
    fi
    return 1
}
Rcm_prompt() {
    # global subcommand
    local first_operand
    local value
    local command="$1"
    local chapter_printed=
    local load_other_options=
    local immediately_other_options=
    local argument_preview_bypass=
    local available_subcommands
    argument_pass=()
    argument_preview=()
    argument_preview_real=()
    argument_placeholders=

    mapping_operand=`$command --help 2>/dev/null | sed -n '/^Mapping Operand[:\.]$/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p'`
    if [ -n "$mapping_operand" ];then
        chapter Mapping operand as value of options.
        unset count
        declare -i count
        count=1
        while true; do
            below=`sed -n ${count}p <<< "$mapping_operand" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`
            if [ -z "$below" ];then
                break
            fi
            for _value in "${argument_operand_prepopulate[@]}";do
                ArrayShift argument_operand_prepopulate[@]
                break
            done
            argument_operand_prepopulate=("${_return[@]}")
            if [ -n "$_value" ];then
                argument_prepopulate+=("${below}=${_value}")
                code "${below}=${_value}"
            fi
            unset _return
            unset _value
            count+=1
        done
        ____
    fi

    parameter='subcommand'
    available_subcommands=()
    _available_subcommands=`$command --help 2>/dev/null | sed -n -E 's/^Available subcommands?: ([^\.]+)\.$/\1/p' | head -1`
    if [ -n "$_available_subcommands" ];then
        available_subcommands=(`echo $_available_subcommands | tr ',' ' '`)
    fi
    _available_subcommands_from_command=`$command --help 2>/dev/null | grep -i -o -E '^Available subcommands? from command:\s*[^\(]+\((\)|[^\)]+\))\.$'`

    # Memulai subcommand.
    for first_operand in "${argument_operand_prepopulate[@]}";do
        ArrayShift argument_operand_prepopulate[@]
        break
    done
    if [ -n "$first_operand" ];then
        chapter Prepare argument for command '`'$command'`'.
        chapter_printed=1
        _; _.
        wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> prepopulated with value <yellow>$first_operand</yellow>." green
        argument_operand_prepopulate=("${_return[@]}")
        unset _return
        subcommand="$first_operand"
    else
        if [ -n "$_available_subcommands_from_command" ];then
            chapter Prepare argument for command '`'$command'`'.
            _; _.
            chapter_printed=1
            _command_arguments=$(echo "$_available_subcommands_from_command" | sed -n -E 's/^Available subcommands? from command:\s*([^\)]+\))\.$/\1/p')
            _command=$(echo "$_command_arguments" | sed -n -E 's/^([^\(]+)\(([^\)]*)\)$/\1/p')
            _arguments=$(echo "$_command_arguments" | sed -n -E 's/^([^\(]+)\(([^\)]*)\)$/\2/p')
            [ -n "$_arguments" ] && _arguments=' '"$_arguments"
            wordWrapDescriptionColorize "Subcommand available from command: <magenta>${_command}${_arguments}</magenta>"
            if command -v "$_command" > /dev/null;then
                mktemp=$(mktemp -p /dev/shm)
                ${_command}${_arguments} > "$mktemp"
                while read line;do
                    [ -n "$line" ] && available_subcommands+=("$line")
                done < "$mktemp"
                rm "$mktemp"
            fi
        fi
        if [ -z "$chapter_printed" ];then
            chapter Prepare argument for command '`'$command'`'.
            chapter_printed=1
        fi
        if [ "${#available_subcommands[@]}" -gt 0 ];then
            what=subcommand
            if [ "${#available_subcommands[@]}" -gt 1 ];then
                what=subcommands
            fi
            if [[ "${#available_subcommands[@]}" -eq 1 ]];then
                value="${available_subcommands[0]}"
                _; _.
                __; _, "Available ${what}: "; yellow "$value";  _, '.'; _.
                if [ -n "$interactive" ];then
                    _; _.
                    wordWrapDescription 'The one and only available value is selected.'
                    userInputBooleanDefaultYes
                    if [ -z "$boolean" ];then
                        value=' '
                    fi
                else
                    _; _.
                    wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> filled with the only available value <yellow>$value</yellow> automatically." green
                fi
            else
                printSelectDialog available_subcommands[@] "$what"
            fi
            if [[ "$value" == ' ' ]];then
                value=
            fi
        fi
        if [ -n "$value" ];then
            subcommand="$value"
        fi
    fi
    if [ -n "$subcommand" ];then
        subcommand_substitute=`$command --help 2>/dev/null | sed -n '/^Subcommand Substitute[:\.]$/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p'`
        if [ -n "$subcommand_substitute" ];then
            # Trim.
            subcommand_substitute=`echo "$subcommand_substitute" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`
            if grep -E -q "^${subcommand}:\s+" <<< "$subcommand_substitute";then
                subcommand_substitute=`grep -o -P "^${subcommand}:\s+\K(.*)" <<< "$subcommand_substitute" | tail -1`
                _; _.
                wordWrapDescriptionColorize "Subcommand <magenta>${subcommand}</magenta> makes command shift to <yellow>$subcommand_substitute</yellow> automatically." green
                ____

                echo "$subcommand_substitute"
                exit 2
            fi
        fi
    fi

    if [ -n "$subcommand" ];then
        argument_pass+=("${subcommand}")
        argument_preview+=("${subcommand}")
        argument_preview_real+=("${subcommand}")
    fi

    # Mulai eksekusi event pre prompt.
    Rcm_event_dispatcher 'Pre Prompt'

    # Populate options.
    if [ -n "$subcommand" ];then
        options=`$command $subcommand --help 2>/dev/null | sed -n '/^Options for command '$subcommand'[:\.]$/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p'`
    else
        options=`$command --help 2>/dev/null | sed -n '/^Options[:\.]$/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p'`
    fi

    if [ -n "$options" ];then
        until [[ -z "$options" ]];do
            parameter=`sed -n 1p <<< "$options" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`
            is_required=
            is_flag=
            value_addon=
            is_flagvalue=
            save_history=1
            is_typing=
            is_press=
            is_flagged=
            default_value=
            prepopulate_value=
            if [[ "${parameter:(-1):1}" == '*' ]];then
                is_required=1
                parameter="${parameter::-1}"
                parameter=`echo "$parameter" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`
            elif [[ "${parameter:(-1):1}" == '^' ]];then
                is_flag=1
                parameter="${parameter::-1}"
                parameter=`echo "$parameter" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`
            fi
            if [[ "$parameter" == '--' ]];then
                is_required=
                is_flag=
                value_addon=multivalue
            fi
            description=`sed -n 2p <<< "$options" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`
            unset count
            declare -i count
            count=3
            placeholders=
            while true; do
                below=`sed -n ${count}p <<< "$options" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`
                if grep -q '^--' <<< "$below";then
                    break
                fi
                if [ -z "$below" ];then
                    break
                fi
                if [[ "${below:0:1}" == '[' ]];then
                    if [ -n "$placeholders" ];then
                        placeholders+=$'\n'
                    fi
                    placeholders+="$below"
                else
                    description+=$'\n'
                    description+="$below"
                fi
                count+=1
            done
            if grep -q -i -E '(^|\.\s)Multivalue\.' <<< "$description";then
                value_addon=multivalue
            fi
            if grep -q -i -E '(^|\.\s)Can have value\.' <<< "$description";then
                value_addon=canhavevalue
            fi
            options=`sed -n ${count}',$p' <<< "$options"`
            value=
            values=()
            flags=1
            backup_value=
            backup_flag=
            if [ -f "$backup_storage" ];then
                backup_value=$(grep -- "^${parameter}=.*$" "$backup_storage" | tail -1 | sed -E 's|'"^${parameter}=(.*)$"'|\1|')
                backup_flag=$(grep -q -- "^${parameter}$" "$backup_storage" && echo 1)
            fi
            history_value=
            if [ -f "$history_storage" ];then
                history_value=$(grep -- "^${parameter}=.*$" "$history_storage" | tail -9 | sed -E 's|'"^${parameter}=(.*)$"'|\1|')
            fi
            available_values=()
            _available_values=`echo "$description" | grep -i -o -E 'Available values?:[^\.]+\.'| sed -n -E 's/^Available values?: ([^\.]+)\.$/\1/ip'`
            if [ -n "$_available_values" ];then
                description=`echo "$description" | sed -E 's/ *Available values?: ([^\.]+)\.//i'`
            fi
            _available_values_from_command=`echo "$description" | grep -i -o -E 'Values? available from command:\s*[^\(]+\((\)|[^\)]+\))(\.|, or others?\.)'`
            _available_values_from_command_executed=
            if [ -n "$_available_values_from_command" ];then
                description=`echo "$description" | sed -E 's/ *Values? available from command: ([^\.]+)\.//i'`
            fi
            or_other=
            if [ -n "$_available_values" ];then
                if grep -i -q -E 'or others?' <<< "$_available_values";then
                    or_other=1
                    _available_values=`echo "$_available_values" | sed -E 's/or others?$//'`
                fi
            fi
            if [ -n "$_available_values_from_command" ];then
                if grep -i -q -E 'or others?' <<< "$_available_values_from_command";then
                    or_other=1
                fi
            fi
            _default_value=`echo "$description" | grep -i -o -E 'Default value from variable:? [^\.]+\.'| sed -n -E 's/^Default value from variable:? ([^\.]+)\.$/\1/ip'`
            if [ -n "$_default_value" ];then
                description=`echo "$description" | sed -E 's/ *Default value from variable:? ([^\.]+)\.//i'`
                default_value="${!_default_value}"
            fi
            _prepopulate_value=`echo "$description" | grep -i -o -E 'Prepopulate value from variable:? [^\.]+\.'| sed -n -E 's/^Prepopulate value from variable:? ([^\.]+)\.$/\1/ip'`
            if [ -n "$_prepopulate_value" ];then
                description=`echo "$description" | sed -E 's/ *Prepopulate value from variable:? ([^\.]+)\.//i'`
                if [ -n "$argument_placeholders" ];then
                    while read line; do
                        find=$(echo ${line} | sed -E 's|^([^:]+):.*|\1|' | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
                        replace=$(echo ${line} | sed -E 's|^[^:]+:(.*)|\1|' | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
                        _prepopulate_value="${_prepopulate_value/"$find"/"$replace"}"
                    done <<< "$argument_placeholders"
                fi
                prepopulate_value="${!_prepopulate_value}"
            fi
            if [ -n "$placeholders" ];then
                while read line; do
                    find=$(echo ${line} | cut -d: -f1 | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
                    replace=$(echo ${line} | cut -d: -f2 | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
                    if [ -n "$_available_values" ];then
                        _available_values="${_available_values/"$find"/"$replace"}"
                    fi
                done <<< "$placeholders"
            fi
            if [ -n "$_available_values" ];then
                available_values=(`echo $_available_values | tr ',' ' '`)
            fi
            _; _.
            if [ -n "$_available_values_from_command" ];then
                # Tidak ada history jika value dari command.
                history_value=
                save_history=
            fi
            if [ -n "$_available_values_from_command" ];then
                # parsing argument.
                _command_arguments=$(echo "$_available_values_from_command" | sed -n -E 's/^Values? available from command:\s*([^\)]+\))(\.$|, or others?\.$)/\1/p')
                _command=$(echo "$_command_arguments" | sed -n -E 's/^([^\(]+)\(([^\)]*)\)$/\1/p')
                _arguments=$(echo "$_command_arguments" | sed -n -E 's/^([^\(]+)\(([^\)]*)\)$/\2/p')
                if command -v "$_command" > /dev/null;then
                    if [ -n "$argument_placeholders" ];then
                        while read line; do
                            find=$(echo ${line} | sed -E 's|^([^:]+):.*|\1|' | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
                            replace=$(echo ${line} | sed -E 's|^[^:]+:(.*)|\1|' | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
                            description="${description/"$find"/"$replace"}"
                            if [ -n "$_arguments" ];then
                                _arguments="${_arguments/"$find"/"$replace"}"
                            fi
                        done <<< "$argument_placeholders"
                    fi
                fi
            fi
            if [ -n "$argument_placeholders" ];then
                while read line; do
                    find=$(echo ${line} | sed -E 's|^([^:]+):.*|\1|' | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
                    replace=$(echo ${line} | sed -E 's|^[^:]+:(.*)|\1|' | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
                    description="${description/"$find"/"$replace"}"
                done <<< "$argument_placeholders"
            fi
            if [ -n "$is_flag" ];then
                _ 'Argument '; magenta ${parameter};_, ' is '; _, optional;_, '.'; _.
                _; _.
                while read line; do
                    wordWrapDescription "$line"
                done <<< "$description"
                _boolean=
                for each in "${argument_prepopulate[@]}";do
                    if grep -q -- "^${parameter}-\$" <<< "$each";then
                        _boolean=0
                        break
                    elif grep -q -- "^${parameter}-=" <<< "$each";then
                        # Ada argument lupa dihapus, contoh: --with-roundcube- mail.example.org
                        # maka set sebagai skip.
                        _boolean=0
                        break
                    elif grep -q -- "^${parameter}\$" <<< "$each";then
                        _boolean=1
                        if [[ "$value_addon" == 'canhavevalue' ]];then
                            value_addon=
                        fi
                        if [[ "$value_addon" == 'multivalue' ]];then
                            ArrayRemove "$parameter" argument_prepopulate[@]
                            argument_prepopulate=("${_return[@]}")
                            unset _return
                        fi
                        break
                    elif grep -q -- "^${parameter}=" <<< "$each";then
                        if [[ "$value_addon" == 'canhavevalue' ]];then
                            _boolean=1
                            value=$(echo "$each" | sed -n -E 's|^[^=]+=(.*)|\1|p')
                            break
                        fi
                    fi
                done
                # Reset first.
                boolean=
                # Variable $boolean digunakan dimana-mana, jadi kita gunakan
                # variable terpisah.
                master_boolean=
                if [[ "$_boolean" == 0 ]];then
                    _; _.
                    __; _, Argument; _, ' '; _, "$parameter"; _, ' ';  _, set to skip by user,' '; _, pass; _, .; _.
                    backup_flag=
                    master_boolean=' '
                elif [[ "$_boolean" == 1 ]];then
                    _; _.
                    if [ -n "$value" ];then
                        wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> prepopulated with value <yellow>${value}</yellow>.'" green
                    else
                        wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> prepopulated." green
                        if [[ "$value_addon" == 'multivalue' ]];then
                            found=
                            for each in "${argument_prepopulate[@]}";do
                                if grep -q -- "^${parameter}\$" <<< "$each";then
                                    found=1
                                    let flags++
                                    wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> prepopulated." green
                                fi
                            done
                            # Biar tidak membingunkan kedepannya, hapus saja semua dari array.
                            if [ -n "$found" ];then
                                ArrayRemoveAll "$parameter" argument_prepopulate[@]
                                argument_prepopulate=("${_return[@]}")
                                unset _return
                            fi
                        fi
                    fi
                    backup_flag=
                    master_boolean=1
                fi

                # Jika $parameter merupakan other option, maka skip semua dialog.
                # jika tidak ada prepopulate value.
                if [ -n "$immediately_other_options" ];then
                    if [ -z "$_boolean" ];then
                        backup_flag=
                        master_boolean=' '
                    fi
                fi

                # Jika non interactive, maka skip.
                if [ -z "$interactive" ];then
                    if [ -z "$_boolean" ];then
                        backup_flag=
                        master_boolean=' '
                    fi
                fi

                if [ -n "$backup_flag" ];then
                    printBackupFlagDialog
                    master_boolean="$boolean"
                    if [[ "$value_addon" == 'canhavevalue' ]];then
                        if [ -n "$backup_value" ];then
                            printBackupDialog
                        fi
                    fi
                fi
                if [ -z "$master_boolean" ];then
                    _; _.
                    __; _, Add this argument?; _.
                    userInputBooleanDefaultNo
                    master_boolean="$boolean"
                    is_press=1
                fi
                if [[ "$master_boolean" == ' ' ]];then
                    master_boolean=
                fi
                # Populate placeholders.
                if [ -n "$argument_placeholders" ];then
                    argument_placeholders+=$'\n'
                fi
                if [ -n "$master_boolean" ]; then
                    is_flagged=1
                    if [[ "$value_addon" == 'canhavevalue' ]];then
                        if [ -z "$value" ];then
                            _; _.
                            __; _, Do you want fill with value?; _.
                            userInputBooleanDefaultNo
                        fi
                        if [ -n "$value" ];then
                            # fill from prepopulated
                            boolean=1
                        fi
                        if [ -n "$boolean" ]; then
                            if [ -z "$value" ];then
                                if [ -n "$history_value" ];then
                                    printHistoryDialog
                                    if [ -n "$value" ];then
                                        _; _.
                                        wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> filled with value <yellow>$value</yellow> which is selected from the list of history." green
                                    fi
                                fi
                            fi
                            if [ -z "$value" ];then
                                if [ "${#available_values[@]}" -gt 0 ];then
                                    printSelectDialog available_values[@]
                                fi
                            fi
                            until [[ -n "$value" ]];do
                                __; read -p "Type the value: " value
                                is_typing=1
                            done
                            # Sanitize user input
                            # Menghapus karakter aneh karena menekan arrow up/down/right/left di keyboard.
                            # Credit: https://stackoverflow.com/a/47918586
                            value=$(echo "$value" | tr -cd '\11\12\15\40-\176' | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
                            argument_pass+=("${parameter}=${value}")
                            [[ "$value" =~ ' ' ]] && _value="'$value'" || _value="$value"
                            argument_preview+=("${parameter}=${_value}")
                            argument_preview_real+=("${parameter}=${_value}")
                        else
                            argument_pass+=("${parameter}")
                            argument_preview+=("${parameter}")
                            argument_preview_real+=("${parameter}")
                        fi
                    else
                        i=1
                        until [[ $i -gt $flags ]];do
                            argument_pass+=("${parameter}")
                            argument_preview+=("${parameter}")
                            argument_preview_real+=("${parameter}")
                            let i++
                        done
                    fi
                    # Populate placeholders.
                    if [ -n "$value" ];then
                        argument_placeholders+='['"$parameter"']: '"$value"
                        argument_placeholders+=$'\n'
                        argument_placeholders+='['"$parameter"'^^]: '"${value^^}"
                    else
                        argument_placeholders+='['"$parameter"']: '"1"
                    fi
                else
                    # Populate placeholders.
                    argument_placeholders+='['"$parameter"']: '"0"
                    if [ -z "$argument_preview_bypass" ];then
                        argument_preview+=("${parameter}-")
                    fi
                fi
                if [ -n "$master_boolean" ];then
                    if [ -n "$is_press" ];then
                        if [ -n "$value" ];then
                            if [ -n "$is_typing" ];then
                                _; _.
                                wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> added with value <yellow>$value</yellow> manually." green
                            fi
                        else
                            _; _.
                            wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> added manually." green
                        fi
                    fi
                fi
            elif [[ "$parameter" == '--' ]];then
                _ 'Argument '; magenta ${parameter};_, ' is '; _, optional;_, '.'; _.
                _; _.
                while read line; do
                    wordWrapDescription "$line"
                done <<< "$description"
                __; _, Add value?; _.
                userInputBooleanDefaultNo
                if [ -n "$boolean" ]; then
                    if [ -n "$history_value" ];then
                        printHistoryDialog
                        if [ -n "$value" ];then
                            _; _.
                            wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> filled with value <yellow>$value</yellow> which is selected from the list of history." green
                        fi
                    fi
                    if [ -z "$value" ];then
                        __; read -p "Type the value: " value
                    fi
                    if [ -n "$value" ];then
                        argument_pass+=("${parameter} ${value}")
                        argument_preview+=("${parameter} ${value}")
                        argument_preview_real+=("${parameter} ${value}")
                    fi
                fi
            else
                if [ -n "$is_required" ];then
                    _ 'Argument '; magenta ${parameter};_, ' is '; yellow required;_, '.'; _.
                else
                    _ 'Argument '; magenta ${parameter};_, ' is '; _, optional;_, '.'; _.
                fi
                _; _.
                while read line; do
                    wordWrapDescription "$line"
                done <<< "$description"
                if [ -n "$default_value" ];then
                    wordWrapDescriptionColorize "Default value: <yellow>${default_value}</yellow>."
                fi
                if [ -n "$prepopulate_value" ];then
                    backup_value=
                    history_value=
                fi
                for each in "${argument_prepopulate[@]}";do
                    if grep -q -- "^${parameter}-\$" <<< "$each";then
                        _; _.
                        __; _, Argument; _, ' '; _, "$parameter"; _, ' ';  _, set to skip by user,' '; _, pass; _, .; _.
                        backup_value=
                        history_value=
                        is_required=
                        value=' '
                        break
                    fi
                done
                # Jika tidak multivalue, tapi di prepopulate berkali-kali, maka
                # kita menggunakan last value.
                for each in "${argument_prepopulate[@]}";do
                    if grep -q -- "^${parameter}=" <<< "$each";then
                        value=$(echo "$each" | sed -n -E 's|^[^=]+=(.*)|\1|p')
                        if [[ "$value_addon" == 'multivalue' ]];then
                            values+=("$value")
                        fi
                        _; _.
                        wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> prepopulated with value <yellow>$value</yellow>." green
                        backup_value=
                    fi
                done

                # Jika $parameter merupakan other option, maka skip semua dialog.
                # jika tidak ada prepopulate value.
                if [ -n "$immediately_other_options" ];then
                    if [ -z "$value" ];then
                        backup_value=
                        value=' '
                    fi
                fi

                # Jika non interactive, maka skip.
                if [ -z "$interactive" ];then
                    if [ -z "$value" ];then
                        backup_value=
                        value=' '
                    fi
                fi

                # Backup dialog belum mendukung multivalue.
                if [ -n "$backup_value" ];then
                    printBackupDialog
                fi
                if [ -z "$value" ];then
                    # History dialog belum mendukung multivalue.
                    if [ -n "$history_value" ];then
                        printHistoryDialog
                        if [ -n "$value" ];then
                            _; _.
                            wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> filled with value <yellow>$value</yellow> which is selected from the list of history." green
                        fi
                    fi
                fi
                if [[ -z "$value" && -n "$prepopulate_value" ]];then
                    # Value from prepopulate argument tetap diutamakan
                    # daripada variable.
                    value="$prepopulate_value"
                    _; _.
                    wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> filled with value <yellow>$value</yellow> from environment variable." green
                fi
                # Available value dialog juga belum mendukung multivalue.
                if [ -z "$value" ];then
                    Rcm_get_list_values
                fi
                if [ -n "$is_required" ];then
                    until [[ -n "$value" ]];do
                        __; read -p "Type the value: " value
                        is_typing=1
                    done
                fi
                if [[ "$value" == ' ' ]];then
                    value=
                fi
                if [[ -z "$value" && -n "$default_value" ]];then
                    value="$default_value"
                fi
                # Populate placeholders.
                if [ -n "$argument_placeholders" ];then
                    argument_placeholders+=$'\n'
                fi
                if [ -n "$value" ];then
                    # Sanitize user input
                    # Menghapus karakter aneh karena menekan arrow up/down/right/left di keyboard.
                    # Credit: https://stackoverflow.com/a/47918586
                    if [ "${#values[@]}" -eq 0 ];then
                        values=("$value")
                    fi
                    for value in "${values[@]}";do
                        value=$(echo "$value" | tr -cd '\11\12\15\40-\176' | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
                        argument_pass+=("${parameter}=${value}")
                        [[ "$value" =~ ' ' ]] && _value="'$value'" || _value="$value"
                        argument_preview+=("${parameter}=${_value}")
                        argument_preview_real+=("${parameter}=${_value}")
                        if [ "${#available_values[@]}" -gt 0 ];then
                            ArrayRemove "$value" available_values[@]
                            available_values=("${_return[@]}")
                            unset _return
                        fi
                    done
                    # Placeholder tidak berlaku untuk multivalue. @todo, masukkan ke dokumentasi.
                    # Hanya berlaku nilai terakhir.
                    argument_placeholders+='['"$parameter"']: '"$value"
                    argument_placeholders+=$'\n'
                    argument_placeholders+='['"$parameter"'^^]: '"${value^^}"
                else
                    argument_placeholders+='['"$parameter"']: -'
                    if [ -z "$argument_preview_bypass" ];then
                        argument_preview+=("${parameter}-")
                    fi
                fi
                if [[ -n "$value" && -n "$is_typing" ]];then
                    _; _.
                    [ -z "$default_value" ] && suffix=' manually' || suffix=' automatically'
                    wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> filled with value <yellow>$value</yellow>${suffix}." green
                fi
            fi
            # Backup to text file.
            if [ -n "$value" ];then
                # Belum support history untuk kasus multivalue.
                mkdir -p $(dirname "$backup_storage")
                echo "${parameter}=${value}" >> "$backup_storage"
                if [ -f "$history_storage" ];then
                    if grep -q -- "^${parameter}=${value}\$" "$history_storage";then
                        save_history=
                    fi
                    if [[ "$value" =~ []\[] ]];then
                        if grep -q -F -- "${parameter}=${value}" "$history_storage";then
                            save_history=
                        fi
                    fi
                fi
                if [ -n "$save_history" ];then
                    mkdir -p $(dirname "$history_storage");
                    echo "${parameter}=${value}" >> "$history_storage"
                fi
            fi
            # Backup to text file for flag.
            if [ -n "$master_boolean" ];then
                mkdir -p $(dirname "$backup_storage")
                echo "${parameter}" >> "$backup_storage"
            fi
            if [[ "$value_addon" == 'multivalue' ]];then
                again=1
                until [ -z "$again" ]; do
                    is_press=
                    boolean=
                    if [ -n "$is_flag" ];then
                        if [[ -n "$is_flagged" && -n "$confirmation" ]];then
                            # Reset condition before multivalue.
                            is_flagged=
                            _; _.
                            __ Add this argument again?
                            userInputBooleanDefaultNo
                            is_press=1
                        fi
                    else
                        if [[ -n "$value" && -n "$confirmation" ]];then
                            # Reset condition before multivalue.
                            value_before="$value"
                            value=
                            _; _.
                            __ Add another value?
                            userInputBooleanDefaultNo
                            is_press=1
                        fi
                    fi
                    if [ -n "$boolean" ];then
                        if [ -n "$is_flag" ];then
                            argument_pass+=("${parameter}")
                            argument_preview+=("${parameter}")
                            argument_preview_real+=("${parameter}")
                            is_flagged=1
                        elif [[ "$parameter" == '--' ]];then
                            if [ -n "$history_value" ];then
                                printHistoryDialog
                                if [ -n "$value" ];then
                                    _; _.
                                    wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> filled with value <yellow>$value</yellow> which is selected from the list of history." green
                                fi
                            fi
                            if [ -z "$value" ];then
                                _; _.
                                __; read -p "Type the value or leave blank to skip: " value
                                is_typing=1
                            fi
                            if [ -n "$value" ];then
                                argument_pass+=("${value}")
                                argument_preview+=("${value}")
                                argument_preview_real+=("${value}")
                            fi
                        else
                            Rcm_get_list_values "$value_before"
                            if [ -n "$value" ];then
                                # Sanitize user input
                                # Menghapus karakter aneh karena menekan arrow up/down/right/left di keyboard.
                                # Credit: https://stackoverflow.com/a/47918586
                                value=$(echo "$value" | tr -cd '\11\12\15\40-\176' | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
                                argument_pass+=("${parameter}=${value}")
                                [[ "$value" =~ ' ' ]] && _value="'$value'" || _value="$value"
                                argument_preview+=("${parameter}=${_value}")
                                argument_preview_real+=("${parameter}=${_value}")
                            fi
                        fi
                        # Backup to text file.
                        if [ -n "$value" ];then
                            mkdir -p $(dirname "$backup_storage");
                            echo "${parameter}=${value}" >> "$backup_storage"
                            if [ -f "$history_storage" ];then
                                if grep -q -- "^${parameter}=${value}\$" "$history_storage";then
                                    save_history=
                                fi
                            fi
                            if [ -n "$save_history" ];then
                                mkdir -p $(dirname "$history_storage");
                                echo "${parameter}=${value}" >> "$history_storage"
                            fi
                        fi
                        if [[ -n "$value" && "$is_typing" ]];then
                            _; _.
                            wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> filled again with value <yellow>$value</yellow> manually." green
                        fi
                        if [[ -n "$is_flagged" && "$is_press" ]];then
                            _; _.
                            wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> added again manually." green
                        fi
                    else
                        again=
                    fi
                done
            fi
            # Other options.
            if [[ -z "$options" && -z "$load_other_options" ]];then
                if [ -n "$subcommand" ];then
                    other_options=`$command --help 2>/dev/null | sed -n '/^Other [Oo]ptions for command '$subcommand'.*[:\.]$/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p'`
                else
                    other_options=`$command --help 2>/dev/null | sed -n '/^Other [Oo]ptions.*[:\.]$/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p'`
                fi
                if [ -n "$other_options" ];then
                    options="$other_options"
                    load_other_options=1
                    if [ -n "$confirmation" ];then
                        _; _.
                        _; _, 'There are '; yellow other ;_, ' arguments available and optional.'; _.
                        _; _.
                        __; _, Prompt other arguments?; _.
                        userInputBooleanDefaultNo
                        if [ -z "$boolean" ]; then
                            immediately_other_options=1
                            argument_preview_bypass=1
                        fi
                    else
                        argument_preview_bypass=1
                        immediately_other_options=1
                    fi
                fi
            fi
        done
        ____

        chapter_printed=
    fi
    if [ -n "$chapter_printed" ];then
        ____
    fi
}
Rcm_prompt_build_command() {
    local _RCM_PROMPT_CHAIN
    wordWrapDescription 'Use command below to return to the last dialog.' 0
    local shortoptions
    [ -n "$resolve_dependencies" ] && shortoptions+='r'
    [ -z "$interactive" ] && shortoptions+='x'
    [ -z "$fast" ] && shortoptions+='s'
    if [ -n "$verbose" ];then
        for ((i = 0 ; i < "$verbose" ; i++)); do
            shortoptions+='v'
        done
    fi
    [ -n "$shortoptions" ] && shortoptions=" -${shortoptions}"
    if [ -z "$RCM_PROMPT_CHAIN" ];then
        _RCM_PROMPT_CHAIN="rcm${shortoptions} ${extension}"
    else
        _RCM_PROMPT_CHAIN="$RCM_PROMPT_CHAIN"
    fi
    for each in "${argument_preview[@]}"; do _RCM_PROMPT_CHAIN+=" ${each}"; done
    words_array=($_RCM_PROMPT_CHAIN)
    wordWrapCommand
}
Rcm_prompt_sigint() {
    _.;
    _.;
    error Interrupt by User.
    _.;
    Rcm_prompt_build_command
    exit 0
}
Rcm_get_list_values() {
    if [[ -n "$_available_values_from_command" && -z "$_available_values_from_command_executed" ]];then
        _available_values_from_command_executed=1
        if command -v "$_command" > /dev/null;then
            _; _.
            [ -n "$_arguments" ] && _arguments=' '"$_arguments"
            wordWrapDescriptionColorize "Value available from command: <magenta>${_command}${_arguments}</magenta>"
            mktemp=$(mktemp -p /dev/shm)
            ${_command}${_arguments} > "$mktemp"
            exit_code=$?
            while read line;do
                [ -n "$line" ] && available_values+=("$line")
            done < "$mktemp"
            rm "$mktemp"
        fi
    fi
    if [ -z "$available_values_backup" ];then
        available_values_backup=("${available_values[@]}")
    fi
    while [[ $# -gt 0 ]]; do
        ArrayRemove "$1" available_values[@]
        available_values=("${_return[@]}")
        unset _return
        shift
    done
    if [ "${#available_values[@]}" -gt 0 ];then
        if [ -n "$or_other" ];then
            printSelectOtherDialog available_values[@]
        elif [[ "${#available_values[@]}" -eq 1 && -n "$is_required" ]];then
            value="${available_values[0]}"
            _; _.
            __; _, "Available value: "; yellow "$value";  _, '.'; _.
            if [ -n "$interactive" ];then
                _; _.
                wordWrapDescription 'The one and only available value is selected.'
                userInputBooleanDefaultYes
                if [ -z "$boolean" ];then
                    value=' '
                fi
            else
                _; _.
                wordWrapDescriptionColorize "Argument <magenta>${parameter}</magenta> filled with the only available value <yellow>$value</yellow> automatically." green
            fi
        else
            printSelectDialog available_values[@]
        fi
    else
        _; _.
        if [[ -n "$_available_values_from_command" && ! $exit_code -eq 0 ]];then
            is_required=
            __; _, Argument; _, ' '; _, "$parameter"; _, ' ';  _, set to skip by command,' '; _, pass; _, .; _.
        elif [[ -n "$_available_values_from_command" && -z "$or_other" ]];then
            __; _, No value available,' '; red Process Terminated; _, .; x
        else
            if [ -n "$default_value" ];then
                __; _, Leave blank will use default value.; _.
                label=$(_, 'Type the value [' 2>&1; yellow "$default_value" 2>&1; _, ']: ' 2>&1)
                __; read -p "$label" value
                [ -z "$value" ] && value=' '
            elif [ -n "$is_required" ];then
                __; read -p "Type the value: " value
            else
                __; read -p "Type the value or leave blank to skip: " value
            fi
            is_typing=1
        fi
    fi
}
Rcm_event_dispatcher() {
    # global command argument_placeholders RCM_ENVIRONMENT_VARIABLES tempfile
    local key value
    local label="$1"; shift
    local to_execute command_raw _command_arguments _command _arguments
    local line  find replace
    to_execute=`${command} --help 2>/dev/null | sed -n '/^'"$label"'[:\.]$/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p'`
    if [ -n "$to_execute" ];then
        Rcm_prompt_build_command
        _.;
        until [[ -z "$to_execute" ]];do
            command_raw=`sed -n 1p <<< "$to_execute" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`
            to_execute=`sed -n '2,$p' <<< "$to_execute"`
            _command_arguments=$(echo "$command_raw" | sed -n -E 's/\s*([^\)]+\))/\1/p')
            _command=$(echo "$_command_arguments" | sed -n -E 's/^([^\(]+)\(([^\)]*)\)$/\1/p')
            _arguments=$(echo "$_command_arguments" | sed -n -E 's/^([^\(]+)\(([^\)]*)\)$/\2/p')
            if command -v "$_command" > /dev/null;then
                if [ -n "$argument_placeholders" ];then
                    while read line; do
                        find=$(echo ${line} | sed -E 's|^([^:]+):.*|\1|' | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
                        replace=$(echo ${line} | sed -E 's|^[^:]+:(.*)|\1|' | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//')
                        # description="${description/"$find"/"$replace"}"
                        if [ -n "$_arguments" ];then
                            _arguments="${_arguments/"$find"/"$replace"}"
                        fi
                    done <<< "$argument_placeholders"
                fi
            fi
            [ -n "$_arguments" ] && _arguments=' '"$_arguments"
            chapter "$label" command.
            code ${_command}${_arguments}
            ____

            if [ -z "$tempfile" ];then
                tempfile=$(mktemp -p /dev/shm -t rcm.XXXXXX)
            fi
            RCM_PROMPT_CHAIN= INDENT+="$RCM_INDENT" ${_command}${_arguments} \
                > "$tempfile" \
                ; [ ! $? -eq 0 ] && { rm "$tempfile"; x; }

            while IFS= read -r to_export; do
                key=$(cut -d= -f1 <<< "$to_export")
                value=$(cut -d= -f2- <<< "$to_export")
                [ -z "$value" ] && value=-
                code export "$key"="$value"
                export "$key"="$value"
                [ -n "$RCM_ENVIRONMENT_VARIABLES" ] && RCM_ENVIRONMENT_VARIABLES+=" "
                RCM_ENVIRONMENT_VARIABLES+="${key}=${value}"
            done < "$tempfile"
            if [ -s "$tempfile" ];then
                ____
            fi

        done
    fi
}

# Requirement, validate, and populate value.

if [ ! -d "$BINARY_DIRECTORY" ];then
    mkdir -p "$BINARY_DIRECTORY"
    if [ ! -d "$BINARY_DIRECTORY" ];then
        error Direktori '`'$BINARY_DIRECTORY'`' tidak ditemukan.; x
    fi
fi

PATH="${BINARY_DIRECTORY}:${PATH}"

_help=$("$command" --help 2>/dev/null)
rcm_config_no_confirmation=$(echo "$_help" | sed -n '/^RCM Config:/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p' | sed 's/^ *//g' | grep '^--no-confirmation')
if [ -n "$rcm_config_no_confirmation" ];then
    confirmation=
fi
if [ -z "$interactive" ];then
    confirmation=
fi

command -v "$command" >/dev/null || { red "Unable to proceed, $command command not found."; x; }

argument_prepopulate=()
argument_operand_prepopulate=()
argument_after_doubledash=()

if [ $# -gt 0 ];then
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --)
                confirmation=
                while [[ $# -gt 0 ]]; do
                    case "$1" in
                        *) argument_after_doubledash+=("$1"); shift ;;
                    esac
                done
                ;;
            --[^-]*)
                if [[ "$2" =~ ^-- ]];then
                    argument_prepopulate+=("$1");
                elif [[ ! $2 == "" && ! $2 =~ ^-[^-] ]];then
                    argument_prepopulate+=("$1"="$2");
                    shift
                else
                    argument_prepopulate+=("$1");
                fi
                shift
                ;;
            -[^-]*)
                # Short option tidak bisa dijadikan prepopulate.
                shift
                ;;
            *)
                argument_operand_prepopulate+=("$1");
                shift
        esac
    done
fi

# Export variables part 1.

# Boolean export as 0 or 1. Must not leave empty string.
[ -n "$fast" ] && rcm_fast=1 || rcm_fast=0
[ -n "$interactive" ] && rcm_interactive=1 || rcm_interactive=0
[ -n "$resolve_dependencies" ] && rcm_resolve_dependencies=1 || rcm_resolve_dependencies=0
export RCM_FAST="$rcm_fast"
export RCM_INTERACTIVE="$rcm_interactive"
export RCM_RESOLVE_DEPENDENCIES="$rcm_resolve_dependencies"

# Other variable, export as is.
export RCM_VERBOSE="$verbose"
export RCM_LOG="$log"
export RCM_VERSION="$rcm_version"
export RCM_TABLE_DOWNLOADS="$table_downloads"
export RCM_TABLE_DEPENDENCIES="$table_dependencies"
export RCM_TABLE_COMMAND_RESOLVED="$table_command_resolved"

backup_storage=$HOME'/.cache/rcm/rcm.'$command'.bak'
history_storage=$HOME'/.cache/rcm/rcm.'$command'.history'
trap Rcm_prompt_sigint SIGINT
Rcm_prompt $command
trap x SIGINT

if [ -n "$subcommand" ];then
    Rcm_event_dispatcher 'Post Prompt for command '$subcommand
else
    Rcm_event_dispatcher 'Post Prompt'
fi
[ -f "$backup_storage" ] && rm "$backup_storage"

shortoptions=
[ -z "$resolve_dependencies" ] && shortoptions+='r'
[ -z "$interactive" ] && shortoptions+='x'
[ -z "$fast" ] && shortoptions+='s'
[ -z "$fast" ] && isfast='' || isfast=' --fast'
[ -n "$verbose" ] && {
    isverbose=
    for ((i = 0 ; i < "$verbose" ; i++)); do
        isverbose+=' --verbose'
        shortoptions+='v'
    done
} || isverbose=
[ -n "$shortoptions" ] && shortoptions=" -${shortoptions}"
argument_preview+=(--)

# Export variables part 2.
# Special for variable RCM_PROMPT_CHAIN, append value then export it.
if [ -z "$RCM_PROMPT_CHAIN" ];then
    RCM_PROMPT_CHAIN="rcm${shortoptions} ${extension}"
fi
for each in "${argument_preview[@]}"; do RCM_PROMPT_CHAIN+=" ${each}"; done
[ -n "$RCM_ENVIRONMENT_VARIABLES" ] && RCM_ENVIRONMENT_VARIABLES+=' '
RCM_PROMPT_CHAIN="${RCM_ENVIRONMENT_VARIABLES}${RCM_PROMPT_CHAIN}"
export RCM_PROMPT_CHAIN="$RCM_PROMPT_CHAIN"
export RCM_ENVIRONMENT_VARIABLES="$RCM_ENVIRONMENT_VARIABLES"
[ -n "$tempfile" ] && rm "$tempfile"

chapter Command has been built.
_ Use command below to arrive in this position with non-interactive mode.; _.
# Simpan ke log, last command.
if [ -n "$confirmation" ];then
    echo "$RCM_PROMPT_CHAIN" >> "$log"
    _ Command has been saved to log file: '`'$(basename "$log")'`'.; _.
fi
if [ "${#argument_after_doubledash[@]}" -eq 0 ];then
    words_array=($RCM_PROMPT_CHAIN)
else
    _rcm_prompt_chain="$RCM_PROMPT_CHAIN"
    _argument_after_doubledash=("${argument_after_doubledash[@]}")
    ArrayShift _argument_after_doubledash[@]
    _argument_after_doubledash=("${_return[@]}")
    unset _return
    for each in "${_argument_after_doubledash[@]}"; do
        # Credit: https://devhints.io/bash
        _argument="${each%%=*}"
        _value="${each#$_argument=}"
        [[ "$_argument" == "$_value" ]] && is_flag=1 || is_flag=
        if [ -n "$is_flag" ];then
            _rcm_prompt_chain+=" ${each}"
        else
            [[ "$_value" =~ ' ' ]] && _value="'$_value'"
            _rcm_prompt_chain+=" ${_argument}=${_value}"
        fi
    done
    words_array=($_rcm_prompt_chain)
fi

wordWrapCommand
____

chapter The real command has been built.
_argument_after_doubledash=()
if [ "${#argument_after_doubledash[@]}" -gt 0 ];then
    for each in "${argument_after_doubledash[@]}"; do
        # Credit: https://devhints.io/bash
        _argument="${each%%=*}"
        _value="${each#$_argument=}"
        [[ "$_argument" == "$_value" ]] && is_flag=1 ||  is_flag=
        if [ -n "$is_flag" ];then
            _argument_after_doubledash+=" ${each}"
        else
            [[ "$_value" =~ ' ' ]] && _value="'$_value'"
            _argument_after_doubledash+=" ${_argument}=${_value}"
        fi
    done
fi

if [[ "${#argument_preview_real[@]}" -gt 0 ]];then
    set -- "${argument_preview_real[@]}" "${_argument_after_doubledash[@]}"
else
    set -- "${_argument_after_doubledash[@]}"
fi
# Hanya --fast dan --verbose yang juga dioper ke command sebagai option.
# Selebihnya dioper sebagai export VARIABLES.
words_array=(${RCM_ENVIRONMENT_VARIABLES} ${command} ${isfast} ${isverbose} $@)
wordWrapCommand
____

if [ -n "$confirmation" ];then
    chapter Execute:
    userInputBooleanDefaultYes
    if [ -z "$boolean" ];then
        exit 0
    fi
    ____

else
    chapter The real command is execute.
    _ Direct to '`'${command}'`' command.; _.
    ____

fi

rcm_config_no_timer=$(echo "$_help" | sed -n '/^RCM Config:/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p' | sed 's/^ *//g' | grep '^--no-timer')
if [ -n "$rcm_config_no_timer" ];then
    timer=
fi
if [ -n "$timer" ];then
    chapter Timer Start.
    _ Begin: $(date +%Y%m%d-%H%M%S); _.
    Rcm_BEGIN=$SECONDS
    ____
fi

if [[ "${#argument_pass[@]}" -gt 0 ]];then
    set -- "${argument_pass[@]}" "${argument_after_doubledash[@]}"
else
    set -- "${argument_after_doubledash[@]}"
fi
INDENT+="$RCM_INDENT" BINARY_DIRECTORY="$BINARY_DIRECTORY" $command $isfast $isverbose "$@"

if [ -n "$timer" ];then
    chapter Timer Finish.
    _ End: $(date +%Y%m%d-%H%M%S); _.
    Rcm_END=$SECONDS
    duration=$(( Rcm_END - Rcm_BEGIN ))
    hours=$((duration / 3600)); minutes=$(( (duration % 3600) / 60 )); seconds=$(( (duration % 3600) % 60 ));
    runtime=`printf "%02d:%02d:%02d" $hours $minutes $seconds`
    _ Duration: $runtime; if [ $duration -gt 60 ];then _, " (${duration} seconds)"; fi; _, '.'; _.
    ____
fi

# parse-options.sh \
# --with-end-options-double-dash \
# --with-end-options-first-operand \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# INCREMENT=(
#     '--verbose|-v'
# )
# FLAG=(
# --fast
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
#     'long:--no-confirmation,parameter:confirmation,flag_option:reverse'
# )
# OPERAND=(
# )
# EOF
# clear
