#!/bin/bash

# Common Functions.
red() { echo -ne "\e[91m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
green() { echo -ne "\e[92m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
yellow() { echo -ne "\e[93m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
blue() { echo -ne "\e[94m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
magenta() { echo -ne "\e[95m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
error() { echo -n "$INDENT" >&2; red '#' "$@" >&2; echo >&2; }
success() { echo -n "$INDENT" >&2; green '#' "$@" >&2; echo >&2; }
chapter() { echo -n "$INDENT" >&2; yellow '#' "$@" >&2; echo >&2; }
title() { echo -n "$INDENT" >&2; blue '#' "$@" >&2; echo >&2; }
code() { echo -n "$INDENT" >&2; magenta "$@" >&2; echo >&2; }
x() { echo >&2; exit 1; }
e() { echo -n "$INDENT" >&2; echo -n "$@" >&2; }
_() { echo -n "$INDENT" >&2; echo -n "#"' ' >&2; [ -n "$1" ] && echo -n "$@" >&2; }
_,() { echo -n "$@" >&2; }
_.() { echo >&2; }
__() { echo -n "$INDENT" >&2; echo -n "# ${RCM_INDENT}" >&2; [ -n "$1" ] && echo "$@" >&2; }
____() { echo >&2; [ -n "$RCM_DELAY" ] && sleep "$RCM_DELAY"; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --fast) fast=1; shift ;;
        --[^-]*) shift ;;
        add|list|execute|helper|init)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Command.
if [ -n "$1" ];then
    command=
    case "$1" in
        add) command="$1"; shift ;;
        list) command="$1"; shift ;;
        execute) command="$1"; shift ;;
        helper) command="$1"; shift ;;
        init) command="$1"; shift ;;
    esac
    if [ -z "$command" ];then
        error Command unknown: '`'"$1"'`'.; x
    fi
fi

case "$command" in
    add)
        _new_arguments=()
        while [[ $# -gt 0 ]]; do
            case "$1" in
                --help) help=1; shift ;;
                --command=*) add_command="${1#*=}"; shift ;;
                --command) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then add_command="$2"; shift; fi; shift ;;
                --fast) fast=1; shift ;;
                --interface=*) interface="${1#*=}"; shift ;;
                --interface) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then interface="$2"; shift; fi; shift ;;
                --name=*) name="${1#*=}"; shift ;;
                --name) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then name="$2"; shift; fi; shift ;;
                --table=*) table="${1#*=}"; shift ;;
                --table) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then table="$2"; shift; fi; shift ;;
                --table-temporary=*) table_temporary="${1#*=}"; shift ;;
                --table-temporary) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then table_temporary="$2"; shift; fi; shift ;;
                --temporary) temporary=1; shift ;;
                --version=*) add_version="${1#*=}"; shift ;;
                --version) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then add_version="$2"; shift; fi; shift ;;
                --[^-]*) shift ;;
                *) _new_arguments+=("$1"); shift ;;
            esac
        done
        set -- "${_new_arguments[@]}"
        unset _new_arguments
        ;;
    list)
        _new_arguments=()
        while [[ $# -gt 0 ]]; do
            case "$1" in
                --help) help=1; shift ;;
                --fast) fast=1; shift ;;
                --interface=*) interface="${1#*=}"; shift ;;
                --interface) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then interface="$2"; shift; fi; shift ;;
                --table=*) table="${1#*=}"; shift ;;
                --table) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then table="$2"; shift; fi; shift ;;
                --table-temporary=*) table_temporary="${1#*=}"; shift ;;
                --table-temporary) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then table_temporary="$2"; shift; fi; shift ;;
                --[^-]*) shift ;;
                *) _new_arguments+=("$1"); shift ;;
            esac
        done
        set -- "${_new_arguments[@]}"
        unset _new_arguments
        ;;
    execute)
        _new_arguments=()
        while [[ $# -gt 0 ]]; do
            case "$1" in
                --help) help=1; shift ;;
                --fast) fast=1; shift ;;
                --interface=*) interface="${1#*=}"; shift ;;
                --interface) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then interface="$2"; shift; fi; shift ;;
                --method=*) method="${1#*=}"; shift ;;
                --method) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then method="$2"; shift; fi; shift ;;
                --name=*) name="${1#*=}"; shift ;;
                --name) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then name="$2"; shift; fi; shift ;;
                --output-file=*) output_file="${1#*=}"; shift ;;
                --output-file) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then output_file="$2"; shift; fi; shift ;;
                --table=*) table="${1#*=}"; shift ;;
                --table) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then table="$2"; shift; fi; shift ;;
                --table-temporary=*) table_temporary="${1#*=}"; shift ;;
                --table-temporary) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then table_temporary="$2"; shift; fi; shift ;;
                --[^-]*) shift ;;
                *) _new_arguments+=("$1"); shift ;;
            esac
        done
        set -- "${_new_arguments[@]}"
        unset _new_arguments
        ;;
    init)
        _new_arguments=()
        while [[ $# -gt 0 ]]; do
            case "$1" in
                --help) help=1; shift ;;
                --fast) fast=1; shift ;;
                --interface=*) interface="${1#*=}"; shift ;;
                --interface) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then interface="$2"; shift; fi; shift ;;
                --table=*) table="${1#*=}"; shift ;;
                --table) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then table="$2"; shift; fi; shift ;;
                --[^-]*) shift ;;
                *) _new_arguments+=("$1"); shift ;;
            esac
        done
        set -- "${_new_arguments[@]}"
        unset _new_arguments
esac

# Define variables and constants.
[ -z "$fast" ] && fast="$RCM_FAST"; [ "$fast" == 0 ] && fast=
RCM_DELAY=${RCM_DELAY:=.5}; [ -n "$fast" ] && unset RCM_DELAY
RCM_INDENT='    '; [ "$(tput cols)" -le 80 ] && RCM_INDENT='  '
# If not set in argument, try load from environment.
[ -z "$verbose" ] && verbose="$RCM_VERBOSE"
quiet=; loud=; louder=; debug=;
[[ -z "$verbose" || "$verbose" -lt 1 ]] && quiet=1 || quiet=
[[ "$verbose" -gt 0 ]] && loud=1
[[ "$verbose" -gt 1 ]] && loud=1 && louder=1
[[ "$verbose" -gt 2 ]] && loud=1 && louder=1 && debug=1

# Functions. Help and Version.
printVersion() {
    echo '0.18.0-alpha.2'
}
printHelp() {
    title Rapid Construct Massive
    _ 'Plugin System'; _.
    _ 'Version '; yellow `printVersion`; _.
    _.
cat << EOF
Usage: rcm-plugin <command> [options]

Available commands: add, list, execute.

Options for command add:
   --interface *
        Set the plugin category. Value available from command: rcm-plugin(helper interface-available), or other.
   --name *
        Set the plugin name.
   --command *
        Command of plugin to execute.
   --version *
        Command version.
   --table
        File table to store plugin information.
        Default value is \$HOME/.config/rcm/rcm.plugin.table.[--interface]
        Prepopulate value from variable RCM_PLUGIN_[--interface^^]_TABLE.
   --temporary ^
        Set as temporary additional.
   --table-temporary
        File table to temporary store plugin information.
        Value available from command: rcm-plugin(helper temporary-suggestion [--temporary] [--interface]), or others.
        Prepopulate value from variable RCM_PLUGIN_[--interface^^]_TABLE_TEMPORARY.

Options for command list:
   --interface *
        Set the plugin category. Value available from command: rcm-plugin(helper interface-available), or other.
   --table
        File table to store plugin information.
        Default value is \$HOME/.config/rcm/rcm.plugin.table.[--interface]"
        Prepopulate value from variable RCM_PLUGIN_[--interface^^]_TABLE.
   --table-temporary
        File table to temporary store plugin information.
        Value available from command: rcm-plugin(helper temporary-suggestion 1 [--interface]), or others.
        Prepopulate value from variable RCM_PLUGIN_[--interface^^]_TABLE_TEMPORARY.

Options for command execute:
   --interface *
        Set the plugin category. Value available from command: rcm-plugin(helper interface-available), or other.
   --table
        File table to store plugin information.
        Default value is \$HOME/.config/rcm/rcm.plugin.table.[--interface]"
        Prepopulate value from variable RCM_PLUGIN_[--interface^^]_TABLE.
   --table-temporary
        File table to temporary store plugin information.
        Value available from command: rcm-plugin(helper temporary-suggestion 1 [--interface]), or others.
        Prepopulate value from variable RCM_PLUGIN_[--interface^^]_TABLE_TEMPORARY.
   --name *
        Set the plugin name.
        Value available from command: rcm-plugin(helper list [--interface] [--table] [--table-temporary]), or others.
   --interface *
        Set the interface.

Global Options:
   --fast
        No delay every subtask.
   --version
        Print version of this script.
   --help
        Show this help.

Environment Variables:
   BINARY_DIRECTORY
        Default to $BINARY_DIRECTORY

RCM Config:
   --no-timer
   --no-confirmation
EOF
}

# Help and Version.
[ -n "$help" ] && { printHelp; exit 1; }
[ -n "$version" ] && { printVersion; exit 1; }

command-add() {
    local command version

    title rcm-plugin::add
    ____

    [ -n "$louder" ] && chapter Dump variable
    if [ -z "$interface" ];then
        error "Argument --interface required."; x
    fi
    [ -n "$louder" ] && code 'interface="'$interface'"'
    if [[ "$interface" =~ [^a-z_] ]];then
        error "Argument --interface is not valid."; x
    fi
    if [ -z "$name" ];then
        error "Argument --name required."; x
    fi
    [ -n "$louder" ] && code 'name="'$name'"'
    if [ -z "$add_command" ];then
        error "Argument --command required."; x
    fi
    command="$add_command"
    [ -n "$louder" ] && code 'command="'$command'"'
    if [ -z "$add_version" ];then
        error "Argument --version required."; x
    fi
    version="$add_version"
    [ -n "$louder" ] && code 'version="'$version'"'
    [ -n "$louder" ] && code 'temporary="'$temporary'"'
    [ -n "$louder" ] && code 'table="'$table'"'
    [ -n "$louder" ] && code 'table_temporary="'$table_temporary'"'
    # If not set in argument, try load from environment.
    local interface_uppercase=${interface^^}
    local parameter_table="RCM_PLUGIN_${interface_uppercase}_TABLE"
    parameter_table=$(echo "$parameter_table"| sed 's|[^A-Z]|_|g' | sed -E 's|_+|_|')
    parameter_table="${!parameter_table}"
    local parameter_table_temporary="RCM_PLUGIN_${interface_uppercase}_TABLE_TEMPORARY"
    parameter_table_temporary=$(echo "$parameter_table_temporary"| sed 's|[^A-Z]|_|g' | sed -E 's|_+|_|')
    parameter_table_temporary="${!parameter_table_temporary}"
    [ -z "$table" ] && table="$parameter_table"
    [ -z "$table_temporary" ] && table_temporary="$parameter_table_temporary"
    [ -n "$louder" ] && code 'table="'$table'"'
    [ -n "$louder" ] && code 'table_temporary="'$table_temporary'"'
    # Use default value.
    if [ -z "$table" ];then
        table="${HOME}/.config/rcm/rcm.plugin.table.${interface}"
    fi
    if [ -n "$temporary" ];then
        if [ -z "$table_temporary" ];then
            mkdir -p "${HOME}/.cache/rcm"
            table_temporary=$(mktemp -p ${HOME}/.cache/rcm -t rcm.plugin.table.${interface}.XXXXXX)
        fi
    fi
    [ -n "$louder" ] && code 'table="'$table'"'
    [ -n "$louder" ] && code 'table_temporary="'$table_temporary'"'
    [ -n "$louder" ] && ____

    chapter Add to table.
    local table_lookup=
    if [ -n "$temporary" ];then
        table_lookup="$table_temporary"
    else
        table_lookup="$table"
    fi
    local line
    if [ -f "$table_lookup" ];then
        line=$(grep -n -F "${name} ${command} ${version}" "$table_lookup")
    fi
    if [ -z "$line" ];then
        local table_dirname=$(dirname "$table_lookup")
        mkdir -p "$table_dirname"
        echo "${name} ${command} ${version}" >> "$table_lookup"
        success Added.
    else
        __ Already added.
    fi
    ____

    if [ -n "$temporary" ];then
        echo "RCM_PLUGIN_${interface_uppercase}_TABLE_TEMPORARY=${table_temporary}"
    else
        echo "RCM_PLUGIN_${interface_uppercase}_TABLE=${table}"
    fi
}
command-list() {
    if [ -z "$interface" ];then
        error "Argument --interface required."; x
    fi
    if [[ "$interface" =~ [^a-z_] ]];then
        error "Argument --interface is not valid."; x
    fi

    # If not set in argument, try load from environment.
    local interface_uppercase=${interface^^}
    local parameter_table="RCM_PLUGIN_${interface_uppercase}_TABLE"
    parameter_table=$(echo "$parameter_table"| sed 's|[^A-Z]|_|g' | sed -E 's|_+|_|')
    parameter_table="${!parameter_table}"
    local parameter_table_temporary="RCM_PLUGIN_${interface_uppercase}_TABLE_TEMPORARY"
    parameter_table_temporary=$(echo "$parameter_table_temporary"| sed 's|[^A-Z]|_|g' | sed -E 's|_+|_|')
    parameter_table_temporary="${!parameter_table_temporary}"
    [ -z "$table" ] && table="$parameter_table"
    [ -z "$table_temporary" ] && table_temporary="$parameter_table_temporary"
    # Use default value.
    if [ -z "$table" ];then
        table="${HOME}/.config/rcm/rcm.plugin.table.${interface}"
    fi
    local contents=
    if [ -f "$table_temporary" ] ;then
        contents+=$'\n'
        contents+=$(cut -d' ' -f1 < "$table_temporary")
    fi
    if [ -f "$table" ] ;then
        # Filter duplikat.
        contents+=$'\n'
        contents+=$(cut -d' ' -f1 <"$table" | sort -u)
    fi
    echo "$contents" | sed '/^[[:space:]]*$/d'
}
command-execute() {
    title rcm-plugin::execute
    ____

    local find replace contents command

    [ -n "$louder" ] && chapter Dump variable
    if [ -z "$interface" ];then
        error "Argument --interface required."; x
    fi
    [ -n "$louder" ] && code 'interface="'$interface'"'
    if [[ "$interface" =~ [^a-z_] ]];then
        error "Argument --interface is not valid."; x
    fi
    if [ -z "$name" ];then
        error "Argument --name required."; x
    fi
    [ -n "$louder" ] && code 'name="'$name'"'
    if [ -z "$method" ];then
        error "Argument --method required."; x
    fi
    [ -n "$louder" ] && code 'method="'$method'"'
    [ -n "$louder" ] && code 'output_file="'$output_file'"'
    # If not set in argument, try load from environment.
    local interface_uppercase=${interface^^}
    local parameter_table="RCM_PLUGIN_${interface_uppercase}_TABLE"
    parameter_table=$(echo "$parameter_table"| sed 's|[^A-Z]|_|g' | sed -E 's|_+|_|')
    parameter_table="${!parameter_table}"
    local parameter_table_temporary="RCM_PLUGIN_${interface_uppercase}_TABLE_TEMPORARY"
    parameter_table_temporary=$(echo "$parameter_table_temporary"| sed 's|[^A-Z]|_|g' | sed -E 's|_+|_|')
    parameter_table_temporary="${!parameter_table_temporary}"
    [ -z "$table" ] && table="$parameter_table"
    [ -z "$table_temporary" ] && table_temporary="$parameter_table_temporary"
    [ -n "$louder" ] && code 'table="'$table'"'
    [ -n "$louder" ] && code 'table_temporary="'$table_temporary'"'
    # Use default value.
    if [ -z "$table" ];then
        table="${HOME}/.config/rcm/rcm.plugin.table.${interface}"
    fi
    [ -n "$louder" ] && code 'table="'$table'"'
    [ -n "$louder" ] && code 'table_temporary="'$table_temporary'"'
    # Translate variable.
    find='$HOME'; replace="$HOME"
    [ -n "$table" ] && table="${table/"$find"/"$replace"}"
    [ -n "$table_temporary" ] && table_temporary="${table_temporary/"$find"/"$replace"}"
    [ -n "$louder" ] && code 'table="'$table'"'
    [ -n "$louder" ] && code 'table_temporary="'$table_temporary'"'
    if [ -f "$table_temporary" ] ;then
        contents+=$'\n'
        contents+=$(<"$table_temporary")
    fi
    if [ -f "$table" ] ;then
        contents+=$'\n'
        contents+=$(<"$table")
    fi
    if [ -n "$contents" ];then
        # @todo, version dipikirkan.
        command=$(echo "$contents" | grep ^"$name" | cut -d' ' -f2 | tail -1)
    fi
    if [ -z "$command" ];then
        error "The Command of \`plugin::${interface}('${name}')\` is not defined in table."; x
    fi
    if ! command -v "$command" > /dev/null;then
        error Command not found: '`'"$command"'`'.; x
    fi

    # red '"$command"' "$command"; _.
    [ -n "$louder" ] && ____

    chapter Execute "plugin::${interface}('${name}')->${method}()"
    code "${command} plugin ${interface} ${name} ${method}"
    ____

    [ -n "$fast" ] && RCM_FAST=1 || RCM_FAST=0
    export RCM_FAST="$RCM_FAST"
    if [ -z "$output_file" ];then
        RCM_ENVIRONMENT_VARIABLES= RCM_PROMPT_CHAIN= INDENT+="    " ${command} plugin ${interface} ${name} ${method} \
            ; [ ! $? -eq 0 ] && x
    else
        RCM_ENVIRONMENT_VARIABLES= RCM_PROMPT_CHAIN= INDENT+="    " ${command} plugin ${interface} ${name} ${method} \
            > "$output_file" \
            ; [ ! $? -eq 0 ] && { rm "$output_file"; x; }
    fi
}
command-init() {

    title rcm-plugin::init
    ____

    [ -n "$louder" ] && chapter Dump variable
    if [ -z "$interface" ];then
        error "Argument --interface required."; x
    fi
    [ -n "$louder" ] && code 'interface="'$interface'"'
    if [[ "$interface" =~ [^a-z_] ]];then
        error "Argument --interface is not valid."; x
    fi
    local interface_uppercase=${interface^^}

    # If not set in argument, try load from environment.
    local parameter_table="RCM_PLUGIN_${interface_uppercase}_TABLE"
    parameter_table=$(echo "$parameter_table"| sed 's|[^A-Z]|_|g' | sed -E 's|_+|_|')
    parameter_table="${!parameter_table}"
    [ -z "$table" ] && table="$parameter_table"
    # Use default value.
    if [ -z "$table" ];then
        table="${HOME}/.config/rcm/rcm.plugin.table.${interface}"
    fi
    [ -n "$louder" ] && ____

    echo "RCM_PLUGIN_${interface_uppercase}_TABLE=${table}"
}
command-helper() {
    local which=$1; shift
    if [ "$which" == do-nothing ];then
        return
    fi
    if [ -n "$which" ];then
        if [[ $(type -t "helper-${which}") == function ]];then
            helper-${which} "$@"
            exit 0
        else
            error Helper unknown: '`'"$command"'`'.; x
        fi
    fi
}
helper-interface-available() {
    if [ -d "${HOME}/.config/rcm" ];then
        cd "${HOME}/.config/rcm"
        ls -1 rcm.plugin.table.* | grep -o -P 'rcm\.plugin\.table\.\K(\S+)'
    fi
}
helper-temporary-suggestion() {
    local is_temporary=$1
    if [ "$is_temporary" == 0 ];then
        exit 1
    fi
    local category=$2
    echo "\$HOME/.cache/rcm/rcm.plugin.table.$category.${RANDOM}${RANDOM}"
}
helper-list() {
    local category=$1
    local table=$2; [ "$table" == - ] && table=
    local table_temporary=$3; [ "$table_temporary" == - ] && table_temporary=
    command-list
}

# Execute command.
if [ -n "$command" ];then
    if [[ $(type -t "command-${command}") == function ]];then
        command-${command} "$@"
        exit 0
    else
        error The function of command '`'"$command"'`' has not yet defined.; x
    fi
fi

printHelp >/dev/null | head -3
_ Try; blue ' 'rcm-plugin; magenta ' '--help; _, ' 'for more information.; _.

# parse-options.sh \
# --without-end-options-double-dash \
# --with-end-options-specific-operand \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --fast
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# OPERAND=(
# add
# list
# execute
# helper
# init
# )
# EOF
# clear

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --fast
# --help
# --temporary
# )
# VALUE=(
# --interface
# --name
# --table
# --table-temporary
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
    # 'long:--command,type:value,parameter:add_command'
    # 'long:--version,type:value,parameter:add_version'
# )
# EOF
# clear

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --fast
# --help
# )
# VALUE=(
# --interface
# --table
# --table-temporary
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --fast
# --help
# )
# VALUE=(
# --interface
# --name
# --table
# --table-temporary
# --method
# --output-file
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --fast
# --help
# )
# VALUE=(
# --interface
# --table
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
