#!/bin/bash

# Rapid Construct Massive
#
# (c) IjorTengab <ijortengab@systemix.id> <ijortengab@gmail.com>
#
# https://github.com/ijortengab/rcm
#
# Command to download: `wget git.io/rcm`
#

# Common Functions.
printVersion() {
    echo '0.18.0-alpha.6'
}
RCM_VERSION=`printVersion`
red() { echo -ne "\e[91m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
green() { echo -ne "\e[92m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
yellow() { echo -ne "\e[93m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
blue() { echo -ne "\e[94m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
magenta() { echo -ne "\e[95m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
error() { echo -n "$INDENT" >&2; red '#' "$@" >&2; echo >&2; }
success() { echo -n "$INDENT" >&2; green '#' "$@" >&2; echo >&2; }
chapter() { echo -n "$INDENT" >&2; yellow '#' "$@" >&2; echo >&2; }
title() { echo -n "$INDENT" >&2; blue '#' "$@" >&2; echo >&2; }
code() { echo -n "$INDENT" >&2; magenta "$@" >&2; echo >&2; }
x() { echo >&2; exit 1; }
e() { echo -n "$INDENT" >&2; echo -n "$@" >&2; }
_() { echo -n "$INDENT" >&2; echo -n "#"' ' >&2; [ -n "$1" ] && echo -n "$@" >&2; }
_,() { echo -n "$@" >&2; }
_.() { echo >&2; }
__() { echo -n "$INDENT" >&2; echo -n "# ${RCM_INDENT}" >&2; [ -n "$1" ] && echo "$@" >&2; }
____() { echo >&2; [ -n "$RCM_DELAY" ] && sleep "$RCM_DELAY"; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
_n=
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help|-h) help=1; shift ;;
        --version|-V) version=1; shift ;;
        --interactive) interactive=1; shift ;;
        --no-confirmation) confirmation=0; shift ;;
        --non-interactive|-x) interactive=0; shift ;;
        --no-timer) timer=0; shift ;;
        --resolved|-r) resolve_dependencies=0; shift ;;
        --slow|-s) fast=0; shift ;;
        --verbose|-v) verbose="$((verbose+1))"; shift ;;
        --without-resolve-dependencies) resolve_dependencies=0; shift ;;
        --with-resolve-dependencies) resolve_dependencies=1; shift ;;
        -[^-]*) _new_arguments+=("$1"); shift ;;
        --)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        *)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
    esac
done
set -- "${_new_arguments[@]}"
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        -[^-]*) OPTIND=1
            while getopts ":hVxrsv" opt; do
                case $opt in
                    h) help=1 ;;
                    V) version=1 ;;
                    x) interactive=0 ;;
                    r) resolve_dependencies=0 ;;
                    s) fast=0 ;;
                    v) verbose="$((verbose+1))" ;;
                esac
            done
            _n="$((OPTIND-1))"
            _n=${!_n}
            shift "$((OPTIND-1))"
            if [[ "$_n" == '--' ]];then
                while [[ $# -gt 0 ]]; do
                    case "$1" in
                        *) _new_arguments+=("$1"); shift ;;
                    esac
                done
            fi
            ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        *)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments
unset _n

# Define variables and constants.
BINARY_DIRECTORY=${BINARY_DIRECTORY:=[__DIR__]}

# Functions.
resolve_relative_path() {
    if [ -d "$1" ];then
        cd "$1" || return 1
        pwd
    elif [ -e "$1" ];then
        if [ ! "${1%/*}" = "$1" ]; then
            cd "${1%/*}" || return 1
        fi
        echo "$(pwd)/${1##*/}"
    else
        return 1
    fi
}

# If not set in argument, try load from environment.
[ -z "$fast" ] && fast="$RCM_FAST"
[ -z "$verbose" ] && verbose="$RCM_VERBOSE"
[ -z "$interactive" ] && interactive="$RCM_INTERACTIVE"
[ -z "$resolve_dependencies" ] && resolve_dependencies="$RCM_RESOLVE_DEPENDENCIES"

# If set in environment, set to variable.
[ -n "$RCM_LOG" ] && log="$RCM_LOG"
[ -n "$RCM_TABLE_DOWNLOADS" ] && table_downloads="$RCM_TABLE_DOWNLOADS"
[ -n "$RCM_TABLE_DEPENDENCIES" ] && table_dependencies="$RCM_TABLE_DEPENDENCIES"
[ -n "$RCM_TABLE_COMMAND_RESOLVED" ] && table_command_resolved="$RCM_TABLE_COMMAND_RESOLVED"
[ -n "$RCM_VERSION" ] && rcm_version="$RCM_VERSION"

# Boolean default to TRUE.
[ -z "$confirmation" ] && confirmation=1; [ "$confirmation" == 0 ] && confirmation=
[ -z "$timer" ] && timer=1; [ "$timer" == 0 ] && timer=
[ -z "$fast" ] && fast=1; [ "$fast" == 0 ] && fast=
[ -z "$resolve_dependencies" ] && resolve_dependencies=1; [ "$resolve_dependencies" == 0 ] && resolve_dependencies=
[ -z "$interactive" ] && interactive=1; [ "$interactive" == 0 ] && interactive=

# Verbosity.
quiet=; loud=; louder=; debug=;
[[ -z "$verbose" || "$verbose" -lt 1 ]] && quiet=1 || quiet=
[[ "$verbose" -gt 0 ]] && loud=1
[[ "$verbose" -gt 1 ]] && loud=1 && louder=1
[[ "$verbose" -gt 2 ]] && loud=1 && louder=1 && debug=1

# Define variables and constants.
RCM_DELAY=${RCM_DELAY:=.5}; [ -n "$fast" ] && unset RCM_DELAY
RCM_INDENT='    '; [ "$(tput cols)" -le 80 ] && RCM_INDENT='  '
[ -z "$log" ] && log=rcm.log
tempfile=
__FILE__=$(resolve_relative_path "$0")
__DIR__=$(dirname "$__FILE__")
find='[__DIR__]'
replace="$__DIR__"
BINARY_DIRECTORY="${BINARY_DIRECTORY/"$find"/"$replace"}"

# Functions. Help and Version.
printHelp() {
    title Rapid Construct Massive
    _ 'Version '; yellow `printVersion`; _.
    _ 'URL '; yellow git.io/rcm; _.
    _.
cat << EOF
Usage: rcm [options]
       rcm <extension> [options]
       rcm [options] <extension> [options]

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.
   --slow, -s
        Add delay every subtask.
   --interactive
        Show asking for confirmation if needed. Default action.
   --non-interactive, -x
        Run without ever asking for user input.
   --verbose, -v
        Verbose mode. Causes rcm to print debugging messages about its progress.
        Multiple -v options increase the verbosity.
        The maximum is 3.
   --without-resolve-dependencies, --resolved, -r
        Skip resolve dependenices.
   --with-resolve-dependencies
        Resolve dependenices. Default action.

Environment Variables:
   BINARY_DIRECTORY
        Default to $BINARY_DIRECTORY
EOF
}

# Help and Version.
[ -n "$help" ] && { printHelp; exit 1; }
[ -n "$version" ] && { printVersion; exit 1; }

# Functions.
Rcm_wget() {
    # Global, untuk debug.
    local http_request line cache_file_basename
    local start end runtime line_number
    http_request=
    local expired="$1"
    local url="$2"
    local table=$HOME/.cache/rcm/rcm.table.cache
    local cache_file=
    if [ -f "$table" ];then
        line=$(grep -n -F "$url"' ' "$table")
        if [ -z "$line" ];then
            http_request=1
        else
            cache_file_basename=$(cut -d' ' -f2 <<< "$line")
            cache_file=$HOME/.cache/rcm/"$cache_file_basename"
        fi
    else
        http_request=1
    fi
    local do_delete_record_cache_file=
    if [ -n "$cache_file" ];then
        if [ -f "$cache_file" ];then
            start=`date -r "$cache_file" +'%s'`
            end=`date +%s`
            runtime=$((end-start))
            if [ $runtime -gt $expired ];then
                do_delete_record_cache_file=1
            fi
        else
            do_delete_record_cache_file=1
        fi
    fi
    if [ -n "$do_delete_record_cache_file" ];then
        line_number=$(cut -d':' -f1 <<< "$line")
        sed -i $line_number'd' "$table"
        http_request=1
        if [ -f "$cache_file" ];then
            rm "$cache_file"
        fi
        cache_file=
    fi
    if [ -n "$http_request" ];then
        mkdir -p $HOME/.cache/rcm
        cache_file=$(mktemp --tmpdir=$HOME/.cache/rcm rcm.wget.XXXXXXXXXXXX.cache)
        cache_file_basename=$(basename "$cache_file")
        # echo wget -q -O "$cache_file" "$url"
        wget -q -O "$cache_file" "$url"
        touch "$cache_file" # wajib karena wget mengubah modified sesuai http header response.
        mkdir -p $(dirname "$table")
        echo "$url" "$cache_file_basename" >> "$table"
    fi
    if [ ! -f "$cache_file" ];then
        exit 1
    fi
    cat "$cache_file"
}

# Functions.
Rcm_init() {
    # global display_waiting
    local owner repository tag_name rcm_extension
    owner=ijortengab
    repository=rcm
    tag_name=`printVersion`
    rcm_extension=$1
    local cache_directory="${HOME}/.cache/rcm/${owner}/${repository}/${tag_name}"
    Rcm_github_download "$owner" "$repository" "$tag_name" "$cache_directory"
    local source="${cache_directory}/${rcm_extension}.sh"
    if [ ! -f "$source" ];then
        error File is not found: "$source".; x
    fi
    local target="${BINARY_DIRECTORY}/${rcm_extension}"
    if [ -f "$target" ];then
        backupFile move "$target"
    fi
    if [ -z "$display_waiting" ];then
        code cp "$source" "$target"
    fi
    cp "$source" "$target"
    if [ -z "$display_waiting" ];then
        _ 'Success install '; magenta "$rcm_extension"; _, ' version: '; yellow "$tag_name"; _.
    fi
}
Rcm_github_download() {
    [[ $(type -t Rcm_wget) == function ]] || { error Function Rcm_wget not found.; x; }
    # global display_waiting
    local owner=$1 repository=$2 tag_name=$3 output_dir=$4
    if [ -z "$owner" ];then
        error "Operand <owner> required."; x
    fi
    if [ -z "$repository" ];then
        error "Operand <repository> required."; x
    fi
    if [ -z "$tag_name" ];then
        error "Operand <tag_name> required."; x
    fi
    if [ -z "$output_dir" ];then
        error "Operand <output_dir> required."; x
    fi
    local url="https://api.github.com/repos/${owner}/${repository}/releases/tags/${tag_name}"
    local tag_name_validate=$(Rcm_wget 3600 "$url" | grep '^  "tag_name": ".*",$' | sed -E 's/  "tag_name": "(.*)",/\1/')
    if [ -z "$tag_name_validate" ];then
        if [ -n "$display_waiting" ];then
            printf "\r\033[K" >&2
        fi
        error "The repository does not have that release tag: ${tag_name}."
        if [ -n "$display_waiting" ];then
            kill -SIGTERM $$
        fi
        # Pastikan exit.
        x
    fi
    if [ -z "$display_waiting" ];then
        _ "Download Github repository ${owner}/${repository}."; _.
    fi
    local tempdir found_directory_extracted cache_directory url_tarball output_dir_parent
    url_tarball="https://api.github.com/repos/${owner}/${repository}/tarball/${tag_name}"
    if [ ! -d "$output_dir" ];then
        if [ -z "$display_waiting" ];then
            _ 'Downloading version: '; yellow "$tag_name"; _.
        fi
        tempdir=$(mktemp -d)
        cd "$tempdir"
        wget -q -O "${tag_name}.tar.gz" "$url_tarball"
        if [ ! -f "${tag_name}.tar.gz" ];then
            error Failed to download file: "${tag_name}.tar.gz".
            cd - >/dev/null
            rm -rf "$tempdir"
            x
        fi
        tar xfz "${tag_name}.tar.gz"
        found_directory_extracted=$(find -maxdepth 1 -mindepth 1 -type d)
        if [ ! -d "$found_directory_extracted" ];then
            error Failed to extract archieve: "${tag_name}.tar.gz".;
            cd - >/dev/null
            rm -rf "$tempdir"
            x
        fi
        output_dir_parent="$(dirname "$output_dir")"
        mkdir -p "$output_dir_parent"
        if [ ! -d "$output_dir_parent" ];then
            error Failed to create output directory parent: "$output_dir_parent".;
        fi
        mv $(realpath "$found_directory_extracted") "$output_dir"
        # Cleaning.
        cd - >/dev/null
        rm -rf "$tempdir"
    else
        if [ -z "$display_waiting" ];then
            _ 'Using downloaded version: '; yellow "$tag_name"; _.
        fi
    fi
}
is_command_resolved() {
    if [ -z "$resolve_dependencies" ];then
        return 0
    fi
    if grep -q -F "$rcm_extension" <<< "$table_command_resolved";then
        return 0
    fi
    return 1
}
if [ -n "$1" ];then

    extension="$1"; shift
    rcm_extension="rcm-${extension}"

    # Title.
    title rcm
    ____

    [ -n "$debug" ] && chapter Dump variable.
    [ -n "$debug" ] && code 'BINARY_DIRECTORY="'$BINARY_DIRECTORY'"'
    [ -n "$debug" ] && code 'RCM_INTERACTIVE="'$RCM_INTERACTIVE'"'
    [ -n "$debug" ] && code 'RCM_VERBOSE="'$RCM_VERBOSE'"'
    [ -n "$debug" ] && code 'RCM_RESOLVE_DEPENDENCIES="'$RCM_RESOLVE_DEPENDENCIES'"'
    [ -n "$debug" ] && code 'RCM_TABLE_DOWNLOADS="'"$RCM_TABLE_DOWNLOADS"'"'
    [ -n "$debug" ] && code 'RCM_TABLE_DEPENDENCIES="'"$RCM_TABLE_DEPENDENCIES"'"'
    [ -n "$debug" ] && code 'RCM_TABLE_COMMAND_RESOLVED="'"$RCM_TABLE_COMMAND_RESOLVED"'"'
    [ -n "$debug" ] && code 'RCM_FAST="'$RCM_FAST'"'
    [ -n "$debug" ] && code 'RCM_LOG="'$RCM_LOG'"'
    [ -n "$debug" ] && code 'RCM_VERSION="'$RCM_VERSION'"'
    [ -n "$debug" ] && code 'interactive="'$interactive'"'
    [ -n "$debug" ] && code 'verbose="'$verbose'"'
    [ -n "$debug" ] && code 'quiet="'$quiet'"'
    [ -n "$debug" ] && code 'loud="'$loud'"'
    [ -n "$debug" ] && code 'louder="'$louder'"'
    [ -n "$debug" ] && code 'debug="'$debug'"'
    [ -n "$debug" ] && code 'resolve_dependencies="'$resolve_dependencies'"'
    [ -n "$debug" ] && code 'log="'$log'"'
    if [ -z "$rcm_version" ];then
        rcm_version=`printVersion`
    elif [[ ! "$rcm_version" == `printVersion` ]];then
        error RCM Version dari parent process tidak sama dengan current process; x
    fi
    [ -n "$debug" ] && code 'rcm_version="'$rcm_version'"'
    [ -n "$debug" ] && ____

    rcm_extension_required=(rcm-exec rcm-get rcm-history rcm-install rcm-list rcm-paragraph rcm-plugin rcm-resolve rcm-update)
    for each in "${rcm_extension_required[@]}"; do
        if ! command -v "$each" > /dev/null;then
            Rcm_init $each
            ____
        fi
    done

    [ -z "$fast" ] && isfast='' || isfast=' --fast'
    [ -n "$verbose" ] && {
        isverbose=
        for ((i = 0 ; i < "$verbose" ; i++)); do
            isverbose+=' --verbose'
        done
    } || isverbose=
    if [[ "$extension" =~ : ]];then
        extension_raw="$extension"
        extension=`cut -d: -f1 <<< "${extension_raw}"`
        extension_version=`cut -d: -f2 <<< "${extension_raw}"`
    else
        extension_raw="$extension"
        extension_version=
    fi

    # Get download information.
    if command -v "$rcm_extension" > /dev/null;then
        _help=$($rcm_extension --help 2>/dev/null)
        _download=$(echo "$_help" | sed -n '/^Download:/,$p' | sed -n '2,/^\s*$/p' | sed 's/^ *//g')
        if [ -n "$_download" ];then
            while IFS= read -r _line; do
                if ! grep -q -F -- "$_line" <<< "$table_downloads";then
                    [ -n "$_line" ] && table_downloads+="$_line"$'\n'
                fi
            done <<< "$_download"
        fi
    fi

    # Boolean export as 0 or 1. Must not leave empty string.
    [ -n "$interactive" ] && RCM_INTERACTIVE=1 || RCM_INTERACTIVE=0
    [ -n "$resolve_dependencies" ] && RCM_RESOLVE_DEPENDENCIES=1 || RCM_RESOLVE_DEPENDENCIES=0
    # Other variable, export as is.
    RCM_TABLE_DOWNLOADS="$table_downloads"
    RCM_TABLE_DEPENDENCIES="$table_dependencies"
    RCM_LOG="$log"
    RCM_VERSION="$rcm_version"

    [ -n "$extension_version" ] && extension_version=":${extension_version}"

    if ! is_command_resolved;then
        [ -n "$extension_version" ] && extension_version=":${extension_version}"
        INDENT+="$RCM_INDENT" \
        BINARY_DIRECTORY="$BINARY_DIRECTORY" \
        RCM_TABLE_DOWNLOADS="$RCM_TABLE_DOWNLOADS" \
        RCM_TABLE_DEPENDENCIES="$RCM_TABLE_DEPENDENCIES" \
        RCM_VERSION="$RCM_VERSION" \
        rcm-resolve $isfast $isverbose "${rcm_extension}${extension_version}" \
            ; [ ! $? -eq 0 ] && x
        table_command_resolved+="$rcm_extension"$'\n'
    fi
    RCM_TABLE_COMMAND_RESOLVED="$table_command_resolved"

    subcommand_substitute=
    if [ -n "$1" ];then
        first_operand="$1"
        _subcommand_substitute=`$rcm_extension --help 2>/dev/null | sed -n '/^Subcommand Substitute[:\.]$/,$p' | sed -n '1,/^\s*$/p' | sed -n '2,/^\s*$/p'`
        if [ -n "$_subcommand_substitute" ];then
            # Trim.
            _subcommand_substitute=`echo "$_subcommand_substitute" | sed 's/^[[:blank:]]*//;s/[[:blank:]]*$//'`
            if grep -E -q "^${first_operand}:\s+" <<< "$_subcommand_substitute";then
                subcommand_substitute=`grep -o -P "^${first_operand}:\s+\K(.*)" <<< "$_subcommand_substitute" | tail -1`
                shift
                chapter Subcommand substitute.
                _; _, Subcommand ; magenta ' '"$first_operand"' '; _, makes command shift to; yellow ' '"$subcommand_substitute"' '; _, automatically.; _.
                ____

            fi
        fi
    fi

    if [ -z "$subcommand_substitute" ];then
        [ -z "$confirmation" ] && isconfirmation=' --no-confirmation' || isconfirmation=' '

        [ -z "$tempfile" ] && tempfile=$(mktemp -p /dev/shm -t rcm.XXXXXX)
        INDENT+="$RCM_INDENT" \
        BINARY_DIRECTORY="$BINARY_DIRECTORY" \
        RCM_INTERACTIVE="$RCM_INTERACTIVE" \
        RCM_RESOLVE_DEPENDENCIES="$RCM_RESOLVE_DEPENDENCIES" \
        RCM_TABLE_DOWNLOADS="$RCM_TABLE_DOWNLOADS" \
        RCM_TABLE_DEPENDENCIES="$RCM_TABLE_DEPENDENCIES" \
        RCM_TABLE_COMMAND_RESOLVED="$RCM_TABLE_COMMAND_RESOLVED" \
        RCM_LOG="$RCM_LOG" \
        RCM_VERSION="$RCM_VERSION" \
        rcm-exec $isfast $isverbose $isconfirmation "${rcm_extension}${extension_version}" "$@" > "$tempfile"
        rcm_exec_exit_code=$?
        if [ -s "$tempfile" ];then
            rcm_exec_stdout=$(<"$tempfile")
        else
            rcm_exec_stdout=
        fi
        rm "$tempfile"
        case "$rcm_exec_exit_code" in
            0) echo "$rcm_exec_stdout" ;;
            1) x ;;
            2) subcommand_substitute="$rcm_exec_stdout" ;;
            *) echo "$rcm_exec_stdout" ;;
        esac
    fi

    if [ -n "$subcommand_substitute" ];then

        extension="${subcommand_substitute:4}"

        INDENT+="$RCM_INDENT" \
        BINARY_DIRECTORY="$BINARY_DIRECTORY" \
        RCM_INTERACTIVE="$RCM_INTERACTIVE" \
        RCM_RESOLVE_DEPENDENCIES="$RCM_RESOLVE_DEPENDENCIES" \
        RCM_TABLE_DOWNLOADS="$RCM_TABLE_DOWNLOADS" \
        RCM_TABLE_DEPENDENCIES="$RCM_TABLE_DEPENDENCIES" \
        RCM_TABLE_COMMAND_RESOLVED="$RCM_TABLE_COMMAND_RESOLVED" \
        RCM_LOG="$RCM_LOG" \
        rcm $isfast $isverbose "$extension" "$@"
    fi
else
    printHelp >/dev/null | head -3
    _ Try; blue ' 'rcm; magenta ' '--help; _, ' 'for more information.; _.
fi

exit 0

# parse-options.sh \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --with-end-options-first-operand \
# --with-end-options-double-dash \
# --no-error-require-arguments << EOF | clip
# INCREMENT=(
#     '--verbose|-v'
# )
# FLAG=(
# '--version|-V'
# '--help|-h'
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
#     'long:--interactive,parameter:interactive'
#     'long:--non-interactive,short:-x,parameter:interactive,flag_option:reverse'
#     'long:--with-resolve-dependencies,parameter:resolve_dependencies'
#     'long:--without-resolve-dependencies,parameter:resolve_dependencies,flag_option:reverse'
#     'long:--resolved,short:-r,parameter:resolve_dependencies,flag_option:reverse'
#     'long:--no-confirmation,parameter:confirmation,flag_option:reverse'
#     'long:--no-timer,parameter:timer,flag_option:reverse'
#     'long:--slow,short:-s,parameter:fast,flag_option:reverse'
# )
# OPERAND=(
# )
# EOF
# clear
