#!/bin/bash

[ -f "$0" ] || { echo "Cannot run as dot command." >&2; kill -INT $$; }

# Define variables and constants.
RCM_EXTENSION_VERSION=0.19.0-alpha.13
RCM_TLD_SPECIAL=${RCM_TLD_SPECIAL:=example test onion invalid local localhost alt}

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm nginx add vhost php-multiple-root [options]

Options:
   --url=URL
        Set the URL.
   --nginx-config-root=VALUE
        Set the NGINX config Root.
   --web-root=[DIR]
        Required if --url is empty of path component.
   --fastcgi-pass=VALUE
        Set the value of fastcgi_pass directive.
   --nginx-config-dir=DIR
        The value to include directive. Include file that contains location directive.
   --nginx-config-file=FILE
        Additional value to include directive. Include file that contains location directive.
   --without-nginx-reload
        Prevent auto reload nginx after add/edit file config.
        Default value is --with-nginx-reload.
   --tls-certificate=[VALUE]
        Directive tls_certificate in nginx config.
        Populate value from variable TLS_CERTIFICATE.
   --tls-certificate-key=[VALUE]
        Directive tls_certificate_key in nginx config.
        Populate value from variable TLS_CERTIFICATE_KEY.

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --fastcgi-pass=*) fastcgi_pass="${1#*=}"; shift ;;
        --fastcgi-pass) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then fastcgi_pass="$2"; shift; fi; shift ;;
        --nginx-config-dir=*) nginx_config_dir="${1#*=}"; shift ;;
        --nginx-config-dir) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then nginx_config_dir="$2"; shift; fi; shift ;;
        --nginx-config-file=*) nginx_config_file="${1#*=}"; shift ;;
        --nginx-config-file) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then nginx_config_file="$2"; shift; fi; shift ;;
        --nginx-config-root=*) nginx_config_root="${1#*=}"; shift ;;
        --nginx-config-root) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then nginx_config_root="$2"; shift; fi; shift ;;
        --tempfile-trigger-reload=*) tempfile_trigger_reload="${1#*=}"; shift ;;
        --tempfile-trigger-reload) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tempfile_trigger_reload="$2"; shift; fi; shift ;;
        --tls-certificate-key=*) tls_certificate_key="${1#*=}"; shift ;;
        --tls-certificate-key) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate_key="$2"; shift; fi; shift ;;
        --tls-certificate=*) tls_certificate="${1#*=}"; shift ;;
        --tls-certificate) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate="$2"; shift; fi; shift ;;
        --url=*) url="${1#*=}"; shift ;;
        --url) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then url="$2"; shift; fi; shift ;;
        --with-nginx-reload) nginx_reload=1; shift ;;
        --without-nginx-reload) nginx_reload=0; shift ;;
        --web-root=*) web_root="${1#*=}"; shift ;;
        --web-root) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then web_root="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm nginx add vhost php-multiple-root
____

# Dependency.
require rcm nginx reload
require vendor/ijortengab/rcm/functions/classes/rcm-file.sh
require vendor/ijortengab/rcm/functions/classes/rcm-dir.sh
require vendor/ijortengab/rcm/functions/utility/url-complete-component.sh
require vendor/ijortengab/rcm/functions/utility/backup-file.sh
require vendor/ijortengab/rcm/functions/utility/link-symbolic.sh

# Functions.
ArraySearch() {
    local index match="$1"
    local source=("${!2}")
    for index in "${!source[@]}"; do
       if [[ "${source[$index]}" == "${match}" ]]; then
           _return=$index; return 0
       fi
    done
    return 1
}
# Required function: ArraySearch.
# Karakter operator yang berlaku adalah: = != < > <= >= ~ !~
tokenToBinary () {
    local token=$1; shift;
    [ -z "$token" ] && { error 'Argument <token> is empty. '; x; }
    local token_list=$1; shift;
    [ -z "$token_list" ] && { error 'Argument <token_list> is empty. '; x; }
    local string=$1; shift;
    [ -z "$string" ] && { error 'Argument <string> is empty. '; x; }
    [[ $(type -t ArraySearch) == function ]] || { error Function ArraySearch not found.; x; }
    local array
    # Jika terjadi pengulangan, contoh:
    # a contains 80  a contains 8080
    # Maka kita ambil yang paling akhir.
    local token_list_last=$(echo "$token_list" | grep "^[$token]\s" | tail -1)
    local operator=$(echo "$token_list_last" | cut -d' ' -f2 )
    local value=$(echo "$token_list_last" | cut -d' ' -f3- )
    case "$operator" in
        =)
            if [[ "$string" == "$value" ]];then echo 1; else echo 0; fi
            ;;
        '<>')
            if [[ "$string" == "$value" ]];then echo 0; else echo 1; fi
            ;;
        '<')
            if [[ "$string" -lt "$value" ]];then echo 1; else echo 0; fi
            ;;
        '>')
            if [[ "$string" -gt "$value" ]];then echo 1; else echo 0; fi
            ;;
        '<=')
            if [[ "$string" -le "$value" ]];then echo 1; else echo 0; fi
            ;;
        '>=')
            if [[ "$string" -ge "$value" ]];then echo 1; else echo 0; fi
            ;;
        '[]')
            read -ra array -d '' <<< "$string"
            if ArraySearch "$value" array[@];then echo 1; else echo 0; fi
            ;;
        '![]')
            read -ra array -d '' <<< "$string"
            if ArraySearch "$value" array[@];then echo 0; else echo 1; fi
            ;;
        '~')
            if grep -q -E "$value" <<< "$string";then echo 1; else echo 0; fi
            ;;
        '!~')
            if grep -q -E "$value" <<< "$string";then echo 0; else echo 1; fi
            ;;
        *)
            echo 0
            error Operator is not valid: '`'$operator'`'; x
    esac
}
# Required function: tokenToBinary.
# Reference: https://github.com/parsecsv/parsecsv-for-php/blob/main/src/Csv.php#L1055
resolveCondition() {
    local condition=$1; shift;
    local token_list=$1; shift;
    local string=$1; shift;
    local i
    i=0
    binary="$condition"
    conditionToBinary() {
        local condition=$1; shift;
        [ -z "$condition" ] && { error 'Argument <condition> is empty. '; x; }
        local token_list=$1; shift;
        local string=$1; shift;
        local each array
        local or=
        local and=
        conditionToBinaryOr () {
            local condition=$1; shift;
            [ -z "$condition" ] && { error 'Argument <condition> is empty. '; x; }
            local token_list=$1; shift;
            local string=$1; shift;
            local each array
            local or=
            IFS='|' read -ra array <<< "$condition"
            for each in "${array[@]}"; do
                if [ -n "$token_list" ];then
                    or+=$(conditionToBinaryAnd "$each" "$token_list" "$string")
                else
                    or+=$(conditionToBinaryAnd "$each")
                fi
            done
            [[ "$or" =~ 1 ]] && echo 1 || echo 0
        }
        conditionToBinaryAnd () {
            local condition=$1; shift;
            [ -z "$condition" ] && { error 'Argument <condition> is empty. '; x; }
            local token_list=$1; shift;
            local string=$1; shift;
            local each array
            local and=
            IFS='&' read -ra array <<< "$condition"
            for each in "${array[@]}"; do
                if [ -n "$token_list" ];then
                    and+=$(tokenToBinary "$each" "$token_list" "$string")
                else
                    and+="$each"
                fi
            done
            [[ "$and" =~ 0 ]] && echo 0 || echo 1
        }
        conditionToBinaryOr "$condition" "$token_list" "$string"
    }
    until [[ "$binary" =~ ^(0|1)$ ]];do
        i=$(( i + 1 ))
        # e 'Looping ke-' "$i" ; _.
        # e '< "$binary"' "$binary" ; _.
        if [[ $(echo "$binary" | grep -i -o -E '\([^\(\)]+\)' | grep -o -E '[^\(\)]+' | wc -l) -eq 0 ]];then
            if [[ "$binary" =~ ^[a-z]$ ]];then
                # e '< "$binary"' "$binary"; _.
                binary=$(conditionToBinary "$binary" "$token_list" "$string")
                # e '> "$binary"' "$binary"; _.
            else
                # error Token tidak valid: '`'$token'`'; x
                # e '< "$binary"' "$binary"; _.
                binary=$(conditionToBinary "$binary")
                # e '> "$binary"' "$binary"; _.
            fi
        else
            while IFS= read insideBraces; do
                find="(${insideBraces})"
                # e '"$find"' "$find" ; _.
                replace=$(conditionToBinary "$insideBraces" "$token_list" "$string")
                # e '"$replace"' "$replace" ; _.
                # _ Jangan gunakan replace all, karena bisa jadi ada tanda kurung yang sama.
                # _ Contoh: binary='(a&b)|c|(a&c)|((m&r|(a&b)))'
                # e '< "$binary"' "$binary" ; _.
                binary="${binary/"$find"/"$replace"}"
                # e '> "$binary"' "$binary" ; _.
            done <<< `echo "$binary" | grep -o -E '\([^\(\)]+\)' | grep -o -E   '[^\(\)]+'`
        fi
        # e '> "$binary"' "$binary"; _.
        # __ Limit adalah 100 ya gaes.
        # __ 100 lopping belum ketemu juga, artinya set error dan kembalikan false
        if [[ $i == 100 ]];then
            error Kesalahan Logic.
            binary=0
        fi
    done
    echo "$binary"
}
# Required function: resolveCondition.
nginxGrep(){
    validateToken() {
        # global token
        if [[ ! "$token" =~ ^[a-z]$ ]];then
            error Token tidak valid: '`'$token'`'; x
        fi
    }
    # Mengubah operator dari text string menjadi simbol, sekaligus validasi.
    # Karakter operator yang berlaku adalah: = != < > <= >= ~ !~
    validateOperator() {
        # global operator
        case "$operator" in
            is|equals|=)
                operator='=' ;;
            '!='|'is not'|'<>')
                operator='<>' ;;
            '<'|'is less than')
                operator='<' ;;
            '>'|'is greater than')
                operator='>' ;;
            '<='|'is less than or equals')
                operator='<=' ;;
            '>='|'is greater than or equals')
                operator='>=' ;;
            '[]'|'contains')
                operator='[]' ;;
            '![]'|'does not contain')
                operator='![]' ;;
            '~'|'match')
                operator='~' ;;
            '!~'|'does not match')
                operator='!~' ;;
            *)
                error Operator is not valid: '`'$operator'`'; x
        esac
    }
    [[ $(type -t resolveCondition) == function ]] || { error Function resolveCondition not found.; x; }
    local i token operator
    local directive=$1; shift
    # Jika total argument setelah directive adalah 7, 10, 13, dst.,
    # maka berarti conditional complex. Contohnya.
    # nginxGrep listen '(a&b)' a contains 8080 b contains ssl < a.txt
    # nginxGrep listen '(a&b)|c' a contain6s 8080 b contains ssl c contains ipv6only=on < a.txt
    token_list=
    if [[ $# -gt 6 && $(( $# % 3 )) == 1 ]];then
        condition=$1; shift
        while [ $# -gt 0 ];do
            token=$1
            validateToken
            operator=$2
            validateOperator
            token_list+="${token} ${operator} $3"
            token_list+=$'\n'
            shift 3;
        done
    # Jika total argument setelah directive adalah 1, maka mencari fix value.
    # Contohnya:
    # nginxGrep listen 8080
    elif [[ $# -eq 1 ]];then
        condition=a
        token_list+="a = $1"
        token_list+=$'\n'
    # Jika total argument setelah directive adalah 2, maka berarti conditional
    # sederhana. Contohnya.
    # nginxGrep listen contains ssl
    # nginxGrep listen 'is not contain' ssl
    elif [[ $# -eq 2 ]];then
        condition=a
        operator=$1
        validateOperator
        token_list+="a ${operator} $2"
        token_list+=$'\n'
    fi
    lines_directive=()
    if [ ! -t 0 ]; then
        i=0
        _ Mencari directive: '`'${directive}'`'; _.
        [ -n "$debug" ] && { _; magenta grep -E "^\s*${directive}\s+[^;]+;\s*\$"; _.; }
        while IFS= read line; do
            i=$(( i + 1 ))
            if [ "${#line}" -eq 0 ];then
                [ -n "$debug" ] && { __; }
            else
                [ -n "$debug" ] && { _; yellow "$line"; _, ' # Line:' $i; }
            fi
            if grep -q -E "^\s*${directive}\s+[^;]+;\s*\$" <<< "$line";then
                [ -n "$debug" ] && { _, ' '; green Baris ditemukan.; }
                lines_directive+=("$line")
            fi
            [ -n "$debug" ] && { _.; }
        done </dev/stdin
    fi
    if [ "${#lines_directive[@]}" -eq 0 ];then
        return 1
    fi
    [ -n "$debug" ] && { _; _.; }
    [ -n "$debug" ] && { _ Variable dump '`'\$condition'`'.; _.; }
    [ -n "$debug" ] && { e; magenta $condition; _.; }
    [ -n "$debug" ] && { _; _.; }
    [ -n "$debug" ] && { _ Variable dump '`'\$token_list'`'.; _.; }
    [ -n "$debug" ] && { while IFS= read line; do [ -n "$line" ] || continue; e; magenta "$line"; _. ; done <<< "$token_list"; }
    # _; _.
    # Directive bisa berulang.
    # Contoh: directive listen bisa berulang sebanyak dua kali.
    # Jadi jika satu saja sudah solve, maka langsung break saja.
    local resolved
    for line in "${lines_directive[@]}"; do
        # e '"$line"' "$line" ; _.
        directive_reverse=$(echo "$line" | sed -E -e "s;\s*${directive}\s+(.*);\1;" -e 's|;\s*$||')
        # e '"$directive_reverse"' "$directive_reverse" ; _.
        resolved=$(resolveCondition "$condition" "$token_list" "$directive_reverse")
        # e '"$resolved"' "$resolved" ; _.
        if [ "$resolved" == 1 ];then
            [ -n "$debug" ] && { _; _.; }
            _ Condition solved pada baris:' '; yellow  "$line"; _.
            [ -n "$debug" ] && { _; _.; }
            return 0
        fi
    done
    return 1
}
findString() {
    # global debug
    # global find_quoted
    # $find_quoted agar bisa di gunakan oleh sed.
    local find="$1" string path="$2" tempfile="$3" deletetempfile
    if [ -z "$tempfile" ];then
        tempfile=$(mktemp -p /dev/shm)
        deletetempfile=1
    fi
    _; _, Memeriksa baris dengan kalimat: '`'$find'`'.;_.
    find_quoted="$find"
    find_quoted=$(sed -E "s/\s+/\\\s\+/g" <<< "$find_quoted")
    find_quoted=$(sed "s/\./\\\./g" <<< "$find_quoted")
    find_quoted=$(sed "s/\*/\\\*/g" <<< "$find_quoted")
    find_quoted=$(sed "s/;$/\\\s\*;/g" <<< "$find_quoted")
    if [[ ! "${find_quoted:0:1}" == '^' ]];then
        find_quoted="^\s*${find_quoted}"
    fi
    _; magenta grep -E '"'"${find_quoted}"'"' '"'"\$path"'"'; _.
    if grep -E "${find_quoted}" "$path" > "$tempfile";then
        string="$(< "$tempfile")"
        while read -r line; do e "$line"; _.; done <<< "$string"
        __ Baris ditemukan.
        [ -n "$deletetempfile" ] && rm "$tempfile"
        return 0
    else
        __ Baris tidak ditemukan.
        [ -n "$deletetempfile" ] && rm "$tempfile"
        return 1
    fi
}
validateContentMaster() {
    local path="$1"
    # listen
    if [ "$url_scheme" == https ];then
        if ! nginxGrep listen '(a&b)|(a&b&c)' a contains "$url_port" b contains ssl c contains ipv6only=on < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    else
        if ! nginxGrep listen contains "$url_port" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    fi
    # server_name
    if ! nginxGrep server_name contains "$url_host" < "$path";then
        __; yellow File akan dibuat ulang.; _.
        return 1
    fi

    if [ "$url_scheme" == https ];then
        # ssl_certificate
        if ! nginxGrep ssl_certificate is "$ssl_certificate" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # ssl_certificate_key
        if ! nginxGrep ssl_certificate_key is "$ssl_certificate_key" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # include
        if ! nginxGrep include is /etc/letsencrypt/options-ssl-nginx.conf < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # include
        if ! nginxGrep ssl_dhparam is /etc/letsencrypt/ssl-dhparams.pem < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    fi
    if [ "$url_scheme" == http ];then
        # ssl_certificate
        if nginxGrep ssl_certificate is "$ssl_certificate" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # ssl_certificate_key
        if nginxGrep ssl_certificate_key is "$ssl_certificate_key" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # include
        if nginxGrep include is /etc/letsencrypt/options-ssl-nginx.conf < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # include
        if nginxGrep ssl_dhparam is /etc/letsencrypt/ssl-dhparams.pem < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    fi
    return 0
}
validateContentSlave() {
    local path="$1"
    # fastcgi_pass
    if ! nginxGrep fastcgi_pass is "$fastcgi_pass" < "$path";then
        __; yellow File akan dibuat ulang.; _.
        return 1
    fi
    if [ -z "$url_path" ];then
        # root
        if ! nginxGrep root is "$web_root" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    fi
    return 0
}
validateContentRedirect() {
    local path="$1"
    # listen
    if ! nginxGrep listen contains 80 < "$path";then
        __; yellow File akan dibuat ulang.; _.
        return 1
    fi
    # server_name
    if ! nginxGrep server_name contains "$url_host" < "$path";then
        __; yellow File akan dibuat ulang.; _.
        return 1
    fi
    return 0
}

if [ -n "$RCM_VERBOSE" ];then
    verbose="$RCM_VERBOSE"
fi
[[ -z "$verbose" || "$verbose" -lt 1 ]] && quiet=1 || quiet=
[[ "$verbose" -gt 0 ]] && loud=1
[[ "$verbose" -gt 1 ]] && loud=1 && louder=1
[[ "$verbose" -gt 2 ]] && loud=1 && louder=1 && debug=1

# Require, validate, and populate value.
chapter Variable dump.
if [ -z "$url" ];then
    error "Argument --url required."; x
fi
code 'url="'$url'"'
url-complete-component
code 'url="'$url'"'
code 'url_scheme="'$url_scheme'"'
code 'url_host="'$url_host'"'
code 'url_port="'$url_port'"'
code 'url_path="'$url_path'"'
code 'url_path_clean="'$url_path_clean'"'
code 'url_path_clean_trailing="'$url_path_clean_trailing'"'

if [ -z "$nginx_config_root" ];then
    error "Argument --nginx-config-root required."; x
fi
code 'nginx_config_root="'$nginx_config_root'"'
if [ -z "$nginx_config_file" ];then
    error "Argument --nginx-config-file required."; x
fi
code 'nginx_config_file="'$nginx_config_file'"'
if [ -z "$nginx_config_dir" ];then
    error "Argument --nginx-config-dir required."; x
fi
code 'nginx_config_dir="'$nginx_config_dir'"'
if [ -z "$fastcgi_pass" ];then
    error "Argument --fastcgi-pass required."; x
fi
if [ -z "$url_path" ];then
    if [ -z "$web_root" ];then
        error "Argument --web-root required."; x
    fi
    slave_dirname="${nginx_config_file%/*}"
    slave_filename="${nginx_config_file##*/}"
else
    slave_dirname="$nginx_config_dir"
    slave_filename="${url_path_clean//\//.}"
fi
code 'slave_filename="'$slave_filename'"'
code 'slave_dirname="'$slave_dirname'"'
rcm-dir "$slave_dirname" terminateIfNotExists
[ -z "$nginx_reload" ] && nginx_reload=1
[ "$nginx_reload" == 0 ] && nginx_reload=
master_include="${nginx_config_dir}/*"
code 'master_include="'$master_include'"'
if [[ "$url_port" == 80 || "$url_port" == 443 ]];then
    master_filename="$url_host"
else
    master_filename="${url_host}.${url_port}"
fi
code 'master_filename="'$master_filename'"'
code 'web_root="'$web_root'"'
code 'fastcgi_pass="'$fastcgi_pass'"'
code 'nginx_reload="'$nginx_reload'"'
code 'tempfile_trigger_reload="'$tempfile_trigger_reload'"'
# code 'tls_certificate="'$tls_certificate'"'
# code 'tls_certificate_key="'$tls_certificate_key'"'
# If not set in argument, try load from environment.
# [ -z "$tls_certificate" ] && tls_certificate="$TLS_CERTIFICATE"
# [ -z "$tls_certificate_key" ] && tls_certificate_key="$TLS_CERTIFICATE_KEY"
# code 'tls_certificate="'$tls_certificate'"'
# code 'tls_certificate_key="'$tls_certificate_key'"'
rcm_nginx_reload=
tempfile=
validate_existing_certificate=
if [[ "$url_scheme" == https ]];then
    if [ -z "$tls_certificate" ];then
        error "Argument --tls-certificate required."; x
    fi
    if [ -z "$tls_certificate_key" ];then
        error "Argument --tls-certificate-key required."; x
    fi
fi
____

chapter Populate variable.
if [[ "$url_scheme" == https ]];then
    ssl_certificate="$tls_certificate"
    ssl_certificate_key="$tls_certificate_key"
fi
code 'ssl_certificate="'$ssl_certificate'"'
code 'ssl_certificate_key="'$ssl_certificate_key'"'
____

path="/etc/nginx/sites-available/$master_filename"
filename="$master_filename"
chapter Mengecek nginx config file: '`'$filename'`'.
code 'path="'$path'"'
rcm-file "$path" isExists

____

create_new=
if [ -n "$found" ];then
    chapter Memeriksa konten.
    validateContentMaster "$path"
    [ ! $? -eq 0 ] && create_new=1;
    ____
else
    create_new=1
fi

if [[ -n "$create_new" && "$url_scheme" == https ]];then
    chapter Memeriksa certificate SSL.
    rcm-file "$ssl_certificate" terminateIfNotExists
    rcm-file "$ssl_certificate_key" terminateIfNotExists
    ____
fi

if [ -n "$create_new" ];then
    path="/etc/nginx/sites-available/$master_filename"
    filename="$master_filename"
    chapter Membuat nginx config file: '`'$filename'`'.
    code 'path="'$path'"'
    if [ -f "$path" ];then
        __ Backup file: '`'"$filename"'`'.
        backup-file move "$path"
    fi
    __ Membuat file "$filename".
    cat <<'EOF' > "$path"
server {
    listen [::]:__URL_PORT____SSL__;
    listen __URL_PORT____SSL____IPV6ONLY__;
    index index.php;
    server_name __URL_HOST__;
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    # include __MASTER_INCLUDE__;
    # include __NGINX_CONFIG_FILE__;

    # ssl_certificate __SSL_CERTIFICATE__;
    # ssl_certificate_key __SSL_CERTIFICATE_KEY__;
    # include /etc/letsencrypt/options-ssl-nginx.conf;
    # ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # error_page 497 301 =307 https://$host:$server_port$request_uri;
}
EOF
    rcm-file "$path" mustExists
    sed -i "s|__URL_HOST__|${url_host}|g" "$path"
    sed -i "s|__SSL_CERTIFICATE__|${ssl_certificate}|g" "$path"
    sed -i "s|__SSL_CERTIFICATE_KEY__|${ssl_certificate_key}|g" "$path"
    sed -i "s|__MASTER_INCLUDE__|${master_include}|g" "$path"
    sed -i "s|__NGINX_CONFIG_FILE__|${nginx_config_file}|g" "$path"
    sed -i "s|__URL_PORT__|${url_port}|g" "$path"
    if [ "$url_scheme" == https ];then
        sed -i "s|__SSL__| ssl|g" "$path"
        # Hanya satu ipv6only=on yang boleh exist pada setiap virtual host.
        if grep -R -q ipv6only=on /etc/nginx/sites-enabled/;then
            sed -i "s|__IPV6ONLY__||g" "$path"
        else
            sed -i "s|__IPV6ONLY__| ipv6only=on|g" "$path"
        fi
        sed -i -E 's|^(\s*)# ssl_certificate (.*);|\1ssl_certificate \2;|g' "$path"
        sed -i -E 's|^(\s*)# ssl_certificate_key (.*);|\1ssl_certificate_key \2;|g' "$path"
        sed -i -E 's|^(\s*)# include /etc/letsencrypt/options-ssl-nginx.conf;|\1include /etc/letsencrypt/options-ssl-nginx.conf;|g' "$path"
        sed -i -E 's|^(\s*)# ssl_dhparam (.*);|\1ssl_dhparam \2;|g' "$path"
    else
        sed -i "s|__SSL__||g" "$path"
        sed -i "s|__IPV6ONLY__||g" "$path"
    fi
    if [ -z "$url_path" ];then
        sed -i 's|# include '"${nginx_config_file}"';|include '"${nginx_config_file}"';|g' "$path"
    else
        sed -i 's|# include '"${master_include}"';|include '"${master_include}"';|g' "$path"
    fi
    ____

    chapter Memeriksa ulang konten.
    validateContentMaster "$path"
    [ ! $? -eq 0 ] && x
    ____

    rcm_nginx_reload=1
fi

path="/etc/nginx/sites-available/$master_filename"
source="$path"
target="/etc/nginx/sites-enabled/$master_filename"
link-symbolic "$source" "$target"

chapter Enable the line to include sub nginx config file: '`'$filename'`'.
if [ -z "$url_path" ];then
    template="    include __NGINX_CONFIG_FILE__;"
    find=$(echo "$template" | sed "s|__NGINX_CONFIG_FILE__|${nginx_config_file}|g")
    if findString "# ${find}" "$path";then
        code sed -i -E "'"'s|'"${find_quoted}"'|'"${find}"'|g'"'" "$path"
        sed -i -E 's|'"${find_quoted}"'|'"${find}"'|g' "$path"
    fi
    if ! nginxGrep include is "$nginx_config_file" < "$path";then
        error Enable gagal.; x
    fi
else
    template="    include __MASTER_INCLUDE__;"
    find=$(echo "$template" | sed "s|__MASTER_INCLUDE__|${master_include}|g")
    if findString "# ${find}" "$path";then
        code sed -i -E "'"'s|'"${find_quoted}"'|'"${find}"'|g'"'" "$path"
        sed -i -E 's|'"${find_quoted}"'|'"${find}"'|g' "$path"
    fi
    if ! nginxGrep include is "$master_include" < "$path";then
        error Enable gagal.; x
    fi
fi
____

path="${slave_dirname}/${slave_filename}"
filename="$slave_filename"
chapter Mengecek nginx config file: '`'$filename'`'.
code 'path="'$path'"'
rcm-file "$path" isExists
____

create_new=
if [ -n "$found" ];then
    chapter Memeriksa konten.
    validateContentSlave "$path"
    [ ! $? -eq 0 ] && create_new=1;
    ____
else
    create_new=1
fi

if [ -n "$create_new" ];then
    path="${slave_dirname}/${slave_filename}"
    filename="$slave_filename"
    chapter Membuat nginx config file: '`'$filename'`'.
    code 'path="'$path'"'
    if [ -f "$path" ];then
        __ Backup file: '`'"$filename"'`'.
        backup-file move "$path" parent
    fi
    __ Membuat file "$filename".
    if [ -z "$url_path" ];then
        cat <<'EOF' > "$path"
location / {
    root __WEB_ROOT__;
    try_files $uri $uri/ /index.php$is_args$args;
    location ~ ^(.+\.php)(.*)$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass __FASTCGI_PASS__;
        fastcgi_read_timeout 3600;
    }
}
EOF
        sed -i "s|__WEB_ROOT__|${web_root}|g" "$path"
        sed -i "s|__FASTCGI_PASS__|${fastcgi_pass}|g" "$path"
    else
        cat <<'EOF' > "$path"
location = __URL_PATH_CLEAN_TRAILING__ {
    return 302 __URL_PATH_CLEAN_TRAILING__/;
}
location __URL_PATH_CLEAN_TRAILING__/ {
    root __NGINX_CONFIG_ROOT__;
    try_files $uri $uri/ __URL_PATH_CLEAN_TRAILING__/index.php$is_args$args;
    location ~ ^(.+\.php)(.*)$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass __FASTCGI_PASS__;
    }
}
EOF
        sed -i "s|__URL_PATH_CLEAN_TRAILING__|${url_path_clean_trailing}|g" "$path"
        sed -i "s|__FASTCGI_PASS__|${fastcgi_pass}|g" "$path"
        sed -i "s|__NGINX_CONFIG_ROOT__|${nginx_config_root}|g" "$path"
    fi
    rcm-file "$path" mustExists
    ____

    chapter Memeriksa ulang konten.
    validateContentSlave "$path"
    [ ! $? -eq 0 ] && x
    ____

    rcm_nginx_reload=1
fi

path="/etc/nginx/sites-available/${master_filename}-redirect"
filename="${master_filename}-redirect"
chapter Mengecek nginx config file: '`'$filename'`'.
code 'path="'$path'"'
rcm-file "$path" isExists
____

if [[ "$url_scheme" == https && "$url_port" == 443 ]];then
    create_new=
    if [ -n "$found" ];then
        chapter Memeriksa konten.
        validateContentRedirect "$path"
        [ ! $? -eq 0 ] && create_new=1;
        ____
    else
        create_new=1
    fi
    if [ -n "$create_new" ];then
        path="/etc/nginx/sites-available/${master_filename}-redirect"
        filename="${master_filename}-redirect"
        chapter Membuat nginx config file: '`'$filename'`'.
        code 'path="'$path'"'
        if [ -f "$path" ];then
            __ Backup file: '`'"$filename"'`'.
            backup-file move "$path"
        fi
        __ Membuat file "$filename".
        cat <<'EOF' > "$path"
server {
    if ($host = __URL_HOST__) {
        return 301 https://$host$request_uri;
    }
    listen [::]:80;
    listen 80;
    server_name __URL_HOST__;
    return 404;
}
EOF
        rcm-file "$path" mustExists
        sed -i "s|__URL_HOST__|${url_host}|g" "$path"
        ____

        chapter Memeriksa ulang konten.
        validateContentRedirect "$path"
        [ ! $? -eq 0 ] && x
        ____

        rcm_nginx_reload=1
    fi
    path="/etc/nginx/sites-available/${master_filename}-redirect"
    source="$path"
    target="/etc/nginx/sites-enabled/${master_filename}-redirect"
    link-symbolic "$source" "$target"
else
    # Nginx reload agar symlink di sites-enabled auto hapus.
    if [ -n "$found" ];then
        chapter Menonaktifkan file config.
        __ Backup file: '`'"$filename"'`'.
        backup-file move "$path"
        rcm_nginx_reload=1
        ____
    fi
fi

# Credit: https://stackoverflow.com/questions/15429043/how-to-redirect-on-the-same-port-from-http-to-https-with-nginx-reverse-proxy
if [[ "$url_scheme" == https && ! "$url_port" == 443 ]];then
    chapter Redirect to https if accessed with http
    path="/etc/nginx/sites-available/$master_filename"
    find="    error_page 497"
    if findString "# ${find}" "$path";then
        code sed -i -E "'"'s|'"${find_quoted}"'|'"${find}"'|g'"'" "$path"
        sed -i -E 's|'"${find_quoted}"'|'"${find}"'|g' "$path"
    fi
    if ! nginxGrep error_page contains 497 < "$path";then
        error Enable gagal.; x
    fi
    ____
fi

if [ -z "$nginx_reload" ];then
    if [ -n "$rcm_nginx_reload" ];then
        if [ -f "$tempfile_trigger_reload" ];then
            echo 1 > "$tempfile_trigger_reload"
        fi
    fi
    rcm_nginx_reload=
fi

if [ -n "$rcm_nginx_reload" ];then
    INDENT+="$RCM_INDENT" \
    rcm nginx reload \
        ; [ ! $? -eq 0 ] && x
fi

[ -n "$tempfile" ] && rm "$tempfile"

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --url
# --nginx-config-root
# --nginx-config-file
# --nginx-config-dir
# --web-root
# --fastcgi-pass
# --tempfile-trigger-reload
# --tls-certificate
# --tls-certificate-key
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
#     'long:--with-nginx-reload,parameter:nginx_reload'
#     'long:--without-nginx-reload,parameter:nginx_reload,flag_option:reverse'
# )
# EOF
# clear
