#!/bin/bash

[ -f "$0" ] || { echo "Cannot run as dot command." >&2; kill -INT $$; }

# Define variables and constants.
RCM_EXTENSION_VERSION=0.19.0-alpha.14
RCM_TLD_SPECIAL=${RCM_TLD_SPECIAL:=example test onion invalid local localhost alt}

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm nginx add vhost php-multiple-root [options]

Options:
   --url=URL
        Set the URL.
   --nginx-config-root=VALUE
        Set the NGINX config Root.
   --root=[DIR]
        Required if --url is empty of path component.
   --fastcgi-pass=VALUE
        Set the value of fastcgi_pass directive.
   --nginx-config-dir=DIR
        The value to include directive. Include file that contains location directive.
   --nginx-config-file=FILE
        Additional value to include directive. Include file that contains location directive.
   --without-nginx-reload
        Prevent auto reload nginx after add/edit file config.
        Default value is --with-nginx-reload.
   --tls-certificate=[VALUE]
        Directive tls_certificate in nginx config.
        Populate value from variable TLS_CERTIFICATE.
   --tls-certificate-key=[VALUE]
        Directive tls_certificate_key in nginx config.
        Populate value from variable TLS_CERTIFICATE_KEY.

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --fastcgi-pass=*) fastcgi_pass="${1#*=}"; shift ;;
        --fastcgi-pass) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then fastcgi_pass="$2"; shift; fi; shift ;;
        --root=*) root="${1#*=}"; shift ;;
        --root) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then root="$2"; shift; fi; shift ;;
        --tempfile-trigger-reload=*) tempfile_trigger_reload="${1#*=}"; shift ;;
        --tempfile-trigger-reload) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tempfile_trigger_reload="$2"; shift; fi; shift ;;
        --tls-certificate-key=*) tls_certificate_key="${1#*=}"; shift ;;
        --tls-certificate-key) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate_key="$2"; shift; fi; shift ;;
        --tls-certificate=*) tls_certificate="${1#*=}"; shift ;;
        --tls-certificate) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate="$2"; shift; fi; shift ;;
        --url=*) url="${1#*=}"; shift ;;
        --url) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then url="$2"; shift; fi; shift ;;
        --with-nginx-reload) nginx_reload=1; shift ;;
        --without-nginx-reload) nginx_reload=0; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm nginx add vhost php-multiple-root
____

# Dependency.
require rcm nginx reload
require vendor/ijortengab/rcm/functions/classes/rcm-file.sh
require vendor/ijortengab/rcm/functions/classes/rcm-dir.sh
require vendor/ijortengab/rcm/functions/utility/url-complete-component.sh
require vendor/ijortengab/rcm/functions/utility/backup-file.sh
require vendor/ijortengab/rcm/functions/utility/link-symbolic.sh
require vendor/ijortengab/rcm/functions/utility/find-string.sh
require vendor/ijortengab/rcm/functions/nginx/rcm-nginx-grep.sh
require vendor/ijortengab/bash/functions/array-pop.sh
require vendor/ijortengab/rcm/functions/utility/link-symbolic-dir.sh

# Functions.
validateContentMaster() {
    local path="$1"
    # listen
    if [ "$url_scheme" == https ];then
        if ! rcm-nginx-grep listen '(a&b)|(a&b&c)' a contains "$url_port" b contains ssl c contains ipv6only=on < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    else
        if ! rcm-nginx-grep listen contains "$url_port" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    fi
    # server_name
    if ! rcm-nginx-grep server_name contains "$url_host" < "$path";then
        __; yellow File akan dibuat ulang.; _.
        return 1
    fi

    if [ "$url_scheme" == https ];then
        # ssl_certificate
        if ! rcm-nginx-grep ssl_certificate is "$ssl_certificate" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # ssl_certificate_key
        if ! rcm-nginx-grep ssl_certificate_key is "$ssl_certificate_key" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # include
        if ! rcm-nginx-grep include is /etc/letsencrypt/options-ssl-nginx.conf < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # include
        if ! rcm-nginx-grep ssl_dhparam is /etc/letsencrypt/ssl-dhparams.pem < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    fi
    if [ "$url_scheme" == http ];then
        # ssl_certificate
        if rcm-nginx-grep ssl_certificate is "$ssl_certificate" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # ssl_certificate_key
        if rcm-nginx-grep ssl_certificate_key is "$ssl_certificate_key" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # include
        if rcm-nginx-grep include is /etc/letsencrypt/options-ssl-nginx.conf < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # include
        if rcm-nginx-grep ssl_dhparam is /etc/letsencrypt/ssl-dhparams.pem < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    fi
    return 0
}
validateContentSlave() {
    local path="$1"
    # fastcgi_pass
    if ! rcm-nginx-grep fastcgi_pass is "$fastcgi_pass" < "$path";then
        __; yellow File akan dibuat ulang.; _.
        return 1
    fi
    if [ -z "$url_path" ];then
        # root
        if ! rcm-nginx-grep root is "$root" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    fi
    return 0
}
validateContentRedirect() {
    local path="$1"
    # listen
    if ! rcm-nginx-grep listen contains 80 < "$path";then
        __; yellow File akan dibuat ulang.; _.
        return 1
    fi
    # server_name
    if ! rcm-nginx-grep server_name contains "$url_host" < "$path";then
        __; yellow File akan dibuat ulang.; _.
        return 1
    fi
    return 0
}

if [ -n "$RCM_VERBOSE" ];then
    verbose="$RCM_VERBOSE"
fi
[[ -z "$verbose" || "$verbose" -lt 1 ]] && quiet=1 || quiet=
[[ "$verbose" -gt 0 ]] && loud=1
[[ "$verbose" -gt 1 ]] && loud=1 && louder=1
[[ "$verbose" -gt 2 ]] && loud=1 && louder=1 && debug=1

include rcm plugin run-static-method web-server nginx get-user-process
nginx_user="$RCM_WEB_SERVER_USER"

# Require, validate, and populate value.
chapter Variable dump.
code nginx_user=$
files_used=()
files_created=()
files_symlink=()
if [ -z "$url" ];then
    error "Argument --url required."; x
fi
code url=$
code root=$
url-complete-component
code url=$
code url_scheme=$
code url_host=$
code url_port=$
code url_path=$
code url_path_clean=$
code url_path_clean_trailing=$

if [[ "$url_scheme" == http && "$url_port" == 80 ]];then
    additional_path_custom_port=
elif [[ "$url_scheme" == https && "$url_port" == 443 ]];then
    additional_path_custom_port=
else
    additional_path_custom_port="/${url_port}"
fi

code additional_path_custom_port=$

conf_nginx=`nginx -V 2>&1 | grep -o -P -- '--conf-path=\K(\S+)'`
code conf_nginx=$
config_dir=$(dirname "$conf_nginx")
code config_dir=$
nginx_config_root="${config_dir}/rcm/sites/${url_host}${additional_path_custom_port}/root"
nginx_config_dir="${config_dir}/rcm/sites/${url_host}${additional_path_custom_port}/location.conf.d"
nginx_config_file="${config_dir}/rcm/sites/${url_host}${additional_path_custom_port}/location.conf"
code nginx_config_root=$
code nginx_config_dir=$
code nginx_config_file=$
if [[ "$url_path_clean" =~ / ]];then
    # Explode by space.
    # read -ra array -d '' <<< "$string"
    # Explode by slash.
    IFS='/' read -ra array <<< "$url_path_clean"
    array-pop array[@]
    array=("${_return_array[@]}"); unset _return_array
    for each in "${array[@]}"; do nginx_config_root+="/${each}.d"; done;
fi
code nginx_config_root=$
____

rcm-dir "$nginx_config_root" createIfNotExists \
    --label="nginx config root" \
    --owner="$nginx_user"

if [ -n "$url_path" ];then
    rcm-dir "$nginx_config_dir" createIfNotExists \
        --label="nginx additional config" \
        --owner="$nginx_user"
fi

target="$nginx_config_root"
if [ -n "$url_path_clean" ];then
    target+="/${url_path_clean}"
fi
chapter Memeriksa direktori simulasi.
code path="$target"
create=
if [[ "$target" == "$nginx_config_root" ]];then
    __ Direktori simulasi sama dengan nginx config root. Symbolic link tidak diperlukan.
else
    __ Direktori simulasi tidak sama dengan nginx config root. Symbolic link diperlukan.
    create=1
fi
____

if [ -n "$create" ];then
    source="$root"
    link-symbolic-dir "$source" "$target" "$nginx_user" absolute
fi

if [ -z "$fastcgi_pass" ];then
    error "Argument --fastcgi-pass required."; x
fi

chapter Populate variable.
web_root=
if [ -z "$url_path" ];then
    web_root="$root"
    slave_dirname="${nginx_config_file%/*}"
    slave_filename="${nginx_config_file##*/}"
else
    slave_dirname="$nginx_config_dir"
    slave_filename="${url_path_clean//\//.}"
fi
slave_filename+=.conf
code slave_filename=$
code slave_dirname=$

rcm-dir "$slave_dirname" terminateIfNotExists
[ -z "$nginx_reload" ] && nginx_reload=1
[ "$nginx_reload" == 0 ] && nginx_reload=
master_include="${nginx_config_dir}/*"
code master_include=$
if [[ "$url_port" == 80 || "$url_port" == 443 ]];then
    master_filename="$url_host"
else
    master_filename="${url_host}.${url_port}"
fi
code master_filename=$
code web_root=$
code fastcgi_pass=$
code nginx_reload=$
code tempfile_trigger_reload=$
# code tls_certificate=$
# code tls_certificate_key=$
# If not set in argument, try load from environment.
# [ -z "$tls_certificate" ] && tls_certificate="$TLS_CERTIFICATE"
# [ -z "$tls_certificate_key" ] && tls_certificate_key="$TLS_CERTIFICATE_KEY"
# code tls_certificate=$
# code tls_certificate_key=$
rcm_nginx_reload=
tempfile=
validate_existing_certificate=
if [[ "$url_scheme" == https ]];then
    if [ -z "$tls_certificate" ];then
        error "Argument --tls-certificate required."; x
    fi
    if [ -z "$tls_certificate_key" ];then
        error "Argument --tls-certificate-key required."; x
    fi
fi
if [[ "$url_scheme" == https ]];then
    ssl_certificate="$tls_certificate"
    ssl_certificate_key="$tls_certificate_key"
fi
code ssl_certificate=$
code ssl_certificate_key=$
____

path="/etc/nginx/sites-available/$master_filename"
filename="$master_filename"
chapter Mengecek nginx config file: '`'$filename'`'.
code path=$
rcm-file "$path" isExists
____

create_new=
if [ -n "$found" ];then
    chapter Memeriksa konten.
    validateContentMaster "$path"
    [ ! $? -eq 0 ] && create_new=1;
    ____
else
    create_new=1
fi

if [[ -n "$create_new" && "$url_scheme" == https ]];then
    chapter Memeriksa certificate SSL.
    rcm-file "$ssl_certificate" terminateIfNotExists
    rcm-file "$ssl_certificate_key" terminateIfNotExists
    ____
fi

if [ -n "$create_new" ];then
    path="/etc/nginx/sites-available/$master_filename"
    filename="$master_filename"
    chapter Membuat nginx config file: '`'$filename'`'.
    code path=$
    if [ -f "$path" ];then
        __ Backup file: '`'"$filename"'`'.
        backup-file move "$path"
    fi
    __ Membuat file "$filename".
    cat <<'EOF' > "$path"
server {
    listen [::]:__URL_PORT____SSL__;
    listen __URL_PORT____SSL____IPV6ONLY__;
    index index.php;
    server_name __URL_HOST__;
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    # include __MASTER_INCLUDE__;
    # include __NGINX_CONFIG_FILE__;

    # ssl_certificate __SSL_CERTIFICATE__;
    # ssl_certificate_key __SSL_CERTIFICATE_KEY__;
    # include /etc/letsencrypt/options-ssl-nginx.conf;
    # ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # error_page 497 301 =307 https://$host:$server_port$request_uri;
}
EOF
    rcm-file "$path" mustExists
    sed -i "s|__URL_HOST__|${url_host}|g" "$path"
    sed -i "s|__SSL_CERTIFICATE__|${ssl_certificate}|g" "$path"
    sed -i "s|__SSL_CERTIFICATE_KEY__|${ssl_certificate_key}|g" "$path"
    sed -i "s|__MASTER_INCLUDE__|${master_include}|g" "$path"
    sed -i "s|__NGINX_CONFIG_FILE__|${nginx_config_file}|g" "$path"
    sed -i "s|__URL_PORT__|${url_port}|g" "$path"
    if [ "$url_scheme" == https ];then
        sed -i "s|__SSL__| ssl|g" "$path"
        # Hanya satu ipv6only=on yang boleh exist pada setiap virtual host.
        if grep -R -q ipv6only=on /etc/nginx/sites-enabled/;then
            sed -i "s|__IPV6ONLY__||g" "$path"
        else
            sed -i "s|__IPV6ONLY__| ipv6only=on|g" "$path"
        fi
        sed -i -E 's|^(\s*)# ssl_certificate (.*);|\1ssl_certificate \2;|g' "$path"
        sed -i -E 's|^(\s*)# ssl_certificate_key (.*);|\1ssl_certificate_key \2;|g' "$path"
        sed -i -E 's|^(\s*)# include /etc/letsencrypt/options-ssl-nginx.conf;|\1include /etc/letsencrypt/options-ssl-nginx.conf;|g' "$path"
        sed -i -E 's|^(\s*)# ssl_dhparam (.*);|\1ssl_dhparam \2;|g' "$path"
    else
        sed -i "s|__SSL__||g" "$path"
        sed -i "s|__IPV6ONLY__||g" "$path"
    fi
    if [ -z "$url_path" ];then
        sed -i 's|# include '"${nginx_config_file}"';|include '"${nginx_config_file}"';|g' "$path"
    else
        sed -i 's|# include '"${master_include}"';|include '"${master_include}"';|g' "$path"
    fi
    ____

    chapter Memeriksa ulang konten.
    validateContentMaster "$path"
    [ ! $? -eq 0 ] && x
    ____

    rcm_nginx_reload=1
fi

path="/etc/nginx/sites-available/$master_filename"
source="$path"
target="/etc/nginx/sites-enabled/$master_filename"
link-symbolic "$source" "$target"

chapter Enable the line to include sub nginx config file: '`'$filename'`'.
if [ -z "$url_path" ];then
    template="    include __NGINX_CONFIG_FILE__;"
    find=$(echo "$template" | sed "s|__NGINX_CONFIG_FILE__|${nginx_config_file}|g")
    if find-string "# ${find}" "$path";then
        code sed -i -E "'"'s|'"${find_quoted}"'|'"${find}"'|g'"'" "$path"
        sed -i -E 's|'"${find_quoted}"'|'"${find}"'|g' "$path"
    fi
    if ! rcm-nginx-grep include is "$nginx_config_file" < "$path";then
        error Enable gagal.; x
    fi
else
    template="    include __MASTER_INCLUDE__;"
    find=$(echo "$template" | sed "s|__MASTER_INCLUDE__|${master_include}|g")
    if find-string "# ${find}" "$path";then
        code sed -i -E "'"'s|'"${find_quoted}"'|'"${find}"'|g'"'" "$path"
        sed -i -E 's|'"${find_quoted}"'|'"${find}"'|g' "$path"
    fi
    if ! rcm-nginx-grep include is "$master_include" < "$path";then
        error Enable gagal.; x
    fi
fi
____

path="${slave_dirname}/${slave_filename}"
filename="$slave_filename"
chapter Mengecek nginx config file: '`'$filename'`'.
code path=$
rcm-file "$path" isExists
____

create_new=
if [ -n "$found" ];then
    chapter Memeriksa konten.
    validateContentSlave "$path"
    [ ! $? -eq 0 ] && create_new=1;
    ____
else
    create_new=1
fi

if [ -n "$create_new" ];then
    path="${slave_dirname}/${slave_filename}"
    filename="$slave_filename"
    chapter Membuat nginx config file: '`'$filename'`'.
    code path=$
    if [ -f "$path" ];then
        __ Backup file: '`'"$filename"'`'.
        backup-file move "$path" parent
    fi
    __ Membuat file "$filename".
    if [ -z "$url_path" ];then
        cat <<'EOF' > "$path"
location / {
    root __WEB_ROOT__;
    try_files $uri $uri/ /index.php$is_args$args;
    location ~ ^(.+\.php)(.*)$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass __FASTCGI_PASS__;
        fastcgi_read_timeout 3600;
    }
}
EOF
        sed -i "s|__WEB_ROOT__|${root}|g" "$path"
        sed -i "s|__FASTCGI_PASS__|${fastcgi_pass}|g" "$path"
    else
        cat <<'EOF' > "$path"
location = __URL_PATH_CLEAN_TRAILING__ {
    return 302 __URL_PATH_CLEAN_TRAILING__/;
}
location __URL_PATH_CLEAN_TRAILING__/ {
    root __NGINX_CONFIG_ROOT__;
    try_files $uri $uri/ __URL_PATH_CLEAN_TRAILING__/index.php$is_args$args;
    location ~ ^(.+\.php)(.*)$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass __FASTCGI_PASS__;
    }
}
EOF
        sed -i "s|__URL_PATH_CLEAN_TRAILING__|${url_path_clean_trailing}|g" "$path"
        sed -i "s|__FASTCGI_PASS__|${fastcgi_pass}|g" "$path"
        sed -i "s|__NGINX_CONFIG_ROOT__|${nginx_config_root}|g" "$path"
    fi
    rcm-file "$path" mustExists
    ____

    chapter Memeriksa ulang konten.
    validateContentSlave "$path"
    [ ! $? -eq 0 ] && x
    ____

    rcm_nginx_reload=1
fi

path="/etc/nginx/sites-available/${master_filename}-redirect"
filename="${master_filename}-redirect"
chapter Mengecek nginx config file: '`'$filename'`'.
code path=$
rcm-file "$path" isExists
____

if [[ "$url_scheme" == https && "$url_port" == 443 ]];then
    create_new=
    if [ -n "$found" ];then
        chapter Memeriksa konten.
        validateContentRedirect "$path"
        [ ! $? -eq 0 ] && create_new=1;
        ____
    else
        create_new=1
    fi
    if [ -n "$create_new" ];then
        path="/etc/nginx/sites-available/${master_filename}-redirect"
        filename="${master_filename}-redirect"
        chapter Membuat nginx config file: '`'$filename'`'.
        code path=$
        if [ -f "$path" ];then
            __ Backup file: '`'"$filename"'`'.
            backup-file move "$path"
        fi
        __ Membuat file "$filename".
        cat <<'EOF' > "$path"
server {
    if ($host = __URL_HOST__) {
        return 301 https://$host$request_uri;
    }
    listen [::]:80;
    listen 80;
    server_name __URL_HOST__;
    return 404;
}
EOF
        rcm-file "$path" mustExists
        sed -i "s|__URL_HOST__|${url_host}|g" "$path"
        ____

        chapter Memeriksa ulang konten.
        validateContentRedirect "$path"
        [ ! $? -eq 0 ] && x
        ____

        rcm_nginx_reload=1
    fi
    path="/etc/nginx/sites-available/${master_filename}-redirect"
    source="$path"
    target="/etc/nginx/sites-enabled/${master_filename}-redirect"
    link-symbolic "$source" "$target"
else
    # Nginx reload agar symlink di sites-enabled auto hapus.
    if [ -n "$found" ];then
        chapter Menonaktifkan file config.
        __ Backup file: '`'"$filename"'`'.
        backup-file move "$path"
        rcm_nginx_reload=1
        ____
    fi
fi

# Credit: https://stackoverflow.com/questions/15429043/how-to-redirect-on-the-same-port-from-http-to-https-with-nginx-reverse-proxy
if [[ "$url_scheme" == https && ! "$url_port" == 443 ]];then
    chapter Redirect to https if accessed with http
    path="/etc/nginx/sites-available/$master_filename"
    find="    error_page 497"
    if find-string "# ${find}" "$path";then
        code sed -i -E "'"'s|'"${find_quoted}"'|'"${find}"'|g'"'" "$path"
        sed -i -E 's|'"${find_quoted}"'|'"${find}"'|g' "$path"
    fi
    if ! rcm-nginx-grep error_page contains 497 < "$path";then
        error Enable gagal.; x
    fi
    ____
fi

if [ -z "$nginx_reload" ];then
    if [ -n "$rcm_nginx_reload" ];then
        if [ -f "$tempfile_trigger_reload" ];then
            echo 1 > "$tempfile_trigger_reload"
        fi
    fi
    rcm_nginx_reload=
fi

if [ -n "$rcm_nginx_reload" ];then
    INDENT+="$RCM_INDENT" \
    rcm nginx reload \
        ; [ ! $? -eq 0 ] && x
fi

[ -n "$tempfile" ] && rm "$tempfile"

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --url
# --root
# --fastcgi-pass
# --tempfile-trigger-reload
# --tls-certificate
# --tls-certificate-key
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
#     'long:--with-nginx-reload,parameter:nginx_reload'
#     'long:--without-nginx-reload,parameter:nginx_reload,flag_option:reverse'
# )
# EOF
# clear
