#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.13

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm postfix add certificate [options]

Reference:
 - https://serverfault.com/questions/928926/postfix-multi-domains-and-multi-certs-on-one-ip
 - https://serverfault.com/questions/920436/set-up-certs-for-multiple-domains-in-postfix-and-dovecot
 - https://www.postfix.org/announcements/postfix-3.4.0.html

Options:
   --fqdn=FQDN
        The FQDN of certificate to be added.
   --ssl-cert=CERT
        Fullpath of SSL Certificate chain.
   --ssl-key=KEY
        Fullpath of SSL Certificate private key.
   --additional-config-file=FILE
        Extra file to store the list of FQDN.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.

Environment Variables:
   POSTFIX_CONFIG_DIR
        Default to $POSTFIX_CONFIG_DIR
   POSTFIX_CONFIG_FILE_MAIN
        Default to $POSTFIX_CONFIG_FILE_MAIN

Dependency:
   postconf
   postmap
   systemctl
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --additional-config-file=*) additional_config_file="${1#*=}"; shift ;;
        --additional-config-file) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then additional_config_file="$2"; shift; fi; shift ;;
        --fqdn=*) fqdn="${1#*=}"; shift ;;
        --fqdn) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then fqdn="$2"; shift; fi; shift ;;
        --non-interactive) non_interactive=1; shift ;;
        --ssl-cert=*) ssl_cert="${1#*=}"; shift ;;
        --ssl-cert) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then ssl_cert="$2"; shift; fi; shift ;;
        --ssl-key=*) ssl_key="${1#*=}"; shift ;;
        --ssl-key) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then ssl_key="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.
POSTFIX_CONFIG_DIR=${POSTFIX_CONFIG_DIR:=/etc/postfix}
POSTFIX_CONFIG_FILE_MAIN=${POSTFIX_CONFIG_FILE_MAIN:=${POSTFIX_CONFIG_DIR}/main.cf}

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Require.
require vendor/ijortengab/rcm/functions/classes/rcm-file.sh
require vendor/ijortengab/rcm/functions/utility/find-string.sh
require vendor/ijortengab/bash/functions/array-diff.sh

# ------------------------------------------------------------------------------

# Title.
title rcm postfix add certificate
____

# Dependency.

# Functions.
verifyKey() {
    local key=$1
    local output=$2
    case "$key" in
        smtpd_tls_chain_files)
            value=$(echo "$output" | sed -E 's|^(.*)\s*=\s*(.*)\s*$|\2|')
            if [ -n "$value" ];then
                IFS=',' read -ra _array <<< "$value"
                array=(); for each in "${_array[@]}"; do array+=($each); done # Trim whitespace.
                references=("${POSTFIX_CONFIG_DIR}/smtpd.key" "${POSTFIX_CONFIG_DIR}/smtpd.cert")
                array-diff references[@] array[@]
                if [ "${#_return[@]}" -eq 0 ];then
                    return 0
                fi
            fi
            ;;
        tls_server_sni_maps)
            if [[ "$output" == "tls_server_sni_maps = hash:${additional_config_file}" ]];then
                return 0
            fi
            ;;
        *)
            value=$(echo "$output" | sed -E 's|'"$find_quoted"'(.*)|\1|')
            read -ra _array -d '' <<< "$value"
            array=(); for each in "${_array[@]}"; do array+=($each); done # Trim whitespace.
            references=($ssl_key $ssl_cert)
            array-diff references[@] array[@]
            if [ "${#_return[@]}" -eq 0 ];then
                return 0
            fi
    esac
    return 1
}

# Require, validate, and populate value.
chapter Variable dump.
code 'POSTFIX_CONFIG_DIR="'$POSTFIX_CONFIG_DIR'"'
code 'POSTFIX_CONFIG_FILE_MAIN="'$POSTFIX_CONFIG_FILE_MAIN'"'
if [ -z "$additional_config_file" ];then
    error "Argument --additional-config-file required."; x
fi
code 'additional_config_file="'$additional_config_file'"'
if [ -z "$fqdn" ];then
    error "Argument --fqdn required."; x
fi
code 'fqdn="'$fqdn'"'
if [ -z "$ssl_cert" ];then
    error "Argument --ssl-cert required."; x
fi
code 'ssl_cert="'$ssl_cert'"'
if [ -z "$ssl_key" ];then
    error "Argument --ssl-key required."; x
fi
code 'ssl_key="'$ssl_key'"'
rcm-file "$ssl_cert" terminateIfNotExists
rcm-file "$ssl_key" terminateIfNotExists
# Exit code sama-sama bernilai 0 pada unknown parameter, sehingga perlu kita gunakan output.
tempfile_error=$(mktemp -p /dev/shm -t rcm-postfix-add-certificate.XXXXXX)
tempfile_output=$(mktemp -p /dev/shm -t rcm-postfix-add-certificate.XXXXXX)
____

restart=
for key in smtpd_tls_cert_file smtpd_tls_key_file; do
    chapter Memastikan key '`'$key'`' disabled.
    postconf -n $key 2> $tempfile_error > $tempfile_output
    error="$(<"$tempfile_error")"
    if [ -n "$error" ];then
        error "$error"; rm $tempfile_error; rm $tempfile_output; x
    fi
    output="$(<"$tempfile_output")"
    if [ -n "$output" ];then
        e "$output"; _.
        __ Key '`'$key'`' is enable. Try to disabled.
        code "postconf -# ${key}"
        postconf -# $key
        restart=1
    else
        __ Key '`'$key'`' has been disabled.
    fi
    ____
done

key=smtpd_tls_chain_files
chapter Memastikan key '`'$key'`' enabled.
rcm-file "${POSTFIX_CONFIG_DIR}/smtpd.key" terminateIfNotExists
rcm-file "${POSTFIX_CONFIG_DIR}/smtpd.cert" terminateIfNotExists

postconf -n $key 2> $tempfile_error > $tempfile_output
error="$(<"$tempfile_error")"
if [ -n "$error" ];then
    error "$error"; rm $tempfile_error; rm $tempfile_output; x
fi
output="$(<"$tempfile_output")"
found=
if [ -n "$output" ];then
    __ Key ditemukan.
    e "$output"; _.
    __ Verifikasi.
    if verifyKey "$key" "$output";then
        found=1
        __ Key ditemukan, dan value cocok.
    else
        __ Key ditemukan, namun value tidak cocok.
        __ Disable and create new one.
        code "postconf -# ${key}"
        postconf -# $key
    fi
fi
if [ -z "$found" ];then
    __ Append value of key '`'$key'`'
    cat << EOF >> "$POSTFIX_CONFIG_FILE_MAIN"
$key =
 ${POSTFIX_CONFIG_DIR}/smtpd.key,
 ${POSTFIX_CONFIG_DIR}/smtpd.cert
EOF
    __ Verifikasi.
    if verifyKey "$key" "$(postconf -n $key)";then
        __ Verifikasi berhasil.
        restart=1
    else
        error Verifikasi gagal.; rm $tempfile_error; rm $tempfile_output; x
    fi
fi
____

key=tls_server_sni_maps
chapter Memastikan key '`'$key'`' enabled.
path="${additional_config_file}"
code 'path="'$path'"'
postconf -n $key 2> $tempfile_error > $tempfile_output
error="$(<"$tempfile_error")"
if [ -n "$error" ];then
    error "$error"; rm $tempfile_error; rm $tempfile_output; x
fi
output="$(<"$tempfile_output")"
found=
if [ -n "$output" ];then
    __ Key ditemukan.
    e "$output"; _.
    __ Verifikasi.
    if verifyKey "$key" "$output";then
        found=1
        __ Key ditemukan, dan value cocok.
    else
        __ Key ditemukan, namun value tidak cocok.
        __ Disable and create new one.
        code "postconf -# ${key}"
        postconf -# $key
    fi
fi
if [ -z "$found" ];then
    __ Set value of key '`'$key'`'
    postconf "${key}=hash:${path}"
    __ Verifikasi.
    if verifyKey "$key" "$(postconf -n $key)";then
        __ Verifikasi berhasil.
        restart=1
    else
        error Verifikasi gagal.; rm $tempfile_error; rm $tempfile_output; x
    fi
fi
____

path="${additional_config_file}"
filename="${path##*/}"
chapter Mengecek file '`'$filename'`'.
code path='"'$path'"'
rcm-file "$path" isExists
____

# Saat ini tidak support untuk format multiline. Contoh:
# ```
# drupal.id
#  /etc/letsencrypt/live/drupal.id/privkey.pem
#  /etc/letsencrypt/live/drupal.id/fullchain.pem
# ```
# Multiline akan dianggap false.
# @todo support multiline.
if [ -n "$found" ];then
    chapter Mengecek fqdn '`'$fqdn'`'.
    code path='"'$path'"'
	if find-string "^${fqdn} " "$path" "$tempfile_output";then
        __ Verifikasi.
        if verifyKey - "$(<"$tempfile_output")";then
            __ Key ditemukan, dan value cocok.
        else
            notfound=1
            __ Key ditemukan, namun value tidak cocok.
            __ Disable and create new one.
            code sed -i -E "'"'s|'"'"'"'"$find_quoted"'"'"'"'.*|# \0|'"'" "$path"
            sed -i -E 's|'"$find_quoted"'.*|# \0|' "$path"
        fi
    else
		notfound=1
	fi
	____
fi
if [ -n "$notfound" ];then
    chapter Menambah FQDN '`'$fqdn'`' ke file '`'$filename'`'.
    dirname="${path%/*}"
    code mkdir -p '"'$dirname'"'
    mkdir -p "$dirname"
    cat << EOF >> "$path"
${fqdn} ${ssl_key} ${ssl_cert}
EOF
	__ Melakukan verifikasi.
	if ! find-string "${fqdn} ${ssl_key} ${ssl_cert}" "$path";then
        error Gagal menambahkan.; rm $tempfile_error; rm $tempfile_output; x
	fi
	__; green Berhasil ditambahkan; _.
    code postmap -F hash:"$path"
    postmap -F hash:"$path"
	restart=1
	____
fi

if [ -n "$restart" ];then
    chapter Restart postfix.
    code systemctl restart postfix
    systemctl restart postfix
    ____
fi

rm $tempfile_error
rm $tempfile_output

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --non-interactive
# )
# VALUE=(
# --fqdn
# --ssl-cert
# --ssl-key
# --additional-config-file
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
