#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.12

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm nginx init

Auto Install Nginx with default version.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.

EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Require.
require vendor/ijortengab/rcm/functions/utility/apt-install.sh

# ------------------------------------------------------------------------------

# Title.
title rcm nginx init
____

apt-install nginx

# Wajib exit 0 jika success.
exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# )
# FLAG_VALUE=(
# )
# EOF
# clear
