#!/bin/bash

[ -f "$0" ] || { echo "Cannot run as dot command." >&2; kill -INT $$; }

# Define variables and constants.
RCM_EXTENSION_VERSION=0.19.0-alpha.14
CERTIFICATE_PREFIX=${CERTIFICATE_PREFIX:=/usr/local/share/certificates}

usage () {
    cat << 'EOF'
Usage: rcm openssl create certificate [options]

Options:
   --domain=VALUE
        Set the domain.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --domain=*) domain="${1#*=}"; shift ;;
        --domain) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then domain="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm openssl create certificate
____

# Dependency.
use ijortengab/rcm rcm-dir
require command openssl

# Requirement, validate, and populate value.
chapter Variable dump.
code domain=$
prefix="$CERTIFICATE_PREFIX"
if [ "$EUID" -ne 0 ];then
    prefix_find=/usr/local
    prefix_replace="${HOME}/.local"
    prefix=${prefix/$prefix_find/$prefix_replace}
fi
code prefix=$
____

rcm-dir "${prefix}/${domain}" createIfNotExists

chapter Generate a Self-Signed Certificate
key_filename="${domain}.key"
certificate_filename="${domain}.crt"
code key_filename=$
code certificate_filename=$
cd "${prefix}/${domain}"
binary=
[ -f "$key_filename" ] && binary+=1
[ -f "$certificate_filename" ] && binary+=1
# code binary=$
if [ ${#binary} -gt 1 ];then
    __ Files has been exists.
else
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout "$key_filename" -out "$certificate_filename" \
    -subj "/C=US/ST=State/L=City/O=Organization/OU=Department/CN=localhost"
fi
____

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --domain
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
