#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.13

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm nginx reload

Reload the nginx without worry.

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Require.
require vendor/ijortengab/rcm/functions/utility/sleep-extended.sh

# ------------------------------------------------------------------------------

# Title.
title rcm nginx reload
____

# Dependency.
require command nginx

# Require, validate, and populate value.
chapter Variable dump.
____

chapter Reload nginx configuration.
__ Cleaning broken symbolic link.
code find /etc/nginx/sites-enabled -xtype l -print -delete
find /etc/nginx/sites-enabled -xtype l -print
find /etc/nginx/sites-enabled -xtype l -delete -print

if nginx -t 2> /dev/null;then
    code nginx -s reload
    nginx -s reload
    # Setelah reload biasanya parent process akan melakukan request http,
    # maka kita perlu sleep
    sleep-extended 3 30
else
    code nginx -t
    nginx -t
    error Terjadi kesalahan konfigurasi nginx. Gagal reload nginx.; x
fi
____

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
