#!/bin/bash

[ -f "$0" ] || { echo "Cannot run as dot command." >&2; kill -INT $$; }

# Define variables and constants.
RCM_EXTENSION_VERSION=0.19.0-alpha.14
PHP_FPM_POOL_DIRECTORY=${PHP_FPM_POOL_DIRECTORY:=/etc/php/[php-version]/fpm/pool.d}
RCM_TLD_SPECIAL=${RCM_TLD_SPECIAL:=example test onion invalid local localhost alt}

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm php add website [options]

Options:
   --url=URL
        Set the URL. The value can be public or private domain, or URL.
        Example: \`example.org\`, \`example.org/path/to/drupal/\`, or \`https://sub.example.org:8080/\`.
   --public-domain
        Make sure that --url is public domain, this will trigger TLS request and DNS verification.
        Special top level domain such us .local, .example, etc will pretend as private domain.
   --acme-client=TLS
        Select acme client to obtain TLS Certificate.
        Values available from command: rcm(plugin list acme-client).
        Conditional: Bypass if --public-domain is not added.
   --web-server=HTTP
        Select web server to build up virtual host.
        Values available from command: rcm(plugin list web-server).
   --php-version=PHP_VERSION
        Set the version of PHP FPM.
        Values available from command: rcm(php list available --fpm).
   --php-fpm-user=[USER]
        Set the Unix user that used by PHP FPM.
        Default value is the user that used by web server (the common name is www-data).
        Values available from command: rcm(system list user regular --with-web-server=[--web-server]), or others.
        If the user does not exists, it will be autocreate as reguler user.
   --php-fpm-section=[SECTION]
        Set the PHP-FPM section.
        Default value is the first found section from the --php-fpm-user.
        Usually is www section.
        The section must exists before.
        Create new PHP FPM section with \`rcm php add pool\`.
        Values available from command: rcm(php list pool [--php-version] [--php-fpm-user]).
   --root=[DIR]
        Set the web root pointing the URL.
        if omit, it will user the \$HOME directory with proper container.
   --index-php[=CONTENT]
        Auto create index.php file.
        Can have value. The value is string that will be printed.
        Example: --index-php="Foo bar" will create contents \`<?= "Foo bar"; ?>\`.
        Shortcut value is: 2, 3, and 4.
        For --index-php=1 is equals to --index-php.
        For --index-php=2 will create contents \`<?php phpinfo(); ?>\`.
        For --index-php=3 will create contents \`<?= 'Hello World'; ?>\`.
        For --index-php=4 will create contents \`<pre><?php print_r(\$_SERVER); ?></pre>\`.

Other options (For expert only):
   --phpinfo
        Shortcut of \`--index-php=2\`.
        It will create index.php file with contents \`<?php phpinfo(); ?>\`.
   --hello
        Shortcut of \`--index-php=3\`.
        It will create index.php file with contents \`<?= 'Hello World'; ?>\`.
   --phpvariables
        Shortcut of \`--index-php=4\`.
        It will create index.php file with contents \`<pre><?php print_r(\$_SERVER); ?></pre>\`.
   --php-fpm-config=[LINE]...
        Additional PHP-FPM Configuration inside pool directory.
        Available value: [1], [2], [3], [4], [5], [6], [7], or other.
        [1]: pm=ondemand
        [2]: php_flag[display_errors]=on
        [3]: php_value[max_execution_time]=300
        [4]: php_admin_value[memory_limit]=256M
        [5]: php_admin_value[upload_max_filesize]=25M
        [6]: php_admin_value[post_max_size]=1024M
        [7]: php_admin_flag[log_errors]=on
        Multivalue.

Additional Options:
   rcm(-p plugin prompt acme-client [--acme-client] obtain)
   rcm(-p plugin prompt web-server [--web-server] init)

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --acme-client=*) acme_client="${1#*=}"; shift ;;
        --acme-client) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then acme_client="$2"; shift; fi; shift ;;
        --hello) index_php=3; shift ;;
        --index-php=*) index_php="${1#*=}"; shift ;;
        --index-php) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then index_php="$2"; shift; else index_php=1; fi; shift ;;
        --no-auto-add-group) no_auto_add_group=1; shift ;;
        --phpinfo) index_php=2; shift ;;
        --phpvariables) index_php=4; shift ;;
        --php-fpm-config=*) php_fpm_config+=("${1#*=}"); shift ;;
        --php-fpm-config) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then php_fpm_config+=("$2"); shift; fi; shift ;;
        --php-fpm-section=*) php_fpm_section="${1#*=}"; shift ;;
        --php-fpm-section) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then php_fpm_section="$2"; shift; fi; shift ;;
        --php-fpm-user=*) php_fpm_user="${1#*=}"; shift ;;
        --php-fpm-user) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then php_fpm_user="$2"; shift; fi; shift ;;
        --php-version=*) php_version="${1#*=}"; shift ;;
        --php-version) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then php_version="$2"; shift; fi; shift ;;
        --public-domain) public_domain=1; shift ;;
        --root=*) root="${1#*=}"; shift ;;
        --root) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then root="$2"; shift; fi; shift ;;
        --url=*) url="${1#*=}"; shift ;;
        --url) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then url="$2"; shift; fi; shift ;;
        --web-server=*) web_server="${1#*=}"; shift ;;
        --web-server) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then web_server="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm php add website
____

# Dependency.
require vendor/ijortengab/rcm/functions/utility/url-complete-component.sh
require vendor/ijortengab/rcm/functions/utility/backup-file.sh
require vendor/ijortengab/rcm/functions/classes/rcm-file.sh
require vendor/ijortengab/rcm/functions/classes/rcm-dir.sh
require vendor/ijortengab/bash/functions/array-search.sh

# Require, validate, and populate value.
chapter Variable dump.
is_wsl=
if [ -f /proc/sys/kernel/osrelease ];then
    read osrelease </proc/sys/kernel/osrelease
    if [[ "$osrelease" =~ microsoft || "$osrelease" =~ Microsoft ]];then
        is_wsl=1
    fi
fi
code is_wsl=$
if [ -z "$php_version" ];then
    error "Argument --php-version required."; x
fi
code php_version=$
if [ -z "$url" ];then
    error "Argument --url required."; x
fi
code url=$
code public_domain=$
[ -n "$public_domain" ] && arg_https='--https' || arg_https=
url-complete-component $arg_https
code url=$
code url_scheme=$
code url_host=$
code url_port=$
code url_path=$
code url_path_clean=$
code url_path_clean_trailing=$
if [ -n "$public_domain" ];then
    if [ -z "$acme_client" ];then
        error "Argument --acme-client required."; x
    fi
fi
code acme_client=$
if [ -z "$web_server" ];then
    error "Argument --web-server required."; x
fi
code web_server=$
code php_fpm_user=$
code php_fpm_section=$
code root=$
add_container=
[ -z "$root" ] && add_container=1
code add_container=$
code index_php=$
code php_fpm_config=@
if [ -n "$is_wsl" ];then
    # Jika mesin menggunakan WSL2, maka tambahkan max_execution_time (waktu proses)
    php_fpm_config=(pm=ondemand php_value[max_execution_time]=60 "${php_fpm_config[@]}")
fi

is_config_line=
is_config_line_array=()
code php_fpm_config=@
for each in "${php_fpm_config[@]}";do
    [[ "$each" =~ ' ' ]] && is_config_line+=" --config-line='${each}'" || is_config_line+=" --config-line=${each}"
    is_config_line_array+=("--config-line=${each}")
done
rcm_nginx_reload=
____

include rcm plugin run-method web-server $web_server init

include rcm plugin run-method web-server $web_server get-user-process

chapter Populate variables.
webserver_user="$RCM_WEB_SERVER_USER"
if [ -z "$webserver_user" ];then
    error "Variable \$webserver_user failed to populate."; x
fi
code webserver_user=$
____

run rcm php init \
    --php-version="$php_version" \
    --extension="fpm" \
    &&
run rcm php switch \
    --php-version="$php_version" \
    ; [ ! $? -eq 0 ] && x

chapter Populate variables.
if [ -z "$php_fpm_user" ];then
    php_fpm_user="$webserver_user"
fi
code php_fpm_user=$
webserver_user_home=$(getent passwd "$webserver_user" | cut -d: -f6 )
code webserver_user_home=$
if [ -z "$root" ];then
    root=$(getent passwd "$php_fpm_user" | cut -d: -f6 )
fi
code root=$
# Jika $HOME nya adalah /nonexistent, maka perlu kita verifikasi lagi.
if [ ! -d "$root" ];then
    root=
fi
if [ -z "$root" ];then
    root=/usr/local/share/www
    add_container=
fi
code root=$
if [ -n "$add_container" ];then
    list_user=()
    while read line; do
        list_user+=($line)
    done <<< `rcm system list user regular 2>/dev/null`
    # Jika user $php_fpm_user adalah reguler, maka tambahkan container public_html
    if array-search "$php_fpm_user" list_user[@];then
        root+=/public_html
    else
        root+=/php
    fi
fi
code root=$
if [ -z "$php_fpm_section" ];then
    __ Get the list of section.
    code rcm php list pool "$php_version" "$php_fpm_user"
    list_section=()
    while read line; do
        list_section+=($line)
    done <<< `rcm php list pool "$php_version" "$php_fpm_user" 2>/dev/null`
    if [ "${#list_section}" -gt 0 ];then
        php_fpm_section="${list_section[0]}"
    else
        error "Variable \$php_fpm_section failed to populate."; x
    fi
fi
code php_fpm_section=$
socket_filename=$( rcm php get-info pool "$php_version" "$php_fpm_section" listen 2>/dev/null)
if [ -z "$socket_filename" ];then
    error "Variable \$socket_filename failed to populate."; x
fi
code socket_filename=$
fastcgi_pass="unix:${socket_filename}"
code fastcgi_pass=$
if [[ "$url_scheme" == http && "$url_port" == 80 ]];then
    additional_path_custom_port=
elif [[ "$url_scheme" == https && "$url_port" == 443 ]];then
    additional_path_custom_port=
else
    additional_path_custom_port="/${url_port}"
fi
root="${root}/${url_host}${additional_path_custom_port}/web${url_path_clean_trailing}"
code root=$
server_name="$url_host"
code server_name=$
root_parent=${root%/*}
code root_parent=$
____

chapter Mengecek direktori root parent '`'$root_parent'`'.
rcm-dir isExists "$root_parent"
____

if [ -n "$notfound" ];then
    chapter Membuat direktori root parent.
    code sudo -u $php_fpm_user mkdir -p '"'$root_parent'"'
    sudo -u $php_fpm_user mkdir -p "$root_parent" 2>/dev/null || {
        code mkdir -p "$root_parent"
        code chown $php_fpm_user:$php_fpm_user '"'$root_parent'"'
        mkdir -p "$root_parent"
        chown $php_fpm_user:$php_fpm_user "$root_parent"
    }
    rcm-dir mustExists "$root_parent"
    ____
fi

chapter Mengecek direktori root '`'$root'`'.
rcm-dir isExists "$root"
____

if [ -n "$notfound" ];then
    chapter Membuat direktori root.
    code sudo -u $php_fpm_user mkdir -p '"'$root'"'
    sudo -u $php_fpm_user mkdir -p "$root" || {
        code mkdir -p "$root"
        code chown $php_fpm_user:$php_fpm_user '"'$root'"'
        mkdir -p "$root"
        chown $php_fpm_user:$php_fpm_user "$root"
    }
    rcm-dir mustExists "$root"
    ____
fi

RCM_WEB_SERVER=$web_server
RCM_WEB_SERVER_VHOST_TAGS=( php subdirectory-safe )
RCM_WEB_SERVER_VHOST_METADATA_YAML=$(cat - <<EOF
fastcgi_pass: $fastcgi_pass
url: $url
root: $root
EOF
)

include rcm plugin run-method web-server $web_server add-vhost

if [ -n "$index_php" ];then
    path="${root}/index.php"
    is_temporary=
    is_temporary_string=
    case "$index_php" in
        1) contents="" ;;
        2) contents="<?php phpinfo(); ?>" ;;
        3) contents="<?= 'Hello World'; ?>" ;;
        4) contents="<pre><?php print_r(\$_SERVER); ?></pre>" ;;
        *) contents="<?= '${index_php}'; ?>" ;;
    esac
else
    path=$(mktemp -p "$root" -t index.XXXXXX.php)
    chown $php_fpm_user:$php_fpm_user "$path"
    is_temporary=1
    is_temporary_string=' temporary'
fi

chapter Mempersiapkan file"$is_temporary_string" '`'index.php'`'.
code path=$
filename=$(basename "$path")
rcm-file "$path" isExists
if [ -n "$found" ];then
    read existing_contents < "$path"
    if [[ ! "$existing_contents" == "$contents" ]];then
        found=
        notfound=1
    fi
fi
if [ -n "$notfound" ];then
    if [ -f "$path" ];then
        __ Backup file "$path".
        backup-file move "$path"
    fi
    __ Membuat file"$is_temporary_string" '`'index.php'`'.
    echo "$contents" > "$path"
    chown $php_fpm_user:$php_fpm_user "$path"
    rcm-file "$path" mustExists
fi
____

chapter Mengecek HTTP Response Code.
if [ "$url_scheme" == https ];then
    _k=' -k'
else
    _k=''
fi
i=0
code=
if [ -z "$tempfile" ];then
    tempfile=$(mktemp -p /dev/shm -t rcm-php-add-website.XXXXXX)
fi
until [ $i -eq 10 ];do
    __; magenta curl"$_k" -o /dev/null -s -w '"'%{http_code}\\n'"' '"'"${url_scheme}://127.0.0.1:${url_port}${url_path_clean_trailing}/${filename}"'"' -H '"'Host: $url_host'"'; _.
    curl$_k -o /dev/null -s -w "%{http_code}\n" "${url_scheme}://127.0.0.1:${url_port}${url_path_clean_trailing}/${filename}" -H "Host: ${url_host}" > $tempfile
    while read line; do e "$line"; _.; done < $tempfile
    code=$(head -1 $tempfile)
    if [[ "$code" =~ ^[2,3] ]];then
        break
    else
        __ Retry.
        __; magenta sleep .5; _.
        sleep .5
    fi
    let i++
done
if [[ "$code" =~ ^[2,3] ]];then
    __ HTTP Response code '`'$code'`' '('Required')'.
else
    __; red Terjadi kesalahan. HTTP Response code '`'$code'`'.; x
fi
____

if [ -n "$tempfile" ];then
    rm "$tempfile"
fi
if [ -n "$is_temporary" ];then
    rm "$path"
fi

chapter Finish.
__ URL'      ': "$url"
__ Web Root : "$root"
____

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --no-auto-add-group
# --public-domain
# )
# VALUE=(
# --url
# --php-version
# --php-fpm-user
# --php-fpm-section
# --root
# --web-server
# --acme-client
# )
# MULTIVALUE=(
# --php-fpm-config
# )
# FLAG_VALUE=(
# --index-php
# )
# CSV=(
    # 'long:--phpinfo,parameter:index_php,flag_option:true=2'
    # 'long:--hello,parameter:index_php,flag_option:true=3'
    # 'long:--phpvariables,parameter:index_php,flag_option:true=4'
# )
# EOF
# clear
