#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.13

# Usage Functions.
usage() {
    # Populate variable $single_line and $multi_line.
    unset count
    declare -i count
    count=0
    single_line=
    multi_line=
    while read line;do
        if [ -d /etc/php/$line/fpm ];then
            if [ $count -gt 0 ];then
                single_line+=", "
            fi
            count+=1
            single_line+="[${count}]"
            multi_line+=$'\n''        '"[${count}]: "${line}
        fi
    done <<< `ls /etc/php/`
    if [ -n "$single_line" ];then
        # single_line=" Available values: ${single_line}, or other."
        single_line=" Available values: ${single_line}."
    fi
    if [ -n "$multi_line" ];then
        multi_line="$multi_line"
    fi
    # Populate variable $users.
    users=`cut -d: -f1 /etc/passwd | while read line; do [ -d /home/$line ] && echo " ${line}"; done | tr $'\n' ','`
    nginx_user=
    conf_nginx=`command -v nginx > /dev/null && nginx -V 2>&1 | grep -o -P -- '--conf-path=\K(\S+)'`
    if [ -f "$conf_nginx" ];then
        nginx_user=`grep -o -P '^user\s+\K([^;]+)' "$conf_nginx"`
    fi
    [ -n "$nginx_user" ] && { nginx_user=" ${nginx_user},"; }
    [ -n "$users" ] && users=" Available values:${nginx_user}${users}."
    cat << EOF
Usage: rcm php add website [options]

Options:
   --url *
        Set the URL. The value can be public or private domain, or URL.
        Example: \`example.org\`, \`example.org/path/to/drupal/\`, or \`https://sub.example.org:8080/\`.
        Special top level domain such us .local, .example, etc will pretend as private domain.
   --php-version *
        Set the version of PHP FPM.${single_line}${multi_line}
   --php-fpm-user
        Set the Unix user that used by PHP FPM.
        Default value is the user that used by web server (the common name is www-data).
        If the user does not exists, it will be autocreate as reguler user.${users}
   --php-fpm-section *
        Set the PHP-FPM section.
        Create new PHP FPM section with \`rcm php-fpm-setup-project-config\`.
        Values available from command: rcm (php list pool [--php-version] [--php-fpm-user]).
   --root
        Set the web root pointing the URL. If empty, it will use the default value of
        \`--prefix\` and \`--container\`.
   --index-php ^
        Auto create index.php file.
        Can have value. The value is string that will be printed.
        Example: --index-php="Foo bar" will create contents \`<?= "Foo bar"; ?>\`.

Other options (For expert only):
   --prefix
        Set prefix directory for project.
        Default to home directory of --php-fpm-user. or /usr/local/share.
   --container
        Set the container directory for all projects.
        Available value: public_html, or other.
        Default to public_html --php-fpm-user is reguler user.
   --phpinfo ^
        Shortcut of \`--index-php=2\`.
        It will create index.php file with contents \`<?php phpinfo(); ?>\`.
   --hello ^
        Shortcut of \`--index-php=3\`.
        It will create index.php file with contents \`<?= 'Hello World'; ?>\`.
   --phpvariables ^
        Shortcut of \`--index-php=4\`.
        It will create index.php file with contents \`<pre><?php print_r(\$_SERVER); ?></pre>\`.
   --php-fpm-config
        Additional PHP-FPM Configuration inside pool directory.
        Available value: [1], [2], [3], [4], [5], [6], [7], or other.
        [1]: pm=ondemand
        [2]: php_flag[display_errors]=on
        [3]: php_value[max_execution_time]=300
        [4]: php_admin_value[memory_limit]=256M
        [5]: php_admin_value[upload_max_filesize]=25M
        [6]: php_admin_value[post_max_size]=1024M
        [7]: php_admin_flag[log_errors]=on
        Multivalue.
   --without-certbot-obtain ^
        The dafault value is \`--with-certbot-obtain\`, it will check the value of
        \`--url\`. The URL that contains https scheme is will automatically obtain.
        The URL that not contains http or https, it means using https excepts special top level domain such us .local, .example, etc.
        Use this option to force certbot to use existing certificate if the \`--url\`
        contains https.
   --certificate-name
        Use the existing certificate name that issued by Let's encrypt or set a
        new name of certificate that to be obtained.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.

Dependency:
   curl
   rcm-php-fpm-setup-project-config
   rcm-php-setup-adjust-cli-version
   rcm-nginx-virtual-host-autocreate-php-multiple-root
   rcm-nginx-reload
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --certificate-name=*) certificate_name="${1#*=}"; shift ;;
        --certificate-name) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then certificate_name="$2"; shift; fi; shift ;;
        --container=*) container="${1#*=}"; shift ;;
        --container) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then container="$2"; shift; fi; shift ;;
        --hello) index_php=3; shift ;;
        --index-php=*) index_php="${1#*=}"; shift ;;
        --index-php) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then index_php="$2"; shift; else index_php=1; fi; shift ;;
        --no-auto-add-group) no_auto_add_group=1; shift ;;
        --phpinfo) index_php=2; shift ;;
        --phpvariables) index_php=4; shift ;;
        --php-fpm-config=*) php_fpm_config+=("${1#*=}"); shift ;;
        --php-fpm-config) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then php_fpm_config+=("$2"); shift; fi; shift ;;
        --php-fpm-section=*) php_fpm_section="${1#*=}"; shift ;;
        --php-fpm-section) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then php_fpm_section="$2"; shift; fi; shift ;;
        --php-fpm-user=*) php_fpm_user="${1#*=}"; shift ;;
        --php-fpm-user) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then php_fpm_user="$2"; shift; fi; shift ;;
        --php-version=*) php_version="${1#*=}"; shift ;;
        --php-version) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then php_version="$2"; shift; fi; shift ;;
        --prefix=*) prefix="${1#*=}"; shift ;;
        --prefix) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then prefix="$2"; shift; fi; shift ;;
        --root=*) root="${1#*=}"; shift ;;
        --root) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then root="$2"; shift; fi; shift ;;
        --url=*) url="${1#*=}"; shift ;;
        --url) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then url="$2"; shift; fi; shift ;;
        --with-certbot-obtain) certbot_obtain=1; shift ;;
        --without-certbot-obtain) certbot_obtain=0; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.
PHP_FPM_POOL_DIRECTORY=${PHP_FPM_POOL_DIRECTORY:=/etc/php/[php-version]/fpm/pool.d}
RCM_TLD_SPECIAL=${RCM_TLD_SPECIAL:=example test onion invalid local localhost alt}

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm php add website
____

# Dependency.

# Functions.

# Require, validate, and populate value.
chapter Variable dump.
[ -n "$fast" ] && isfast=' --fast' || isfast=''
code no_auto_add_group="$no_auto_add_group"
is_wsl=
if [ -f /proc/sys/kernel/osrelease ];then
    read osrelease </proc/sys/kernel/osrelease
    if [[ "$osrelease" =~ microsoft || "$osrelease" =~ Microsoft ]];then
        is_wsl=1
    fi
fi
code 'is_wsl="'$is_wsl'"'
if [ -z "$php_version" ];then
    error "Argument --php-version required."; x
fi
code php_version="$php_version"
if [ -z "$url" ];then
    error "Argument --url required."; x
fi
code 'url="'$url'"'
urlCompleteComponent
code 'url="'$url'"'
code 'url_scheme="'$url_scheme'"'
code 'url_host="'$url_host'"'
code 'url_port="'$url_port'"'
code 'url_path="'$url_path'"'
code 'url_path_clean="'$url_path_clean'"'
code 'url_path_clean_trailing="'$url_path_clean_trailing'"'
if [ -n "$is_wsl" ];then
    # Jika mesin menggunakan WSL2, maka tambahkan max_execution_time (waktu proses)
    php_fpm_config=(pm=ondemand php_value[max_execution_time]=60 "${php_fpm_config[@]}")
fi
is_config_line=
is_config_line_array=()
# Dump array dengan single quote.
e; magenta 'php_fpm_config=('
first=1
for each in "${php_fpm_config[@]}";do
    if [ -n "$first" ];then
        magenta "'""$each""'"; first=
    else
        magenta " '""$each""'";
    fi
    [[ "$each" =~ ' ' ]] && is_config_line+=" --config-line='${each}'" || is_config_line+=" --config-line=${each}"
    is_config_line_array+=("--config-line=${each}")
done
magenta ')'; _.
code 'certificate_name="'$certificate_name
if [ -z "$php_fpm_section" ];then
    error "Argument --php-fpm-section required."; x
fi
code 'php_fpm_section="'$php_fpm_section'"'
[ -z "$certbot_obtain" ] && certbot_obtain=1
[ "$certbot_obtain" == 0 ] && certbot_obtain=
code 'certbot_obtain="'$certbot_obtain'"'
if [ -n "$is_tld_special" ];then
    certbot_obtain=
fi
code 'certbot_obtain="'$certbot_obtain'"'
[ -n "$certbot_obtain" ] && is_certbot_obtain=' --with-certbot-obtain' || is_certbot_obtain=' --without-certbot-obtain'
code 'is_certbot_obtain="'$is_certbot_obtain'"'
code 'root="'$root'"'
code 'prefix="'$prefix'"'
code 'container="'$container'"'
if [ -n "$root" ];then
    if [ -d "$root" ];then
        if [ ! "${root:0:1}" == / ];then
            root=$(resolve_relative_path "$root")
        fi
    else
        error Directory root is not exists; x
    fi
    # Input dari user selesai, sekarang kembalikan ke semula.
    # root adalah prefix.
    prefix="$root"
    container=.
else
    # Verifikasi prefix dari user.
    if [ -n "$prefix" ];then
        if [ -d "$prefix" ];then
            if [ ! "${prefix:0:1}" == / ];then
                prefix=$(resolve_relative_path "$prefix")
            fi
        else
            error Directory prefix is not exists; x
        fi
    fi
fi
code 'prefix="'$prefix'"'
code 'index_php="'$index_php'"'
rcm_nginx_reload=
____

INDENT+="    " \
rcm-php-setup-adjust-cli-version $isfast \
    --php-version="$php_version" \
    ; [ ! $? -eq 0 ] && x

# Code below from
# rcm-drupal-setup-wrapper-nginx-virtual-host-autocreate-php-multiple-root.sh
chapter Populate variables.
nginx_user=
conf_nginx=`command -v nginx > /dev/null && command -v nginx > /dev/null && nginx -V 2>&1 | grep -o -P -- '--conf-path=\K(\S+)'`
if [ -f "$conf_nginx" ];then
    nginx_user=`grep -o -P '^user\s+\K([^;]+)' "$conf_nginx"`
fi
code 'nginx_user="'$nginx_user'"'
if [ -z "$nginx_user" ];then
    error "Variable \$nginx_user failed to populate."; x
fi
if [ -z "$php_fpm_user" ];then
    php_fpm_user="$nginx_user"
fi
code 'php_fpm_user="'$php_fpm_user'"'
nginx_user_home=$(getent passwd "$nginx_user" | cut -d: -f6 )
if [ -z "$prefix" ];then
    prefix=$(getent passwd "$php_fpm_user" | cut -d: -f6 )
fi
# Jika $php_fpm_user adalah nginx, maka $HOME nya adalah /nonexistent, maka
# perlu kita verifikasi lagi.
if [ ! -d "$prefix" ];then
    prefix=
fi
if [ -z "$prefix" ];then
    prefix=/usr/local/share
    container=www
fi
if [ -z "$container" ];then
    if [ "$php_fpm_user" == "$nginx_user" ];then
        container=.
    else
        container=public_html
    fi
fi
code 'prefix="'$prefix'"'
code 'container="'$container'"'
socket_filename=$(rcm-php-fpm-setup-project-config get --php-fpm-user="$php_fpm_user" --php-version="$php_version" --section="$php_fpm_section" --key=listen)
if [ -z "$socket_filename" ];then
    __; red Socket Filename of PHP-FPM not found.; x
fi
code 'socket_filename="'$socket_filename'"'
fastcgi_pass="unix:${socket_filename}"
code 'fastcgi_pass="'$fastcgi_pass'"'

if [[ "$url_port" == 80 || "$url_port" == 443 ]];then
    additional_path_custom_port=
else
    additional_path_custom_port="/${url_port}"
fi

root="${prefix}/${container}/${url_host}${additional_path_custom_port}/web${url_path_clean_trailing}"
code 'root="'$root'"'
server_name="$url_host"
code server_name="$server_name"
root_parent=$(dirname "$root")
code 'root_parent="'$root_parent'"'
____

chapter Mengecek direktori root parent '`'$root_parent'`'.
isDirExists "$root_parent"
____

if [ -n "$notfound" ];then
    chapter Membuat direktori root parent.
    code sudo -u $php_fpm_user mkdir -p '"'$root_parent'"'
    sudo -u $php_fpm_user mkdir -p "$root_parent" || {
        code mkdir -p "$root_parent"
        code chown $php_fpm_user:$php_fpm_user '"'$root_parent'"'
        mkdir -p "$root_parent"
        chown $php_fpm_user:$php_fpm_user "$root_parent"
    }
    dirMustExists "$root_parent"
    ____
fi

chapter Mengecek direktori root '`'$root'`'.
isDirExists "$root"
____

if [ -n "$notfound" ];then
    chapter Membuat direktori root.
    code sudo -u $php_fpm_user mkdir -p '"'$root'"'
    sudo -u $php_fpm_user mkdir -p "$root" || {
        code mkdir -p "$root"
        code chown $php_fpm_user:$php_fpm_user '"'$root'"'
        mkdir -p "$root"
        chown $php_fpm_user:$php_fpm_user "$root"
    }
    dirMustExists "$root"
    ____
fi

# User yang digunakan sudah pasti adalah user nginx, karena akan dibuat di
# `/var/www`.
chapter Populate variable.
nginx_config_root="${nginx_user_home}/${url_host}${additional_path_custom_port}/nginx"
code 'nginx_config_root="'$nginx_config_root'"'
nginx_config_dir="${nginx_user_home}/${url_host}${additional_path_custom_port}/nginx.conf.d"
code 'nginx_config_dir="'$nginx_config_dir'"'
nginx_config_file="${nginx_user_home}/${url_host}${additional_path_custom_port}/nginx.conf"
code 'nginx_config_file="'$nginx_config_file'"'
adjustNginxConfigRoot "$url_path"
code 'nginx_config_root="'$nginx_config_root'"'
____

chapter Mengecek direktori nginx config root '`'$nginx_config_root'`'.
isDirExists "$nginx_config_root"
____

if [ -n "$notfound" ];then
    chapter Membuat direktori nginx config root '`'$nginx_config_root'`'.
    code mkdir -p '"'$nginx_config_root'"'
    mkdir -p "$nginx_config_root"
    code chown -R $nginx_user:$nginx_user '"'$nginx_config_root'"'
    chown -R $nginx_user:$nginx_user "$nginx_config_root"
    dirMustExists "$nginx_config_root"
    ____
fi

target="$nginx_config_root"
if [ -n "$url_path_clean" ];then
    target+="/${url_path_clean}"
fi
code 'target="'$target'"'
chapter Memeriksa direktori target '`'$target'`'
create=
if [[ "$target" == "$nginx_config_root" ]];then
    __ Target sama dengan nginx config root. Symbolic link tidak diperlukan.
else
    __ Target tidak sama dengan nginx config root. Symbolic link diperlukan.
    create=1
fi
____

if [ -n "$create" ];then
    source="$root"
    link_symbolic_dir "$source" "$target" "$nginx_user" absolute
fi

if [ -n "$url_path" ];then
    chapter Mengecek direktori nginx additional config '`'$nginx_config_dir'`'.
    isDirExists "$nginx_config_dir"
    ____

    if [ -n "$notfound" ];then
        chapter Membuat direktori nginx config root '`'$nginx_config_dir'`'.
        code mkdir -p '"'$nginx_config_dir'"'
        mkdir -p "$nginx_config_dir"
        code chown -R $nginx_user:$nginx_user '"'$nginx_config_dir'"'
        chown -R $nginx_user:$nginx_user "$nginx_config_dir"
        dirMustExists "$nginx_config_dir"
        ____
    fi
fi

chapter Prepare Arguments.
web_root=
if [ -z "$url_path" ];then
    web_root="$root"
fi
code 'nginx_config_root="'$nginx_config_root'"'
code 'nginx_config_dir="'$nginx_config_dir'"'
code 'nginx_config_file="'$nginx_config_file'"'
code 'url="'$url'"'
code 'web_root="'$web_root'"'
code 'fastcgi_pass="'$fastcgi_pass'"'
____

if [ -z "$tempfile" ];then
    tempfile=$(mktemp -p /dev/shm -t rcm-php-add-website.XXXXXX)
fi

chapter Mengecek '$PATH'.
code PATH="$PATH"
if grep -q '/snap/bin' <<< "$PATH";then
    __ '$PATH' sudah lengkap.
else
    __ '$PATH' belum lengkap.
    __ Memperbaiki '$PATH'
    PATH=/snap/bin:$PATH
    if grep -q '/snap/bin' <<< "$PATH";then
        __; green '$PATH' sudah lengkap.; _.
        __; magenta PATH="$PATH"; _.
    else
        __; red '$PATH' belum lengkap.; x
    fi
fi
____

INDENT+="    " \
PATH=$PATH \
RCM_TLD_SPECIAL="$RCM_TLD_SPECIAL" \
rcm-nginx-virtual-host-autocreate-php-multiple-root $isfast \
    $is_certbot_obtain \
    --without-nginx-reload \
    --tempfile-trigger-reload="$tempfile" \
    --url="$url" \
    --nginx-config-root="$nginx_config_root" \
    --nginx-config-file="$nginx_config_file" \
    --nginx-config-dir="$nginx_config_dir" \
    --web-root="$web_root" \
    --fastcgi-pass="$fastcgi_pass" \
    --certbot-certificate-name="$certificate_name" \
    ; [ ! $? -eq 0 ] && x

if [ -s "$tempfile" ];then
    rcm_nginx_reload=1
fi

if [ -n "$rcm_nginx_reload" ];then
    INDENT+="    " \
    rcm-nginx-reload \
        ; [ ! $? -eq 0 ] && x
fi

if [ -n "$index_php" ];then
    path="${root}/index.php"
    is_temporary=
    is_temporary_string=
    case "$index_php" in
        1) contents="" ;;
        2) contents="<?php phpinfo(); ?>" ;;
        3) contents="<?= 'Hello World'; ?>" ;;
        4) contents="<pre><?php print_r(\$_SERVER); ?></pre>" ;;
        *) contents="<?= '${index_php}'; ?>" ;;
    esac
else
    path=$(mktemp -p "$root" -t index.XXXXXX.php)
    chown $php_fpm_user:$php_fpm_user "$path"
    is_temporary=1
    is_temporary_string=' temporary'
fi

chapter Mempersiapkan file"$is_temporary_string" '`'index.php'`'.
code 'path="'$path'"'
filename=$(basename "$path")
isFileExists "$path"
if [ -n "$found" ];then
    read existing_contents < "$path"
    if [[ ! "$existing_contents" == "$contents" ]];then
        found=
        notfound=1
    fi
fi
if [ -n "$notfound" ];then
    if [ -f "$path" ];then
        __ Backup file "$path".
        backupFile move "$path"
    fi
    __ Membuat file"$is_temporary_string" '`'index.php'`'.
    echo "$contents" > "$path"
    chown $php_fpm_user:$php_fpm_user "$path"
    fileMustExists "$path"
fi
____

chapter Mengecek HTTP Response Code.
if [ "$url_scheme" == https ];then
    _k=' -k'
else
    _k=''
fi
i=0
code=
if [ -z "$tempfile" ];then
    tempfile=$(mktemp -p /dev/shm -t rcm-php-add-website.XXXXXX)
fi
until [ $i -eq 10 ];do
    __; magenta curl"$_k" -o /dev/null -s -w '"'%{http_code}\\n'"' '"'"${url_scheme}://127.0.0.1:${url_port}${url_path_clean_trailing}/${filename}"'"' -H '"'Host: $url_host'"'; _.
    curl$_k -o /dev/null -s -w "%{http_code}\n" "${url_scheme}://127.0.0.1:${url_port}${url_path_clean_trailing}/${filename}" -H "Host: ${url_host}" > $tempfile
    while read line; do e "$line"; _.; done < $tempfile
    code=$(head -1 $tempfile)
    if [[ "$code" =~ ^[2,3] ]];then
        break
    else
        __ Retry.
        __; magenta sleep .5; _.
        sleep .5
    fi
    let i++
done
if [[ "$code" =~ ^[2,3] ]];then
    __ HTTP Response code '`'$code'`' '('Required')'.
else
    __; red Terjadi kesalahan. HTTP Response code '`'$code'`'.; x
fi
____

if [ -n "$tempfile" ];then
    rm "$tempfile"
fi
if [ -n "$is_temporary" ];then
    rm "$path"
fi

chapter Finish.
__ URL'      ': "$url"
__ Web Root : "$root"
____

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --no-auto-add-group
# )
# VALUE=(
# --url
# --php-version
# --php-fpm-user
# --php-fpm-section
# --certificate-name
# --prefix
# --container
# --root
# )
# MULTIVALUE=(
# --php-fpm-config
# )
# FLAG_VALUE=(
# --index-php
# )
# CSV=(
    # 'long:--with-certbot-obtain,parameter:certbot_obtain'
    # 'long:--without-certbot-obtain,parameter:certbot_obtain,flag_option:reverse'
    # 'long:--phpinfo,parameter:index_php,flag_option:true=2'
    # 'long:--hello,parameter:index_php,flag_option:true=3'
    # 'long:--phpvariables,parameter:index_php,flag_option:true=4'
# )
# EOF
# clear
