#!/bin/bash

[ -f "$0" ] || { echo "Cannot run as dot command." >&2; kill -INT $$; }

# Define variables and constants.
RCM_EXTENSION_VERSION=0.19.0-alpha.14

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm plugin list [options]
       rcm plugin list [interface] [options]
       rcm plugin list <interface> [plugin-name] [options]

List available plugin.

Options:
   --plugin-name
        Show dialog to select <interface> argument then list the plugin that
        implements <interface> interface.
   --method
        Extend the --plugin-name to show dialog to select <plugin-name> argument
        then list the method of <plugin-name>.
        Conditional: Bypass if --plugin-name is not added.
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --method) method_interactive=1; shift ;;
        --plugin-name) plugin_name_interactive=1; shift ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Functions.
populateList() {
    list=()
    while IFS= read -r each;do
        list+=("$each")
    done <<< `ls -1 "$prefix"`
}

# ------------------------------------------------------------------------------

# Title.
title rcm plugin list
____

# Dependency.
require vendor/ijortengab/rcm/functions/base/print-select-dialog.sh
require vendor/ijortengab/bash/functions/array-search.sh

# Requirement, validate, and populate value.
chapter Variable dump.
command="rcm plugin list"
code plugin_name_interactive="$plugin_name_interactive"
code method_interactive="$method_interactive"
interface="$1"
plugin_name="$2"
prefix="$RCM_LIB"/interfaces
list=()
____

while IFS= read -r each;do
    find="${prefix}/"; replace=
    each="${each/#$find/$replace}"
    find=/implements; replace=
    each="${each/%$find/$replace}"
    list+=("$each")
done <<< `find -L "$prefix" -type d -iname implements`

while true; do
    if [ -z "$interface" ];then
        if [ -n "$plugin_name_interactive" ];then
            parameter=interface
            parameter_plural=interfaces
            _; _.
            _ Select available interface of plugin.; _.
            print-select-dialog list[@] "$parameter" "$parameter_plural"
            interface="$value"
            finish=list-plugin
        else
            finish=list-interface
        fi
    else
        if ! ArraySearch "$interface" list[@];then
            error The interface of plugin is unknown: '`'"$interface"'`'.; x
        fi
        finish=list-plugin
    fi
    command+=" ${interface}"
    prefix+="/${interface}"
    if [ -z "$plugin_name" ];then
        if [[ -n "$plugin_name_interactive" && -n "$method_interactive" ]];then
            prefix+="/implements"
            populateList
            parameter=plugin
            parameter_plural=plugins
            _; _.
            _ Select available plugin which implements '`'"$interface"'`' interface.; _.
            print-select-dialog list[@] "$parameter" "$parameter_plural"
            plugin_name="$value"
            finish=list-method
        fi
    else
        prefix+="/implements"
        populateList
        if ! ArraySearch "$plugin_name" list[@];then
            error The plugin name is unknown: '`'"$plugin_name"'`'.; x
        fi
        finish=list-method
    fi
    command+=" ${plugin_name}"
    break
done

chapter Command.
_; _, Execute' '; magenta $command; _.
____

case "$finish" in
    list-interface)
        for each in "${list[@]}"; do
            echo "$each"
        done
        ;;
    list-plugin)
        if [ -f "$prefix/list.sh" ];then
            source "$prefix/list.sh"
        elif [ -d "$prefix/implements" ];then
            ls -1 "$prefix/implements"
        fi
        ;;
    list-method)
        prefix+="/${plugin_name}"
        if [ -d "$prefix/methods" ];then
            ls -1 "$prefix/methods"
        fi
esac

exit 0

# parse-options.sh \
# --with-end-options-double-dash \
# --with-end-options-specific-operand \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
    # 'long:--plugin-name,parameter:plugin_name_interactive'
    # 'long:--method,parameter:method_interactive'
# )
# OPERAND=(
# )
# EOF
# clear
