#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.13

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm dovecot init

Auto Install Dovecot with default version.

Options:
   --dbms=DB
        Select database management system to store the data.
        Values available from command: rcm(plugin list dovecot/dbms).
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || usage 1

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --dbms=*) dbms="${1#*=}"; shift ;;
        --dbms) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then dbms="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Require.
require vendor/ijortengab/rcm/functions/utility/apt-install.sh

# ------------------------------------------------------------------------------

# Title.
title rcm dovecot init
____

# Define variables and constants.

if [ -z "$dbms" ];then
    error "Argument --dbms is required."; exit 1
fi

[ -n "$RCM_DEBUG" ] && chapter Variable dump.
[ -n "$RCM_DEBUG" ] && code 'dbms="'$dbms'"'
[ -n "$RCM_DEBUG" ] && ____

apt-install dovecot-core dovecot-imapd dovecot-pop3d dovecot-sieve dovecot-lmtpd

include `rcm plugin run-method dovecot/dbms $dbms init`

# Wajib exit 0 jika success.
exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --dbms
# )
# FLAG_VALUE=(
# )
# EOF
# clear
