#!/bin/bash

[ -f "$0" ] || { echo "Cannot run as dot command." >&2; kill -INT $$; }

# Define variables and constants.
RCM_EXTENSION_VERSION=0.19.0-alpha.14

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm dig get-info cname [options]
       rcm dig get-info cname [options] [alias-of]

alias-of:
    Set the target hostname of alias to be match.
    If omit, it will set to domain.

Options:
   --domain=DOMAIN
        Domain name to be checked.
   --hostname=[HOSTNAME]
        Set the hostname.

Other options:
   --name-server=[DNS]
        Set the Name server. Default value is - (dash). Available values: [1], [2], or other.
        [1]: 8.8.8.8
        [2]: 1.1.1.1

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.
   --reverse
        Reverse the result.
   --name-exists-sure
        Bypass domain exists checking.
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --domain=*) domain="${1#*=}"; shift ;;
        --domain) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then domain="$2"; shift; fi; shift ;;
        --hostname=*) hostname="${1#*=}"; shift ;;
        --hostname) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then hostname="$2"; shift; fi; shift ;;
        --name-exists-sure) name_exists_sure=1; shift ;;
        --name-server=*) name_server="${1#*=}"; shift ;;
        --name-server) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then name_server="$2"; shift; fi; shift ;;
        --reverse) reverse=1; shift ;;
        --with-color) colorize=1; shift ;;
        --without-color) colorize=0; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Boolean default to TRUE.
[ -z "$colorize" ] && colorize=1; [ "$colorize" == 0 ] && colorize=

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm dig get-info cname
____

# Dependency.
require command dig

# Functions.
# Global Used: add_name_server, tempfile.
isRecordExist() {
    local type="$1" found name_dot name_dot_escape
    local data_escape stdout
    local domain="$2"
    local name="$3"
    local data="$4"
    [ -n "$5" ] && tempfile="$5" || tempfile=$(mktemp -p /dev/shm -t rcm-dig-get-info-cname.XXXXXX)
    if [ "$data" == '@' ];then
        data="$domain"
    fi
    code dig "$type" $name${add_name_server}
    dig "$type" $name $add_name_server > "$tempfile"
    name_dot="${name}."
    name_dot_escape=${name_dot//\./\\.}
    stdout=$(<"$tempfile")
    [ -n "$RCM_DEBUG" ] && { while IFS= read -r line; do e "$line"; _.; done < "$tempfile" ; _. ; }
    data_escape=${data//\./\\.}
    data_escape=${data_escape//\*/\.*}
    data_escape=${data_escape//\ /\\ }
    code grep -E --ignore-case "'"^"$name_dot_escape"'\s+''[0-9]+''\s+'IN'\s+'"$type"'\s+'"$data_escape""'"
    if grep -q -E --ignore-case ^"$name_dot_escape"'\s+''[0-9]+''\s+'IN'\s+'"$type"'\s+'"$data_escape" <<< "$stdout";then
        return 0
    fi
    return 1
}

# Require, validate, and populate value.
[ -n "$RCM_DEBUG" ] && chapter Variable dump.
if [ -z "$domain" ];then
    error "Argument --domain required."; x
fi
[ -n "$RCM_DEBUG" ] && code domain="$domain"
[ -n "$RCM_DEBUG" ] && code name_server="$name_server"
if [[ "$name_server" == - ]];then
    name_server=
fi
[ -n "$name_server" ] && option_name_server=' --name-server='"$name_server" || option_name_server=''
[ -n "$name_server" ] && add_name_server=' @'"$name_server" || add_name_server=''
[ -n "$name_server" ] && label_name_server=' in DNS '"$name_server" || label_name_server=''
type=cname
[ -n "$RCM_DEBUG" ] && code type="$type"
type_uppercase=${type^^}
if [ -z "$hostname" ];then
    error "Argument --hostname required"; x
fi
alias_of=
if [ -n "$1" ];then
    alias_of="$1"
fi
[ -n "$RCM_DEBUG" ] && code type_uppercase="$type_uppercase"
[ -n "$RCM_DEBUG" ] && code hostname="$hostname"
[ -n "$RCM_DEBUG" ] && code alias_of="$alias_of"
[ -n "$RCM_DEBUG" ] && code colorize="$colorize"
[ -n "$RCM_DEBUG" ] && ____

if [ -z "$name_exists_sure" ];then
    INDENT+="    " \
    rcm dig get-info ns \
        --domain="$domain" \
        $option_name_server \
        ; [ ! $? -eq 0 ] && x
fi

[ -z "$hostname" ] && hostname=@
[[ "$hostname" == @ ]] && fqdn_string="$domain" || fqdn_string="${hostname}.${domain}"

if [ -z "$alias_of" ];then
    code dig CNAME "$fqdn_string" $add_name_server +short
    dig CNAME "$fqdn_string" $add_name_server +short
    exit 0
fi

record_found=
data="$alias_of"
[ -n "$alias_of" ] && alias_to="$alias_of" || alias_to="$domain"
chapter Query "$type_uppercase" Record for FQDN '`'${fqdn_string}'`'
if isRecordExist "$type_uppercase" "$domain" "$fqdn_string" "$data" "$mktemp";then
    record_found=1
    log="${type_uppercase} Record of "'`'"${fqdn_string}"'`'" alias to "'`'"${alias_to}"'`'" FOUND${label_name_server}."
else
    log="${type_uppercase} Record of "'`'"${fqdn_string}"'`'" alias to "'`'"${alias_to}"'`'" NOT FOUND${label_name_server}."
fi
____

chapter Result
rm "$tempfile"
if [ -n "$record_found" ];then
    result='success'
    if [ -n "$reverse" ];then
        result='error'
    fi
else
    result='error'
    if [ -n "$reverse" ];then
        result='success'
    fi
fi

if [ -z "$colorize" ];then
    __ "$log"
else
    $result "$log"
fi

[ "$result" == error ] && x
____

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --name-exists-sure
# --reverse
# )
# VALUE=(
# --domain
# --hostname
# --name-server
# )
# FLAG_VALUE=(
# )
# CSV=(
    # 'long:--with-color,parameter:colorize'
    # 'long:--without-color,parameter:colorize,flag_option:reverse'
# )
# EOF
# clear
