#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.6

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm-cron-setup-wsl-port-forwarding [options]

Options:
   --host-port *
        Set the host port that will be forwarded.
   --guest-port *
        Set the guest port as destination form host port.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.

Environment Variables:
   BASENAME
        Default to $BASENAME

Dependency:
   crontab
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --guest-port=*) guest_port="${1#*=}"; shift ;;
        --guest-port) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then guest_port="$2"; shift; fi; shift ;;
        --host-port=*) host_port="${1#*=}"; shift ;;
        --host-port) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then host_port="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.
BASENAME=${BASENAME:=host-port-[HOST_PORT]-forward-guest-port-[GUEST_PORT]}

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm-cron-setup-wsl-port-forwarding
____

# Dependency.

# Functions.
isFileExists() {
    # global used:
    # global modified: found, notfound
    # function used: __
    found=
    notfound=
    if [ -f "$1" ];then
        __ File '`'$(basename "$1")'`' ditemukan.
        found=1
    else
        __ File '`'$(basename "$1")'`' tidak ditemukan.
        notfound=1
    fi
}
fileMustExists() {
    # global used:
    # global modified:
    # function used: __, success, error, x
    if [ -f "$1" ];then
        __; green File '`'$(basename "$1")'`' ditemukan.; _.
    else
        __; red File '`'$(basename "$1")'`' tidak ditemukan.; x
    fi
}

# Require, validate, and populate value.
chapter Variable dump.
if [ -z "$host_port" ];then
    error "Argument --host-port required."; x
fi
code 'host_port="'$host_port'"'
if [ -z "$guest_port" ];then
    error "Argument --guest-port required."; x
fi
code 'guest_port="'$guest_port'"'
code 'BASENAME="'$BASENAME'"'
find='[HOST_PORT]'
replace="$host_port"
BASENAME="${BASENAME/"$find"/"$replace"}"
find='[GUEST_PORT]'
replace="$guest_port"
BASENAME="${BASENAME/"$find"/"$replace"}"
code 'BASENAME="'$BASENAME'"'
basename_string="$BASENAME"
code 'basename_string="'$basename_string'"'
case `uname` in
    CYGWIN*) is_cygwin=1 ;;
    *) is_cygwin= ;;
esac
code 'is_cygwin="'$is_cygwin'"'
____

if [ -z "$root_sure" ];then
    chapter Mengecek '`'Run as Administrator'`'.
    admin=$(/usr/bin/id -G | /usr/bin/grep -Eq '\<544\>' && echo yes || echo no)
    if [[ "$admin" == 'yes' ]]; then
        __ Run as admin.;
    else
        __ Run as Standard user.
    fi
    ____
fi

filename_string="/var/log/${basename_string}.log"
chapter Mengecek file log '`'$filename_string'`'
isFileExists "$filename_string"
if [ -n "$notfound" ];then
    __ Membuat file.
    touch "$filename_string"
    fileMustExists "$filename_string"
fi
____

filename_string="/usr/local/${basename_string}.sh"
chapter Mengecek shell script '`'$filename_string'`'
isFileExists "$filename_string"
if [ -n "$notfound" ];then
    __ Membuat file.
    mkdir -p $(dirname "$filename_string")
    touch "$filename_string"
    chmod a+x "$filename_string"
    string=$(cat << 'EOF'
#!/bin/bash
echo $(date +%Y%m%d-%H%M%S) '[notice]' Begin trigger.
begin=$SECONDS
PATH=/cygdrive/c/Windows/system32:$PATH
host_port=__HOST_PORT__
guest_port=__GUEST_PORT__
declare -i count
count=0
until [[ $(wsl --list --running --quiet | wc -l) -gt 0 ]]; do
    count+=1
    if [ $count -eq 60 ];then
        echo $(date +%Y%m%d-%H%M%S) '[notice]' Timeout, wait a minute.
        echo $(date +%Y%m%d-%H%M%S) '[notice]' Command to stop this process: '`'kill $$'`'.
        sleep 59
        count=0
    fi
    sleep 1
done
count=0
connectaddress=$(wsl ip address show dev eth0 | grep 'inet ' | grep -P -o '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | head -1)
until [[ -n "$connectaddress" ]]; do
    count+=1
    if [ $count -eq 60 ];then
        echo $(date +%Y%m%d-%H%M%S) '[notice]' Timeout, wait a minute.
        echo $(date +%Y%m%d-%H%M%S) '[notice]' Command to stop this process: '`'kill $$'`'.
        sleep 59
        count=0
    fi
    sleep 1
    connectaddress=$(wsl ip address show dev eth0 | grep 'inet ' | grep -P -o '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | head -1)
done
tempfile=$(mktemp)
netsh interface portproxy delete v4tov4 listenport=$host_port 2>&1 >> "$tempfile"
netsh advfirewall firewall delete rule name=$host_port 2>&1 >> "$tempfile"
netsh interface portproxy add v4tov4 listenport=$host_port connectport=$guest_port connectaddress="$connectaddress" 2>&1 >> "$tempfile"
netsh advfirewall firewall add rule name=$host_port dir=in action=allow protocol=TCP localport=$host_port 2>&1 >> "$tempfile"
netsh interface portproxy show v4tov4 2>&1 >> "$tempfile"
ifs="$IFS"
while IFS= read line; do
    echo $(date +%Y%m%d-%H%M%S) '[debug] ' "$line"
done < "$tempfile"
IFS="$ifs"
rm "$tempfile"
end=$SECONDS
duration=$(( end - begin ))
echo -n $(date +%Y%m%d-%H%M%S) '[notice]' End trigger.' '
hours=$((duration / 3600)); minutes=$(( (duration % 3600) / 60 )); seconds=$(( (duration % 3600) % 60 ));
runtime=`printf "%02d:%02d:%02d" $hours $minutes $seconds`
echo -n Duration: $runtime; if [ $duration -gt 60 ];then echo -n " (${duration} seconds)"; fi; echo -n '.'; echo
EOF
    )
    string=$(sed -e "s,__HOST_PORT__,$host_port," -e "s,__GUEST_PORT__,$guest_port," <<< "$string" )
    echo "$string" > "$filename_string"
    fileMustExists "$filename_string"
fi
____

chapter Mengecek cronjob.
line='@reboot /usr/local/'"$basename_string"'.sh >> /var/log/'"$basename_string"'.log'
code '"'"$line"'"'
crontab=$(crontab -l | sed '/^#.*$/d')
notfound=
if grep -q -F "$line" <<< "$crontab"; then
    __ Cronjob ditemukan
else
    __ Cronjob tidak ditemukan
    notfound=1
fi
____

if [ -n "$notfound" ];then
    chapter Menambah cronjob.
    if [ -n "$is_cygwin" ];then
        crontab=$(crontab -l | sed '/^# DO NOT EDIT THIS FILE/,+2d')
    else
        crontab=$(crontab -l)
    fi
    (echo "$crontab"; echo "$line") | crontab -
    crontab=$(crontab -l | sed '/^#.*$/d')
    if grep -q -F "$line" <<< "$crontab"; then
        __; green Cronjob ditemukan; _.
    else
        __; red Cronjob tidak ditemukan; x
    fi
    ____
fi

chapter Dump crontab.
code crontab -l
_; _.
crontab -l;
____

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --host-port
# --guest-port
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# EOF
# clear
