#!/bin/bash

# Prerequisite.
[ -f "$0" ] || { echo -e "\e[91m" "Cannot run as dot command. Hit Control+c now." "\e[39m"; read; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --fast) fast=1; shift ;;
        --php-version=*) php_version="${1#*=}"; shift ;;
        --php-version) if [[ ! $2 == "" && ! $2 =~ ^-[^-] ]]; then php_version="$2"; shift; fi; shift ;;
        --root-sure) root_sure=1; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Functions.
[[ $(type -t RcmWslSetupLempStack_printVersion) == function ]] || RcmWslSetupLempStack_printVersion() {
    echo '0.1.0'
}
[[ $(type -t RcmWslSetupLempStack_printHelp) == function ]] || RcmWslSetupLempStack_printHelp() {
    cat << EOF
RCM WSL Setup
Variation LEMP Stack
Version `RcmWslSetupLempStack_printVersion`

EOF
    cat << 'EOF'
Usage: rcm-wsl-setup-lemp-stack.sh [options]

Options:
   --php-version
        Set the version of PHP FPM.

Global Options:
   --fast
        No delay every subtask.
   --version
        Print version of this script.
   --help
        Show this help.
   --root-sure
        Bypass root checking.

Dependency:
   nginx
   php
   mariadb
EOF
}

# Help and Version.
[ -n "$help" ] && { RcmWslSetupLempStack_printHelp; exit 1; }
[ -n "$version" ] && { RcmWslSetupLempStack_printVersion; exit 1; }

# Dependency.
while IFS= read -r line; do
    command -v "${line}" >/dev/null || { echo -e "\e[91m""Unable to proceed, ${line} command not found." "\e[39m"; exit 1; }
done <<< `RcmWslSetupLempStack_printHelp | sed -n '/^Dependency:/,$p' | sed -n '2,/^$/p' | sed 's/^ *//g'`

# Common Functions.
[[ $(type -t red) == function ]] || red() { echo -ne "\e[91m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
[[ $(type -t green) == function ]] || green() { echo -ne "\e[92m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
[[ $(type -t yellow) == function ]] || yellow() { echo -ne "\e[93m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
[[ $(type -t blue) == function ]] || blue() { echo -ne "\e[94m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
[[ $(type -t magenta) == function ]] || magenta() { echo -ne "\e[95m" >&2; echo -n "$@" >&2; echo -ne "\e[39m" >&2; }
[[ $(type -t error) == function ]] || error() { echo -n "$INDENT" >&2; red "$@" >&2; echo >&2; }
[[ $(type -t success) == function ]] || success() { echo -n "$INDENT" >&2; green "$@" >&2; echo >&2; }
[[ $(type -t chapter) == function ]] || chapter() { echo -n "$INDENT" >&2; yellow "$@" >&2; echo >&2; }
[[ $(type -t title) == function ]] || title() { echo -n "$INDENT" >&2; blue "$@" >&2; echo >&2; }
[[ $(type -t code) == function ]] || code() { echo -n "$INDENT" >&2; magenta "$@" >&2; echo >&2; }
[[ $(type -t x) == function ]] || x() { echo >&2; exit 1; }
[[ $(type -t e) == function ]] || e() { echo -n "$INDENT" >&2; echo "$@" >&2; }
[[ $(type -t _) == function ]] || _() { echo -n "$INDENT" >&2; echo -n "$@" >&2; }
[[ $(type -t _,) == function ]] || _,() { echo -n "$@" >&2; }
[[ $(type -t _.) == function ]] || _.() { echo >&2; }
[[ $(type -t __) == function ]] || __() { echo -n "$INDENT" >&2; echo -n '    ' >&2; [ -n "$1" ] && echo "$@" >&2 || echo -n  >&2; }
[[ $(type -t ____) == function ]] || ____() { echo >&2; [ -n "$delay" ] && sleep "$delay"; }

# Functions.
[[ $(type -t fileMustExists) == function ]] || fileMustExists() {
    # global used:
    # global modified:
    # function used: __, success, error, x
    if [ -f "$1" ];then
        __; green File '`'$(basename "$1")'`' ditemukan.; _.
    else
        __; red File '`'$(basename "$1")'`' tidak ditemukan.; x
    fi
}

[[ $(type -t RcmWslSetupLempStack_makeSureRunning) == function ]] || RcmWslSetupLempStack_makeSureRunning() {
    local service="$1"
    chapter Memeriksa apakah daemon "$service" is running
    __ Memeriksa System V script '`'/etc/init.d/"$service"'`'
    fileMustExists /etc/init.d/"$service"
    if /etc/init.d/"$service" status 2>&1 >/dev/null; then
        __ Daemon "$service" running.
    else
        __ Daemon "$service" is not running.
        __ Trying to start.
        /etc/init.d/"$service" start
        if /etc/init.d/"$service" status 2>&1 >/dev/null; then
            __; green Daemon "$service" running.; _.
        else
            __; red Daemon "$service" is not running.; x
        fi
    fi
    ____
}

# Title.
title RCM WSL Setup
_ 'Variation '; yellow LEMP Stack; _.
_ 'Version '; yellow `RcmWslSetupLempStack_printVersion`; _.
____

# Require, validate, and populate value.
chapter Dump variable.
code 'php_version="'$php_version'"'
delay=.5; [ -n "$fast" ] && unset delay
____

if [ -z "$root_sure" ];then
    chapter Mengecek akses root.
    if [[ "$EUID" -ne 0 ]]; then
        error This script needs to be run with superuser privileges.; x
    else
        __ Privileges.; root_sure=1
    fi
    ____
fi

chapter Memerikasa apakah mesin ini merupakan WSL.
wsl=
if [ -f /proc/sys/kernel/osrelease ];then
    read osrelease </proc/sys/kernel/osrelease
    code osrelease=$osrelease
    # debian: osrelease=5.10.0-19-amd64
    # wsl2: 4.4.0-19041-Microsoft
    # wsl2: 4.19.128-microsoft-standard
    if [[ "$osrelease" =~ microsoft || "$osrelease" =~ Microsoft ]];then
        __ Mesin merupakan WSL.
        wsl=1
    else
        __ Mesin bukan merupakan WSL.
    fi
fi
____

if [ -n "$wsl" ];then
    RcmWslSetupLempStack_makeSureRunning nginx
    RcmWslSetupLempStack_makeSureRunning mariadb
    RcmWslSetupLempStack_makeSureRunning "php${php_version}-fpm"
fi
____

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --fast
# --version
# --help
# --root-sure
# )
# VALUE=(
# --php-version
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# EOF
# clear
