#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.11

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm nginx add vhost php-default [options]

Options:
   --url=URL
        Set the URL.
   --root=ROOT
        Set the value of root directive.
   --fastcgi-pass=SOCKET
        Set the value of fastcgi_pass directive.
   --without-nginx-reload
        Prevent auto reload nginx after add/edit file config.
        Default value is --with-nginx-reload.
   --tls-certificate=[FILE]
        Directive tls_certificate in nginx config.
        Populate value from variable TLS_CERTIFICATE.
   --tls-certificate-key=[FILE]
        Directive tls_certificate_key in nginx config.
        Populate value from variable TLS_CERTIFICATE_KEY.

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --fastcgi-pass=*) fastcgi_pass="${1#*=}"; shift ;;
        --fastcgi-pass) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then fastcgi_pass="$2"; shift; fi; shift ;;
        --fast) fast=1; shift ;;
        --root=*) root="${1#*=}"; shift ;;
        --root) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then root="$2"; shift; fi; shift ;;
        --tempfile-trigger-reload=*) tempfile_trigger_reload="${1#*=}"; shift ;;
        --tempfile-trigger-reload) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tempfile_trigger_reload="$2"; shift; fi; shift ;;
        --tls-certificate-key=*) tls_certificate_key="${1#*=}"; shift ;;
        --tls-certificate-key) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate_key="$2"; shift; fi; shift ;;
        --tls-certificate=*) tls_certificate="${1#*=}"; shift ;;
        --tls-certificate) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate="$2"; shift; fi; shift ;;
        --url=*) url="${1#*=}"; shift ;;
        --url) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then url="$2"; shift; fi; shift ;;
        --with-nginx-reload) nginx_reload=1; shift ;;
        --without-nginx-reload) nginx_reload=0; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

require vendor/ijortengab/bash/functions/array-search.sh
require vendor/ijortengab/rcm/functions/classes/rcm-file.sh
require vendor/ijortengab/rcm/functions/classes/rcm-resolve-condition.sh
require vendor/ijortengab/rcm/functions/utility/backup-dir.sh
require vendor/ijortengab/rcm/functions/utility/backup-file.sh
require vendor/ijortengab/rcm/functions/utility/link-symbolic.sh
require vendor/ijortengab/rcm/functions/utility/parse-url.sh
require vendor/ijortengab/rcm/functions/utility/url-complete-component.sh
require vendor/ijortengab/rcm/functions/nginx/rcm-nginx-grep.sh

# ------------------------------------------------------------------------------

# Title.
title rcm nginx add vhost php-default
____

# Dependency.
require rcm nginx reload

# Define variables and constants.
[ -z "$fast" ] && fast="$RCM_FAST"; [ "$fast" == 0 ] && fast=
RCM_DELAY=${RCM_DELAY:=.5}; [ -n "$fast" ] && unset RCM_DELAY
RCM_INDENT='    '; [ "$(tput cols)" -le 80 ] && RCM_INDENT='  '
RCM_TLD_SPECIAL=${RCM_TLD_SPECIAL:=example test onion invalid local localhost alt}

validate-content() {
    local path="$1"

    # listen
    if [ "$url_scheme" == https ];then
        if ! rcm-nginx-grep listen '(a&b)|(a&b&c)' a contains "$url_port" b contains ssl c contains ipv6only=on < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    else
        if ! rcm-nginx-grep listen contains "$url_port" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    fi
    # root
    if ! rcm-nginx-grep root "$root" < "$path";then
        __; yellow File akan dibuat ulang.; _.
        return 1
    fi
    # server_name
    if ! rcm-nginx-grep server_name contains "$url_host" < "$path";then
        __; yellow File akan dibuat ulang.; _.
        return 1
    fi
    # fastcgi_pass
    if ! rcm-nginx-grep fastcgi_pass is "$fastcgi_pass" < "$path";then
        __; yellow File akan dibuat ulang.; _.
        return 1
    fi
    if [ "$url_scheme" == https ];then
        # ssl_certificate
        if ! rcm-nginx-grep ssl_certificate is "$ssl_certificate" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # ssl_certificate_key
        if ! rcm-nginx-grep ssl_certificate_key is "$ssl_certificate_key" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # include
        if ! rcm-nginx-grep include is /etc/letsencrypt/options-ssl-nginx.conf < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # include
        if ! rcm-nginx-grep ssl_dhparam is /etc/letsencrypt/ssl-dhparams.pem < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    fi
    if [ "$url_scheme" == http ];then
        # ssl_certificate
        if rcm-nginx-grep ssl_certificate is "$ssl_certificate" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # ssl_certificate_key
        if rcm-nginx-grep ssl_certificate_key is "$ssl_certificate_key" < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # include
        if rcm-nginx-grep include is /etc/letsencrypt/options-ssl-nginx.conf < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
        # include
        if rcm-nginx-grep ssl_dhparam is /etc/letsencrypt/ssl-dhparams.pem < "$path";then
            __; yellow File akan dibuat ulang.; _.
            return 1
        fi
    fi
    return 0
}
validate-content-redirect() {
    local path="$1"
    # listen
    if ! rcm-nginx-grep listen contains 80 < "$path";then
        __; yellow File akan dibuat ulang.; _.
        return 1
    fi
    # server_name
    if ! rcm-nginx-grep server_name contains "$url_host" < "$path";then
        __; yellow File akan dibuat ulang.; _.
        return 1
    fi
    return 0
}

# Require, validate, and populate value.
chapter Variable dump.
if [ -z "$url" ];then
    error "Argument --url required."; x
fi
code 'url="'$url'"'

url-complete-component
code 'url="'$url'"'
code 'url_scheme="'$url_scheme'"'
code 'url_host="'$url_host'"'
code 'url_port="'$url_port'"'
code 'url_path="'$url_path'"'
code 'url_path_clean="'$url_path_clean'"'
code 'url_path_clean_trailing="'$url_path_clean_trailing'"'
if [[ "$url_port" == 80 || "$url_port" == 443 ]];then
    filename="$url_host"
else
    filename="${url_host}.${url_port}"
fi
if [ -z "$root" ];then
    error "Argument --root required."; x
fi
if [ -z "$fastcgi_pass" ];then
    error "Argument --fastcgi-pass required."; x
fi
[ -z "$nginx_reload" ] && nginx_reload=1
[ "$nginx_reload" == 0 ] && nginx_reload=
code 'filename="'$filename'"'
code 'root="'$root'"'
code 'fastcgi_pass="'$fastcgi_pass'"'
code 'nginx_reload="'$nginx_reload'"'
code 'tempfile_trigger_reload="'$tempfile_trigger_reload'"'
code 'tls_certificate="'$tls_certificate'"'
code 'tls_certificate_key="'$tls_certificate_key'"'
# If not set in argument, try load from environment.
[ -z "$tls_certificate" ] && tls_certificate="$TLS_CERTIFICATE"
[ -z "$tls_certificate_key" ] && tls_certificate_key="$TLS_CERTIFICATE_KEY"
code 'tls_certificate="'$tls_certificate'"'
code 'tls_certificate_key="'$tls_certificate_key'"'
rcm_nginx_reload=
tempfile=
validate_existing_certificate=
if [[ "$url_scheme" == https ]];then
    if [ -z "$tls_certificate" ];then
        error "Argument --tls-certificate required."; x
    fi
    if [ -z "$tls_certificate_key" ];then
        error "Argument --tls-certificate-key required."; x
    fi
fi
____

path="/etc/nginx/sites-available/$filename"
chapter Mengecek nginx config file: '`'$filename'`'.
code 'path="'$path'"'
rcm-file "$path" isExists
____

chapter Populate variable.
if [[ "$url_scheme" == https ]];then
    ssl_certificate="$tls_certificate"
    ssl_certificate_key="$tls_certificate_key"
fi
code 'ssl_certificate="'$ssl_certificate'"'
code 'ssl_certificate_key="'$ssl_certificate_key'"'
____

create_new=
if [ -n "$found" ];then
    chapter Memeriksa konten.
    validate-content "$path"
    [ ! $? -eq 0 ] && create_new=1;
    ____
else
    create_new=1
fi

if [[ -n "$create_new" && "$url_scheme" == https ]];then
    chapter Memeriksa certificate SSL.
    rcm-file "$ssl_certificate" terminateIfNotExists
    rcm-file "$ssl_certificate_key" terminateIfNotExists
    ____
fi

if [ -n "$create_new" ];then
    path="/etc/nginx/sites-available/$filename"
    chapter Membuat nginx config file: '`'$filename'`'.
    code 'path="'$path'"'
    if [ -f "$path" ];then
        __ Backup file "$filename".
        backup-file move "$path"
    fi
    __ Membuat file "$filename".
    cat <<'EOF' > "$path"
server {
    listen __URL_PORT____SSL__;
    listen [::]:__URL_PORT____SSL____IPV6ONLY__;
    root __ROOT__;
    index index.php;
    server_name __URL_HOST__;
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }
    location ~ ^(.+\.php)(.*)$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass __FASTCGI_PASS__;
        fastcgi_read_timeout 3600;
    }
    # ssl_certificate __SSL_CERTIFICATE__;
    # ssl_certificate_key __SSL_CERTIFICATE_KEY__;
    # include /etc/letsencrypt/options-ssl-nginx.conf;
    # ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # error_page 497 301 =307 https://$host:$server_port$request_uri;
}
EOF
    rcm-file "$path" mustExists

    sed -i "s|__ROOT__|${root}|g" "$path"
    sed -i "s|__URL_HOST__|${url_host}|g" "$path"
    sed -i "s|__SSL_CERTIFICATE__|${ssl_certificate}|g" "$path"
    sed -i "s|__SSL_CERTIFICATE_KEY__|${ssl_certificate_key}|g" "$path"
    sed -i "s|__FASTCGI_PASS__|${fastcgi_pass}|g" "$path"
    sed -i "s|__URL_PORT__|${url_port}|g" "$path"
    if [ "$url_scheme" == https ];then
        sed -i "s|__SSL__| ssl|g" "$path"
        # Hanya satu ipv6only=on yang boleh exist pada setiap virtual host.
        if grep -R -q ipv6only=on /etc/nginx/sites-enabled/;then
            sed -i "s|__IPV6ONLY__||g" "$path"
        else
            sed -i "s|__IPV6ONLY__| ipv6only=on|g" "$path"
        fi
        sed -i -E 's|^(\s*)# ssl_certificate (.*);|\1ssl_certificate \2;|g' "$path"
        sed -i -E 's|^(\s*)# ssl_certificate_key (.*);|\1ssl_certificate_key \2;|g' "$path"
        sed -i -E 's|^(\s*)# include /etc/letsencrypt/options-ssl-nginx.conf;|\1include /etc/letsencrypt/options-ssl-nginx.conf;|g' "$path"
        sed -i -E 's|^(\s*)# ssl_dhparam (.*);|\1ssl_dhparam \2;|g' "$path"
    else
        sed -i "s|__SSL__||g" "$path"
        sed -i "s|__IPV6ONLY__||g" "$path"
    fi
    ____

    chapter Memeriksa ulang konten.
    validate-content "$path"
    [ ! $? -eq 0 ] && x
    ____

    rcm_nginx_reload=1
fi

source="$path"
target="/etc/nginx/sites-enabled/$filename"
link-symbolic "$source" "$target"

path="/etc/nginx/sites-available/${filename}-redirect"
filename_redirect="${filename}-redirect"
chapter Mengecek nginx config file: '`'$filename_redirect'`'.
rcm-file "$path" isExists
____

if [[ "$url_scheme" == https && "$url_port" == 443 ]];then
    create_new=
    if [ -n "$found" ];then
        chapter Memeriksa konten.
        validate-content-redirect "$path"
        [ ! $? -eq 0 ] && create_new=1;
        ____
    else
        create_new=1
    fi
    if [ -n "$create_new" ];then
        path="/etc/nginx/sites-available/${filename}-redirect"
        filename_redirect="${filename}-redirect"
        chapter Membuat nginx config file: '`'$filename_redirect'`'.
        code 'path="'$path'"'
        if [ -f "$path" ];then
            __ Backup file: '`'"$filename_redirect"'`'.
            backup-file move "$path"
        fi
        __ Membuat file "$filename_redirect".
        cat <<'EOF' > "$path"
server {
    if ($host = __URL_HOST__) {
        return 301 https://$host$request_uri;
    }
    listen [::]:80;
    listen 80;
    server_name __URL_HOST__;
    return 404;
}
EOF
        rcm-file "$path" mustExists
        sed -i "s|__URL_HOST__|${url_host}|g" "$path"
        ____

        chapter Memeriksa ulang konten.
        validate-content-redirect "$path"
        [ ! $? -eq 0 ] && x
        ____

        rcm_nginx_reload=1
    fi
    path="/etc/nginx/sites-available/${filename}-redirect"
    source="$path"
    target="/etc/nginx/sites-enabled/${filename}-redirect"
    link-symbolic "$source" "$target"
else
    # Nginx reload agar symlink di sites-enabled auto hapus.
    if [ -n "$found" ];then
        chapter Menonaktifkan file config.
        __ Backup file: '`'"$filename_redirect"'`'.
        backup-file move "$path"
        rcm_nginx_reload=1
        ____
    fi
fi

# Credit: https://stackoverflow.com/questions/15429043/how-to-redirect-on-the-same-port-from-http-to-https-with-nginx-reverse-proxy
if [[ "$url_scheme" == https && ! "$url_port" == 443 ]];then
    chapter Redirect to https if accessed with http
    path="/etc/nginx/sites-available/$filename"
    find="    error_page 497"
    if find-string "# ${find}" "$path";then
        code sed -i -E "'"'s|'"${find_quoted}"'|'"${find}"'|g'"'" "$path"
        sed -i -E 's|'"${find_quoted}"'|'"${find}"'|g' "$path"
    fi
    if ! rcm-nginx-grep error_page contains 497 < "$path";then
        error Enable gagal.; x
    fi
    ____
fi

if [ -z "$nginx_reload" ];then
    if [ -n "$rcm_nginx_reload" ];then
        if [ -f "$tempfile_trigger_reload" ];then
            echo 1 > "$tempfile_trigger_reload"
        fi
    fi
    rcm_nginx_reload=
fi

if [ -n "$rcm_nginx_reload" ];then
    INDENT+="    " \
    rcm nginx reload \
        ; [ ! $? -eq 0 ] && x
fi

[ -n "$tempfile" ] && rm "$tempfile"

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --fast
# --version
# --help
# )
# VALUE=(
# --url
# --root
# --fastcgi-pass
# --tempfile-trigger-reload
# --tls-certificate
# --tls-certificate-key
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
#     'long:--with-nginx-reload,parameter:nginx_reload'
#     'long:--without-nginx-reload,parameter:nginx_reload,flag_option:reverse'
# )
# EOF
# clear
