#!/bin/bash

[ -f "$0" ] || { echo "Cannot run as dot command." >&2; kill -INT $$; }

# Define variables and constants.
RCM_EXTENSION_VERSION=0.19.0-alpha.13

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm nginx add vhost static-hello-world [options]

Options:
   --domain=DOMAIN
        Set the domain name.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --domain=*) domain="${1#*=}"; shift ;;
        --domain) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then domain="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm nginx add vhost static-hello-world
____

# Dependency.
require command nginx
require command curl
require rcm nginx add vhost static-default
require vendor/ijortengab/rcm/functions/utility/backup-file.sh
require vendor/ijortengab/rcm/functions/classes/rcm-file.sh

# Require, validate, and populate value.
chapter Variable dump.
[ -n "$fast" ] && isfast=' --fast' || isfast=''
if [ -z "$domain" ];then
    error "Argument --domain required."; x
fi
code 'domain="'$domain'"'
____

chapter Prepare arguments.
root="/var/www/$domain/web"
code root="$root"
filename="$domain"
code filename="$filename"
server_name="$domain"
code server_name="$server_name"
____

INDENT+="    " \
rcm nginx add vhost static-default \
    --root="$root" \
    --filename="$filename" \
    --server-name="$server_name" \
    ; [ ! $? -eq 0 ] && x

chapter Mempersiapkan web root directory.
__; magenta root='"'$root'"'; _.
notfound=
if [ -d "$root" ];then
    __ Direktori '`'$root'`' ditemukan.
else
    __ Direktori '`'$root'`' tidak ditemukan.
    notfound=1
fi
____

if [ -n "$notfound" ];then
    chapter Membuat directory.
    mkdir -p "$root"
    if [ -d "$root" ];then
        __; green Direktori '`'$root'`' ditemukan.; _.
    else
        __; red Direktori '`'$root'`' tidak ditemukan.; x
    fi
    ____
fi

chapter Mempersiapkan file '`'index.html'`'.
notfound=1
path="$root/index.html"
if [ -f "$path" ];then
    read contents < "$path"
    if [ "$contents" == "Hello World" ];then
        notfound=
    fi
fi
if [ -n "$notfound" ];then
    if [ -f "$path" ];then
        __ Backup file "$path".
        backup-file move "$path"
    fi
    __ Membuat file '`'index.html'`'.
    echo Hello World > "$path"
fi
rcm-file "$path" mustExists
____

chapter Mengecek HTTP Response Code.
i=0
code=
if [ -z "$tempfile" ];then
    tempfile=$(mktemp -p /dev/shm -t rcm-nginx-add-vhost-static-hello-world.XXXXXX)
fi
until [ $i -eq 10 ];do
    __; magenta curl -o /dev/null -s -w '"'%{http_code}\\n'"' '"'http://127.0.0.1'"' -H '"'Host: $domain'"'; _.
    curl -o /dev/null -s -w "%{http_code}\n" "http://127.0.0.1" -H "Host: ${domain}" > $tempfile
    while read line; do e "$line"; _.; done < $tempfile
    code=$(head -1 $tempfile)
    if [[ "$code" =~ ^[2,3] ]];then
        break
    else
        __ Retry.
        __; magenta sleep .5; _.
        sleep .5
    fi
    let i++
done
if [[ "$code" =~ ^[2,3] ]];then
    __ HTTP Response code '`'$code'`' '('Required')'.
else
    __; red Terjadi kesalahan. HTTP Response code '`'$code'`'.; x
fi
____

if [ -n "$tempfile" ];then
    rm "$tempfile"
fi

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --domain
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# EOF
# clear
