#!/bin/bash

# Rapid Construct Massive
#
# (c) IjorTengab <ijortengab@systemix.id> <ijortengab@gmail.com>
#
# https://github.com/ijortengab/rcm
#
# Command to download: `wget git.io/rcm`
#
RCM_EXTENSION_VERSION=0.19.0-alpha.4

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm install [options]
       rcm install <url> [extension-version] [options]

Options:
    --url=URL
        The URL of Repository.
        Only supports URLs from Github.
    --extension-version=[SEMVER]
        The version of extenstion. Default value is \`latest\`.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.

Environment Variables:
   BINARY_DIRECTORY
        Default to $BINARY_DIRECTORY

Mapping Operand:
   --url
   --extension-version
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --extension-version=*) extension_version="${1#*=}"; shift ;;
        --extension-version) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then extension_version="$2"; shift; fi; shift ;;
        --url=*) url="${1#*=}"; shift ;;
        --url) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then url="$2"; shift; fi; shift ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.
BINARY_DIRECTORY=${BINARY_DIRECTORY:=[__DIR__]}
# If not set in argument, try load from environment.
RCM_TLD_SPECIAL=${RCM_TLD_SPECIAL:=example test onion invalid local localhost alt}
# If set in environment, set to variable.
[ -n "$RCM_TABLE_DOWNLOADS" ] && table_downloads="$RCM_TABLE_DOWNLOADS"

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

require vendor/ijortengab/rcm/functions/utility/url-complete-component.sh
require vendor/ijortengab/rcm/functions/classes/rcm-wget.sh
require vendor/ijortengab/rcm/functions/classes/rcm-dir.sh

# ------------------------------------------------------------------------------

# Title.
title rcm install
____

# Functions.
# Mapping operand to value of options.
chapter Mapping operand as value of options.
if [ -n "$1" ];then
    code --url=$1
    url=$1; shift
fi
if [ -n "$1" ];then
    code --extension-version=$1
    extension_version=$1; shift
fi
____

# Require, validate, and populate value.
chapter Variable dump.
if [ -z "$url" ];then
    error "Argument --url required."; x
fi
code 'url="'$url'"'
if [ -z "$extension_version" ];then
    extension_version=latest
fi
code 'extension_version="'$extension_version'"'
tempfile=
url-complete-component
if [ ! "$url_host" == github.com ];then
    error Only supports URLs from Github.; x
fi
table=$HOME/.config/rcm/rcm.table.extension
github_owner_repo=$(cut -d/ -f 2,3 <<< $url_path)
version="$extension_version"
____

chapter Download from Github.
url_tarball=
if [ "$version" == latest ];then
    tag_name=$(rcm-wget 3600 https://api.github.com/repos/$github_owner_repo/releases/latest | grep '^  "tag_name": ".*",$' | sed -E 's/  "tag_name": "(.*)",/\1/')
    if [ -z "$tag_name" ];then
        error "The repository does not have any releases."; x
    fi
    version=$(sed -E 's/v?(.*)/\1/' <<< "$tag_name")
    url_tarball='https://api.github.com/repos/'$github_owner_repo'/tarball/'$tag_name
fi

if [ -z "$url_tarball" ];then
    tag_name=$(rcm-wget 3600 https://api.github.com/repos/$github_owner_repo/releases/tags/$version | grep '^  "tag_name": ".*",$' | sed -E 's/  "tag_name": "(.*)",/\1/')
    if [ -z "$tag_name" ];then
        error "The repository does not have that release tag."; x
    fi
    url_tarball='https://api.github.com/repos/'$github_owner_repo'/tarball/'$tag_name
fi

cache_directory=$HOME/.cache/rcm/$github_owner_repo/$version
if [ ! -d "$cache_directory" ];then
    if [ -n "$loud" ];then
        _ 'Downloading version: '; yellow $version; _.
    fi
    tempdir=$(mktemp -d)
    cd "$tempdir"
    wget -q -O "${tag_name}.tar.gz" "$url_tarball"
    if [ ! -f "${tag_name}.tar.gz" ];then
        error Failed to download file: "${tag_name}.tar.gz".
        rm -rf "$tempdir"
        x
    fi
    tar xfz "${tag_name}.tar.gz"
    found_directory_extracted=$(find -maxdepth 1 -mindepth 1 -type d)
    if [ ! -d "$found_directory_extracted" ];then
        error Failed to extract archieve: "${tag_name}.tar.gz".;
        cd - >/dev/null
        rm -rf "$tempdir"
        x
    fi
    mkdir -p $(dirname "$cache_directory");
    mv $(realpath "$found_directory_extracted") "$cache_directory"
    # Cleaning.
    cd - >/dev/null
    rm -rf "$tempdir"
else
    if [ -n "$loud" ];then
        _ 'Using downloaded version: '; yellow $version; _.
    fi
fi
____

chapter Memeriksa direktori commands.
target="${RCM_LIB}/commands"
code 'target="'$target'"'
rcm-dir "$target" terminateIfNotExists

source="${cache_directory}/rcm/install/commands"
code 'source="'$source'"'
rcm-dir "$source" isExists
if [ -n "$found" ];then
    __ Copy commands directory.
    while IFS= read -r line; do
        code cp -r "${source}/${line}" -T "${target}/${line}"
        cp -r "${source}/${line}" -T "${target}/${line}"; [ $? -eq 0 ] || x
    done <<< `ls -1 "$source"`
fi
____

chapter Memeriksa direktori interfaces.
target="${RCM_LIB}/interfaces"
code 'target="'$target'"'
rcm-dir "$target" terminateIfNotExists

source="${cache_directory}/rcm/install/interfaces"
code 'source="'$source'"'
rcm-dir "$source" isExists
if [ -n "$found" ];then
    __ Copy interfaces directory.
    while IFS= read -r line; do
        code cp -r "${source}/${line}" -T "${target}/${line}"
        cp -r "${source}/${line}" -T "${target}/${line}"; [ $? -eq 0 ] || x
    done <<< `ls -1 "$source"`
fi
____

exit 0

# parse-options.sh \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --with-end-options-double-dash \
# --no-error-require-arguments << EOF | clip
# INCREMENT=(
# )
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --url
# --extension-version
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
