#!/bin/bash

RCM_EXTENSION_VERSION=0.18.0-alpha.6

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm-system-ram-swap-4gb [options]

Global Options:
   --fast
        No delay every subtask.
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Title.
title rcm-system-ram-swap-4gb
____

# Dependency.
while IFS= read -r line; do
    [[ -z "$line" ]] || command -v `cut -d: -f1 <<< "${line}"` >/dev/null || { error Unable to proceed, command not found: '`'`cut -d: -f1 <<< "${line}"`'`'.; x; }
done <<< `usage 2>/dev/null | sed -n '/^Dependency:/,$p' | sed -n '2,/^\s*$/p' | sed 's/^ *//g'`

path=/swapfile-rcm-4G

chapter Membuat file swap.
code fallocate -l 4G "$path"
code chmod 600 "$path"
code mkswap "$path"
____

if [ ! -f "$path" ];then
    fallocate -l 4G "$path"
    chmod 600 "$path"
    mkswap "$path"
fi
chapter Mengaktifkan file swap.
if grep -q "^${path}$" <<< `swapon --show=name --noheadings --raw`;then
    code swapon "$path"
else
    code swapon "$path"
    swapon "$path"
fi
____

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
