#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.3

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm-nginx-variables-export [command] [options]

Available commands: tls-certificate.

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.

Options for command tls-certificate:
   --tls-certificate
        Directive ssl_certificate in nginx config.
        Prepopulate value from variable TLS_CERTIFICATE.
   --tls-certificate-key
        Directive ssl_certificate_key in nginx config.
        Prepopulate value from variable TLS_CERTIFICATE_KEY.

RCM Config:
   --no-timer
   --no-confirmation
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        tls-certificate)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Command.
if [ -n "$1" ];then
    command=
    case "$1" in
        tls-certificate) command="$1"; shift ;;
    esac
    if [ -z "$command" ];then
        error Command unknown: '`'"$1"'`'.; x
    fi
fi

# Parse arguments per command. Generated by parse-options.sh
case "$command" in
    tls-certificate)
        _new_arguments=()
        while [[ $# -gt 0 ]]; do
            case "$1" in
                --help) help=1; shift ;;
                --version) version=1; shift ;;
                --fast) fast=1; shift ;;
                --tls-certificate-key=*) tls_certificate_key="${1#*=}"; shift ;;
                --tls-certificate-key) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate_key="$2"; shift; fi; shift ;;
                --tls-certificate=*) tls_certificate="${1#*=}"; shift ;;
                --tls-certificate) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then tls_certificate="$2"; shift; fi; shift ;;
                --[^-]*) shift ;;
                *) _new_arguments+=("$1"); shift ;;
            esac
        done
        set -- "${_new_arguments[@]}"
        unset _new_arguments
        ;;
esac

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Functions.
command-tls-certificate() {
    # If not set in argument, try load from environment.
    [ -z "$tls_certificate" ] && tls_certificate="$TLS_CERTIFICATE"
    [ -z "$tls_certificate_key" ] && tls_certificate_key="$TLS_CERTIFICATE_KEY"
    # Export.
    echo 'TLS_CERTIFICATE='"$tls_certificate"
    echo 'TLS_CERTIFICATE_KEY='"$tls_certificate_key"
}

# Execute command.
if [ -n "$command" ];then
    if [[ $(type -t "command-${command}") == function ]];then
        command-${command} "$@"
        exit 0
    else
        error Command unknown: '`'"$command"'`'.; x
    fi
fi

usage >/dev/null | head -3
_ Try; blue ' 'rcm-nginx-variables-export; magenta ' '--help; _, ' 'for more information.; _.

# parse-options.sh \
# --with-end-options-double-dash \
# --with-end-options-specific-operand \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# OPERAND=(
# tls-certificate
# )
# EOF
# clear

# parse-options.sh \
# --compact \
# --clean \
# --no-hash-bang \
# --without-end-options-double-dash \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --tls-certificate
# --tls-certificate-key
# )
# EOF
# clear
