#!/bin/bash

RCM_EXTENSION_VERSION=0.18.0-alpha.6

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm-nginx-reload [options]

Options:

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.

Dependency:
   nginx
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm-nginx-reload
____

# Dependency.

# Functions.
sleepExtended() {
    # Menggunakan global variable countdown agar sleep ini dapat di-interupsi.
    # Contoh:
    # ```
    # immediately() {
    #     countdown=0
    # }
    # trap immediately SIGINT
    # sleepExtended 30
    # trap x SIGINT
    # ```
    local timer=$1
    local width=$2
    if [ -z "$width" ];then
        width=80
    fi
    if [ "$timer" -gt 0 ];then
        dikali10=$((timer*10))
        countdown=$dikali10
        _dotLength=$(( ( width * countdown ) / dikali10 ))
        printf "\r\033[K" >&2
        e; printf %"$_dotLength"s | tr " " "." >&2
        printf "\r"
        while [ "$countdown" -ge 0 ]; do
            dotLength=$(( ( width * countdown ) / dikali10 ))
            if [[ ! "$dotLength" == "$_dotLength" ]];then
                _dotLength="$dotLength"
                printf "\r\033[K" >&2
                e; printf %"$dotLength"s | tr " " "." >&2
                printf "\r"
            fi
            countdown=$((countdown - 1))
            sleep .1
        done
    fi
}

# Require, validate, and populate value.
chapter Variable dump.
____

chapter Reload nginx configuration.
__ Cleaning broken symbolic link.
code find /etc/nginx/sites-enabled -xtype l -print -delete
find /etc/nginx/sites-enabled -xtype l -print
find /etc/nginx/sites-enabled -xtype l -delete -print

if nginx -t 2> /dev/null;then
    code nginx -s reload
    nginx -s reload
    # Setelah reload biasanya parent process akan melakukan request http,
    # maka kita perlu sleep
    sleepExtended 3 30
else
    code nginx -t
    nginx -t
    error Terjadi kesalahan konfigurasi nginx. Gagal reload nginx.; x
fi
____

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
