#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.13

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm dig get-info ip-address [options]

Options:
   --fqdn=FQDN
        Fully Qualified Domain Name to be checked.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.

Dependency:
   host
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --reverse) reverse=1; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

if [ -n "$1" ];then
    case "$1" in
        get-ipv4) command="$1"; shift ;;
    esac
fi

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Functions.
get-ipv4() {
    _ip=`wget -T 3 -t 1 -4qO- "http://ip1.dynupdate.no-ip.com/"`
    if [ -n "$_ip" ];then
        echo "$_ip"
    else
        ip addr show | grep -o "inet [0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*"
    fi
}

# Require.
require vendor/ijortengab/bash/functions/array-search.sh

# ------------------------------------------------------------------------------

# Title.
title rcm dig get-info ip-address
____

# Dependency.
require command wget
require command host

# Require, validate, and populate value.
fqdn=
if [ -n "$1" ];then
    fqdn="$1"
fi
ip_address=
if [ -n "$2" ];then
    ip_address="$2"
fi
if [ -z "$fqdn" ];then
    get-ipv4
    exit 0
fi
code 'fqdn="'$fqdn'"'
code 'ip_address="'$ip_address'"'
if [ -z "$ip_address" ];then
    code rcm dig get-info a --domain="$fqdn"
    rcm dig get-info a --domain="$fqdn"
    exit 0
    error "Argument --ip-address required."; x
fi

chapter Variable dump.
fqdn_raw="$fqdn"
code 'fqdn_raw="'$fqdn_raw'"'
code 'fqdn="'$fqdn'"'
code 'ip_address="'$ip_address'"'
tempfile=$(mktemp -p /dev/shm -t rcm-dig-get-info-ip-address.XXXXXX)
____

code host -t A $fqdn
host -t A "$fqdn" > "$tempfile"
while IFS= read line; do e "$line"; _.; done < "$tempfile"
stdout=$(<"$tempfile")
found=
code found="$found"
code fqdn="$fqdn"
address=()
while read line; do
    _ "$line"; _.
    __ Try
    data="${fqdn} is an alias for "
    data_escape=${data//\./\\.}
    __; magenta grep -E --ignore-case '"'"^${data_escape}"'"'; _.
    if grep -q -E --ignore-case "^${data_escape}" <<< "$line";then
        __ Alias ditemukan.
        __; magenta sed -E '"'"s|^${data_escape}(.*)\.$|\1|"'"'; _.
        __ Value of variable '`'\$fqdn'`' diperbarui.
        fqdn=$(echo "$line"| sed -E "s|^${data_escape}(.*)\.$|\1|")
        __; magenta fqdn="$fqdn"; _.
    else
        __ Try
        data="${fqdn} has address "
        data_escape=${data//\./\\.}
        __; magenta grep -E --ignore-case "'""^${data_escape}""'"; _.
        if grep -q -E --ignore-case "^${data_escape}" <<< "$line";then
            __ Get Address
            __; magenta sed -E '"'"s|^${data_escape}(.*)$|\1|"'"'; _.
            address+=($(echo "$line"| sed -E "s|^${data_escape}(.*)$|\1|"))
        fi
    fi
done <<< "$stdout"
____

if ArraySearch "$ip_address" address[@];then
    found=1
fi

chapter Result
rm "$tempfile"
if [ -n "$found" ];then
    result='success'
    if [ -n "$reverse" ];then
        result='error'
    fi
    $result FQDN "$fqdn_raw" has address "$ip_address".
else
    result='error'
    if [ -n "$reverse" ];then
        result='success'
    fi
    $result FQDN "$fqdn_raw" has not address "$ip_address".
    if [ "${#address[@]}" -gt 0 ];then
        for each in "${address[@]}";do
            _ FQDN "$fqdn_raw" has address "$each".; _.
        done
    fi
fi

[ "$result" == error ] && x
____

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --reverse
# )
# VALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
