#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.7

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm-mariadb-user-autocreate [options]

Options:
   --db-user *
        The database user.
   --db-user-password *
        The database user password.
   --db-user-host
        Host of the the database user come from. Default value: localhost.

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.

Dependency:
   mysql
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --db-user=*) db_user="${1#*=}"; shift ;;
        --db-user) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then db_user="$2"; shift; fi; shift ;;
        --db-user-host=*) db_user_host="${1#*=}"; shift ;;
        --db-user-host) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then db_user_host="$2"; shift; fi; shift ;;
        --db-user-password=*) db_user_password="${1#*=}"; shift ;;
        --db-user-password) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then db_user_password="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm-mariadb-user-autocreate
____

# Dependency.

# Requirement, validate, and populate value.
chapter Variable dump.
if [ -z "$db_user" ];then
    error "Argument --db-user required."; x
fi
code 'db_user="'$db_user'"'
if [ -z "$db_user_password" ];then
    error "Argument --db-user-password required."; x
fi
code 'db_user_password="'$db_user_password'"'
if [ -z "$db_user_host" ];then
    db_user_host=localhost
fi
code 'db_user_host="'$db_user_host'"'
____

chapter Mengecek database user '`'$db_user'`'.
code mysql --silent --skip-column-names -e '"''select COUNT(*) FROM mysql.user WHERE user = '"'""$db_user""'"' and host = '"'""$db_user_host""'"';''"'
msg=$(mysql --silent --skip-column-names -e "select COUNT(*) FROM mysql.user WHERE user = '$db_user' and host = '$db_user_host';")
notfound=
if [ $msg -gt 0 ];then
    __ Database user ditemukan.
else
    __ Database user tidak ditemukan.
    notfound=1
fi
____

if [ -n "$notfound" ];then
    chapter Membuat database user.
    code 'mysql -e ''"''create user '"'""${db_user}""'"'@'"'""${db_user_host}""'"' identified by '"'""${db_user_password}""'"';''"'
    mysql -e "create user '${db_user}'@'${db_user_host}' identified by '${db_user_password}';"
    msg=$(mysql --silent --skip-column-names -e "select COUNT(*) FROM mysql.user WHERE user = '$db_user' and host = '$db_user_host';")
    if [ $msg -gt 0 ];then
        __; green Database user ditemukan.; _.
    else
        __; red Database user tidak ditemukan; x
    fi
    ____
elif [ "$db_user_host" == localhost ];then
    chapter Mengecek password database user.
    u="$db_user"
    p="$db_user_password"
    code 'mysql --defaults-extra-file=<(printf ''"''[client]\nuser = %s\npassword = %s''"'' ''"'"$u"'"'' ''"'"$p"'"'') -h ''"'"$db_user_host"'"'' -r -N -s -e ''"''"'
    if mysql --defaults-extra-file=<(printf "[client]\nuser = %s\npassword = %s" "$u" "$p") -h "$db_user_host" -r -N -s -e "";then
        __ Database user password valid.
    else
        __; red Database user password tidak valid; x
    fi
    ____
fi

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --db-user
# --db-user-host
# --db-user-password
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# EOF
# clear
