#!/bin/bash

[ -f "$0" ] || { echo "Cannot run as dot command." >&2; kill -INT $$; }

# Define variables and constants.
RCM_EXTENSION_VERSION=0.19.0-alpha.14

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm plugin get-socket --interactive
       rcm plugin get-socket <interface> <plugin-name> <method>

Options:
   --interactive
        Show dialog to fill miss arguments.

Other options:
   --hide-title
        Hide title.
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --hide-title) hide_title=1; shift ;;
        --interactive) interactive=1; shift ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Functions.
populateList() {
    list=()
    while IFS= read -r each;do
        list+=("$each")
    done <<< `ls -1 "$prefix"`
}

# ------------------------------------------------------------------------------

if [ -z "$hide_title" ];then
    title rcm plugin get-socket
    ____
fi

# Dependency.
require vendor/ijortengab/rcm/functions/base/print-select-dialog.sh
require vendor/ijortengab/bash/functions/array-search.sh

# Requirement, validate, and populate value.
# chapter Variable dump.
command="rcm plugin get-socket"
interface="$1"
plugin_name="$2"
method="$3"
prefix="$RCM_LIB"/interfaces
list=()
if [ -z "$interface" ];then
    [ -n "$help" ] && { usage; exit 0; }
    [ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }
fi
# ____

while IFS= read -r each;do
    find="${prefix}/"; replace=
    each="${each/#$find/$replace}"
    find=/implements; replace=
    each="${each/%$find/$replace}"
    list+=("$each")
done <<< `find -L "$prefix" -type d -iname implements`

if [ -z "$interface" ];then
    if [ -n "$interactive" ];then
        parameter=interface
        parameter_plural=interfaces
        _; _.
        _ Select the interface of plugin.; _.
        print-select-dialog list[@] "$parameter" "$parameter_plural"
        interface="$value"
        command+=" ${interface}"
        _; _.
        _; _, Execute' '; magenta $command '--interactive'; _.
    else
        error Argument '<interface>' is required or activate the --interactive option.; x
    fi
else
    if ! ArraySearch "$interface" list[@];then
        error The interface of plugin is unknown: '`'"$interface"'`'.; x
    fi
    command+=" ${interface}"
fi
prefix+="/${interface}"
if [ -z "$plugin_name" ];then
    if [ -n "$interactive" ];then
        prefix+="/implements"
        populateList
        parameter=plugin
        parameter_plural=plugins
        _; _.
        _ Select plugin which implements '`'"$interface"'`' interface.; _.
        print-select-dialog list[@] "$parameter" "$parameter_plural"
        plugin_name="$value"
        command+=" ${plugin_name}"
        _; _.
        _; _, Execute' '; magenta $command '--interactive'; _.
    else
        error Argument '<plugin-name>' is required or activate the --interactive option.; x
    fi
else
    prefix+="/implements"
    populateList
    if ! ArraySearch "$plugin_name" list[@];then
        error The plugin name is unknown: '`'"$plugin_name"'`'.; x
    fi
    command+=" ${plugin_name}"
fi
prefix+="/${plugin_name}"
if [ -z "$method" ];then
    if [ -n "$interactive" ];then
        prefix+="/methods"
        populateList
        parameter=method
        parameter_plural=method
        _; _.
        _ Select method for '`'"$plugin_name"'`' plugin.; _.
        print-select-dialog list[@] "$parameter" "$parameter_plural"
        method="$value"
        command+=" ${method}"
        _; _.
        _; _, Execute' '; magenta $command ; _.
    else
        error Argument '<method>' is required or activate the --interactive option.; x
    fi
else
    prefix+="/methods"
    populateList
    if ! ArraySearch "$method" list[@];then
        error The method name is unknown: '`'"$method"'`'.; x
    fi
fi

prefix+="/${method}"
if [ -n "$help" ];then
    if [ -f "$prefix/help.txt" ];then
        cat "$prefix/help.txt"
    fi
elif [ -n "$version" ];then
    echo $RCM_EXTENSION_VERSION; exit 0;
else
    echo "$prefix/socket.sh"
fi

exit 0

# parse-options.sh \
# --with-end-options-double-dash \
# --with-end-options-specific-operand \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --hide-title
# --interactive
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# OPERAND=(
# )
# EOF
# clear
