#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.5

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm-mariadb-setup-project-database [options]

Options:
   --project-name *
        Set the project name. This should be in machine name format.
   --project-parent-name
        Set the project parent name. The parent is not have to exists before.
   --db-suffix-name
        The database suffix name.
   --without-autocreate-db ^
        Skip autocreate database. Default to --with-autocreate-db.

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.

Environment Variables.
   MARIADB_PREFIX_MASTER
        Default to /usr/local/share/mariadb
   MARIADB_USERS_CONTAINER_MASTER
        Default to users

Dependency:
   mysql
   pwgen
   rcm-mariadb-database-autocreate
   rcm-mariadb-user-autocreate
   rcm-mariadb-assign-grant-all
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --db-suffix-name=*) db_suffix_name="${1#*=}"; shift ;;
        --db-suffix-name) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then db_suffix_name="$2"; shift; fi; shift ;;
        --project-name=*) project_name="${1#*=}"; shift ;;
        --project-name) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then project_name="$2"; shift; fi; shift ;;
        --project-parent-name=*) project_parent_name="${1#*=}"; shift ;;
        --project-parent-name) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then project_parent_name="$2"; shift; fi; shift ;;
        --with-autocreate-db) autocreate_db=1; shift ;;
        --without-autocreate-db) autocreate_db=0; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm-mariadb-setup-project-database
____

# Dependency.

# Functions.
databaseCredential() {
    if [ -f "${MARIADB_PREFIX_MASTER}/${MARIADB_USERS_CONTAINER_MASTER}/${db_user}" ];then
        local DB_USER DB_USER_PASSWORD
        . "${MARIADB_PREFIX_MASTER}/${MARIADB_USERS_CONTAINER_MASTER}/${db_user}"
        db_user=$DB_USER
        db_user_password=$DB_USER_PASSWORD
    else
        mkdir -p "${MARIADB_PREFIX_MASTER}/${MARIADB_USERS_CONTAINER_MASTER}"
        db_user_password=$(pwgen -s 32 -1)
        cat << EOF > "${MARIADB_PREFIX_MASTER}/${MARIADB_USERS_CONTAINER_MASTER}/${db_user}"
DB_USER=$db_user
DB_USER_PASSWORD=$db_user_password
EOF
        chmod 0500 "${MARIADB_PREFIX_MASTER}/${MARIADB_USERS_CONTAINER_MASTER}"
        chmod 0400 "${MARIADB_PREFIX_MASTER}/${MARIADB_USERS_CONTAINER_MASTER}/${db_user}"
    fi
}

# Requirement, validate, and populate value.
chapter Variable dump.
[ -n "$fast" ] && isfast=' --fast' || isfast=''
if [ -z "$project_name" ];then
    error "Argument --project-name required."; x
fi
code 'project_name="'$project_name'"'
code 'project_parent_name="'$project_parent_name'"'
code 'db_suffix_name="'$db_suffix_name'"'
db_user="$project_name"
db_user_host="localhost"
db_name="$project_name"
[ -n "$project_parent_name" ] && {
    db_user="$project_parent_name"
    db_name="${project_parent_name}__${project_name}"
}
[ -n "$db_suffix_name" ] && {
    db_name="${db_name}__${db_suffix_name}"
}
code 'db_user="'$db_user'"'
code 'db_user_host="'$db_user_host'"'
code 'db_name="'$db_name'"'
MARIADB_PREFIX_MASTER=${MARIADB_PREFIX_MASTER:=/usr/local/share/mariadb}
code 'MARIADB_PREFIX_MASTER="'$MARIADB_PREFIX_MASTER'"'
MARIADB_USERS_CONTAINER_MASTER=${MARIADB_USERS_CONTAINER_MASTER:=users}
code 'MARIADB_USERS_CONTAINER_MASTER="'$MARIADB_USERS_CONTAINER_MASTER'"'
[ -z "$autocreate_db" ] && autocreate_db=1
[ "$autocreate_db" == 0 ] && autocreate_db=
____

chapter Mengecek database credentials: '`'$MARIADB_PREFIX_MASTER/$MARIADB_USERS_CONTAINER_MASTER/$db_user'`'.
databaseCredential
if [[ -z "$db_user" ]];then
    __; red Informasi credentials tidak lengkap: '`'$MARIADB_PREFIX_MASTER/$MARIADB_USERS_CONTAINER_MASTER/$db_user'`'.; x
else
    code db_user="$db_user"
fi
if [[ -z "$db_user_password" ]];then
    __; red Informasi credentials tidak lengkap: '`'$MARIADB_PREFIX_MASTER/$MARIADB_USERS_CONTAINER_MASTER/$db_user'`'.; x
else
    code db_user_password="$db_user_password"
fi
____

INDENT+="    " \
rcm-mariadb-user-autocreate $isfast \
    --db-user="$db_user" \
    --db-user-host="$db_user_host" \
    --db-user-password="$db_user_password" \
    ; [ ! $? -eq 0 ] && x
if [ -n "$autocreate_db" ];then
    INDENT+="    " \
    rcm-mariadb-database-autocreate $isfast \
        --db-name="$db_name" \
        && INDENT+="    " \
    rcm-mariadb-assign-grant-all $isfast \
        --db-name="$db_name" \
        --db-user="$db_user" \
        --db-user-host="$db_user_host" \
        --database-exists-sure \
        --user-exists-sure \
        ; [ ! $? -eq 0 ] && x
fi

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --project-name
# --project-parent-name
# --db-suffix-name
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
    # 'long:--with-autocreate-db,parameter:autocreate_db'
    # 'long:--without-autocreate-db,parameter:autocreate_db,flag_option:reverse'
# )
# EOF
# clear
