#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.1

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm-mariadb-database-autocreate [options]

Options:
   --db-name *
        The database name.

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.

Dependency:
   mysql
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --db-name=*) db_name="${1#*=}"; shift ;;
        --db-name) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then db_name="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm-mariadb-database-autocreate
____

# Dependency.

# Requirement, validate, and populate value.
chapter Variable dump.
if [ -z "$db_name" ];then
    error "Argument --db-name required."; x
fi
code 'db_name="'$db_name'"'
____

chapter Mengecek database '`'$db_name'`'.
code 'mysql --silent --skip-column-names -e ''"''select schema_name from information_schema.schemata where schema_name = '"'""$db_name""'"'"'
msg=$(mysql --silent --skip-column-names -e "select schema_name from information_schema.schemata where schema_name = '$db_name'")
notfound=
if [[ $msg == $db_name ]];then
    __ Database ditemukan.
else
    __ Database tidak ditemukan.
    notfound=1
fi
____

if [ -n "$notfound" ];then
    chapter Membuat database.
    code 'mysql -e ''"''create database '"$db_name"' character set utf8 collate utf8_general_ci;''"'
    mysql -e "create database $db_name character set utf8 collate utf8_general_ci;"
    code 'mysql --silent --skip-column-names -e ''"''select schema_name from information_schema.schemata where schema_name = '"'""$db_name""'"'"'
    msg=$(mysql --silent --skip-column-names -e "select schema_name from information_schema.schemata where schema_name = '$db_name'")
    if [[ $msg == $db_name ]];then
        __; green Database ditemukan.; _.
    else
        __; red Database tidak ditemukan.; x
    fi
    ____
fi

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --db-name
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# EOF
# clear
