#!/bin/bash

[ -f "$0" ] || { echo "Cannot run as dot command." >&2; kill -INT $$; }

# Define variables and constants.
RCM_EXTENSION_VERSION=0.19.0-alpha.13

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm php add pool [options]

Options:
   --php-version=PHP_VERSION
        Set the version of PHP FPM.
        Values available from command: rcm(php list available --fpm).
   --web-server=HTTP
        Select web server to fill the listen.owner directive in config.
        The listen.owner should be set to the user that the web server
        runs as.
        Values available from command: rcm(plugin list web-server).
   --section=SECTION
        Set the section name.
   --php-fpm-user=[USER]
        Set the Unix user that used by PHP FPM.
        Values available from command: rcm(system list user regular), or others.
        If the user does not exists, it will be autocreate as reguler user.
   --file=[FILENAME]
        Set the name of file config. The filename should has the .conf extension
        to enabled by PHP-FPM daemon but you free to ignore it.
        If omit, it will use the section name with .conf extension or the main
        configuration file.
   --config-line=[LINE]...
        Additional config in the pool.

Other Options (For expert only):
   --without-autocreate-user
        Skip autocreate Unix user while config is created.
        Default to --with-autocreate-user.
        Useful if you prefer terminate process than autocreate the user.

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --config-line=*) config_line+=("${1#*=}"); shift ;;
        --config-line) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then config_line+=("$2"); shift; fi; shift ;;
        --file=*) file="${1#*=}"; shift ;;
        --file) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then file="$2"; shift; fi; shift ;;
        --php-fpm-user=*) php_fpm_user="${1#*=}"; shift ;;
        --php-fpm-user) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then php_fpm_user="$2"; shift; fi; shift ;;
        --php-version=*) php_version="${1#*=}"; shift ;;
        --php-version) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then php_version="$2"; shift; fi; shift ;;
        --section=*) section="${1#*=}"; shift ;;
        --section) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then section="$2"; shift; fi; shift ;;
        --with-autocreate-user) autocreate_user=1; shift ;;
        --without-autocreate-user) autocreate_user=0; shift ;;
        --web-server=*) web_server="${1#*=}"; shift ;;
        --web-server) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then web_server="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

if [ -n "$RCM_VERBOSE" ];then
    verbose="$RCM_VERBOSE"
fi
[[ -z "$verbose" || "$verbose" -lt 1 ]] && quiet=1 || quiet=
[[ "$verbose" -gt 0 ]] && loud=1
[[ "$verbose" -gt 1 ]] && loud=1 && louder=1
[[ "$verbose" -gt 2 ]] && loud=1 && louder=1 && debug=1

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm php add pool
____

# Dependency.
require command nginx
require vendor/ijortengab/rcm/functions/utility/backup-file.sh
require vendor/ijortengab/rcm/functions/classes/rcm-file.sh
require vendor/ijortengab/rcm/functions/utility/php-pool-write.sh

# Requirement, validate, and populate value.
chapter Variable dump.
code 'command="'$command'"'
if [ -z "$php_version" ];then
    error "Argument --php-version required."; x
fi
code 'php_version="'$php_version'"'
if [ -z "$php_fpm_user" ];then
    error "Argument --php-fpm-user required."; x
fi
code 'php_fpm_user="'$php_fpm_user'"'
if [ -z "$section" ];then
    error "Argument --section required."; x
fi
code 'section="'$section'"'
# Rename variable.
section_name="$section"
code 'section_name="'$section_name'"'
if [ -z "$file" ];then
    file="$section_name"
    file+=".conf"
fi
code 'file="'$file'"'
# Rename variable.
config_file="$file"
code 'config_file="'$config_file'"'
find='[php-version]'
replace="$php_version"
[ -z "$autocreate_user" ] && autocreate_user=1
[ "$autocreate_user" == 0 ] && autocreate_user=
code 'config_line=('"${config_line[@]}"')'
e; magenta 'config_line=('
first=1
for each in "${config_line[@]}";do
    if [ -n "$first" ];then
        magenta "'""$each""'";
        first=
    else
        magenta " '""$each""'";
    fi
done
magenta ')'; _.
____

chapter Mengecek file '*.conf' yang mengandung section '`'$section_name'`'
found=
found_file=
while read file; do
    # Ternyata lebih cepat menggunakan grep.
    # if php -r "$php" is_exists "$file" "$section_name";then
        # found=1
        # found_file="$file"
        # break;
    # fi
    if grep -q -F "[$section_name]" "$file";then
        found=1
        found_file="$file"
        break;
    fi
done <<< `ls "$PHP_FPM_POOL_DIRECTORY"/*.conf`

if [ -n "$found" ];then
    __ Ditemukan section '`'"$section_name"'`' pada file "$found_file"
else
    __ Tidak ditemukan section '`'"$section_name"'`'.
fi
____

restart=
if [ -n "$found" ];then
    if [ "${#config_line[@]}" -gt 0 ];then
        config_lines=
        for each in "${config_line[@]}";do
            config_lines+="$each"$'\n'
        done

        chapter Mengecek informasi file config.
        path="$found_file"
        code path='"'$path'"'
        filename="${found_file##*/}"
        reference="$(php -r "$php" serialized_ini_string <<< "$config_lines")"
        is_different=
        if php -r "$php" is_different "$path" "$reference";then
            is_different=1
            __ Diperlukan modifikasi file '`'$filename'`'.
        else
            __ File '`'$filename'`' tidak ada perubahan.
        fi
        ____

        if [ -n "$is_different" ];then
            chapter Memodifikasi file '`'$filename'`'.
            __ Backup file "$filename"
            backup-file copy "$path"
            php -r "$php" save "$path" "$reference" "$section_name"
            if php -r "$php" is_different "$path" "$reference";then
                __; red Modifikasi file '`'$filename'`' gagal.; x
            else
                __; green Modifikasi file '`'$filename'`' berhasil.; _.
                restart=1
            fi
            ____
        fi
    fi
    [ -n "$debug" ] && { while IFS= read -r line; do e "$line"; _.; done < "$found_file" ; _. ; }
else
    default_config="$(php -r "echo serialize([
        'user' => '$php_fpm_user',
        'group' => '$php_fpm_user',
        'listen' => '/run/php/php${php_version}-fpm-${section_name}.sock',
        'listen.owner' => '$nginx_user',
        'listen.group' => '$nginx_user',
        'pm' => 'dynamic',
        'pm.max_children' => '5',
        'pm.start_servers' => '2',
        'pm.min_spare_servers' => '1',
        'pm.max_spare_servers' => '3',
    ]);")"

    additional_config=
    if [ "${#config_line[@]}" -gt 0 ];then
        config_lines=
        for each in "${config_line[@]}";do
            config_lines+="$each"$'\n'
        done
        additional_config="$(php -r "$php" serialized_ini_string <<< "$config_lines")"
    fi

    chapter Membuat file PHP-FPM config.
    config_file="${PHP_FPM_POOL_DIRECTORY}/${config_file}"
    code 'config_file="'$config_file'"'
    if [ -f "$config_file" ];then
        __ Backup file "$config_file".
        backup-file move "$config_file"
    fi
    __ Membuat file '`'"$config_file"'`'.
    php -r "$php" create "$config_file" "$section_name" "$default_config" "$additional_config"
    rcm-file "$config_file" mustExists
    found_file="$config_file"
    restart=1
    ____
fi

found=1
if [ -n "$restart" ];then
    chapter Mengecek PHP-FPM User.
    code id -u '"'$php_fpm_user'"'
    if id "$php_fpm_user" >/dev/null 2>&1; then
        __ User '`'$php_fpm_user'`' found.
    else
        __ User '`'$php_fpm_user'`' not found.;
        found=
    fi
    ____
fi
if [ -z "$found" ];then
    chapter Membuat Unix user.
    if [ -n "$autocreate_user" ];then
        code adduser $php_fpm_user --disabled-password --gecos "''"
        adduser "$php_fpm_user" --disabled-password --gecos ''
    else
        __ Flag --without-autocreate-user ditemukan.
        error User tidak dapat dibuat; x
    fi
    ____
fi
if [ -n "$restart" ];then
    chapter Restart PHP-FPM configuration.
    code /etc/init.d/php${php_version}-fpm restart
    /etc/init.d/php${php_version}-fpm restart 2>&1 &>/dev/null
    ____
fi

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --with-end-options-specific-operand \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --php-version
# --php-fpm-user
# --section
# --file
# --web-server
# )
# MULTIVALUE=(
# --config-line
# )
# FLAG_VALUE=(
# )
# CSV=(
    # 'long:--with-autocreate-user,parameter:autocreate_user'
    # 'long:--without-autocreate-user,parameter:autocreate_user,flag_option:reverse'
# )
# OPERAND=(
# )
# EOF
# clear
