#!/bin/bash

source /usr/local/rcm/$RCM_VERSION/functions/common/echo.sh
source /usr/local/rcm/$RCM_VERSION/functions/common/echo-wrap.sh
source /usr/local/rcm/$RCM_VERSION/functions/common/echo-wrap-color.sh
source /usr/local/rcm/$RCM_VERSION/functions/common/echo-wrap-list.sh
source /usr/local/rcm/$RCM_VERSION/functions/common/echo-wrap-multiline.sh
source /usr/local/rcm/$RCM_VERSION/functions/array/array-search.sh
source /usr/local/rcm/$RCM_VERSION/functions/array/array-shift.sh
source /usr/local/rcm/$RCM_VERSION/functions/array/array-remove.sh
source /usr/local/rcm/$RCM_VERSION/functions/array/array-remove-all.sh

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
_n=
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help|-h) help=1; shift ;;
        --version|-V) version=1; shift ;;
        --interactive|-i) interactive=1; shift ;;
        --non-interactive) interactive=0; shift ;;
        --slow|-s) fast=0; shift ;;
        --timer|-t) timer=1; shift ;;
        --verbose|-v) verbose="$((verbose+1))"; shift ;;
        --yes|-y) autoyes=1; shift ;;
        -[^-]*) _new_arguments+=("$1"); shift ;;
        --)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        *)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
    esac
done
set -- "${_new_arguments[@]}"
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        -[^-]*) OPTIND=1
            while getopts ":hVistvy" opt; do
                case $opt in
                    h) help=1 ;;
                    V) version=1 ;;
                    i) interactive=1 ;;
                    s) fast=0 ;;
                    t) timer=1 ;;
                    v) verbose="$((verbose+1))" ;;
                    y) autoyes=1 ;;
                esac
            done
            _n="$((OPTIND-1))"
            _n=${!_n}
            shift "$((OPTIND-1))"
            if [[ "$_n" == '--' ]];then
                while [[ $# -gt 0 ]]; do
                    case "$1" in
                        *) _new_arguments+=("$1"); shift ;;
                    esac
                done
            fi
            ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        *)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments
unset _n

# If not set in argument, try load from environment.
[ -z "$fast" ] && fast="$RCM_FAST"
[ -z "$verbose" ] && verbose="$RCM_VERBOSE"
[ -z "$interactive" ] && interactive="$RCM_INTERACTIVE"

# Boolean default to TRUE.
[ -z "$fast" ] && fast=1; [ "$fast" == 0 ] && fast=

# Copy to RCM variable then unset.
RCM_TIMER="$timer"; unset timer

# Verbosity.
RCM_QUIET=; RCM_LOUD=; RCM_LOUDER=; RCM_DEBUG=;
[[ -z "$verbose" || "$verbose" -lt 1 ]] && RCM_QUIET=1 || RCM_QUIET=
[[ "$verbose" -gt 0 ]] && RCM_LOUD=1
[[ "$verbose" -gt 1 ]] && RCM_LOUD=1 && RCM_LOUDER=1
[[ "$verbose" -gt 2 ]] && RCM_LOUD=1 && RCM_LOUDER=1 && RCM_DEBUG=1

# Define variables and constants.
RCM_DELAY=${RCM_DELAY:=.5}; [ -n "$fast" ] && unset RCM_DELAY
RCM_INDENT='    '; [ "$(tput cols)" -le 80 ] && RCM_INDENT='  '
[ -z "$RCM_LOG" ] && { [ "$EUID" -ne 0 ] && RCM_LOG=$HOME/rcm.log || RCM_LOG=/var/log/rcm.log; }
tempfile=

# Functions. Help and Version.
printVersion() {
    echo $RCM_VERSION
}
printHelp() {
    title Rapid Construct Massive
    _ 'Version '; yellow $RCM_VERSION; _.
    _ 'URL '; yellow git.io/rcm; _.
    _.
cat << EOF
Usage: rcm [options]
       rcm <extension> [options]
       rcm [options] <extension> [options]

Options:
   --version
        Print version of this script.
   --help
        Show this help.
   --slow, -s
        Add delay every subtask.
   --yes, -y
        Skip every question and use the default value even the default value is equivalent to negate.
   --interactive, -i
        Display the user input if needed.
   --non-interactive
        Run without ever asking for user input. Default action.
   --verbose, -v
        Verbose mode. Causes rcm to print debugging messages about its progress.
        Multiple -v options increase the verbosity.
        The maximum is 3.
EOF
}

# Help and Version.
[ -n "$help" ] && { printHelp; exit 1; }
[ -n "$version" ] && { printVersion; exit 1; }

if [ -z "$1" ];then
    printHelp >/dev/null | head -3
    _ Try; blue ' 'rcm; magenta ' '--help; _, ' 'for more information.; _.
    exit 0
fi

extension="$1"; shift
command="rcm-${extension}"

# Title.
title rcm
____

# Functions.
read-true() {
    _; _.
    __;  _, '['; yellow Enter; _, ']'; _, ' '; yellow Y; _, 'es and continue.'; _.
    __;  _, '['; yellow Esc; _, ']'; _, ' '; yellow N; _, 'o and skip.'; _.
    boolean=
    _; _.
    __ Press the yellow key to select.
    while true; do
        __; read -rsn 1 -p "Select: " char
        if [ -z "$char" ];then
            char=y
        fi
        case $char in
            y|Y) echo "$char" >&2; boolean=1; break;;
            n|N) echo "$char" >&2; break ;;
            $'\33') echo "n" >&2; break ;;
            *) echo >&2
        esac
    done
}
read-false() {
    _; _.
    __;  _, '['; yellow Enter; _, ']'; _, ' '; yellow N; _, 'o and skip.'; _.
    __;  _, '['; yellow Y; _, ']'; _, ' '; yellow Y; _, 'es and continue.'; _.
    boolean=
    _; _.
    __ Press the yellow key to select.
    while true; do
        __; read -rsn 1 -p "Select: " char
        if [ -z "$char" ];then
            char=n
        fi
        case $char in
            y|Y) echo "$char" >&2; boolean=1; break;;
            n|N) echo "$char" >&2; break ;;
            *) echo >&2
        esac
    done
}
printBackupDialog() {
    _; _.
    echo-wrap-color "Restore the value: <yellow>$backup_value</yellow>. Would you like to use that value?"
    read-true
    if [ -n "$boolean" ];then
        _; _.
        value="$backup_value";
        if [ -n "$is_flag" ];then
            echo-wrap-color "Argument <magenta>${parameter}</magenta> added with value <yellow>$value</yellow> which is restored." green
        else
            echo-wrap-color "Argument <magenta>${parameter}</magenta> filled with value <yellow>$value</yellow> which is restored." green
        fi
    fi
}
printBackupFlagDialog() {
    _; _.
    echo-wrap "This argument has been added before. Would you like to restore this argument?"
    read-true
    if [ -n "$boolean" ];then
        _; _.
        echo-wrap-color "Argument <magenta>${parameter}</magenta> added which is restored." green
    fi
}
printHistoryDialog() {
    local count_max=$(wc -l <<< "$history_value")
    if [ $count_max -gt 9 ];then
        count_max=9
    fi
    unset count
    declare -i count
    count=0
    _; _.
    echo-wrap 'There are values available from history.'

    while read opt; do
        count+=1
        __; _, '['; yellow $count; _, ']'; _, ' '; _, "$opt"; _.
    done <<< "$history_value"
    _; _.
    __;  _, '['; yellow Enter; _, ']'; _, ' '; yellow S; _, 'kip and continue.'; _.
    _; _.
    __ Press the yellow key to select.
    while true; do
        __; read -rsn 1 -p "Select: " char;
        if [ -z "$char" ];then
            char=s
        fi
        case $char in
            s|S) echo "$char" >&2; break ;;
            [1-$count_max])
                echo "$char" >&2
                value=$(sed -n ${char}p <<< "$history_value")
                save_history=
                break ;;
            *) echo >&2
        esac
    done
}
printSelectDialog() {
    declare -i count
    declare -i new_line
    local source=("${!1}")
    local what="$2"
    local each reference_key
    if [ -z "$what" ];then
        what=value
        if [ "${#source[@]}" -gt 1 ];then
            what=values
        fi
    fi
    _; _.
    words_array=("${source[@]}")
    echo-wrap-list "Available ${what}:"
    _; _.
    __; _, '['; yellow Enter; _, ']'; _, ' '; yellow T; _, 'ype the value.'; _.
    __; _, '['; yellow Backspace; _, ']'; _, ' '; yellow S; _, 'witch to select list.'; _.
    if [ -z "$is_required" ];then
        __; _, '['; yellow Esc; _, ']'; _, ' '; yellow L; _, 'eave blank and skip.'; _.
    fi
    _; _.
    __ Press the yellow key to select.
    select_mode=
    local type_mode=
    local skip=
    while true; do
        __; read -rsn 1 -p "Select: " char;
        if [ -z "$char" ];then
            char=t
        fi
        if [ -n "$is_required" ];then
            case $char in
                t|T) type_mode=1; echo "$char" >&2; break ;;
                s|S) select_mode=1; echo "$char" >&2; break ;;
                $'\177') select_mode=1; echo "s" >&2; break ;;
                *) echo >&2; new_line+=1
            esac
        else
            case $char in
                t|T) type_mode=1; echo "$char" >&2; break ;;
                s|S) select_mode=1; echo "$char" >&2; break ;;
                $'\177') select_mode=1; echo "s" >&2; break ;;
                $'\33') skip=1; echo "l" >&2; break ;;
                l|L) skip=1; echo "$char" >&2; break ;;
                *) echo >&2; new_line+=1
            esac
        fi
    done
    # Credit: https://stackoverflow.com/questions/5861428/bash-script-erase-previous-line
    PREVIOUS_LINE=5
    if [ -z "$is_required" ];then
        PREVIOUS_LINE=$((PREVIOUS_LINE+1))
    fi
    if [[ -n "$select_mode" ]];then
        PREVIOUS_LINE=$((PREVIOUS_LINE+WRAP_LINE+1+new_line))
        for ((i = 0 ; i < $PREVIOUS_LINE ; i++)); do
            printf '\e[A\e[K' >&2
        done
        __ "Available ${what}:"
        for ((i = 0 ; i < ${#source[@]} ; i++)); do
            count+=1
            if [ $count -lt 10 ];then
                __; _, '['; yellow $count; _, ']'; _, ' '; _, "${source[$i]}"; _.
            else
                __; _, '['$count']' "${source[$i]}"; _.
            fi
        done
        _; _.
        __; _, '['; yellow Enter; _, ']'; _, ' '; _, 'Type the '; yellow N; _, 'umber key.'; _.
        if [ -z "$is_required" ];then
            __; _, '['; yellow Esc; _, ']'; _, ' '; yellow L; _, 'eave blank and skip.'; _.
        fi
        _; _.
        __ Press the yellow key to select.
        count_max="${#source[@]}"
        if [ $count_max -gt 9 ];then
            count_max=9
        fi
        while true; do
            __; read -rsn 1 -p "Select: " char;
            if [ -z "$char" ];then
                char=n
            fi
            case $char in
                n|N) echo "$char" >&2; break ;;
                [1-$count_max])
                    echo "$char" >&2
                    i=$((char - 1))
                    value="${source[$i]}"
                    break ;;
                *)
                    if [ -n "$is_required" ];then
                        echo >&2
                    else
                        case $char in
                            $'\33') skip=1; echo "l" >&2; break ;;
                            l|L) skip=1; echo "$char" >&2; break ;;
                            *) echo >&2
                        esac
                    fi
            esac
        done
        if [[ -z "$skip" ]];then
            if [ -z "$value" ];then
                _; _.
            fi
            until [ -n "$value" ];do
                __; read -p "Type the number: " value
                if [[ $value =~ [^0-9] ]];then
                    value=
                    __; red Please type one of available number.;_.
                fi
                if [[ $value =~ ^0 ]];then
                    value=
                    __; red Please type one of available number.;_.
                fi
                if [ -n "$value" ];then
                    value=$((value - 1))
                    value="${source[$value]}"
                    if [ -z "$value" ];then
                        __; red Please type one of available number.;_.
                    fi
                fi
            done
            _; _.
            echo-wrap-color "Argument <magenta>${parameter}</magenta> filled with value <yellow>$value</yellow> which is selected from the list." green
        fi
    fi
    if [[ -n "$type_mode" ]];then
        _; _.
    fi
    while true; do
        if [ -n "$value" ];then
            ArraySearch "$value" source[@]
            reference_key="$_return"; unset _return; # Clear.
            if [ -n "$reference_key" ];then
                break
            else
                __; red Please type one of available values.;_.
                value=
            fi
        else
            if [ -n "$is_required" ];then
                __; read -p "Type the value: " value
            elif [ -z "$skip" ];then
                __; read -p "Type the value or leave blank to skip: " value
                if [ -z "$value" ];then
                    break
                fi
            else
                break
            fi
        fi
    done
}
printSelectOtherDialog() {
    declare -i count
    declare -i new_line
    local source=("${!1}")
    local what="$2"
    local each reference_key
    if [ -z "$what" ];then
        what=value
        if [ "${#source[@]}" -gt 1 ];then
            what=values
        fi
    fi
    _; _.
    words_array=("${source[@]}")
    words_array+=(other)
    echo-wrap-list "Available ${what}:"
    _; _.
    __; _, '['; yellow Enter; _, ']'; _, ' '; yellow T; _, 'ype the value.'; _.
    __; _, '['; yellow Backspace; _, ']'; _, ' '; yellow S; _, 'witch to select list.'; _.
    if [ -z "$is_required" ];then
        __; _, '['; yellow Esc; _, ']'; _, ' '; yellow L; _, 'eave blank and skip.'; _.
    fi
    _; _.
    __ Press the yellow key to select.
    local select_mode=
    local type_mode=
    local skip=
    while true; do
        __; read -rsn 1 -p "Select: " char;
        if [ -z "$char" ];then
            char=t
        fi
        case $char in
            t|T) type_mode=1; echo "$char" >&2; break ;;
            s|S) select_mode=1; echo "$char" >&2; break ;;
            $'\177') select_mode=1; echo "s" >&2; break ;;
            *)
                if [ -n "$is_required" ];then
                    echo >&2; new_line+=1
                else
                    case $char in
                        $'\33') skip=1; echo "l" >&2; break ;;
                        l|L) skip=1; echo "$char" >&2; break ;;
                        *) echo >&2; new_line+=1
                    esac
                fi
        esac
    done
    # Credit: https://stackoverflow.com/questions/5861428/bash-script-erase-previous-line
    PREVIOUS_LINE=5
    if [ -z "$is_required" ];then
        PREVIOUS_LINE=$((PREVIOUS_LINE+1))
    fi
    if [[ -n "$select_mode" ]];then
        PREVIOUS_LINE=$((PREVIOUS_LINE+WRAP_LINE+1+new_line))
        for ((i = 0 ; i < $PREVIOUS_LINE ; i++)); do
            printf '\e[A\e[K' >&2
        done
        __ Available values:
        for ((i = 0 ; i < ${#source[@]} ; i++)); do
            count+=1
            if [ $count -lt 10 ];then
                __; _, '['; yellow $count; _, ']'; _, ' '; _, "${source[$i]}"; _.
            else
                __; _, '['$count']' "${source[$i]}"; _.
            fi
        done
        _; _.
        __; _, '['; yellow Enter; _, ']'; _, ' '; _, 'Type the '; yellow N; _, 'umber key.'; _.
        __; _, '['; yellow Backspace; _, ']'; _, ' '; _, 'Switch to '; yellow T; _, 'ype other value.'; _.
        if [ -z "$is_required" ];then
            __; _, '['; yellow Esc; _, ']'; _, ' '; yellow L; _, 'eave blank and skip.'; _.
        fi
        _; _.
        __ Press the yellow key to select.
        count_max="${#source[@]}"
        if [ $count_max -gt 9 ];then
            count_max=9
        fi
        while true; do
            __; read -rsn 1 -p "Select: " char;
            if [ -z "$char" ];then
                char=n
            fi
            case $char in
                t|T) type_mode=1; echo "$char" >&2; break ;;
                $'\177') type_mode=1; echo "s" >&2; break ;;
                n|N) echo "$char" >&2; break ;;
                [1-$count_max])
                    echo "$char" >&2
                    i=$((char - 1))
                    value="${source[$i]}"
                    break ;;
                *)
                    if [ -n "$is_required" ];then
                        echo >&2
                    else
                        case $char in
                            $'\33') skip=1; echo "l" >&2; break ;;
                            l|L) skip=1; echo "$char" >&2; break ;;
                            *) echo >&2
                        esac
                    fi
            esac
        done
        if [[ -z "$type_mode" && -z "$skip" ]];then
            if [ -z "$value" ];then
                _; _.
            fi
            until [ -n "$value" ];do
                __; read -p "Type the number: " value
                if [[ $value =~ [^0-9] ]];then
                    value=
                    __; red Please type one of available number.;_.
                fi
                if [[ $value =~ ^0 ]];then
                    value=
                    __; red Please type one of available number.;_.
                fi
                if [ -n "$value" ];then
                    value=$((value - 1))
                    value="${source[$value]}"
                    if [ -z "$value" ];then
                        __; red Please type one of available number.;_.
                    fi
                fi
            done
            _; _.
            echo-wrap-color "Argument <magenta>${parameter}</magenta> filled with value <yellow>$value</yellow> which is selected from the list." green
        fi
    fi
    if [[ -n "$type_mode" ]];then
        _; _.
        if [ -z "$value" ];then
            if [ -n "$is_required" ];then
                __; read -p "Type the value: " value
            elif [ -z "$skip" ];then
                __; read -p "Type the value or leave blank to skip: " value
            fi
            is_typing=1
        fi
    fi
}
Rcm_prompt_build_command() {
    local _RCM_PROMPT_CHAIN
    echo-wrap 'Use command below to return to the last dialog.' 0
    local shortoptions
    [ -n "$interactive" ] && shortoptions+='i'
    [ -n "$autoyes" ] && shortoptions+='y'
    [ -n "$timer" ] && shortoptions+='t'
    [ -z "$fast" ] && shortoptions+='s'
    if [ -n "$verbose" ];then
        for ((i = 0 ; i < "$verbose" ; i++)); do
            shortoptions+='v'
        done
    fi
    [ -n "$shortoptions" ] && shortoptions=" -${shortoptions}"
    if [ -z "$RCM_PROMPT_CHAIN" ];then
        _RCM_PROMPT_CHAIN="rcm${shortoptions} ${extension}"
    else
        _RCM_PROMPT_CHAIN="$RCM_PROMPT_CHAIN"
    fi
    for each in "${RCM_ARGUMENT_PREVIEW[@]}"; do _RCM_PROMPT_CHAIN+=" ${each}"; done
    words_array=($_RCM_PROMPT_CHAIN)
    echo-wrap-multiline
}
Rcm_prompt_sigint() {
    _.;
    _.;
    error Interrupt by User.
    _.;
    Rcm_prompt_build_command
    exit 0
}
Rcm_get_list_values() {
    if [[ -n "$_available_values_from_command" && -z "$_available_values_from_command_executed" ]];then
        _available_values_from_command_executed=1
        if command -v "$_command" > /dev/null;then
            _; _.
            [ -n "$_arguments" ] && _arguments=' '"$_arguments"
            echo-wrap-color "Value available from command: <magenta>${_command}${_arguments}</magenta>"
            mktemp=$(mktemp -p /dev/shm)
            ${_command}${_arguments} > "$mktemp"
            exit_code=$?
            while read line;do
                [ -n "$line" ] && available_values+=("$line")
            done < "$mktemp"
            rm "$mktemp"
        fi
    fi
    if [ -z "$available_values_backup" ];then
        available_values_backup=("${available_values[@]}")
    fi
    while [[ $# -gt 0 ]]; do
        ArrayRemove "$1" available_values[@]
        available_values=("${_return[@]}")
        unset _return
        shift
    done
    if [ "${#available_values[@]}" -gt 0 ];then
        if [ -n "$or_other" ];then
            printSelectOtherDialog available_values[@]
        elif [[ "${#available_values[@]}" -eq 1 && -n "$is_required" ]];then
            value="${available_values[0]}"
            _; _.
            __; _, "Available value: "; yellow "$value";  _, '.'; _.
            if [ -z "$autoyes" ];then
                _; _.
                echo-wrap 'The one and only available value is selected.'
                read-true
                if [ -z "$boolean" ];then
                    value=' '
                fi
            else
                _; _.
                echo-wrap-color "Argument <magenta>${parameter}</magenta> filled with the only available value <yellow>$value</yellow> automatically." green
            fi
        else
            printSelectDialog available_values[@]
        fi
    else
        _; _.
        if [[ -n "$_available_values_from_command" && ! $exit_code -eq 0 ]];then
            is_required=
            __; _, Argument; _, ' '; _, "$parameter"; _, ' ';  _, set to skip by command,' '; _, pass; _, .; _.
        elif [[ -n "$_available_values_from_command" && -z "$or_other" ]];then
            __; _, No value available,' '; red Process Terminated; _, .; x
        else
            if [ -n "$default_value" ];then
                __; _, Leave blank will use default value.; _.
                label=$(_, 'Type the value [' 2>&1; yellow "$default_value" 2>&1; _, ']: ' 2>&1)
                __; read -p "$label" value
                [ -z "$value" ] && value=' '
            elif [ -n "$is_required" ];then
                __; read -p "Type the value: " value
            else
                __; read -p "Type the value or leave blank to skip: " value
            fi
            is_typing=1
        fi
    fi
}

# Requirement, validate, and populate value.
_help=$("$command" --help 2>/dev/null)

command -v "$command" >/dev/null || { red "Unable to proceed, $command command not found."; x; }

RCM_PREPOPULATE_ARGUMENTS=()
RCM_PREPOPULATE_ARGUMENT_OPTIONS=()
RCM_PREPOPULATE_ARGUMENT_OPERANDS=()
RCM_PREPOPULATE_ARGUMENT_NON_OPTIONS=()

if [ $# -gt 0 ];then
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --)
                while [[ $# -gt 0 ]]; do
                    case "$1" in
                        *)
                            RCM_PREPOPULATE_ARGUMENT_NON_OPTIONS+=("$1");
                            RCM_PREPOPULATE_ARGUMENTS+=("$1");
                            shift ;;
                    esac
                done
                ;;
            --[^-]*)
                if [[ "$2" =~ ^-- ]];then
                    RCM_PREPOPULATE_ARGUMENT_OPTIONS+=("$1");
                    RCM_PREPOPULATE_ARGUMENTS+=("$1");
                elif [[ ! $2 == "" && ! $2 =~ ^-[^-] ]];then
                    RCM_PREPOPULATE_ARGUMENT_OPTIONS+=("$1"="$2");
                    RCM_PREPOPULATE_ARGUMENTS+=("$1"="$2");
                    shift
                else
                    RCM_PREPOPULATE_ARGUMENT_OPTIONS+=("$1");
                    RCM_PREPOPULATE_ARGUMENTS+=("$1");
                fi
                shift
                ;;
            -[^-]*)
                # Short option tidak bisa dijadikan prepopulate.
                RCM_PREPOPULATE_ARGUMENTS+=("$1");
                shift
                ;;
            *)
                RCM_PREPOPULATE_ARGUMENT_OPERANDS+=("$1");
                RCM_PREPOPULATE_ARGUMENTS+=("$1");
                shift
        esac
    done
fi

# Export variables part 1.
# Boolean export as 0 or 1. Must not leave empty string.
[ -n "$fast" ] && rcm_fast=1 || rcm_fast=0
export RCM_FAST="$rcm_fast"
# Other variable, export as is.
export RCM_VERBOSE="$verbose"

if [ -n "$interactive" ];then

    source /usr/local/rcm/$RCM_VERSION/functions/rcm/rcm-prompt.sh

    backup_storage=$HOME'/.cache/rcm/rcm.'$command'.bak'
    history_storage=$HOME'/.cache/rcm/rcm.'$command'.history'
    trap Rcm_prompt_sigint SIGINT

    RCM_ARGUMENT_PASS=()
    RCM_ARGUMENT_PREVIEW=()
    RCM_ARGUMENT_PREVIEW_REAL=()
    RCM_ARGUMENT_PLACEHOLDERS=

    RCM_CONTENTS=`$command --help 2>/dev/null`
    rcm-prompt
    trap x SIGINT

    [ -f "$backup_storage" ] && rm "$backup_storage"

    # Set command with non interactive mode.
    _interactive="$interactive"
    _autoyes="$autoyes"
    interactive=
    autoyes=

    shortoptions=
    [ -n "$interactive" ] && shortoptions+='i'
    [ -n "$autoyes" ] && shortoptions+='y'
    [ -n "$timer" ] && shortoptions+='t'
    [ -z "$fast" ] && shortoptions+='s'
    [ -z "$fast" ] && isfast='' || isfast=' --fast'
    [ -n "$verbose" ] && {
        isverbose=
        for ((i = 0 ; i < "$verbose" ; i++)); do
            isverbose+=' --verbose'
            shortoptions+='v'
        done
    } || isverbose=
    [ -n "$shortoptions" ] && shortoptions=" -${shortoptions}"

    # Restore.
    interactive="$_interactive"
    autoyes="$_autoyes"

    # Export variables part 2.
    # Special for variable RCM_PROMPT_CHAIN, append value then export it.
    if [ -z "$RCM_PROMPT_CHAIN" ];then
        RCM_PROMPT_CHAIN="rcm${shortoptions} ${extension}"
    fi
    for each in "${RCM_ARGUMENT_PREVIEW_REAL[@]}"; do RCM_PROMPT_CHAIN+=" ${each}"; done
    [ -n "$RCM_ENVIRONMENT_VARIABLES" ] && RCM_ENVIRONMENT_VARIABLES+=' '
    RCM_PROMPT_CHAIN="${RCM_ENVIRONMENT_VARIABLES}${RCM_PROMPT_CHAIN}"
    export RCM_PROMPT_CHAIN="$RCM_PROMPT_CHAIN"
    export RCM_ENVIRONMENT_VARIABLES="$RCM_ENVIRONMENT_VARIABLES"
    [ -n "$tempfile" ] && rm "$tempfile"

    chapter Command has been built.
    _ Use command below to arrive in this position with non-interactive mode.; _.
    # Simpan ke log, last command.
    echo "$RCM_PROMPT_CHAIN" >> "$RCM_LOG"
    _ Command has been saved to log file: '`'$(basename "$RCM_LOG")'`'.; _.
    if [ "${#RCM_PREPOPULATE_ARGUMENT_NON_OPTIONS[@]}" -eq 0 ];then
        words_array=($RCM_PROMPT_CHAIN)
    else
        _rcm_prompt_chain="$RCM_PROMPT_CHAIN"
        _argument_after_doubledash=("${RCM_PREPOPULATE_ARGUMENT_NON_OPTIONS[@]}")
        ArrayShift _argument_after_doubledash[@]
        _argument_after_doubledash=("${_return[@]}")
        unset _return
        for each in "${_argument_after_doubledash[@]}"; do
            # Credit: https://devhints.io/bash
            _argument="${each%%=*}"
            _value="${each#$_argument=}"
            [[ "$_argument" == "$_value" ]] && is_flag=1 || is_flag=
            if [ -n "$is_flag" ];then
                _rcm_prompt_chain+=" ${each}"
            else
                [[ "$_value" =~ ' ' ]] && _value="'$_value'"
                _rcm_prompt_chain+=" ${_argument}=${_value}"
            fi
        done
        words_array=($_rcm_prompt_chain)
    fi

    echo-wrap-multiline
    ____

    if [[ "${#RCM_ARGUMENT_PASS[@]}" -gt 0 ]];then
        set -- "${RCM_ARGUMENT_PASS[@]}" "${RCM_PREPOPULATE_ARGUMENT_NON_OPTIONS[@]}"
    else
        set -- "${RCM_PREPOPULATE_ARGUMENT_NON_OPTIONS[@]}"
    fi

    if [ -z "$autoyes" ];then
        chapter Execute:
        read-true
        if [ -z "$boolean" ];then
            exit 0
        fi
        ____

    fi

else
    set -- "${RCM_PREPOPULATE_ARGUMENTS[@]}"
fi

if [ -n "$RCM_TIMER" ];then
    chapter Timer Start.
    _ Begin: $(date +%Y%m%d-%H%M%S); _.
    RCM_BEGIN=$SECONDS
    ____
fi

INDENT+="$RCM_INDENT" $command $isfast $isverbose "$@"

if [ -n "$RCM_TIMER" ];then
    chapter Timer Finish.
    _ End: $(date +%Y%m%d-%H%M%S); _.
    RCM_END=$SECONDS
    duration=$(( RCM_END - RCM_BEGIN ))
    hours=$((duration / 3600)); minutes=$(( (duration % 3600) / 60 )); seconds=$(( (duration % 3600) % 60 ));
    runtime=`printf "%02d:%02d:%02d" $hours $minutes $seconds`
    _ Duration: $runtime; if [ $duration -gt 60 ];then _, " (${duration} seconds)"; fi; _, '.'; _.
    ____
fi

exit 0

# parse-options.sh \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --with-end-options-first-operand \
# --with-end-options-double-dash \
# --no-error-require-arguments << EOF | clip
# INCREMENT=(
#     '--verbose|-v'
# )
# FLAG=(
# '--version|-V'
# '--help|-h'
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
#     'long:--yes,short:-y,parameter:autoyes'
#     'long:--interactive,short:-i,parameter:interactive'
#     'long:--non-interactive,parameter:interactive,flag_option:reverse'
#     'long:--timer,short:-t,parameter:timer'
#     'long:--slow,short:-s,parameter:fast,flag_option:reverse'
# )
# OPERAND=(
# )
# EOF
# clear
