#!/bin/bash

source "${RCM_LIB}"/functions/common/echo.sh
source "${RCM_LIB}"/functions/common/echo-wrap.sh
source "${RCM_LIB}"/functions/common/echo-wrap-color.sh
source "${RCM_LIB}"/functions/common/echo-wrap-list.sh
source "${RCM_LIB}"/functions/common/echo-wrap-multiline.sh
source "${RCM_LIB}"/functions/common/read-true.sh
source "${RCM_LIB}"/functions/common/read-false.sh
source "${RCM_LIB}"/functions/array/array-search.sh
source "${RCM_LIB}"/functions/array/array-shift.sh
source "${RCM_LIB}"/functions/array/array-remove.sh
source "${RCM_LIB}"/functions/array/array-remove-all.sh

# Parse arguments. Generated by parse-options.sh
_new_arguments=()
_n=
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help|-h) help=1; shift ;;
        --version|-V) version=1; shift ;;
        --interactive|-i) interactive=1; shift ;;
        --non-interactive) interactive=0; shift ;;
        --slow|-s) fast=0; shift ;;
        --timer|-t) timer=1; shift ;;
        --verbose|-v) verbose="$((verbose+1))"; shift ;;
        --yes|-y) autoyes=1; shift ;;
        -[^-]*) _new_arguments+=("$1"); shift ;;
        --)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        --[^-]*) shift ;;
        *)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
    esac
done
set -- "${_new_arguments[@]}"
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        -[^-]*) OPTIND=1
            while getopts ":hVistvy" opt; do
                case $opt in
                    h) help=1 ;;
                    V) version=1 ;;
                    i) interactive=1 ;;
                    s) fast=0 ;;
                    t) timer=1 ;;
                    v) verbose="$((verbose+1))" ;;
                    y) autoyes=1 ;;
                esac
            done
            _n="$((OPTIND-1))"
            _n=${!_n}
            shift "$((OPTIND-1))"
            if [[ "$_n" == '--' ]];then
                while [[ $# -gt 0 ]]; do
                    case "$1" in
                        *) _new_arguments+=("$1"); shift ;;
                    esac
                done
            fi
            ;;
        --) shift
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
        *)
            while [[ $# -gt 0 ]]; do
                case "$1" in
                    *) _new_arguments+=("$1"); shift ;;
                esac
            done
            ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments
unset _n

# If not set in argument, try load from environment.
[ -z "$fast" ] && fast="$RCM_FAST"
[ -z "$verbose" ] && verbose="$RCM_VERBOSE"
[ -z "$interactive" ] && interactive="$RCM_INTERACTIVE"

# Boolean default to TRUE.
[ -z "$fast" ] && fast=1; [ "$fast" == 0 ] && fast=

# Copy to RCM variable then unset.
RCM_TIMER="$timer"; unset timer

# Verbosity.
RCM_QUIET=; RCM_LOUD=; RCM_LOUDER=; RCM_DEBUG=;
[[ -z "$verbose" || "$verbose" -lt 1 ]] && RCM_QUIET=1 || RCM_QUIET=
[[ "$verbose" -gt 0 ]] && RCM_LOUD=1
[[ "$verbose" -gt 1 ]] && RCM_LOUD=1 && RCM_LOUDER=1
[[ "$verbose" -gt 2 ]] && RCM_LOUD=1 && RCM_LOUDER=1 && RCM_DEBUG=1

# Define variables and constants.
RCM_DELAY=${RCM_DELAY:=.5}; [ -n "$fast" ] && unset RCM_DELAY
RCM_INDENT='    '; [ "$(tput cols)" -le 80 ] && RCM_INDENT='  '
[ -z "$RCM_LOG" ] && { [ "$EUID" -ne 0 ] && RCM_LOG=$HOME/rcm.log || RCM_LOG=/var/log/rcm.log; }
tempfile=

# Functions. Help and Version.
printVersion() {
    echo $RCM_VERSION
}
printHelp() {
    title Rapid Construct Massive
    _ 'Version '; yellow $RCM_VERSION; _.
    _ 'URL '; yellow git.io/rcm; _.
    _.
cat << EOF
Usage: rcm [options]
       rcm <extension> [options]
       rcm [options] <extension> [options]

Options:
   --version
        Print version of this script.
   --help
        Show this help.
   --slow, -s
        Add delay every subtask.
   --yes, -y
        Skip every question and use the default value even the default value is equivalent to negate.
   --interactive, -i
        Display the user input if needed.
   --non-interactive
        Run without ever asking for user input. Default action.
   --verbose, -v
        Verbose mode. Causes rcm to print debugging messages about its progress.
        Multiple -v options increase the verbosity.
        The maximum is 3.
EOF
}

# Help and Version.
[ -n "$help" ] && { printHelp; exit 1; }
[ -n "$version" ] && { printVersion; exit 1; }

if [ -z "$1" ];then
    printHelp >/dev/null | head -3
    _ Try; blue ' 'rcm; magenta ' '--help; _, ' 'for more information.; _.
    exit 0
fi

extension="$1"; shift
command="rcm-${extension}"

# Title.
title rcm
____

# Functions.

# Requirement, validate, and populate value.
_help=$("$command" --help 2>/dev/null)

command -v "$command" >/dev/null || { red "Unable to proceed, $command command not found."; x; }

RCM_PREPOPULATE_ARGUMENTS=()
RCM_PREPOPULATE_ARGUMENT_OPTIONS=()
RCM_PREPOPULATE_ARGUMENT_OPERANDS=()
RCM_PREPOPULATE_ARGUMENT_NON_OPTIONS=()

if [ $# -gt 0 ];then
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --)
                while [[ $# -gt 0 ]]; do
                    case "$1" in
                        *)
                            RCM_PREPOPULATE_ARGUMENT_NON_OPTIONS+=("$1");
                            RCM_PREPOPULATE_ARGUMENTS+=("$1");
                            shift ;;
                    esac
                done
                ;;
            --[^-]*)
                if [[ "$2" =~ ^-- ]];then
                    RCM_PREPOPULATE_ARGUMENT_OPTIONS+=("$1");
                    RCM_PREPOPULATE_ARGUMENTS+=("$1");
                elif [[ ! $2 == "" && ! $2 =~ ^-[^-] ]];then
                    RCM_PREPOPULATE_ARGUMENT_OPTIONS+=("$1"="$2");
                    RCM_PREPOPULATE_ARGUMENTS+=("$1"="$2");
                    shift
                else
                    RCM_PREPOPULATE_ARGUMENT_OPTIONS+=("$1");
                    RCM_PREPOPULATE_ARGUMENTS+=("$1");
                fi
                shift
                ;;
            -[^-]*)
                # Short option tidak bisa dijadikan prepopulate.
                RCM_PREPOPULATE_ARGUMENTS+=("$1");
                shift
                ;;
            *)
                RCM_PREPOPULATE_ARGUMENT_OPERANDS+=("$1");
                RCM_PREPOPULATE_ARGUMENTS+=("$1");
                shift
        esac
    done
fi

# Export variables part 1.
# Boolean export as 0 or 1. Must not leave empty string.
[ -n "$fast" ] && rcm_fast=1 || rcm_fast=0
export RCM_FAST="$rcm_fast"
# Other variable, export as is.
export RCM_VERBOSE="$verbose"

if [ -n "$interactive" ];then

    source "${RCM_LIB}"/functions/rcm/rcm-prompt.sh

    backup_storage=$HOME'/.cache/rcm/rcm.'$command'.bak'
    history_storage=$HOME'/.cache/rcm/rcm.'$command'.history'

    RCM_ARGUMENT_PASS=()
    RCM_ARGUMENT_PREVIEW=()
    RCM_ARGUMENT_PREVIEW_REAL=()
    RCM_ARGUMENT_PLACEHOLDERS=

    RCM_CONTENTS=`$command --help 2>/dev/null`
    rcm-prompt
    trap x SIGINT

    [ -f "$backup_storage" ] && rm "$backup_storage"

    # Set command with non interactive mode.
    _interactive="$interactive"
    _autoyes="$autoyes"
    interactive=
    autoyes=

    shortoptions=
    [ -n "$interactive" ] && shortoptions+='i'
    [ -n "$autoyes" ] && shortoptions+='y'
    [ -n "$timer" ] && shortoptions+='t'
    [ -z "$fast" ] && shortoptions+='s'
    [ -z "$fast" ] && isfast='' || isfast=' --fast'
    [ -n "$verbose" ] && {
        isverbose=
        for ((i = 0 ; i < "$verbose" ; i++)); do
            isverbose+=' --verbose'
            shortoptions+='v'
        done
    } || isverbose=
    [ -n "$shortoptions" ] && shortoptions=" -${shortoptions}"

    # Restore.
    interactive="$_interactive"
    autoyes="$_autoyes"

    # Export variables part 2.
    # Special for variable RCM_PROMPT_CHAIN, append value then export it.
    if [ -z "$RCM_PROMPT_CHAIN" ];then
        RCM_PROMPT_CHAIN="rcm${shortoptions} ${extension}"
    fi
    for each in "${RCM_ARGUMENT_PREVIEW_REAL[@]}"; do RCM_PROMPT_CHAIN+=" ${each}"; done
    [ -n "$RCM_ENVIRONMENT_VARIABLES" ] && RCM_ENVIRONMENT_VARIABLES+=' '
    RCM_PROMPT_CHAIN="${RCM_ENVIRONMENT_VARIABLES}${RCM_PROMPT_CHAIN}"
    export RCM_PROMPT_CHAIN="$RCM_PROMPT_CHAIN"
    export RCM_ENVIRONMENT_VARIABLES="$RCM_ENVIRONMENT_VARIABLES"
    [ -n "$tempfile" ] && rm "$tempfile"

    chapter Command has been built.
    _ Use command below to arrive in this position with non-interactive mode.; _.
    # Simpan ke log, last command.
    echo "$RCM_PROMPT_CHAIN" >> "$RCM_LOG"
    _ Command has been saved to log file: '`'$(basename "$RCM_LOG")'`'.; _.
    if [ "${#RCM_PREPOPULATE_ARGUMENT_NON_OPTIONS[@]}" -eq 0 ];then
        words_array=($RCM_PROMPT_CHAIN)
    else
        _rcm_prompt_chain="$RCM_PROMPT_CHAIN"
        _argument_after_doubledash=("${RCM_PREPOPULATE_ARGUMENT_NON_OPTIONS[@]}")
        ArrayShift _argument_after_doubledash[@]
        _argument_after_doubledash=("${_return[@]}")
        unset _return
        for each in "${_argument_after_doubledash[@]}"; do
            # Credit: https://devhints.io/bash
            _argument="${each%%=*}"
            _value="${each#$_argument=}"
            [[ "$_argument" == "$_value" ]] && is_flag=1 || is_flag=
            if [ -n "$is_flag" ];then
                _rcm_prompt_chain+=" ${each}"
            else
                [[ "$_value" =~ ' ' ]] && _value="'$_value'"
                _rcm_prompt_chain+=" ${_argument}=${_value}"
            fi
        done
        words_array=($_rcm_prompt_chain)
    fi

    echo-wrap-multiline
    ____

    if [[ "${#RCM_ARGUMENT_PASS[@]}" -gt 0 ]];then
        set -- "${RCM_ARGUMENT_PASS[@]}" "${RCM_PREPOPULATE_ARGUMENT_NON_OPTIONS[@]}"
    else
        set -- "${RCM_PREPOPULATE_ARGUMENT_NON_OPTIONS[@]}"
    fi

    if [ -z "$autoyes" ];then
        chapter Execute:
        read-true
        if [ -z "$RCM_BOOLEAN" ];then
            exit 0
        fi
        ____

    fi

else
    set -- "${RCM_PREPOPULATE_ARGUMENTS[@]}"
fi

if [ -n "$RCM_TIMER" ];then
    chapter Timer Start.
    _ Begin: $(date +%Y%m%d-%H%M%S); _.
    RCM_BEGIN=$SECONDS
    ____
fi

INDENT+="$RCM_INDENT" $command $isfast $isverbose "$@"

if [ -n "$RCM_TIMER" ];then
    chapter Timer Finish.
    _ End: $(date +%Y%m%d-%H%M%S); _.
    RCM_END=$SECONDS
    duration=$(( RCM_END - RCM_BEGIN ))
    hours=$((duration / 3600)); minutes=$(( (duration % 3600) / 60 )); seconds=$(( (duration % 3600) % 60 ));
    runtime=`printf "%02d:%02d:%02d" $hours $minutes $seconds`
    _ Duration: $runtime; if [ $duration -gt 60 ];then _, " (${duration} seconds)"; fi; _, '.'; _.
    ____
fi

exit 0

# parse-options.sh \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --with-end-options-first-operand \
# --with-end-options-double-dash \
# --no-error-require-arguments << EOF | clip
# INCREMENT=(
#     '--verbose|-v'
# )
# FLAG=(
# '--version|-V'
# '--help|-h'
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
#     'long:--yes,short:-y,parameter:autoyes'
#     'long:--interactive,short:-i,parameter:interactive'
#     'long:--non-interactive,parameter:interactive,flag_option:reverse'
#     'long:--timer,short:-t,parameter:timer'
#     'long:--slow,short:-s,parameter:fast,flag_option:reverse'
# )
# OPERAND=(
# )
# EOF
# clear
