#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.7

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm-composer-autoinstaller [options]

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm-composer-autoinstaller
____

# Dependency.

# Functions.

# Require, validate, and populate value.
chapter Variable dump.
____

# Credit:
# https://www.google.com/search?q=php+http+proxy+environment+variable
# https://stackoverflow.com/a/40771206
# https://gist.github.com/ebuildy/381f116e9cd18216a69188ce0230708d
php=$(cat <<-'EOF'
$proxy = getenv('http_proxy');
if (!empty($proxy)) {
    $proxy = str_replace('http://', 'tcp://', $proxy);
    $context = array(
        'http' => array(
            'proxy' => $proxy,
            'request_fulluri' => true,
            'verify_peer'      => false,
            'verify_peer_name' => false,
        ),
        "ssl"=>array(
            "verify_peer"=>false,
            "verify_peer_name"=>false
        )
    );
    stream_context_set_default($context);
}
$mode = $_SERVER['argv'][1];
switch ($mode) {
    case 'get_expected_checksum':
        copy("https://composer.github.io/installer.sig", "php://stdout");
        break;

    case 'download':
        copy('https://getcomposer.org/installer', 'composer-setup.php');
        break;

    case 'get_actual_checksum':
        echo hash_file('sha384', 'composer-setup.php');
        break;
}

EOF
)

chapter Memastikan command '`'composer'`'
notfound=
if command -v composer >/dev/null;then
    __ Command composer ditemukan.
else
    __ Command composer tidak ditemukan.
    notfound=1
fi
____

if [ -n "$notfound" ];then
    chapter Mendownload Installer
    __ Mengecek Checksum.
    EXPECTED_CHECKSUM=$(php -r "$php" get_expected_checksum)
    __; magenta EXPECTED_CHECKSUM="$EXPECTED_CHECKSUM"; _.
    cd /tmp
    __ Mendownload File '`'getcomposer.org/installer'`' sebagai file '`'composer-setup.php'`'
    php -r "$php" download
    ACTUAL_CHECKSUM="$(php -r "$php" get_actual_checksum)"
    __; magenta ACTUAL_CHECKSUM="$ACTUAL_CHECKSUM"; _.
    if [[ ! "$EXPECTED_CHECKSUM" == "$ACTUAL_CHECKSUM" ]];then
        rm composer-setup.php
        error 'ERROR: Invalid installer checksum'; x
    fi
    ____

    chapter Menginstall Composer
    code php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    if php composer-setup.php --install-dir=/usr/local/bin --filename=composer;then
        __; green Berhasil install Composer.; _.
    else
        __; red Failed install Composer.; x
    fi
    rm composer-setup.php
    cd - >/dev/null
    ____

    chapter Verifikasi command '`'composer'`'
    if command -v composer >/dev/null;then
        __; green Command composer ditemukan.; _.
    else
        __; red Command composer tidak ditemukan.; x
    fi
    ____
fi

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# EOF
# clear
