#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.9

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm mariadb assign grant-all [options]

Options:
   --db-name=NAME
        The database name. Value available from command: rcm(mariadb list database).
   --db-user=USER
        The database user. Value available from command: rcm(mariadb list user).
   --db-user-host=[HOSTNAME]
        Host of the the database user come from. Default value: localhost.
   --database-exists-sure
        Bypass database checking.
   --user-exists-sure
        Bypass database user checking.

Global Options.
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --database-exists-sure) database_exists_sure=1; shift ;;
        --db-name=*) db_name="${1#*=}"; shift ;;
        --db-name) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then db_name="$2"; shift; fi; shift ;;
        --db-user-host=*) db_user_host="${1#*=}"; shift ;;
        --db-user-host) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then db_user_host="$2"; shift; fi; shift ;;
        --db-user=*) db_user="${1#*=}"; shift ;;
        --db-user) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then db_user="$2"; shift; fi; shift ;;
        --user-exists-sure) user_exists_sure=1; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm mariadb assign grant-all
____

# Dependency.
require command mysql

# Requirement, validate, and populate value.
chapter Variable dump.
if [ -z "$db_name" ];then
    error "Argument --db-name required."; x
fi
code 'db_name="'$db_name'"'
if [ -z "$db_user" ];then
    error "Argument --db-user required."; x
fi
code 'db_user="'$db_user'"'
if [ -z "$db_user_host" ];then
    db_user_host=localhost
fi
code 'db_user_host="'$db_user_host'"'
code 'database_exists_sure="'$database_exists_sure'"'
code 'user_exists_sure="'$user_exists_sure'"'
____

if [ -z "$database_exists_sure" ];then
    chapter Mengecek database '`'$db_name'`'.
    code 'mysql --silent --skip-column-names -e ''"''select schema_name from information_schema.schemata where schema_name = '"'""$db_name""'"'"'
    msg=$(mysql --silent --skip-column-names -e "select schema_name from information_schema.schemata where schema_name = '$db_name'")
    notfound=
    if [[ $msg == $db_name ]];then
        __ Database ditemukan.
    else
        __; red Database tidak ditemukan; x
    fi
    ____
fi

if [ -z "$user_exists_sure" ];then
    chapter Mengecek database user '`'$db_user'`'.
    code mysql --silent --skip-column-names -e '"''select COUNT(*) FROM mysql.user WHERE user = '"'""$db_user""'"';''"'
    msg=$(mysql --silent --skip-column-names -e "select COUNT(*) FROM mysql.user WHERE user = '$db_user';")
    notfound=
    if [ $msg -gt 0 ];then
        __ Database user ditemukan.
    else
        __; red Database user tidak ditemukan; x
        notfound=1
    fi
    ____
fi

chapter Mengecek grants user '`'$db_user'`' ke database '`'$db_name'`'.
notfound=
# GRANT USAGE ON *.* TO `xxx`@`localhost` IDENTIFIED BY PASSWORD '*650AEE8441BAF8090D260F1E4A0430DD2AF92FBA'
# GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `xxx\\_%`.* TO `xxx`@`localhost`
# GRANT USAGE ON *.* TO `yyy`@`localhost` IDENTIFIED BY PASSWORD '*23FF9BDB84CBF879F19D46CB6B85F0550CB64F5C'
# GRANT ALL PRIVILEGES ON `yyy_drupal`.* TO `yyy`@`localhost`
# GRANT ALL PRIVILEGES ON `yyy_drupal\\_%`.* TO `yyy`@`localhost`
# "The first grant was auto-generated." Source: https://phoenixnap.com/kb/mysql-show-user-privileges
# GRANT USAGE ON *.* TO `roundcube`@`localhost` IDENTIFIED BY PASSWORD '*C75329CD384E7527992AED32A0A0DF1FA0342B15'
# GRANT ALL PRIVILEGES ON `roundcubemail`.* TO `roundcube`@`localhost`
__; magenta mysql '"'$db_name'"' --silent --skip-column-names -e '"'show grants for ${db_user}@${db_user_host}'"'; _.
while read line; do e "$line"; _.; done <<< `mysql "$db_name" --silent --skip-column-names -e "show grants for ${db_user}@${db_user_host}"`
msg=$(mysql "$db_name" --silent --skip-column-names -e "show grants for ${db_user}@${db_user_host}")
__; magenta grep -F "'"GRANT ALL PRIVILEGES ON '`'$db_name'`'.* TO '`'$db_user'`'@'`'$db_user_host'`'"'"; _.
if grep -q -F 'GRANT ALL PRIVILEGES ON `'"$db_name"'`.* TO `'"$db_user"'`@`'"$db_user_host"'`' <<< "$msg";then
    __ Granted.
else
    __ Not granted.
    notfound=1
fi
____

if [ -n "$notfound" ];then
    chapter Memberi grants user '`'$db_user'`' ke database '`'$db_name'`'.
    mysql -e "grant all privileges on \`${db_name}\`.* TO '${db_user}'@'${db_user_host}';"
    mysql -e "grant all privileges on \`${db_name}\_%\`.* TO '${db_user}'@'${db_user_host}';"
    msg=$(mysql "$db_name" --silent --skip-column-names -e "show grants for ${db_user}@${db_user_host}")
    if grep -q -F 'GRANT ALL PRIVILEGES ON `'"$db_name"'`.* TO `'"$db_user"'`@`'"$db_user_host"'`' <<< "$msg";then
        __; green Granted.; _.
    else
        __; red Not granted.; x
    fi
    ____
fi

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --database-exists-sure
# --user-exists-sure
# )
# VALUE=(
# --db-name
# --db-user
# --db-user-host
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# EOF
# clear
