#!/bin/bash

RCM_EXTENSION_VERSION=0.18.0-alpha.6

source=$RCM_LIB/functions/common/echo.sh; [ -f "$source" ] && source "$source" || exit 1

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --php-version=*) php_version="${1#*=}"; shift ;;
        --php-version) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then php_version="$2"; shift; fi; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Usage Functions.
usage() {
    cat << 'EOF'
Usage: rcm-php-setup-adjust-cli-version [options]

Options:
   --php-version
        Set the version of PHP.

Global Options.
   --fast
        No delay every subtask.
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

# Help and Version.
[ -n "$help" ] && { usage; exit 1; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Title.
title rcm-php-setup-adjust-cli-version
____

# Dependency.
while IFS= read -r line; do
    [[ -z "$line" ]] || command -v `cut -d: -f1 <<< "${line}"` >/dev/null || { error Unable to proceed, command not found: '`'`cut -d: -f1 <<< "${line}"`'`'.; x; }
done <<< `usage 2>/dev/null | sed -n '/^Dependency:/,$p' | sed -n '2,/^\s*$/p' | sed 's/^ *//g'`

# Require, validate, and populate value.
chapter Variable dump.
code 'php_version="'$php_version'"'
____

update=
chapter Check PHP CLI version
current_value=$(update-alternatives --query php | grep -o -P 'Value: \K(.*)')
code 'current_value="'$current_value'"'
if [ -n "$php_version" ];then
    major=`echo "$php_version" | cut -d. -f1`
    minor=`echo "$php_version" | cut -d. -f2`
    expected_value=$(command -v php)"${major}.${minor}"
    code 'expected_value="'$expected_value'"'
    if [[ "$current_value" == "$expected_value" ]];then
        __ PHP CLI version tidak perlu diubah.
    else
        __ PHP CLI version perlu diubah.
        update=1
    fi
fi
____

if [ -n "$update" ];then
    chapter Set PHP CLI version
    found=
    success=
    while IFS= read line; do
        if [[ "$expected_value" == "$line" ]];then
            found=1
            break
        fi
    done <<< `update-alternatives --query php | grep -o -P 'Alternative: \K(.*)'`
    if [ -n "$found" ];then
        __ Alternative "$expected_value" dapat dijadikan sebagai link.
        __; magenta update-alternatives --set php "$line"; _.
        update-alternatives --quiet --set php "$line"
        _current_value=$(update-alternatives --query php | grep -o -P 'Value: \K(.*)')
        __; magenta '_current_value="'$_current_value'"'; _.
        if [[ "$_current_value" == "$current_value" ]];then
            __; red Gagal mengubah PHP CLI version menjadi "$expected_value"; x
        else
            __; green Berhasil mengubah PHP CLI version menjadi "$expected_value"; _.
            success==1
        fi
    else
        error Alternative "$expected_value" tidak dapat dijadikan sebagai link.;
        _ Periksa menggunakan command berikut:; _.
        code update-alternatives --query php
        x
    fi
    if [ -n "$success" ];then
        __; magenta php -v; _.
        php -v
    fi
    ____
fi

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# --php-version
# )
# FLAG_VALUE=(
# )
# EOF
# clear
