#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.13

# Usage Functions.
usage() {
    cat << EOF
Usage: rcm php list pool
EOF
}

[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
_new_arguments=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# ------------------------------------------------------------------------------

# Title.
title rcm php list pool
____

# Dependency.

# Functions.

# Require, validate, and populate value.

command-section-suggestion() {
    local php_version=$1
    local php_fpm_user=$2
    if [ -z "$php_version" ];then
        error PHP s Version is required.; x
    fi
    # echo php_version "$php_version"
    # echo php_fpm_user "$php_fpm_user"

    find='[php-version]'
    replace="$php_version"
    PHP_FPM_POOL_DIRECTORY="${PHP_FPM_POOL_DIRECTORY/"$find"/"$replace"}"
    if [ ! -d "$PHP_FPM_POOL_DIRECTORY" ];then
        error PHP Version is not exists in system.; x
    fi
    while read file; do
        grep -h -E '^\s*\[[^]]+]\s*$' "$file" | sed -E 's,\[(.*)\],\1,' | sort
    done <<< `ls "$PHP_FPM_POOL_DIRECTORY"/*.conf`
}

command-${command} "$@"

exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# )
# VALUE=(
# )
# MULTIVALUE=(
# )
# FLAG_VALUE=(
# )
# CSV=(
# )
# EOF
# clear
