#!/bin/bash

RCM_EXTENSION_VERSION=0.19.0-alpha.12

# Usage Functions.
usage() {
    cat << EOF
Auto Install Postfix with default version.

Usage: rcm postfix init [options]

Options:
   --main-mailer-type=TYPE
        Select the Mailer Type in a Postfix Installation.
        Available values: [1].
        [1]: Internet site
   --mailname=FQDN
        The Fully Qualified Domain Name (FQDN) of the mail server (e.g., smtp.example.com).
        Value available from command: hostname(-f), or other.
   --dbms=DB
        Select database management system to store the data.
        Values available from command: rcm(plugin list postfix/dbms).
   --public-domain
        Make sure that --mailname is public domain, this will trigger TLS request and DNS verification.
   --acme-client=TLS
        Select acme client to obtain TLS Certificate.
        Values available from command: rcm(plugin list acme-client).
        Conditional: Bypass if --public-domain is not added.

Additional Options:
   rcm(-p plugin prompt acme-client [--acme-client] obtain)

Global Options:
   --version
        Print version of this script.
   --help
        Show this help.
EOF
}

# Prevent scripts from being executed directly.
[ -f "${RCM_LIB}/require.sh" ] && source "${RCM_LIB}/require.sh" || { usage >&2; exit 1; }

# Parse arguments. Generated by parse-options.sh.
while [[ $# -gt 0 ]]; do
    case "$1" in
        --help) help=1; shift ;;
        --version) version=1; shift ;;
        --acme-client=*) acme_client="${1#*=}"; shift ;;
        --acme-client) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then acme_client="$2"; shift; fi; shift ;;
        --dbms=*) dbms="${1#*=}"; shift ;;
        --dbms) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then dbms="$2"; shift; fi; shift ;;
        --mailname=*) mailname="${1#*=}"; shift ;;
        --mailname) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then mailname="$2"; shift; fi; shift ;;
        --main-mailer-type=*) main_mailer_type="${1#*=}"; shift ;;
        --main-mailer-type) if [[ ! $2 == "" && ! $2 =~ (^--$|^-[^-]|^--[^-]) ]]; then main_mailer_type="$2"; shift; fi; shift ;;
        --public-domain) public_domain=1; shift ;;
        --[^-]*) shift ;;
        *) _new_arguments+=("$1"); shift ;;
    esac
done
set -- "${_new_arguments[@]}"
unset _new_arguments

# Define variables and constants.

# Help and Version.
[ -n "$help" ] && { usage; exit 0; }
[ -n "$version" ] && { e $RCM_EXTENSION_VERSION; x; }

# Require.
require vendor/ijortengab/rcm/functions/utility/apt-install.sh

# ------------------------------------------------------------------------------

# Title.
title rcm postfix init
____

# Dependency.
require command debconf-set-selections

# Define variables and constants.
if [ -z "$mailname" ];then
    error "Argument --mailname required."; x
fi

if [ -z "$main_mailer_type" ];then
    error "Argument --main-mailer-type required."; x
fi

if [ -z "$dbms" ];then
    error "Argument --dbms is required."; exit 1
fi

if [ -n "$public_domain" ];then
    if [ -z "$acme_client" ];then
        error "Argument --acme-client is required."; x
    fi
fi

[ -n "$RCM_DEBUG" ] && chapter Variable dump.
[ -n "$RCM_DEBUG" ] && code 'mailname="'$mailname'"'
[ -n "$RCM_DEBUG" ] && code 'main_mailer_type="'$main_mailer_type'"'
[ -n "$RCM_DEBUG" ] && code 'dbms="'$dbms'"'
[ -n "$RCM_DEBUG" ] && ____

debconf-set-selections <<< "postfix postfix/mailname string ${mailname}"
debconf-set-selections <<< "postfix postfix/main_mailer_type string '${main_mailer_type}'"

apt-install postfix postfix-doc

include `rcm plugin run-method postfix/dbms $dbms init`

if [ -n "$public_domain" ];then

    RCM_FQDN=$(</etc/mailname)

    include `rcm plugin run-method acme-client $acme_client obtain`

fi

# Wajib exit 0 jika success.
exit 0

# parse-options.sh \
# --without-end-options-double-dash \
# --compact \
# --clean \
# --no-hash-bang \
# --no-original-arguments \
# --no-error-invalid-options \
# --no-error-require-arguments << EOF | clip
# FLAG=(
# --version
# --help
# --public-domain
# )
# VALUE=(
# --mailname
# --main-mailer-type
# --dbms
# --acme-client
# )
# FLAG_VALUE=(
# )
# EOF
# clear
